### ISSUE TITLE
Allow raw server log for each server

### ISSUE THREAD

**Issue by squigglezworth** [weechat/weechat#1000]
`/server raw -server <server>`

**Comment by ToxicFrog** [comment]
As a workaround in the meantime, you can use regex filters (the messages in `irc_raw` are untagged, so tag filters won't work):

`/filter add raw_myserver_only irc.irc_raw * !myserver\t.*`

**Comment by flashcode** [comment]
I'm adding advanced filtering in irc raw buffer: filter by server, IRC message type, etc.
