### ISSUE TITLE
auto scrolling buffer list.

### ISSUE THREAD

**Issue by amosbird** [weechat/weechat#1001]
It would be more informative to have buffer list auto scrolled to current highlighted one. Currently the buffer list is static ![](https://la.wentropy.com/loMT.png)

**Comment by weechatter** [comment]
is related to https://github.com/weechat/weechat/issues/332

**Comment by flashcode** [comment]
Done with new option buflist.look.auto_scroll under some conditions, see my comment: https://github.com/weechat/weechat/issues/332#issuecomment-306998647
