### ISSUE TITLE
Memory leak present on 1.8

### ISSUE THREAD

**Issue by felixsanz** [weechat/weechat#1010]
I have my system configured so it spawns weechat on a terminal at login.

I also have encrypted sec.info data, so when weechat starts, it asks me for the password.

Well, it happened me twice that, instead of giving the password, i just closed the terminal window directly (because i didn't want to use weechat that time), and after few seconds (30-90s) i start hearing the fan of my laptop like a turbine. I take a look at the temperatures and the CPU is at 90ºC!! Because the CPU is working at 100% load. I take a look at `top` and the process eating that much CPU is weechat. So i kill it (have to use kill 9) and it's fixed, but what if i'm not there or i don't notice? :/

I don't know much about debug/debugging weechat, so please if you need some reports or something tell me. Also, this doesn't happen all the time, so it'll be a little hard to reproduce i guess.

If it helps, i did nothing fancy with my laptop, just turn it ON, close weechat, ncmpcpp and htop terminal windows (as they open on startup), and then i left the laptop like that. I didn't open anything or used any app.

Version: 1.8
Plugins activated: iset, highmon, autosort

**Comment by flashcode** [comment]
It should be fixed, if you can, please try the latest development version and tell me if it's OK now.
To reproduce, just closing the terminal on the secure password prompt should be enough to cause the infinite loop.
