### ISSUE TITLE
Using /names after joining a channel wipes per-nick account, realname and away data

### ISSUE THREAD

**Issue by mquin** [weechat/weechat#1019]
Where WHOX is available weechat collects account, realname and (with away polling) away data.

If /names is used on a channel this information is wiped, but can be restored by issuing a suitable WHO request manually.

From IRC:

09:54 <sim642> The fault is on this line: https://github.com/weechat/weechat/blob/370fbeb5a39b0b168551c1dd6d23c02f60c32721/src/plugins/irc/irc-protocol.c#L4346
09:55 <sim642> for an already existing nick in the channel it overrides away, account and realname with defaults

**Comment by flashcode** [comment]
Fixed, thanks for reporting.
