### ISSUE TITLE
It is not clear what /path/to/directory in the install instructions refers to (README.adoc)

### ISSUE THREAD

**Issue by JonasT** [weechat/weechat#1024]
It is not obvious to me what /path/to/directory in the install instructions refers to. I suggest to clarify it: if it refers to where it should be installed, why not suggest something reasonable like `/usr/`? If it is supposed to refer to the source code directory, why not instead write something like: ``cmake .. -DCMAKE_INSTALL_PREFIX=`pwd`/../``?

**Comment by flashcode** [comment]
In the user's guide, there are 2 parts: "Installation in system directories (requires root privileges)" (so in /usr directories), and "Installation in custom directory" (so typically to install in your home).
So it's explained how to install in system directories (standard install) or anywhere (custom install).
What should be added to be more clear?

**Comment by JonasT** [comment]
I am referring to the README.md to the section "Compile" which has this line:

`$ cmake .. -DCMAKE_INSTALL_PREFIX=/path/to/directory`

It is never explained what this path actually refers to.

**Comment by flashcode** [comment]
Done. Hopefully it's more clear now.

**Comment by JonasT** [comment]
@flashcode looks good now, thanks! <3 though the last line `# make install` has a # in front instead of $ now, is that intentional?

**Comment by flashcode** [comment]
Yes, intentional, because the command must be executed as root. I can mention that on the line if that's not clear enough.

**Comment by JonasT** [comment]
Why not use `$ sudo make install` then? I have never seen this indicated by changing the bash prompt to a `#` in any manual before, so I can imagine others might not be aware of this syntax either. `sudo` on the other hand should be universally known

**Comment by bendem** [comment]
It's a common notation and it is widely used across the internet, guessing you have not followed many linux guides before.

```
$ a-command-ran-by-normal-user
# a-command-ran-by-root
```

**Comment by JonasT** [comment]
@bendem I haven't seen it ever before, and I'm using Linux since at least 2002. Again what's wrong with just using the more widely recognized "sudo"?

**Comment by flashcode** [comment]
@JonasT: I'll change the README to use sudo.

**Comment by JonasT** [comment]
@flashcode sorry for the comment noise, I guess the root notation is not really a super important detail. Thanks for considering to change it though :smile:

**Comment by flashcode** [comment]
Done (forgot to mention this issue in the commit).

_Sent from my OnePlus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
