### ISSUE TITLE
Buflist: add setting to toggle appending each buffer with newline

### ISSUE THREAD

**Issue by squigglezworth** [weechat/weechat#1027]
`buflist.look.add_newline` 

Default would be on, and so each buffer in the list has a newline added. However, when off, do not add any newlines, meaning it would need to be specified in buflist.format.buffer(_current)

**Comment by flashcode** [comment]
A newline added, where?

**Comment by squigglezworth** [comment]
As of now, each item is essentially `${format_buffer}\n` and I'd like to be able to toggle the default \n

With it off, and if the user does not specify a newline in their formats, all the buffers would appear to be on one line.

**Comment by flashcode** [comment]
Adding such option is not very hard, but it will break the mouse click on buffer names: it will be very hard (to not say impossible) for WeeChat to know on which buffer you click with the mouse, if you have possible more than one buffer per line.

**Comment by flashcode** [comment]
Done, with a warning in the new option about mouse.
