### ISSUE TITLE
Can't input some Unicode characters

### ISSUE THREAD

**Issue by mkoskar** [weechat/weechat#1032]
I've noticed that some Unicode characters will be input as space.

I'm testing in ``urxvt`` (also ``termite``) and with plain default config ``weechat -d $(mktemp -d)``.
I input ``U+1F95D`` (using urxvt's ISO 4755 support; that is ``Ctrl-Shift-1f95d`` but I see and also confirm with ``Ctrl-Shift-LeftMouseButton`` that terminal received space (``0x20``) instead. Situation is the same when I try to input these with pasting X primary selection.

Note that ``U+1F982`` works ok. Both encode similarly to 4 bytes in UTF-8 (``f0   9f   a5   9d`` vs. ``f0   9f   a6   82``).

Also note that I can insert these outside of Weechat fine, I've tested as terminal echo with plain ``$ cat`` and also inside ``vim`` and ``nvim``.

```
 $ /usr/bin/weechat -v             
1.9
```

**Comment by flashcode** [comment]
I can input and send the chars `U+1F95D` and `U+1F982` in my WeeChat (2.0-dev), using rxvt. For both, I see a square (that means my font does not support this char), so it is not a space displayed.

**Comment by flashcode** [comment]
My config:
- WeeChat 2.0-dev (v1.9-171-ga59ce8331)
- libc 2.24
- rxvt-unicode 9.22
- ncurses 6.0 (patch 20161126)

**Comment by mkoskar** [comment]
I've tried to compile latest git (a59ce8331a868aa4214241b1395b2af395afed27) version, issue still persists here.

* glibc 2.25-5 - [PKGBUILD ](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/glibc&id=acaf761656678996770118dec29ce62212b0f88e)
* ncurses 6.0+20170527-1 - [PKGBUILD](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/ncurses&id=b5f8b4e9ccfee6d6489b900e9225847af3483c72)

**Comment by mkoskar** [comment]
I've retested this now with success and suspect upgrading to glibc `2.26` fixed it.

**Comment by flashcode** [comment]
OK, thanks for status update, so I close the issue.
