### ISSUE TITLE
fset: spaces at beginning of input are NOT ignored?

### ISSUE THREAD

**Issue by l** [weechat/weechat#1035]
Arguments description of /fset command says that
1. spaces at beginning of input are ignored
2. "q" closes the fset buffer
3. " q" searches all options with "q" inside name

It looks that input " q" is distinguished from input "q".
Do I misunderstand something?

**Comment by flashcode** [comment]
As "q" is used to close the buffer, " q" (with a leading space) can be used to search just "q" in option names.

**Comment by l** [comment]
Thanks for your comments.

> Note: spaces at beginning of input are ignored, so for example
> "q" closes the fset buffer while " q" searches all options
> with "q" inside name.

Is the sentence in src/plugins/fset/fset-command.c
describing behavior of function fset_buffer_input_cb in src/plugins/fset/fset-buffer.c?

If this is true. It would be nice to use following sentence.

Note: If input has one or more leading spaces following words are interpreted as filter,
otherwise input is interpreted as operation to fset buffer. For example
input " q" searches all options with "q" inside name
while input "q" closes the fset buffer.

Sincerely yours,

**Comment by flashcode** [comment]
Fixed, thanks.
