### ISSUE TITLE
anti_flood_prio_high and low in milliseconds instead of seconds

### ISSUE THREAD

**Issue by Underdoge** [weechat/weechat#1039]
Hello,

It would be nice to have these settings in milliseconds instead of seconds.

Currently you can only set it in seconds, and when sending multiple lines at a time the output speed is too slow even if set to 1 second, and if set to zero seconds the output is too fast and it usually triggers server side flood protections and you get kicked (as you should).

So my suggestion would be for this parameter to allow settings like 100ms, 300ms, 500ms, etc. (without the ms) which is usually faster for sending multiple lines and you can fine tune it for each network's flood protection threshold.

I could help with the development if necessary.

Thanks!

**Comment by sim642** [comment]
The issue with changing the unit used by these options is that it'd break all existing configurations. Someone with a default value of 2 (s) currently would after this change have it at 2 (ms), which is not what they wanted.

**Comment by flashcode** [comment]
Yes, @sim642. So if the unit is changed, the option will be renamed. Users will lose the old value (with a warning), but there will be no confusion with the value between seconds and milliseconds.
I already planned to change this unit and use milliseconds, which will cause some changes in the internal IRC timers.

**Comment by Underdoge** [comment]
Thank you @flashcode!

**Comment by flashcode** [comment]
Hi,

I pushed a branch for tests here: https://github.com/weechat/weechat/tree/irc-anti-flood-milliseconds

Note that this will remove existing server options "anti_flood_prio_high" and "anti_flood_prio_low", which are replaced by "anti_flood_delay" (in milliseconds).

There are still queues with priority internally (immediate send / high priority / low priority), but this is transparent and only one delay can now be configured, which is enough.

**Comment by flashcode** [comment]
Branch has been merged, the option has been renamed to just `anti_flood`.
