### ISSUE TITLE
Suddenly unable to connect

### ISSUE THREAD

**Issue by txtsd** [weechat/weechat#1052]
```
02:38:39  -- | irc: connecting to server xxx.xxx/7778 (SSL)...
02:38:40 =!= | irc: TLS handshake failed
02:38:40 =!= | irc: error: Error in the pull function.
02:38:40  -- | irc: reconnecting to server in 5 seconds
02:38:45  -- | irc: reconnecting to server...
02:38:45  -- | irc: connecting to server xxx.xxx/7778 (SSL)...
02:38:46 =!= | irc: TLS handshake failed
02:38:46 =!= | irc: error: The TLS connection was non-properly 
02:38:46  -- | irc: reconnecting to server in 5 seconds
02:38:51  -- | irc: reconnecting to server...
02:38:51  -- | irc: connecting to server xxx.xxx/7778 (SSL)...
02:38:52 =!= | irc: TLS handshake failed
02:38:52 =!= | irc: error: Error in the pull function.
```

Nothing changed, but weechat suddenly stopped being able to connect to my server, which hosts a znc instance.

Using `WeeChat 2.0-dev (git: v1.9-247-g902da71ff) [compiled on Aug 15 2017 02:37:57]`

I updated my packages locally and on my server, but it doesn't seem to have made an effect.

**Comment by flashcode** [comment]
Hi,
Restarting WeeChat does not help?

**Comment by txtsd** [comment]
@flashcode It does not. I restarted my local system and the server too.

**Comment by flashcode** [comment]
So it could be a problem in the server side (znc). I see no reason why WeeChat would suddenly refuse the connection.
Did you upgrade the GnuTLS lib maybe?

**Comment by txtsd** [comment]
@flashcode Nope. Nothing had changed. I'll see what I can find about what's going on.

**Comment by txtsd** [comment]
Turns out my TLS certs had updated but my znc.pem failed to update.
