### ISSUE TITLE
Error: unable to create/append

### ISSUE THREAD

**Issue by the207life** [weechat/weechat#1058]
Has been working flawlessly up until today. Went to startup in Terminal on Ubuntu (17.04 64-bit) and received the following error: 

> Error: unable to create/append to log file (weechat.log)
If another WeeChat process is using this file, try to run WeeChat
with another home using the "--dir" command line option.

**Comment by weechatter** [comment]
Check out if already a weechat instance is running.

**Comment by the207life** [comment]
Got a response of "4081". Any suggestions?

**Comment by weechatter** [comment]
weechat is already running (with process ID 4081), therefore you can not run a second weechat with the same directory (config). Attach to your already running weechat or maybe kill the process (on your own risk!)
