### ISSUE TITLE
channel's name in buflist are evaluated

### ISSUE THREAD

**Issue by fwtw** [weechat/weechat#1060]
steps to reproduce:
try joining channel that contains `${...}` in it's name, i.e. `/join #${window.buffer.full_name}`

what happened:
buflist shows the evaluated channel name, i.e. `#irc.server.somechannelname`

expected result:
buflist shouldn't evaluate it, shows them as literal `#${window.buffer.full_name}` instead

**Comment by flashcode** [comment]
Fixed.

Now some custom variables/options may require some extra `${eval:${...}}`, see the release notes: https://github.com/weechat/weechat/blob/master/ReleaseNotes.adoc#v2.0_buflist_eval
