### ISSUE TITLE
generate and bundle man pages and docs in release tarballs

### ISSUE THREAD

**Issue by radhermit** [weechat/weechat#1062]
It would be nice if release tarballs contained pre-generated docs and man pages so package maintainers wouldn't have to force asciidoctor and its relatively large list of dependencies to be installed if users want to install a certain release's docs.

**Comment by radhermit** [comment]
I should note this request is from a source-based distro perspective but could benefit anyone doing the actual release builds.

**Comment by flashcode** [comment]
Hi,
It could be possible to make another tarball with docs (though I'm not even sure this is required), but for me a tarball is a source package and should not contain any compiled doc/source inside.
By the way, asciidoctor just depends on a ruby interpreter, which is not a big dependency (at least on Debian).

**Comment by radhermit** [comment]
Right, I guess I was factoring in the deps required to run the tests for asciidoctor which pull the long chain. :smile:
