### ISSUE TITLE
buflist: Allow sorting by localvars

### ISSUE THREAD

**Issue by tomoe-mami** [weechat/weechat#1066]
Currently buflist only accepts sorting by hdata vars of buffer/irc_server/irc_channel. It would be nice if it also supports localvars. It will benefit people who want to make custom sorting or people who use protocols other than IRC. They can write a simple script/trigger that fills the localvars with some data and let buflist sort the buffers.

**Comment by flashcode** [comment]
Done.

I added the support of a path to a variable (eg: "var1.var2.var3") in function hdata_compare, and this function is now able to compare hashtable values.

So you can now do this to sort buffers on local variable "myvar" in buflist:

    /set buflist.look.sort "local_variables.myvar"
