### ISSUE TITLE
Installing compiled .deb package on raspbian

### ISSUE THREAD

**Issue by Cyberek** [weechat/weechat#1067]
I'm trying to install the prepared .deb package for raspbian (raspberry pi).

This missing dependencies is all I get :(.

Seems there are unavailable for this distribution.
@weechatter - can you help please?
```

sudo apt-get -f install weechat-core
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 weechat-core : Depends: libgcrypt20 (>= 1.7.0) but 1.6.3-2+deb8u4 is to be installed
                Depends: libgnutls30 (>= 3.5.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by weechatter** [comment]
You have Raspbian “stretch” or "jessie"? Check out that you are using the correct repository.

**Comment by Cyberek** [comment]
And this is exactly the answer that helped me - I was on jessie trying to install stretch. Changing this file:
`/etc/apt/sources.list.d/weechat.list`
and replacing stretch with jessie fixed the issue (later I have updated from jessie to stretch and redownloaded the package.

But now I went to another issue (trying to authenticate weetweetch.py plugin:
```
 python: stdout/stderr: Traceback (most recent call last):
 python: stdout/stderr:   File "/home/pi/.weechat/python/autoload/weetweet.py", line 1168, in oauth_proc_cb
python: stdout/stderr:     oauth_token, oauth_token_secret = parse_oauth_tokens(out)
python: stdout/stderr:   File "/home/pi/.weechat/python/autoload/weetweet.py", line 1128, in parse_oauth_tokens
 python: stdout/stderr:     return oauth_token, oauth_token_secret
 python: stdout/stderr: UnboundLocalError: local variable 'oauth_token' referenced before assignment
python: error in function "oauth_proc_cb"
```

**Comment by weechatter** [comment]
Ok. I am closing the issue...please open an issue for the script problem: https://github.com/weechat/scripts/issues

i don't use the script, therefore i can not help.
