### ISSUE TITLE
Xfer file transfer fails when window is resized (tiling window manager)

### ISSUE THREAD

**Issue by IllDepence** [weechat/weechat#1068]
* **WeeChat version:** WeeChat 1.4 [compiled on Apr 26 2017 18:10:49]
* **operating system:** Ubuntu 16.04.3 LTS (Xenial Xerus) x86_64
* **steps to reproduce:** use a tiling window manager (e.g. i3), start weechat, receive a file transfer, open a new window (this automatically resizes the weechat window to fit both windows on the screen) 
* **actual result:** file transfer fails
* **expected result:** file transfer should continue

**Comment by flashcode** [comment]
Hi,
This bug has been fixed in version 1.5 (see #677 and #680).
Latest version released is 1.9, so you should upgrade.

**Comment by flashcode** [comment]
If you need ubuntu packages, check: https://weechat.org/download/debian/
