### ISSUE TITLE
Allow to close several buffers at once

### ISSUE THREAD

**Issue by Porkepix** [weechat/weechat#1071]
[Feature request]
It is currently already possible to close a range of buffers, like if I type `/close 20-25` it'll close buffer 20 to 25.
What would be nice is to add the possibility to close several not consecutives buffers at once, both by typing for example `/close 4 10 5 25 12` or `/close #foo #bar #test` while having autocomplete for buffers names.

**Comment by Porkepix** [comment]
The same way it would be nice to be able to join multiple chans at once with `/join #foo #bar #test`.
I don't know if this should be a separated issue or can be in this same one by editing the issue title?

**Comment by flashcode** [comment]
It is already possible to join multiple channels at once, the syntax comes from IRC protocol (not WeeChat): `/join #channel1,#channel2,#channel3` (without any spaces, because spaces are used to separate channels from keys, if needed).

**Comment by Porkepix** [comment]
My bad then, didn't knew that. So the syntax is something like `/join #foo fookey,#bar bar_key,#test test_key`?

**Comment by flashcode** [comment]
No, for the syntax, see example in `/help join`.

**Comment by Porkepix** [comment]
Ok I saw it then. Might be a bit confusing imho, but if that's IRC specs, well, nothing to do about it. Sorry for the off-topic anyway.

**Comment by flashcode** [comment]
Closing the issue as it was added in version 2.3 (commit 65f1c82a87bc14c15ccf99bb213b16b42ca545fe).
