### ISSUE TITLE
Allow escaped colons in ternary value_if_true.

### ISSUE THREAD

**Issue by miniCruzer** [weechat/weechat#1072]
With the old buffers.pl, I was able to set a prefix for query buffers to display a "Q: ", and to duplicate this with the buflist module, I set `buflist.format.buffer = ${if:${type}==private?Q :}`. Colon or not isn't a big deal, but it seems useful to be able to escape a colon in the ternary if an actual colon is desired as part of the value.

**Comment by flashcode** [comment]
You can escape chars with this syntax: `${\uxx}` which gives for your example: `${if:${type}==private?Q${\u3a} :}` (3A being the ASCII hex code of colon).

**Comment by miniCruzer** [comment]
Thanks, this works!
