### ISSUE TITLE
irc.look.notice_welcome_redirect help talks about "freenode server"

### ISSUE THREAD

**Issue by Mikaela** [weechat/weechat#1095]
> "irc.look.notice_welcome_redirect":
>   description: automatically redirect channel welcome notices to the channel buffer; such notices have the nick as target but a channel name in beginning of notice message, for example notices sent by freenode server which look like: "[#channel] Welcome to this channel..."

To be exact, these notices aren't sent by *freenode server*, but *Atheme IRC Services*.

**Comment by flashcode** [comment]
The sentence mentions "from freenode server" versus "from a user". So even if it's sent by Atheme IRC Services, from WeeChat point of view, it comes from the IRC server where you are connected to.

**Comment by Mikaela** [comment]
I think coming from nickname ChanServ rather than whatever.freenode.net it's closer to coming from user than IRC server. Do I also become a IRC server if I `/notice FlashCode [#weechat] Hello` which is what is done?

In case you wish for upstream documentation, I would suggest `/msg chanserv help set ENTRYMSG` which I think this setting is talking about.

**Comment by Mikaela** [comment]
Proposal:

> ...for example ENTRYMSGs sent by Atheme IRC Services which look like: "[#channel] Welcome to this channel..."

I think saying ChanServ would be wrong as Atheme isn't the only IRC Services package and BotServ can be used to rename ChanServ on per-channel basis.

**Comment by flashcode** [comment]
OK, done.
