### ISSUE TITLE
Relay debug messages in main weechat buffer are printed repeatedly

### ISSUE THREAD

**Issue by davemulford** [weechat/weechat#1101]
The following messages are printed in the `weechat` buffer a few times per second.

    debug: adding hook: type=2 (timer), plugin="relay", priority=1000
    debug: removing hook: type=2 (timer), plugin="relay"

I've looked in `/help`, `/set relay.*`, and the [weechat relay docs](https://weechat.org/files/doc/stable/weechat_user.en.html#relay_plugin).

Is there any way to suppress these messages?

### Environment
- Fedora 25 64-bit
- Weechat 1.9, from the Fedora dnf package

**Comment by flashcode** [comment]
Hi,
You have probably enabled the debug for core (such messages are not displayed by default). Try: `/debug set core 0`

**Comment by davemulford** [comment]
Thank you! I don't remember enabling that debug flag, but I'm sure it's my fault. I'll close this issue now.

Thanks again!
