### ISSUE TITLE
weechat.look.input_share = all is non-functional

### ISSUE THREAD

**Issue by netzverweigerer** [weechat/weechat#1104]
weechat.look.input_share set to all won't share input history among different buffers, tried on multiple machines with multiple versions/setups.

**Comment by netzverweigerer** [comment]
nb: Weechat version I tested with here is WeeChat 1.6 on Alpine Linux:
weechat-1.6-r2

**Comment by weechatter** [comment]
Option works for me as expected.
/help weechat.look.input_share
description: share commands, text, or both in input for all buffers (there is still local history for each buffer)

Means, the "content" from the "input bar" will be shared to next buffer, NOT the command history. For a global command history use "/input history_global_previous" its assigned to ctrl-<arrow up>

**Comment by flashcode** [comment]
As @weechatter said, the option is not used to share history, but just share the input when you switch buffer (the input is kept while switching active buffer).
For the global history, default keys are ctrl-up/down and if needed you can bind that on up/down, see the FAQ here: https://weechat.org/files/doc/devel/weechat_faq.en.html#global_history

**Comment by netzverweigerer** [comment]
Thanks for the explanations. :-)
