### ISSUE TITLE
Fails to install on High Sierra

### ISSUE THREAD

**Issue by ahmedelgabri** [weechat/weechat#1106]
Since I already opened this by mistake when I was searching for a solution, I won't bloat the issues & I'll reopen this. If this is ok (and apologies for that)

I can't install weechat on High Sierra with this error. I opened an issue in homebrew already https://github.com/Homebrew/homebrew-core/issues/20921 but I think it might be an issue with weechat since the error is during the build & related to cmake (I think)

<img width="1666" alt="screen shot 2017-11-24 at 10 22 13" src="https://user-images.githubusercontent.com/63876/33203761-72d6d28c-d101-11e7-8aa4-5a51f8288e47.png">

**Comment by ahmedelgabri** [comment]
Sorry mistake

**Comment by flashcode** [comment]
Still the same problem?
Please check that gcrypt lib is installed.

**Comment by ahmedelgabri** [comment]
I already tried removing & reinstalling `libgcrypt` & it didn't work

**Comment by ahmedelgabri** [comment]
Fixed here https://github.com/Homebrew/homebrew-core/issues/20921#issuecomment-347298441 I had to reinstall `libgcrypt` & `libgpg-error`
