### ISSUE TITLE
core: allow creation of buffers

### ISSUE THREAD

**Issue by mumixam** [weechat/weechat#1113]
I would like to be able to create buffers without having to use a API function to do so.
`/buffer create newbuf`
I would also like to see a switch added to /print to create a buffer if it doesn't exist
`/print -buffer core.test -create my message`

**Comment by flashcode** [comment]
Feature implemented.

The commands `/buffer` and `/print` have been updated, the syntax is:

    /buffer add [-free] [-switch] <name>
    /print -newbuffer <name> [-free] [-switch]
