### ISSUE TITLE
forgotten passphrase .. how to start again?

### ISSUE THREAD

**Issue by laymonk** [weechat/weechat#1115]
Hello,

I have a somewhat embarrassing situation where I forgot my secure passphrase, and could not use weechat for a while.  I held out hoping to remember the passphrase, but I'm still unable to.  

So, I bit the bullet and skipped the passphrase .. 

Now, my challenge is how to start again .. 
* Weechat will not allow me to set a new passphrase, nor to delete old encrypted data, nor anything really .. all commands result in:
```
You must decrypt data still encrypted before doing any operation on secured data or passphrase
```
* So, we check `/secure' and see .. 
```
Hash algo: sha256  Cipher: aes256  Salt: on
Passphrase is not set

Secured data STILL ENCRYPTED: (use /secure decrypt, see /help secure)

  secret1
  secret2
  blahsecret
  more secrets
```
* But decrypt commands are not working because although the passphrase is not set, entering a single space or nothing at all has not worked .. meanwhile, the secure feature suggests that the only solution is to first decrypt and would not accept any other commands (even to set a new passphrase)

Please, how do I get out of this .. I don't care about the current secrets and would rather delete and recreate them .. I just want to start using the /secure feature again, and start anew.

Thanks in advance ..

**Comment by stfnm** [comment]
Try deleting the file ```~/.weechat/sec.conf```.

**Comment by laymonk** [comment]
DOH, I knew it was going to be something simple like that ..  but understandably not well advertised ..

Thanks a million for the quick response .. and I can confirm this works and allows me to start over.
