### ISSUE TITLE
weechat 2.0 crashes always on exit

### ISSUE THREAD

**Issue by mschaaf** [weechat/weechat#1118]
I am running weechat 2.0 on ubuntu 16.04.1
I have debug symbols install for libc and weechat and have the following crash file collected.

[_usr_bin_weechat.1000.crash.gz](https://github.com/weechat/weechat/files/1571404/_usr_bin_weechat.1000.crash.gz)

**Comment by flashcode** [comment]
Hi,
This could be related to guile plugin (see #779).
Could you please try to disable just this plugin and test:

    /set weechat.plugin.autoload  "*,!guile"
    /save
Then start WeeChat again.
Or you could try to start WeeChat without any plugin to check if there's a crash on exit: `weechat -p`.

**Comment by mschaaf** [comment]
Yes, it seems it is the guild plugin. After not loading it weechat exits without crash.
Thanks for your help.
I will close it as a duplicate of #779
