### ISSUE TITLE
Provide a way for a weechat to be run headless

### ISSUE THREAD

**Issue by sferich888** [weechat/weechat#1120]
Weechat should have the capability to be run headless for several reasons! 

1. For the use, as a proxy or gateway
   - Running weechat as a proxy or gateway using ncusess is/can be problematic when trying to deal with docker containers or other environments that simply have no need for actually interacting with weechat via the cli. 
2. For the purposes of configuration (in an automated fashion). 
   - Today the configuration of weechat is VAST and the recommended approach is to use commands to configure your tool. However, recording these commands and sharing them with friends cannot always yield the same results. 
        - As the product does not [recommend modifying configuration files](https://weechat.org/files/doc/devel/weechat_faq.en.html#editing_config_files) automating or rebuilding your irc layout can be challenging (or force you to not follow the documented recommendations). see [Bug 1526634](https://bugzilla.redhat.com/show_bug.cgi?id=1526634)

Providing a way for weechat to be run without a tty or in a headless mode could position the product to better accept new technology paradigms (like containers, and automation for configuration).

**Comment by AGausmann** [comment]
I'm also interested in this feature. Weechat is nearly as popular (if not more) as a relay server as it is for being a single-instance client. Being able to run as a headless daemon that does not depend on a TTY would be fantastic for things like deploying the relay in a Docker container (as I am interested in doing)
