### ISSUE TITLE
Allow donating BTC or other cryptocurrencies

### ISSUE THREAD

**Issue by squigglezworth** [weechat/weechat#1126]
It seems several people want to donate either specifically with BTC, or anonymously.

**Comment by flashcode** [comment]
Hi,

I allowed some days ago the donation via Liberapay, which has very low fees: https://weechat.org/about/donate/

Donations via BTC or cryptocurrencies are not planned for now, not enough time on my side to setup that.
Anyway, even if it's allowed, an issue could be created on the web site repository (it's not related to WeeChat itself): https://github.com/weechat/weechat.org

**Comment by squigglezworth** [comment]
All good points. Apologies for the wrong repo. That didn't click for me :)
