### ISSUE TITLE
Compilation not functional on Subsystem

### ISSUE THREAD

**Issue by clragon** [weechat/weechat#1128]
![screenshot_1](https://user-images.githubusercontent.com/11785085/34630250-b281aafc-f26b-11e7-865c-f140166f0b11.png)

Cannot compile it, since the subsystem seems to mess with the variables and make takes the wrong Python installation? is there a way to fix this?

**Comment by flashcode** [comment]
Hi,
Is python installed with the official packages of the distribution, or is it compiled manually in a custom directory?

**Comment by clragon** [comment]
Yes, python is instaleld on my Subsystem, Ubuntu bash, 2.7 and 3.6 and 3.6 is installed on my Windows 10 host system. For whatever reason, when tryign to install weechat, it tries to use the windows installed python since the subsystem imports host system variables. this results in it trying to find io.h which doesnt seem to exist (probably either windows or linux only library) and then in compilation failure. weirdly enough, I installed weechat successfully just a few days ago on the same subsystem....

**Comment by flashcode** [comment]
You could try to completely remove your build directory, run cmake again and compile.
I just tried to do that and it works fine (my subsystem version is Ubuntu/Trusty, the default one).
So I'm not able to reproduce your problem.
