### ISSUE TITLE
Get backlogs for queries only.

### ISSUE THREAD

**Issue by roughnecks** [weechat/weechat#1132]
Hi there.

If you aren't running weechat 24/24H it's kinda pointless to get channels backlogs, because you probably missed quite a lot of content anyway, while queries do make more sense.

So it would be nice to have a weechat's backlogs setting for queries only.

Cheers.

**Comment by flashcode** [comment]
Done, you can set this new option:

    /set logger.look.backlog_conditions "${type} == private"
