### ISSUE TITLE
Option to dump state file (like /upgrade -quit does) upon receiving a SIGTERM.

### ISSUE THREAD

**Issue by skyhighwings** [weechat/weechat#114]
This would be nice because my weechat sessions occasionally get killed and I would like to not lose any of the state I can keep.

**Comment by flashcode** [comment]
With this commit, you can use the signal "signal_sigterm" in a trigger to run a custom command (and return "ok_eat", so that WeeChat ignores the signal).

For example: 

    /trigger add sigterm signal signal_sigterm "" "" "/upgrade -quit" "ok_eat"
