### ISSUE TITLE
alias: allow arbitrary text to be passed from arguments into /exec

### ISSUE THREAD

**Issue by foghawk** [weechat/weechat#1140]
I have a script which prints some information and lets me add a comment. I would like to be able to call this script from WeeChat using an alias, with `$*` capturing the comment to add, without manually escaping the comment's plain text. However, AFAICT there is no way to do this without mangling it in some way.

Since `/alias`'s `$*` expands the argument list directly into the command it calls, there is no point at which I can consume the text as written. `/exec -sh` will choke on apostrophes, while `-nosh`, although it handles most characters safely, _strips_ some quotes (regardless of whether the alias's `$*` has been protected by single or double quotes or none at all). Single (unescaped) quotes work only in double quotes, and double quotes only in single, so there is no quotation level I can choose for the alias which will work for all comments.

Adding a variant of `$*` to `/alias` which automatically escapes the arguments (to either shell or `-nosh` standards) would solve my problem, and seems like the best way to do so.

(Possible alternatives include changing the `-nosh` behavior—which I found surprising—and, provided `/exec`'s `-inclose` does not have a similar problem, allowing it to be used when a process is started and not just while it is running.)

**Comment by flashcode** [comment]
Hi,
Just to clarify, could you please give an example of what you want to do, and what you expect as result?

**Comment by foghawk** [comment]
I would like a way to get a string from my command line into a script called by `/exec`, unaltered, without escaping characters within it by hand. I don't care how, but one way might be to have something like:

`/alias add out /exec -o echo "$&"`

with `$&` like `$*`, except that it automatically escapes double quotes (or single quotes, doesn't matter). Then the command

`/out "scare" quotes`

would expand to `/exec -o echo "\"scare\" quotes"` (instead of `/exec -o echo ""scare" quotes"` as with `$*`), so that the text I supplied to `/out` would appear in my output exactly as I typed it.

(The script I mentioned in my original post is more complicated than echo, so I do have reasons for not wanting to send input normally.)

Does that help?

**Comment by JKirchartz** [comment]
I think this is an excellent addition to Weechat - but if you don't want to or can't compile Weechat with this patch I've seen a way to use triggers to escape strings, from @pascalpoitra here: 

https://gist.github.com/pascalpoitras/8406501#escape
