### ISSUE TITLE
move config files from ~/.weechat to ~/.config/weechat

### ISSUE THREAD

**Issue by nekoswag** [weechat/weechat#1141]
Config files should not be in the home directory directly.

**Comment by weechatter** [comment]
you can place config wherever you want, use "weechat -d".

For example:
weechat -d ~/.config/weechat

**Comment by flashcode** [comment]
Some people asked to have multiple directories for storing config, logs, scripts, ... (not with the same parent).
This is not possible, you can just change the WeeChat home directory with everything inside.
If that's what you want I can reopen the issue as enhancement.
