### ISSUE TITLE
Make logger fsync log files when flushing

### ISSUE THREAD

**Issue by autrilla** [weechat/weechat#1145]
Currently weechat calls fflush (https://github.com/weechat/weechat/blob/master/src/plugins/logger/logger.c#L608 and https://github.com/weechat/weechat/blob/master/src/plugins/logger/logger.c#L846) when flushing the log files. However, this can cause the files to never end up on disk (or whatever storage medium). In my particular case, I've tried to set up `gcsfuse` to store all my weechat configuration and logs on Google Cloud Storage, and the files are not transferred to GCS until either weechat is closed (and therefore so are the log files) or I manually run sync or fsync. It would be nice for the log files to be synced to the underlying physical storage whenever the logger flush timer runs. Would this change be acceptable?

I'm not sure whether this should be considered a bug or a feature request.

**Comment by weechatter** [comment]
and option logger.file.flush_delay does not help?

**Comment by flashcode** [comment]
I can add an option similar to weechat.look.save_config_with_fsync but in logger plugin for log files. Please note that this is extremely slow to do that (20 to 200x slower, so weechat may freeze some seconds in worst case), so maybe it could be done only after the flush (so not at each write in a file). Would that be OK for you?

**Comment by flashcode** [comment]
@autrilla: I'll add the option, no need for a patch, thank you. I'll just add a boolean to perform an fsync on each flush if enabled (off by default).
