### ISSUE TITLE
weechat is stuck while loading: reading from stdin times out

### ISSUE THREAD

**Issue by TomasTomecek** [weechat/weechat#1150]
Hi, I have a weird bug report for you. Before I unleash gdb, I would love to hear some opinion. I am running weechat 2.0.1 in a linux container -- it gets stuck and this is what strace tells me:

```
poll([{fd=0, events=POLLIN}], 1, 999)   = 0 (Timeout)
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2272, ...}) = 0
fcntl(0, F_GETFD)                       = 0
poll([{fd=0, events=POLLIN}], 1, 999)   = 0 (Timeout)
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2272, ...}) = 0
fcntl(0, F_GETFD)                       = 0
poll([{fd=0, events=POLLIN}], 1, 998)   = 0 (Timeout)
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2272, ...}) = 0
fcntl(0, F_GETFD)                       = 0
poll([{fd=0, events=POLLIN}], 1, 998)   = 0 (Timeout)
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2272, ...}) = 0
fcntl(0, F_GETFD)                       = 0
poll([{fd=0, events=POLLIN}], 1, 999)   = 0 (Timeout)
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2272, ...}) = 0
fcntl(0, F_GETFD)                       = 0
```

I literally don't understand how stdin is able to timeout. I invoke bash inside the container and then run weechat like this:
```
$ weechat -s -a -p
```

I even tried other terminal interactive applications and they work just fine (e.g. htop).

**Comment by mumixam** [comment]
have you tried setting TZ? to prevent polling of /etc/localtime?
```
TZ="Europe/Paris" weechat -s -a -p
````

**Comment by TomasTomecek** [comment]
That was easy! And it works.

I'm actually mounting `/etc/localtime` from host to the container. This is a systemd-based distro and the file is actually a symlink. Host:
```
/etc/localtime -> ../usr/share/zoneinfo/Europe/Bratislava
```

Container:
```
/etc/localtime -> ../usr/share/zoneinfo/Etc/UTC
```

Seems like that weechat can't deal with UTC -- would be awesome if it error'd out telling me that I should set a timezone.

**Comment by TomasTomecek** [comment]
It seems the culprit is that the container engine does not set configure tty correctly. Reported it over there: https://github.com/projectatomic/libpod/issues/351#issuecomment-366499920 Feel free to close this one if you think that weechat can't do anything about this.

**Comment by flashcode** [comment]
Hi,
I think this is not a WeeChat issue, and I'm not sure if WeeChat itself has control on that (if you think WeeChat can enforce something, please let me know).
So I close the issue.
