### ISSUE TITLE
WEECHAT SHOULD UPPERCASE NICKS IF I TAB-COMPLETE THEM WHILE USING CAPSLOCK

### ISSUE THREAD

**Issue by pragma-** [weechat/weechat#1153]

**Comment by flashcode** [comment]
Hi,

WeeChat runs in terminal and I think there is no way to know if your CAPS LOCK key is enabled or not.

The only thing WeeChat could do is to complete to upper case if you type upper case letters to complete, but then this should be smart enough: in some cases, when the nick begins with an upper case letter, you might want to type an upper case letter and complete to lower case.
