### ISSUE TITLE
Wrong dependency for weechat-devel-php package in Ubuntu Bionic 

### ISSUE THREAD

**Issue by PaulW2U** [weechat/weechat#1154]
OS: Ubuntu 18.04 (Bionic)
Weechat: 2.1-dev

The latest build of weechat-devel-php for Ubuntu Bionic (2.1-1-dev20180305) depends on libphp7.1-embed but this package is not available in new installations of Ubuntu Bionic. It may available if an Artful release has been upgraded by changing the repository names rather than using the official upgrade process which would delete this package after installing the updated version which is libphp7.2-embed.

Trying to install weechat-devel-php gives the following terminal output:
```
sudo apt install weechat-devel-php
[sudo] password for paul: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 weechat-devel-php : Depends: libphp7.1-embed but it is not installable
E: Unable to correct problems, you have held broken packages.
```
See also https://packages.ubuntu.com/bionic/libphp-embed

**Comment by flashcode** [comment]
Hi,
Thanks for reporting the problem.
This should be fixed in the next Debian build (in about 4-5 hours for Ubuntu Bionic).
