### ISSUE TITLE
List (/list) channels on a specific server

### ISSUE THREAD

**Issue by JuanKman94** [weechat/weechat#1165]
* **Version**: WeeChat 2.0.1 [compiled on Jan 31 2018 10:58:17]
* **OS**: Fedora 27 64-bit

The current `/list` command does not work properly when trying to list channels on a specific server.
According to `/help list`

```
[irc]  /list  [<channel>[,<channel>...]] [<server>] [-re <regex>]
```

But when invoking the command there's no way to tell weechat what server to query, e.g.,

```
/list myserver -re #myre.*
```

## Actual result

```
Bad list syntax, type /QUOTE HELP LIST
```

## Expected result

A list (empty or not) of channels on the specified server

Perhaps a `-server` keyword could be added to the parameters in way similar to the `/join` command

**Comment by sim642** [comment]
Unfortunately the meaning of `<server>` on that command is somewhat unexpected and different from other uses. [In RFC 2812](https://tools.ietf.org/html/rfc2812#section-3.2.6) it is defined as which specific server on the network should do the listing and this is why the argument is in such inconvenient order and doesn't seem to work — it does something completely different. Weechat simply provides the protocol command as is.

Currently you can run `/list` on a specific server using `/command`, which allows running commands on different Weechat buffers.

Adding a `-server` flag would provide a more convenient built-in way to do that but would also create additional confusion if the syntax was like
```
/list  [<channel>[,<channel>...]] [<server>] [-re <regex>] [-server <server>]
```

Maybe the existing original wording should be changed (to `<target>` like in the RFC) before adding the flag to avoid any confusion and additional explanations added to clarify its use, which is rather obscure.
