### ISSUE TITLE
Setting split_msg_max_length to 0 makes local echo weird

### ISSUE THREAD

**Issue by lieuwex** [weechat/weechat#1173]
I don't really have any clue if this is a problem with my setup, but as far as things are looking right now, when I set split_msg_max_length to 0 on a server. It breaks local echo message echo:

Suppose my name is 'Lieuwex' and I send a message to 'Alice'.

For example, with `split_msg_max_length=null`:
```
> hello!
Lieuwex | hello!
```

With `split_msg_max_length=0`:
```
> hello!
Lieuwex | Alice :hello!
```

So it seems to just echo back everything after the `PRIVMSG`.

It seems like a weird unconnected problem, but I can reproduce on multiple networks.

**Comment by flashcode** [comment]
Thanks for reporting, it is fixed.
The bug was introduced with the new server option "split_msg_max_length" in version 2.1.

**Comment by lieuwex** [comment]
That was quick!
Thank you :)
