### ISSUE TITLE
Channel name prepended to sent messages on upstream inspircd

### ISSUE THREAD

**Issue by f0o** [weechat/weechat#1179]
## Bug, feature, or question?
Bug

## Current behavior
Weechat prepends the current channel name to every message sent to a server running inspircd 2.0.25.

## Steps to reproduce

1. Start inspircd 2.0.25
2. Connect to via weechat
3. Join a Channel (such as `#test`) and write anything
4. See line like: `08:51:21 @f0o | #test :foobar`

## Desired behavior
Don't prepend channel names to messages

## Suggested solutions
Honestly no clue, the IRC protocol looks like RFC standard.
It does use IRCv3, maybe there's a bug somewhere in that on weechat?

## Additional information
Works fine in irssi, raw-sockets, hexchat..

---

- WeeChat version: 1.5 (upstream epel-release) + 1.9.1 + 2.1
- OS, distribution and version: CentOS 7.4.1704 + Gentoo

**Comment by flashcode** [comment]
Hi,
Is there any public inspircd server where I can test this behavior?

**Comment by f0o** [comment]
Sure thing, join irc.voodoo.systems port 6697 SSL (let's encrypt)

I also noticed this is the case for Queries :/

**Comment by weechatter** [comment]
is it maybe related: https://github.com/weechat/weechat/issues/1173

**Comment by f0o** [comment]
@weechatter if the issue was introduced in 2.1, how is it affecting 1.5 and 1.9.1 as well?

for the record:
```
irc.server.a.split_msg_max_length            integer  null -> 512
irc.server.b.split_msg_max_length            integer  null -> 512
irc.server.c.split_msg_max_length           integer  null -> 512
irc.server.d.split_msg_max_length             integer  null -> 512
irc.server.e.split_msg_max_length           integer  null -> 512
irc.server.f.split_msg_max_length             integer  null -> 512
irc.server_default.split_msg_max_length            integer  512
```

**Comment by f0o** [comment]
I think I solved it.

The network had maxlength for nicks etc set to 1024, once lowered to defaults it started to work fine again

**Comment by f0o** [comment]
Closing as it was related to nick/chan length being advertised as >512 from the server
