### ISSUE TITLE
Starting WeeChat overrides custom tmux window names

### ISSUE THREAD

**Issue by bddenhartog** [weechat/weechat#1182]
## Bug, feature, or question?

Bug

## Current behavior

Custom tmux window name is overridden when starting Weechat

## Steps to reproduce

1. Attach to an existing tmux session or create a new one
2. Set a custom window name (`tmux rename-window potato`)
3. Start weechat in that window
4. See the name change to `WeeChat 2.1`

## Desired behavior

Starting weechat shouldn't change my existing (custom) tmux window title. By default, tmux window names are set to the active program's name. In the default (and desired) case, a new window title is equal to the name of your shell, and would automatically change to `weechat` when executing the binary.

## Suggested solutions

Based on weechat/weechat#685, my understanding that this is the intended behavior. I would suggest, then, to only change the tmux window name if it is not equal to that of the current shell. This would retain the behavior for those that don't use a custom naming scheme for their windows, and would enable those that wish to, not have to manually change the name _after_ loading weechat.  

---

- WeeChat version: 2.1
- OS, distribution and version: Arch Linux

**Comment by flashcode** [comment]
Hi,
This is controled by the option `weechat.look.window_title` which is not empty by default and causes the terminal title to be always updated.
I agree with the fact that it could be annoying, so I suggest to just use an empty value by default in this option, and show the current default value (`WeeChat ${info:version}`) as an example in `/help weechat.look.window_title`, so that the user can set if needed.

**Comment by bddenhartog** [comment]
>I suggest to just use an empty value by default in this option, and show the current default value (WeeChat ${info:version}) as an example in /help weechat.look.window_title, so that the user can set if needed.

Agreed that this would be a good solution.

**Comment by trygveaa** [comment]
IMO, I don't think the default title should have been removed. It is useful that programs set the title so you get useful titles with the default config. Bash by default sets the current directory as the title each time you change directory, so I can't really see how it's an issue that processes sets the title. If that's an issue for you, you should configure tmux to not use the title.

Though, when it comes to tmux, I see that at least with the most recent version now (3.2) it separates the window title and terminal title, so if you set a window title it is not overridden by WeeChat even if it sets a title.
