### ISSUE TITLE
no libv8-dev for arm64(aarch64), is there an alternative??(stuck with version 1.6)

### ISSUE THREAD

**Issue by rjshaver** [weechat/weechat#1184]
Feature request:  no Javascript support for arm64 devices, is there an alternative library for libv8-dev for the arm64 architecture?

Recently, I purchased a Rock64 from Pine64.org.  I was hoping that the version 2.1 for armhf would be available for my new purchase.  Soon, I saw rather quickly that I could not use the armhf repos to install on my little SBC.  I did not try to force the installation but knew I could download and compile the source code.  While trying to complete all the dependencies with 'sudo apt-get build-dep weechat' which worked well except for the libv8-dev package.  After searching for it under the debian arm64(aarch64) packages, I found that it has not been built.  I was not sure if I could find and build this library from the source code(do not know where to find source and dependencies).  

So, I decided to compile with 'cmake -DENABLE_JAVASCRIPT=OFF'.  It works and I have gotten it to run but it may be missing some functionality for some scripts.  

Is there a solution for this missing feature?  Either an alternative library for javascript functionality or a way to compile libv8-dev. 

It seems to work well when I was running it.  I plan on recompiling on Ubuntu-Mate when I finished another feature, so it would be good to have a solution and not have to be concerned about any missing functionality.

Thanks so much for any information you might have available on compiling weechat on arm64.

Weechat 2.2-1.
Ubuntu stretch (on Rock64 SBC with aarch64 architecture, arm64)

**Comment by weechatter** [comment]
If you want javascript and its not available on your system, you'll have to compile javascript yourself.
To be honest, there is only one script written in javascript for WeeChat. Why do you need javascript plugin
for WeeChat, do you want to write your own scripts in javascript?
Javascript-Plugin is nice to have but really not necessary, you are missing at least *one* script so far.

**Comment by rjshaver** [comment]
So, for confirmation, I would need to find the source for libv8-dev and compile.  I may just be able to use another language, but wanted to check first before struggling with something that is an easy fix.  Thanks much for your time.  Great product.  Keep up the great work!!
