### ISSUE TITLE
Buffer property for default completion template

### ISSUE THREAD

**Issue by sim642** [weechat/weechat#1189]
## Bug, feature, or question?
Feature

## Current behavior
Default completions must be specified in the `weechat.completion.default_template` option, which applies to all buffers. It's not possible for a plugin/script to use a different `default_template` in the buffers it creates to provide some specific suggestions.

## Suggested solutions
Buffer's should maybe also have a `default_template` property that overrides the option if set. This would allow a plugin to set the property with its custom default template for its own buffers and provide custom buffer-specific completions.

## Additional information
Technically a plugin could append its desired completion to the option as well but that then applies to all buffers, which might be undesirable if it doesn't make sense in other buffers. It's also not ideal that a plugin would modify options programmatically on the user's behalf, especially since something could go wrong if the `default_template` option is already customized.

_This has come up regarding Slack server-specific custom emoji completions: https://github.com/bqv/weechat-slack/issues/3 and https://github.com/bqv/weechat-slack/commit/5217251e94b2e5ea54a48ac660cb303257489f91#commitcomment-28954893._

**Comment by bqv** [comment]
Tracking this with bqv/weechat-slack#10

**Comment by bqv** [comment]
Can I suggest that the buffer local variable not override `default_template`, but rather extend it? That way, users can customize `default_template` and retain their extra completions while also retaining plugin-specific completions.

**Comment by flashcode** [comment]
Hi,

This was implemented with #1600 in version 3.1, in this commit: 0294b246f6e6697022068265e74c9b66795fae42.
As the option is evaluated it is possible to either replace or extend the default completion, as explaing in the commit message.

So I close this issue as duplicate.
