### ISSUE TITLE
Verbose connect to server?

### ISSUE THREAD

**Issue by PanosFirmpas** [weechat/weechat#1191]
## Bug, feature, or question?
Question

## Current behavior
│11:55:35 freenode  -- | irc: connecting to server chat.freenode.net/6667...
│11:56:35 freenode =!= | irc: timeout
│11:56:35 freenode  -- | irc: reconnecting to server in 10 seconds
│11:56:45 freenode  -- | irc: reconnecting to server...
│11:56:45 freenode  -- | irc: connecting to server chat.freenode.net/6667...
│11:57:45 freenode =!= | irc: timeout
│11:57:45 freenode  -- | irc: reconnecting to server in 20 seconds
│11:58:05 freenode  -- | irc: reconnecting to server...
│11:58:05 freenode  -- | irc: connecting to server chat.freenode.net/6667...

## Desired behavior
I'm admittedly new to this, but I'm completely stuck as I can't find any further  information on what I could do now to troubleshoot this issue.    
It times out: no google results about it timing out, no github issue results about timing out,
no verbose option for the connection, nothing
It's probably the %#$%#$% proxy setting of my work network but how can I confirm that?
    
So where do I go from here?

- WeeChat version:  2.1
- OS, distribution and version:  Debian Stretch up-to-date

**Comment by flashcode** [comment]
Hi,
If you need a proxy to reach the freenode server, did you set the option `irc.server.freenode.proxy`, and did you define the specified proxy with `/proxy add <name> ...` (see `/help proxy`)?

**Comment by flashcode** [comment]
By the way, if there's no answer at all on the connection (for example your proxy completely discard the connection attempt without any feedback), WeeChat can not display more info for this problem. On WeeChat side, it's just a timeout (ie nothing received).

**Comment by PanosFirmpas** [comment]
Hi thanks for the quick reply !    
    
I set the proxy in the same way that we usually set in the OS's "Network" settings
I tried with port 0 (cause that's what I have in my system's SOCK proxy ) in which case nothing changed,
then I tried with port 8080 which seems to be the proxy's ... default??... port in which case this happens:

│12:31:39 freenode  -- | irc: connecting to server chat.freenode.net/6667 via http proxy <name1>.<name2>.<countrycode>/8080...
│12:31:39 freenode =!= | irc: proxy fails to establish connection to server (check username/password if used and if
│                      | server address/port is allowed by proxy)
│12:31:39 freenode  -- | irc: reconnecting to server in 10 seconds
│12:31:49 freenode  -- | irc: reconnecting to server...
│12:31:49 freenode  -- | irc: connecting to server chat.freenode.net/6667 via http proxy <name1>.<name2>.<countrycode>/8080...
│12:31:49 freenode =!= | irc: proxy fails to establish connection to server (check username/password if used and if
│                      | server address/port is allowed by proxy)
│12:31:49 freenode  -- | irc: reconnecting to server in 20 seconds



So I guess the proxy is blocking the port and I'm SOL?

**Comment by flashcode** [comment]
The proxy is maybe blocking the port 6667.
In this case you could try as a workaround to make a ssh tunnel to a machine outside your network, and use that as a gateway to reach the IRC server.
You could also try with other IRC clients to check if you can connect.
If the proxy is blocking, then for me it's not a WeeChat issue.

**Comment by PanosFirmpas** [comment]
Alright, thanks for the help ! :)
