### ISSUE TITLE
ctrl-w inconsistenly deletes spacing

### ISSUE THREAD

**Issue by pushcx** [weechat/weechat#1195]
In version 2.1 on current Arch Linux, `ctrl-w` to delete the previous word acts inconsistently. Normally it acts like `ctrl-w` [in readline](https://www.gnu.org/software/bash/manual/html_node/Readline-Killing-Commands.html):

> *C-w*
> 
> Kill from the cursor to the previous whitespace.

However WeeChat has a bug: when the word preceeding the word to be deleted ends in a comma or period, the space is also deleted.

> normal behavior, text before:
>     foo bar|
> text after:
>     foo |

> buggy behavior, text before:
>    foo. bar|
> text after:
>    foo.|

This is a very small but very distracting bug - rather than backspace to try to correct typos, I hit `ctrl-w` to remove the entire previous word and replace it. Because of the bug, I often end up with clauses or sentences run together without a space.

The only issue I could find similar to this was #599, but I don't think either issue is the root cause of another.

**Comment by flashcode** [comment]
And "funny", if you type `abc... def` then ctrl-W, only `abc.` remains in input (without the space), so it strips all non-word chars except one, and it strips the space, as you noticed.
I'm fixing this problem.

**Comment by pushcx** [comment]
Ah, I get it, it's deleting back to one character after the previous alphanumeric! `foo  bar|` -> `foo |` Interesting behavior, and thanks for tackling this. :)

**Comment by flashcode** [comment]
What's the issue number you found? #599 seems not related to this problem (it's a typo in German translation).

**Comment by flashcode** [comment]
Ah, found it, #559. It's a bit different, but once I fixed this problem, I can introduce a new option to implement the new feature (different behavior between ctrl-W and alt-backspace).

**Comment by flashcode** [comment]
Fixed.
@pushcx: please confirm if everything is OK for you now. Thanks.

**Comment by pushcx** [comment]
Yep, it works. I played around with more punctuation and it doesn't exactly match readline's ctrl-w behavior in a string like `foo (bar) baz`, but I'm not concerned by a corner case on a corner case, the bug I reported is fixed. Thanks!

**Comment by flashcode** [comment]
Hi,
@pushcx: thanks for testing, good news.
Please tell me the case which is not working right, I'll make some tests and fix if there's still a bug.
By the way, do you know you can customize the chars WeeChat considers as part of word?
So for example you can tell WeeChat to remove all chars except spaces with this command: `/set weechat.look.word_chars_input  "!\u0020,*"`
Or you can do a mix between that and the default value.

**Comment by pushcx** [comment]
I did see the setting, but didn't know how many commands it would affect.

So with cursor starting at the end of the string `foo (bar) baz`, the `|`s indicate where each `ctrl-w` stopped:
* readline in bash: `|foo |(bar) |baz`
* weechat: `|foo |(|bar) baz`

This is just me playing around for a few minutes, I don't know `readline` so well that I can generate meaningful test cases or explain its behavior. I certainly don't mind if this issue stays closed without further code changes.

**Comment by flashcode** [comment]
To have the same behavior as readline, you can change the value of option to mention that parentheses are part of words: `/set weechat.look.word_chars_input "!\u00A0,-,_,|,(,),alnum"`
