### ISSUE TITLE
${cut:} but keep the suffix

### ISSUE THREAD

**Issue by adtac** [weechat/weechat#1200]
## Bug, feature, or question?

Feature request: `${cut:5,+,"longstring"}$` currently results in `"longs+"`. I would like keep the *last* five characters instead of the first five characters. That is, I'd like to have a function that would result in "+tring".

Use-case: A lot of the channels I'm connected to have a same prefix. This information is useless to me, and it's easier to switch channels if I know the suffix.

## Current behavior

This feature does not exist.

## Steps to reproduce

N/A

## Desired behavior

I'd like to have a function that would allow me to keep the last `n` characters of a string (just like `${cut:}` allows me to keep the first `n` characters of a string).

## Suggested solutions

I can see two solutions:

 - Implement a function that does exactly this.

 - Implement a `${rev:}` method that would reverse a string. If this is done, I can achieve the required effect by using a double reverse: `${rev:${cut:5,+,${rev:"longstring"}}}` would result in `"+tring"`. I think this solution is more robust as it would allow the `rev` method to be used elsewhere too.

## Additional information

N/A

---

- WeeChat version: 2.2-dev (compiled from `master`)
- OS, distribution and version: Debian 9.3

**Comment by flashcode** [comment]
Done, the `${rev:xxx}` has been implemented.

**Comment by adtac** [comment]
Well, that was fast! :D 

Amazing, thanks!
