### ISSUE TITLE
Active buffer never unread when connected via a relay

### ISSUE THREAD

**Issue by Ketrel** [weechat/weechat#1206]
## Bug, feature, or question?
Bug/Feature (depending)

## Current behavior
The active buffer does not show as unread (since it's active).
However, when connected via a relay, it also never shows unread there

## Steps to reproduce

1. Have multiple buffers open, and be in one actively (for example, #weechat on Freenode) on the server side
2. Connect via a relay and an android app for example
3. New mess arrives in buffer #weechat and in buffer #freenode
4. On the relay, you will see #freenode is unread, but #weechat has no unread messages

## Desired behavior
1. New message arrives on #freenode and #weechat
2. Both buffers show unread

## Suggested solutions
When at least active relay connection is open, only interacting with a buffer marks it read, be that switching to it, or sending a message to it, etc.  Idling in said buffer would NOT cause it to be marked read if a new message arrive.

Behavior when 0 relay clients are connected could remain unchanged.

--

- WeeChat version: 2.1
- OS, distribution and version: Ubuntu Server 16.04 LTS

**Comment by flashcode** [comment]
Hi,

The relay connections are completely independent of behavior in WeeChat itself, so I'm not sure changing behavior based on the connected clients is a good thing (at least by default, you are free to write a script to do that).

By the way, you can configure the conditions to add a buffer in the hotlist: by default the buffer is added only if you are away or if the buffer is not displayed. You can remove these conditions to update always the hotlist, so that the active buffer is added like any other buffer:

    /set weechat.look.hotlist_add_conditions "1"

**Comment by Ketrel** [comment]
Looking at the default config of that option I see it has the option to check a value such as `${buffer.num_displayed} == 0`

Is there a similar variable for number of connected relay clients?  If so I could use that to achieve the same result.

**Comment by oakkitten** [comment]
a workaround i'm using, switching to buffer `weechat` after some inactivity

    /trigger addreplace idle_timer timer 60000;0;0               
    /trigger set idle_timer conditions ${info:inactivity} >= 600 
    /trigger set idle_timer command /buffer weechat

**Comment by flashcode** [comment]
@Ketrel: yes the number of connected clients is known via an info, so you can set such condition:

    /set weechat.look.hotlist_add_conditions "${away} || ${buffer.num_displayed} == 0 || ${info:relay_client_count,connected} > 0"

For a list of available info by plugin, see: https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_info_get

**Comment by Ketrel** [comment]
@flashcode 

Yes, changing that setting in that way produces the result I was aiming for.  Since that's all done without any coding change, perhaps if that's a more expected behavior, that setting could merely have the default value changed. I'd imagine most people using relays would appreciate this, and it wouldn't change anything for anyone who's not using a relay.

**Comment by flashcode** [comment]
Alright.

I'll add the protocol filtering in the info "relay_client_count" to count only the clients connected with "weechat" protocol (IRC relay is a bit different and should not change the hotlist behavior on current buffer).

So the default value will be:

    /set weechat.look.hotlist_add_conditions "${away} || ${buffer.num_displayed} == 0 || ${info:relay_client_count,weechat,connected} > 0"
