### ISSUE TITLE
PHP plugin not found when compiling on CentOS 7.5.1804 with PHP 7.2

### ISSUE THREAD

**Issue by Chaz6** [weechat/weechat#1207]
## Bug, feature, or question?
When trying to compile weechat on CentOS with PHP 7.2, the php plugin is not found.

## Current behavior
```
$ rpm -q php72u-devel php72u-embedded
php72u-devel-7.2.6-1.ius.centos7.x86_64
php72u-embedded-7.2.6-1.ius.centos7.x86_64

$ ./configure > /dev/null 2>&1; cat config.log
[..]
configure:23590: checking for PHP headers and libraries with pkg-config
configure:23609: checking for PHP headers and libraries with php-config
configure:23614: checking for php-config7.2
configure:23644: result: no
configure:23614: checking for php-config72
configure:23644: result: no
configure:23614: checking for php-config7.1
configure:23644: result: no
configure:23614: checking for php-config71
configure:23644: result: no
configure:23614: checking for php-config7.0
configure:23644: result: no
configure:23614: checking for php-config70
configure:23644: result: no
configure:23614: checking for php-config7
configure:23644: result: no
configure:23614: checking for php-config
configure:23630: found /usr/bin/php-config
configure:23641: result: php-config
configure:23739: checking for PHP compiling and linking
configure:23743: result: no
configure:23748: WARNING:
*** PHP (>=7.0) headers and/or libraries couldn't be found on your system.
*** Try to install libphp-embed with your software package manager.
*** WeeChat will be built without PHP support.
[..]
```

## Steps to reproduce

1. Install php72u and attempt to compile weechat. 

## Desired behavior
Weechat finds php.

## Suggested solutions
I don't know sorry.

## Additional information
configure does not appear to attempt to try compiling a test program.

---

- WeeChat version: 2.2-dev (0f694f57b339c630675ee16e9b9c29b2773e99b0)
- OS, distribution and version: CentOS 7.5.1804 x86_64

**Comment by Chaz6** [comment]
Some more information, the test fails with missing -ledit and -largon2. I resolved this by installing libedit-devel and libargon2-devel. I will feed this back to the IUS maintainers.

**Comment by Chaz6** [comment]
One more note, I had to alter ./configure to change the line
```
                    PHP_LFLAGS="-L$($PHPCONFIG --prefix)/lib/ $($PHPCONFIG --libs) -lphp$l"
```
to
```
                    PHP_LFLAGS="-L$($PHPCONFIG --prefix)/lib64/ $($PHPCONFIG --libs) -lphp7"
```
then it detected the plugin and compiled successfully.

**Comment by flashcode** [comment]
Hi,
CMake is the recommended way to compile WeeChat. Does it work out of the box with CMake ?

**Comment by Chaz6** [comment]
Yes it compiles fine with CMake on CentOS.
