### ISSUE TITLE
Relay tries to set IPV6_V6ONLY on OpenBSD 6.3 which is readonly

### ISSUE THREAD

**Issue by KireinaHoro** [weechat/weechat#1213]
## Bug, feature, or question?

According to [the OpenBSD man page](https://man.openbsd.org/ip6),

> **IPV6_V6ONLY** int *
> Get or set whether only IPv6 connections can be made to this socket. For wildcard sockets, this can restrict connections to IPv6 only. With OpenBSD IPv6 sockets are always IPv6-only, so the socket option is read-only (not modifiable).

As a result, it would be an inappropriate assumption of system behavior to only judge by `#ifdef IPV6_V6ONLY`.  The following is the code snippet in question:

https://github.com/weechat/weechat/blob/ed4837b2f60ffcde770a75fa595f26731575d9e3/src/plugins/relay/relay-server.c#L454-L472

## Current behavior

On OpenBSD systems with IPv6 available, trying to enable relay won't work, giving out the following message: 

```
  weechat =!= | relay: cannot set socket option "IPV6_V6ONLY" to 0: error 22 Invalid argument
```

## Steps to reproduce

1. Install weechat on OpenBSD 6.3
2. Enable relay with `/relay add weechat 9001`
3. Observe weechat window for logs

## Desired behavior

Relay working as usual

## Suggested solutions

Change

```c
#ifdef IPV6_V6ONLY
```

to

```c
#if defined IPV6_V6ONLY && !defined __OpenBSD__
```
---

- WeeChat version: 2.0.1
- OS, distribution and version: OpenBSD 6.3

**Comment by flashcode** [comment]
Thanks, fixed.
Please confirm if this is working well for you (I tested on OpenBSD 6.3, but a confirmation is welcome anyway).

**Comment by KireinaHoro** [comment]
Great, it's working perfectly now. Thanks!

**Comment by flashcode** [comment]
OK, nice.
