### ISSUE TITLE
"/fset -set" truncates long values

### ISSUE THREAD

**Issue by xnrand** [weechat/weechat#1218]
## Current behavior
When "/fset -set" is used either directly as a command or via the fset buffer, the resulting "/set" command will be truncated for config vars with very long values, resulting in an inability to meaningfully edit those values using that feature.  
This differs from iset.pl's behavior which does not truncate the commands/values.

## Steps to reproduce

1. Create a config var with a very long value (>4096 characters)
2. Use "/fset -set conf.ig.var" or press alt+enter on the config var in the fset buffer

## Desired behavior
The resulting /set command should not be truncated. 

## Suggested solutions
Buffer size increase from 4096 to a significantly larger value

---

- WeeChat version: 2.1
- OS, distribution and version: GNU/Linux Ubuntu 18.04 LTS

**Comment by flashcode** [comment]
Thanks for reporting, fixed.
