### ISSUE TITLE
Allow fifo plugin path to be overridden in configuration

### ISSUE THREAD

**Issue by nwf** [weechat/weechat#122]
It'd be great if the fifo plugin could land its named pipe "somewhere else" -- our users' home directories are in AFS and as such do not support named pipes.  Landing them in /tmp, OTOH, is probably fine.  Best would be a configuration knob, of course.

Cheers!

**Comment by grawity** [comment]
`$XDG_RUNTIME_DIR/weechat/` → `$TMPDIR/weechat-$UID/` → `/tmp/weechat-$UID/` would be the best options.

**Comment by flashcode** [comment]
Closing this issue, implemented by #850 in WeeChat 1.7.
