### ISSUE TITLE
no host_* tag when irc_nick_back event ("* (u@h) is back on server") happens

### ISSUE THREAD

**Issue by fejjj** [weechat/weechat#1221]
## Bug summary
trying to suppress 'user is back on server' messages for bitlbee/facebook protocol

## Current behavior
--> | facebook-nick (id@facebook) is back on server [irc_nick_back]

## Desired behavior
--> | facebook_nick (id@facebook) is back on server [irc_nick_back,nick_facebook-nick,host_id@facebook]

---

- WeeChat version: 
- OS, distribution and version: 
uname -a:
Linux cheese 4.15.0-24-generic #26-Ubuntu SMP Wed Jun 13 08:44:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

weechat 2.1

**Comment by flashcode** [comment]
Tags added. I added as well the tag "log4", as a log level, which is the same as the other join/part/quit messages.
