### ISSUE TITLE
!search commands in Channels

### ISSUE THREAD

**Issue by cirojr82** [weechat/weechat#1224]
## Question

Hello everybody. Congratulations for the great work here, your app is awesome.

My question is: when I send commands like "!search linux_mint.iso", "!latest", any command that starts with !, nothing happens. It should list the result of my search, but nothing happens.

Am I doing something wrong or WeeChat doen't support such commands with "!" and listing the results of it?

Thaks!

---

- WeeChat version: WeeChat 1.7.1
- OS, distribution and version: Dietpi (Raspberry Pi)

**Comment by weechatter** [comment]
press CTRL + r  to switch to built-in search mode.
check : https://weechat.org/files/doc/stable/weechat_user.en.html#key_bindings

You can also use the /grep script:
/script install grep.py
