### ISSUE TITLE
Compiling WeeChat w/ Python 3 on macOS breaks

### ISSUE THREAD

**Issue by MindTooth** [weechat/weechat#1229]
## Bug summary
Recently I [submitted a pull](https://github.com/Homebrew/homebrew-core/pull/30228) to the Homebrew repo to enable Python 3.  This did not go without breaking.  [See issue](https://github.com/Homebrew/homebrew-core/issues/30509).  Seems that this has been a problem for a long time, as MacPorts have been running their own set of [patches](https://github.com/macports/macports-ports/commit/7a573aab25511885a6052fa6468d5245dc41f0b7) since 2015 to make it compile.

As the one that submitting the option of Python 3 for Homebrew's WeeChat, I feel that I should report this.  And a few guys could not find any reference that this issue had been reported before.

They strongly suspected that this were related to Python 3.

Thanks for taking a look into this.

## Current behavior
Building with Python 3, the build errors out.

Some errors:
```log
[ 49%] Building C object src/plugins/irc/CMakeFiles/irc.dir/irc-ignore.o
cd /tmp/weechat-20180727-73871-23o08g/weechat-2.2/build/src/plugins/irc && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -DENABLE_NLS -DHAVE_CONFIG_H -DHAVE_GCRYPT -DHAVE_GNUTLS -DHAVE_ICONV -DHAVE_ZLIB -DWEECHAT_LICENSE=\"GPL3\" -DWEECHAT_VERSION=\"2.2\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -D_LARGE_FILES -Dirc_EXPORTS -I/usr/local/include -I/tmp/weechat-20180727-73871-23o08g/weechat-2.2/build  -Wall -Wextra -Werror-implicit-function-declaration -DNDEBUG -fPIC   -fPIC -fPIC -o CMakeFiles/irc.dir/irc-ignore.o   -c /tmp/weechat-20180727-73871-23o08g/weechat-2.2/src/plugins/irc/irc-ignore.c
ld: -stack_size option can only be used when linking a main executable
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/plugins/python/python.so] Error 1
make[1]: *** [src/plugins/python/CMakeFiles/python.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

```log
[ 47%] Building C object src/plugins/irc/CMakeFiles/irc.dir/irc-debug.o
cd /tmp/weechat-20180730-47838-1exy9g3/weechat-2.2/build/src/plugins/irc && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -DENABLE_NLS -DHAVE_CONFIG_H -DHAVE_GCRYPT -DHAVE_GNUTLS -DHAVE_ICONV -DHAVE_ZLIB -DWEECHAT_LICENSE=\"GPL3\" -DWEECHAT_VERSION=\"2.2\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -D_LARGE_FILES -Dirc_EXPORTS -I/usr/local/include -I/tmp/weechat-20180730-47838-1exy9g3/weechat-2.2/build  -Wall -Wextra -Werror-implicit-function-declaration -DNDEBUG -fPIC   -fPIC -fPIC -o CMakeFiles/irc.dir/irc-debug.o   -c /tmp/weechat-20180730-47838-1exy9g3/weechat-2.2/src/plugins/irc/irc-debug.c
ld: -stack_size option can only be used when linking a main executable
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/plugins/python/python.so] Error 1
make[1]: *** [src/plugins/python/CMakeFiles/python.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

## Steps to reproduce

1. `brew install weechat --with-python`
2. Build fail
3. Sad face.

## Desired behavior
Being able to compile without error.

## Suggested solutions
They mentioned in the Homebrew bug report that this might because of the WeeChat's way with CMake and Python 3.  Not really sure to relay the correct message, but please look at the [bug report](https://github.com/Homebrew/homebrew-core/issues/30509) over at Homebrew repo, as well as the patch by MacPorts.

## Additional information

---

- WeeChat version: 2.2
- OS, distribution and version: macOS High Sierra 10.13.6

**Comment by GilDev** [comment]
No news on this? No way to install Weechat with Python2/3 support?

**Comment by MindTooth** [comment]
@flashcode https://github.com/weechat/weechat/commit/789fa972f8f57b8fb2cf40a032bee2ea5b2508cc

Does that mean Weechat is Python 3.0 ready?

**Comment by weechatter** [comment]
WeeChat is Python3 ready since v0.3.7 (Feb 2012!).

The default python version weechat was compiled with, was python 2.x. Since 1st of july 2019, the
default python version is 3.x

**Comment by MindTooth** [comment]
That might be, but there were a reason that it did not work before.  And I've been watching to see anything related to Python 3 in the commits, so either I can close this or keep watching.

I were able to compile this time around, and even run it.  So that at least fixes the original issue.

Though, `/script upgrade` gave me this:
<img width="1736" alt="Screenshot 2019-07-06 at 10 17 21" src="https://user-images.githubusercontent.com/33870508/60753728-669f1f00-9fd7-11e9-9ddb-8bb75a985af2.png">

**Comment by flashcode** [comment]
@MindTooth: so if you can compile fine and if `/debug libs` shows Python 3, then we can close this issue.
The error message on your screenshot is probably caused by something else (a script?).

**Comment by MindTooth** [comment]
I had not enabled the Python3 flag.  So it was a fluke.  But I'm starting to maybe believe that this is caused by Homebrew instead.  Not that I can say for sure.

I'm getting the same error as above, a linking error when trying to compile the Python bit.

If you can't think of anything related to WeeChat that might cause this, I'm happy to close this, and let someone else picking the fight when the time comes.  Especially now that macOS Catalina won't include Python2.

**Comment by flashcode** [comment]
Unfortunately I have no macOS, so I can not debug and fix this problem.
If someone can give me an access on macOS, I'll try to debug.
I also plan to rewrite the Python CMake detection stuff in WeeChat, when I'll have some time.

**Comment by MindTooth** [comment]
Not sure when, but it now seems that the formula defaults to Python 3.  And a `/python version` shows `3.7.4`.

Going ahead with closing this..

**Comment by flashcode** [comment]
Python detection was changed on July, 24 (commit ad7d16a5b3b72fd2af2c98535a2358d8eaaf9b74).
Maybe it fixed the Python 3 compilation on macOS.
