### ISSUE TITLE
PHP plugin SIGSEGV

### ISSUE THREAD

**Issue by d3xt3r01** [weechat/weechat#1236]
## Bug summary
Can't find /usr/lib64/php7.1/lib64/libphp7.so and even with LD_LIBRARY_PATH .. a SIGSEGV is caused. 

## Current behavior

    =!= | Error: unable to load plugin "/usr/lib64/weechat/plugins/php.so": libphp7.so: cannot open shared object file: No such file or directory

    *** Very bad! WeeChat is crashing (SIGSEGV received)
    *** Full crash dump was saved to .weechat-test/weechat_crash_20180822_25932.log file.
    ***
    *** Please help WeeChat developers to fix this bug:
    ***   1. If you have a core file, please run:  gdb /path/to/weechat core
    ***      then issue command: "bt full" and send result to developers
    ***      (see user's guide for more info about report of crashes).
    ***   2. Otherwise send backtrace (below), only if it is a complete trace.
    ***      Keep the crash log file, just in case developers ask you some info
    ***      (be careful, private info like passwords may be in this file).
    
    ======= WeeChat backtrace =======
    (written by WeeChat 2.2, compiled on Aug 22 2018 18:18:56)
    001  ??:? [function weechat_backtrace]
    002  ??:? [function debug_sigsegv]
    003  ??:? [function __restore_rt]
    004  ??:? [function __nss_passwd_lookup]
    005  ??:? [function read64]
    006  ??:? [function netsnmp_tdomain_init]
    007  ??:? [function print_mib_tree]
    008  ??:? [function init_snmp]
    009  ??:? [function zm_startup_snmp]
    010  ??:? [function zend_startup_module_ex]
    011  ??:? [function zend_startup_module_ex]
    012  ??:? [function zend_hash_apply]
    013  ??:? [function zend_startup_modules]
    014  ??:? [function php_module_startup]
    015  ??:? [function php_embed_init]
    016  ??:? [function weechat_plugin_init]
    017  ??:? [function plugin_call_init]
    018  ??:? [function plugin_auto_load]
    019  ??:? [function plugin_init]
    020  ??:? [function weechat_init]
    021  ??:? [function main]
    022  ??:? [function __libc_start_main]
    023  ??:? [function _start]
    ======= End of  backtrace =======

## Steps to reproduce

1.  Compile 
2. Start with LD_LIBRARY_PATH=/usr/lib64/php7.1/lib64/ weechat -a --dir .weechat-test

## Desired behavior
Load the php plugin ?

## Suggested solutions
The gentoo people suggest RPATH fix

---

- WeeChat version: 2.2
- OS, distribution and version:  Gentoo

**Comment by flashcode** [comment]
Hi,
Is this problem still happening today with latest stable or devel version?
