### ISSUE TITLE
Add aliases for key bindings

### ISSUE THREAD

**Issue by ek4** [weechat/weechat#1238]
## Feature description

Add aliases for key bindings, for example `F5` on `meta2-15~` and `meta2-[E`, so that the key `F5` can be used directly in a key binding: `/key bind F5 /some_command`.

**Comment by weechatter** [comment]
All the weird codes are the peculiarity of terminal key handling. There is no magic mapping of all
the keys things, because WeeChat just uses whatever the terminal tells it.
Therefore you have the alt+k mode, see /help key

**Comment by arza-zara** [comment]
I think this is a viable suggestion, not invalid. For example we could have aliases like F1 -> meta2-11~ & meta-OP.

**Comment by flashcode** [comment]
Hi @ek4,

I started to write a specification that will address this issue: https://specs.weechat.org/specs/2023-002-key-bindings-improvements.html

This is still a draft and not complete, but your feedback is welcome on the proposed changes.

**Comment by flashcode** [comment]
Hi,

For your information I pushed the branch [key-bindings-improvements](https://github.com/weechat/weechat/tree/key-bindings-improvements) (work in progress):

- add of `/key debug` that displays the new key name using alias (eg: `meta2-1;3D` is now `meta-left`)
- configuration is unchanged for now: it is fully compatible with master branch, keys are not yet renamed in config.

Please try with many terminals and different keys to ensure all keys are properly converted to the new name.
If not, please ping me.

**Comment by flashcode** [comment]
All changes are implemented on the branch.

As there are many breaking changes, please send feedback before it's merged and available for all testers of development version.
