### ISSUE TITLE
oper user prefix is not shown to users joining

### ISSUE THREAD

**Issue by jkhsjdhjs** [weechat/weechat#1239]
## Bug summary
When using the InspIRCd command `OJOIN` to join a channel as oper in network business weechat isn't showing the `!` prefix in front of your username in the userlist and it's also not showing the modes `+Yo` being set on you.

Other weechat users are seeing the `!` in front of your nick and the modes being set. However, if those users cycle the `!` in front of your nick is also not shown to them.

## Current behavior
The `!` prefix is not shown to users joining a channel and not shown to yourself when using `OJOIN`.

## Steps to reproduce

First way (using InspIRCd):
Join a channel using `OJOIN`. The oper prefix isn't shown in the userlist, also there is no message shown that `+Yo` is set.

Second way:
1. Join a channel with two clients.
2. Set `+Y` on any client, you will both see the oper prefix.
3. Cycle with the other client, it won't see the oper prefix anymore.

## Desired behavior
Every weechat client seeing the oper prefix in front of users with the corresponding modes when joining a channel.

---

- WeeChat version: 2.2, 2.3-dev
- OS, distribution and version: Arch Linux

**Comment by flashcode** [comment]
Hi,
Do you have an example of server and channel to join, in order to reproduce the problem?
Thanks.

**Comment by jkhsjdhjs** [comment]
Yes, #1239 on irc.n0xy.net:6697.
SSL Fingerprint: `44:40:68:02:47:F7:08:AE:27:63:D5:46:CF:48:30:51:B8:32:4C:C0:51:7D:C0:24:9F:59:A3:70:A2:0C:CB:1C`

**Comment by jkhsjdhjs** [comment]
Actually not a weechat issue, see https://github.com/znc/znc/issues/1594.
Thanks to @flashcode for helping debugging this!

**Comment by Mikaela** [comment]
@jkhsjdhjs my guess would bring this back to WeeChat configuration and https://github.com/weechat/weechat/issues/320. Do you have `multi-prefix` in `irc.server_default.capabilities`? If not, WeeChat won't request it from ZNC and ZNC assumes that WeeChat doesn't support it and I think this might cause your issue.

See also:

* https://wiki.znc.in/Weechat#Enabling_server-time_.26_other_IRCv3_capabilities

**Comment by flashcode** [comment]
@Mikaela: but shouldn't ZNC then send just the highest prefix, instead of nothing?

**Comment by Mikaela** [comment]
I think that depends what is the highest prefix which was not said in this issue, but it turned out to be https://github.com/znc/znc/issues/1528 .
