### ISSUE TITLE
Programatically request/get "focus" hashtable

### ISSUE THREAD

**Issue by GermainZ** [weechat/weechat#1245]
## Feature description
The "focus" hashtable is currently only populated on user input (in cursor mode). That is, once the user presses a key or clicks a mouse button (e.g. [q to quote](https://github.com/weechat/weechat/blob/51bda896c8ec4c8b424ba731944758bbae9e5855/src/gui/gui-chat.c#L1081)).

Being able to programmatically request the "focus" hashtable would allow scripts, in some admittedly niche cases, to leverage cursor mode and extend it.

P.S. Perhaps putting it under `info_get_hashtable` would make sense?

**Comment by sim642** [comment]
### Possible solution
`info_get_hashtable` with x and y coordinates to query the focus data for, as if the cursor was at those coordinates. Scripts that want to use it can get screen coordinates for windows, their chat areas and bars with infolists/hdatas already to query the interesting area correctly.
