### ISSUE TITLE
Reloading a Python script while any of its hooks are active crashes WeeChat

### ISSUE THREAD

**Issue by GermainZ** [weechat/weechat#1246]
## Bug summary
Reloading a Python script while any of its hooks are active crashes WeeChat:

```
Fatal Python error: Py_EndInterpreter: thread still has a frame
Current thread 0x00007fa0be8f0480 (most recent call first):
zsh: abort (core dumped)  weechat
```

## Steps to reproduce
Loading the sample script below will cause the crash (`/script load crashtest.py`).

`crashtest.py`:
```
import weechat

SCRIPT_NAME = "crashtest"
SCRIPT_AUTHOR = "GermainZ <germanosz@gmail.com>"
SCRIPT_VERSION = "0.1"
SCRIPT_LICENSE = "WTFPL"
SCRIPT_DESC = ("Sample script to reproduce crash")

weechat.register(SCRIPT_NAME, SCRIPT_AUTHOR, SCRIPT_VERSION, 
                 SCRIPT_LICENSE, SCRIPT_DESC, "", "")

def timer_cb(data, remaining_calls):
    # Let's reload this script before this hook completes.
    weechat.command("", "/script reload crashtest")
    return weechat.WEECHAT_RC_OK

weechat.hook_timer(1, 0, 1, "timer_cb", "")
```

---

- WeeChat version: WeeChat 2.3-dev (git: v2.2-69-ga9e84bfc5)
- OS, distribution and version: Arch Linux

**Comment by weechatter** [comment]
i would not say its a bug in weechat, use this line instead:

**Comment by flashcode** [comment]
Yes, I'll check why it crashes and what I can do, but it's not a good idea in a callback to do such actions. Callbacks should do basic things and not actions like reloading plugins or scripts, or you can use `/wait` command to force WeeChat to execute the command after/outside the callback.

**Comment by GermainZ** [comment]
Indeed, I only noticed this because one of my scripts allows user input. Checking the input and adding "wait" for "/script" commands in my script is perfectly acceptable, I just didn't think of it. Thanks.

**Comment by flashcode** [comment]
You could even use `/wait` for any commands, as other commands could bring similar problem. I think it's safe to always use `/wait` for commands in a callback.
