### ISSUE TITLE
Question: Can I Navigate Between Multiple Server Buffers With Shortcuts?

### ISSUE THREAD

**Issue by BurnyBoi** [weechat/weechat#1247]
I currently have 2 server buffers in weechat: 1 for freenode, and 1 for Matrix using their lua plugin:

https://imgur.com/a/tVg3mAG

If I try to use any commands for going up and down in the buflist, such as alt+(up & down), alt+(left & right), or F5 and F6 to go between the server buffers, it will skip whichever one is not "selected". There are only 2 ways that I know of to switch between the server buffers, both of which aren't that efficient compared to the commands I mentioned:

- I can use alt+m to enable mouse support, and click the other server buffer
- I can use '/buffer name' to go to either server buffer

Once I do select the freenode server buffer in the above example, now the quick navigation shortcuts will ignore the matrix buffer. 

Is there any way to make it so I can go up and down between server buffers like all the other ones? Ideally, since they're both listed, I would expect to be able to use alt+(up & down), alt+(left & right), or F5 and F6 to go between them just like chat buffers, or possibly have some other 2-key combo to go between them.

---

- WeeChat version: 2.2-2
- OS, distribution and version: Parabola GNU/Linux

**Comment by flashcode** [comment]
Hi,
The matrix script does not define an "IRC server" (as the irc plugin does), but if it creates a buffer merged with another one, you can use the key `ctrl+X` on the buffer to switch the active buffer.
If needed, you could ask directly to the script author if there are other ways to switch to a "matrix server".

**Comment by BurnyBoi** [comment]
Thanks for the info! Ctrl-X is working as expected to switch between the freenode and matrix buffer

**Comment by flashcode** [comment]
If needed, you have a list of all keys in the user's guide: https://weechat.org/doc/user#key_bindings
