### ISSUE TITLE
--run-command aggregation

### ISSUE THREAD

**Issue by timokau** [weechat/weechat#1248]
## Feature description

Currently multiple `--run-command` arguments override each other. So `weechat -r '/quit' -r ';'` will not actually quit. I think that is not intuitive behaviour and it makes writing an alias/wrapper that runs some commands on startup harder. I would expect `weechat -r 'a' -r 'b'` to be equivalent to `weechat -r 'a;b'`.

**Comment by flashcode** [comment]
Hi,
Good idea, I'll implement that quickly.

**Comment by timokau** [comment]
Thank you!
