### ISSUE TITLE
Also show x-real-ip in relay.list

### ISSUE THREAD

**Issue by ThoreKr** [weechat/weechat#1256]
## Feature description
As added by #440 incoming relay connections through a proxy log the real ip address to the core buffer. Unfortunately this address isn't shown in the `relay.list` buffer which makes it a bit annoying to track down connection issues.

Suggested behaviour would be to display the ip there as well, when the header is set.

**Comment by vectr0n** [comment]
+1

**Comment by flashcode** [comment]
Thanks for the suggestion, implemented.
