### ISSUE TITLE
Use weechat behind corporate proxy for IRC

### ISSUE THREAD

**Issue by fabstao** [weechat/weechat#1261]
## Question
Hi!

Weechat supports connection through a security proxy? irc.server....proxy is for IRC proxy use, right?

Thanks!

---

- WeeChat version: 
- OS, distribution and version:

**Comment by weechatter** [comment]
You have to create a proxy first, see /help proxy

**Comment by fabstao** [comment]
Hi! already created and assigned to the connection:

`13:10:22  weechat     | List of proxies:
          │13:10:22  weechat     |   squid: http, myproxy.address.com/3128 (IPv4), username: (none), password: (none)
`
`13:12:00  weechat     | Server: freenode [not connected]
          │13:12:00  weechat     |   addresses. . . . . . : 'chat.freenode.net/6697'
          │13:12:00  weechat     |   proxy. . . . . . . . : 'squid'
          │13:12:00  weechat     |   ipv6 . . . . . . . . :   (on)
          │13:12:00  weechat     |   ssl. . . . . . . . . : on
          │13:12:00  weechat     |   ssl_cert . . . . . . :   ('')
          │13:12:00  weechat     |   ssl_priorities . . . :   ('NORMAL:-VERS-SSL3.0')
          │13:12:00  weechat     |   ssl_dhkey_size . . . :   (2048)
          │13:12:00  weechat     |   ssl_fingerprint. . . :   ('')
          │13:12:00  weechat     |   ssl_verify . . . . . :   (on)
          │13:12:00  weechat     |   password . . . . . . :   (hidden)
          │13:12:00  weechat     |   capabilities . . . . :   ('')
          │13:12:00  weechat     |   sasl_mechanism . . . :   ('plain')
          │13:12:00  weechat     |   sasl_username. . . . : 'fnick'
          │13:12:00  weechat     |   sasl_password. . . . : (hidden)
          │13:12:00  weechat     |   sasl_key. .  . . . . :   ('')
          │13:12:00  weechat     |   sasl_timeout . . . . :   (15 seconds)
          │13:12:00  weechat     |   sasl_fail. . . . . . :   ('continue')
          │13:12:00  weechat     |   autoconnect. . . . . : on
          │13:12:00  weechat     |   autoreconnect. . . . :   (on)
          │13:12:00  weechat     |   autoreconnect_delay. :   (10 seconds)
          │13:12:00  weechat     |   nicks. . . . . . . . :   ('fnick,fnick1,fnick2,fnick3,fnick4')
          │13:12:00  weechat     |   nicks_alternate. . . :   (on)
          │13:12:00  weechat     |   username . . . . . . : 'fnick'
          │13:12:00  weechat     |   realname . . . . . . :   ('')
          │13:12:00  weechat     |   local_hostname . . . :   ('')
          │13:12:00  weechat     |   usermode . . . . . . :   ('')
          │13:12:00  weechat     |   command. . . . . . . :   ('')
          │13:12:00  weechat     |   command_delay. . . . :   (0 seconds)
          │13:12:00  weechat     |   autojoin . . . . . . :   ('')
          │13:12:00  weechat     |   autorejoin . . . . . :   (off)
          │13:12:00  weechat     |   autorejoin_delay . . :   (30 seconds)
          │13:12:00  weechat     |   connection_timeout . :   (60 seconds)
          │13:12:00  weechat     |   anti_flood_prio_high :   (2 seconds)
          │13:12:00  weechat     |   anti_flood_prio_low. :   (2 seconds)
          │13:12:00  weechat     |   away_check . . . . . :   (0 minutes)
          │13:12:00  weechat     |   away_check_max_nicks :   (25)
          │13:12:00  weechat     |   msg_kick . . . . . . :   ('')
          │13:12:00  weechat     |   msg_part . . . . . . :   ('WeeChat ${info:version}')
          │13:12:00  weechat     |   msg_quit . . . . . . :   ('WeeChat ${info:version}')
          │13:12:00  weechat     |   notify . . . . . . . :   ('')
          │13:12:00  weechat     |   split_msg_max_length :   (512)
`

Connection error:

`13:14:24 freenode  -- | irc: reconnecting to server...
          │13:14:24 freenode  -- | irc: connecting to server chat.freenode.net/6697 (SSL) via http myproxy.address.com/3128...
          │13:14:24 freenode =!= | irc: TLS handshake failed
          │13:14:24 freenode =!= | irc: error: The TLS connection was non-properly terminated.
`

Thanks!

**Comment by flashcode** [comment]
Hi,

You could check in your proxy logs if there are some errors.
