### ISSUE TITLE
${cutscr mess with ${color}

### ISSUE THREAD

**Issue by pascalpoitras** [weechat/weechat#1264]
## Bug summary

If I put, for example, ${color:31}+ in the second field of ${cutscr, it works great

`/eval -n ${cutscr:2,${color:31}+,hello}`

this return he+ as expected

However, if I add a background color, ${cutscr start to cut the color somehow:

`/eval -n ${cutscr:2,${color:31,32}+,hello}`

this return @0 instead of he+

## Additional information

I have only tested ${cut and ${cutscr

---

- WeeChat version: WeeChat 2.3-dev (git: v2.2-112-g82697714e)
- OS, distribution and version: Debian Stable Stretch

**Comment by flashcode** [comment]
The problem is that the comma is used as separator between count, suffix and string, and that `${color:31,32}` is adding a comma.
Not easy to fix, I'm thinking about a way to use another separator (keeping the comma by default for compatibility).

**Comment by pascalpoitras** [comment]
or you could create a ${colorbg: instead I guess

**Comment by flashcode** [comment]
There's a workaround which is working: `/eval -n ${cutscr:2,${color:31}${color:,32}+,hello}`

**Comment by pascalpoitras** [comment]
thanks!
