### ISSUE TITLE
Cursor command to move to bottom of an area

### ISSUE THREAD

**Issue by mkaito** [weechat/weechat#1282]
## Feature description
When I enter cursor mode, it's much more likely that I want to act on one of the more recent entries in the chat window. But since the cursor always starts at the top, I first have to move it all the way down to what I would actually act on.

I would like to propose something like this:

```
# enter cursor mode, move to bottom of chat area.
/cursor go chat bottom

# move cursor to the bottom of the current area 
/cursor move bottom
```

**Comment by weechatter** [comment]
/cursor go x,y  wil move the cursor to the coord x,y
you can use a very high number for "y" to move cursor to last line.

**Comment by mkaito** [comment]
That seems to freeze weechat, actually.

**Comment by weechatter** [comment]
I understood, thats why i marked it as "enhancement" ;-)
My suggestions was just a kind of work around. Personel i like your idea.

**Comment by mkaito** [comment]
> But how to handle when "/window splith" is used?

That's a good question. Maybe you don't want to make the logic too complicated, and that's a fair argument, but here's what I'd consider intuitive:

* Say you have 4 splits in a 2x2 layout, and top right is focused.
* You run `/cursor go chat bottom`
* Cursor goes to the bottom of the focused chat area

**Comment by trygveaa** [comment]
> But how to handle when "/window splith" is used?

`/cursor go chat` already goes to the focused chat area, so wouldn't it be natural that `/cursor go chat bottom` goes to the bottom of that same chat area?

**Comment by weechatter** [comment]
yes, it does. don't use split windows myself :-)

**Comment by pmodin** [comment]
Hi, I ran into this issue, but the solution by @mkaito didn't work for me as that put the cursor on a buflist I had on the left hand side.

> ```
> /key bind ctrl-L /cursor;/cursor go 1,9000;/cursor move up;/cursor move up
> ```

I found this to work better, ignoring my bar;
```
/key bind ctrl-L /cursor go chat;/cursor move area_down;/cursor move up
```

**Comment by flashcode** [comment]
Done.

New parameters to move cursor:

```
/cursor go <area> top_left
/cursor go <area> top_right
/cursor go <area> bottom_left
/cursor go <area> bottom_right
/cursor move top_left
/cursor move top_right
/cursor move bottom_left
/cursor move bottom_right
/cursor move edge_top
/cursor move edge_bottom
/cursor move edge_left
/cursor move edge_right  
```

New keys in cursor mode and keys changes to move to another area, see the user's guide: https://weechat.org/files/doc/weechat/devel/weechat_user.en.html#key_bindings_cursor_context
