### ISSUE TITLE
FreeBSD server-time capability issue

### ISSUE THREAD

**Issue by aperum** [weechat/weechat#1289]
## Bug summary
I'm using weechat on FreeBSD 12.0 with ZNC as the server. After enabling the server-time capability a times displayed in the buffer are actually times from when the line is displayed not when it was received.

I can see in the raw IRC buffer that the correct @time tag is received but the time in the buffer window is still the current time not what is sent in @time.

With the help of sim642 on #weechat we could boil this down to the use of strptime at https://github.com/weechat/weechat/blob/master/src/plugins/irc/irc-protocol.c#L6110 .

%z seems quite glibc specific and also the milliseconds seem to throw strptime off on FreeBSD.

## Current behavior
Buffer lines are displayed with the current timestamp instead of the time in the @time tag when server-time is activated.

## Steps to reproduce

1.  /set irc.server_default.capabilities account-notify,away-notify,cap-notify,multi-prefix,server-time,znc.in/server-time-iso,znc.in/self-message
2. /reconnect -all
3. Open the raw IRC buffer
4. Receive a message on any channel
5. Compare @time in the raw buffer with the time printed in the channel buffer (the difference is quite clear if the local time is not NTP controlled and a bit off ;)

## Desired behavior

Use the time given by the server for buffer output.

## Suggested solutions

Maybe there is POSIX way to do this which works on Linux and FreeBSD? I'm no programmer but i'll try a few things and report back here if i find something.

## Additional information

The time received from the server has the format: @time=2019-01-09T13:00:03.589Z

---

- WeeChat version: 2.3
- OS, distribution and version: 
FreeBSD cthulhu.olymp.local 12.0-RELEASE FreeBSD 12.0-RELEASE r341666 GENERIC  amd64

**Comment by sim642** [comment]
#### Milliseconds
As pointed out by @grawity on IRC, both glibc and FreeBSD's libc `strptime` probably fail when trying to parse the milliseconds. The difference is that glibc populates the `tm` struct as it goes while FreeBSD doesn't. For some unexplained reason the code
https://github.com/weechat/weechat/blob/8629bf4b06f2d32a21b864fbe765bbe6d4472610/src/plugins/irc/irc-protocol.c#L6109-L6119
doesn't check `strptime` return value for failure, but instead the year in the structure. Seems to me like the return value should be checked instead.

#### Timezone
In neither case the parsing actually deals with the `Z` in the timestamp. The non-standard `%z` format specifier in FreeBSD implementation cannot actually handle `Z` anyway, only numeric offsets.
