### ISSUE TITLE
Aspell issues on Void musl

### ISSUE THREAD

**Issue by ErinVoid** [weechat/weechat#1290]
## Bug summary
Issue is aspell does not work on musl [\Void 4.19.13_1 x86_64-musl AuthenticAMD uptodate rF]. See (https://github.com/void-linux/void-packages/issues/6883)

## Current behavior
Spelling does not work and all words are highlighted as being correct. The following messages are in the "Freenode" window:
```
13:35:23  weechat     | aspell: warning: dictionary "en" is not available on your system
13:35:23  weechat    | aspell: error: unable to create speller for lang "en"
13:35:26  weechat    | aspell: error: unable to create speller for lang ""en"
```

## Steps to reproduce
Install below packages, enable aspell and type. It potentially is solely a musl based issue as discussion in the irc channel suggests that the glibc version works correctly. Information on the Internet could link the problem to setting a locale or lack of!
```
weechat-2.3_1
weechat-aspell-2.3_1
aspell-0.60.6.1_10
aspell-en-2018.04.16_1
aspell-fr-0.50.3_2
```

## Desired behavior
Spelling to work correctly. aspell works correctly in a terminal, i.e.`$ aspell check my.txt`

## Suggested solutions
Some discussion on the Internet suggests it maybe that the locale isn't set but this isn't possible on musl yet. 

## Additional information
None

---

In the above post.

**Comment by ErinVoid** [comment]
Void have disabled "aspell" in their build. Works with hunspell. Should it be renamed to "spell" or similar?

**Comment by flashcode** [comment]
Yes, see: #1299
