### ISSUE TITLE
IRCv3.2 batch Extension

### ISSUE THREAD

**Issue by sim642** [weechat/weechat#1292]
IRCv3.2 [`batch`](https://ircv3.net/specs/extensions/batch-3.2.html) capability is unsupported by WeeChat and there seems to be no issue tracking it either. While batches in general are not immediately useful, the `netsplit`/`netjoin` and `chathistory` batch types could be useful for different (nicer) buffer printing.

## Minimum support
The specification says that
> Client MAY ignore the type and process messages one by one. For example, that happens if the type is unknown to the client.

Therefore at minimum we could "support" the `batch` capability and raw IRC command by implementing them to do absolutely nothing (except not give an error about unknown raw IRC command).

## Simple support
For some non-trivial batch support, WeeChat could at least save batch IDs, types and arguments as buffer line tags. I think batch IDs from IRC message tags end up there anyway (?), but that's difficult to use (e.g. to filter by) and requires a script to do the batch type bookkeeping. WeeChat could itself also put the batch type as a tag to every line, this would make it reasonably simple to
1. create filters for netsplits and netjoins,
2. create line triggers etc to custom-color chathistory, for example.

Such approach would probably be sufficient for most imaginable cases, at least for now when batches aren't a big thing yet, but it wouldn't work for nested batches (e.g. netsplit in chathistory), which the specification also requires.

## Full support
For a more complete support I don't have a good proposal but some thoughts I've had before and now.

### Tree structure
The nesting of batches is essentially a tree structure for the batches. It may be necessary/useful for WeeChat to somehow work with batches in a tree data structure, either internally to process them or somehow to also expose it.

### Hooks and redirection
For supporting specific batch types (either by WeeChat itself or scripts), it could be useful to be able to somehow hook into handling of batches to be able to control how they're processed (message by message or together at the end) and get the data for processing. Doing batch and especially nested batch bookkeeping _ad-hoc_ only in WeeChat or separately by each script wanting to use them is ugly. Maybe an IRC redirections-like mechanism could also be used for requesting batch processing at once at end, e.g. for outputting a single netsplit message.

---

Feel free to suggest improvements or other ideas, especially regarding gaining full support for batch nesting and easy use.

**Comment by FelipeResende** [comment]
Hi @sim642,I'm still new to weechat code and to irc, but  I would like to help with this feature. Have you thought of other ideas to address this?

As I'm not aware of all functionalities weechat provide, when I looked at the code to find where I had to change, it seemed to be simpler than after reading your thoughts on how to implement it (I was thinking about it isolated from the rest). So my thoughts might not be feasible at all, but I would like to give it a try.

Reading through the code, I got an idea of where I have to change to create e new irc protocol callback to handle the BATCH command, but I don't know how to address your thoughts on allowing scripts to handle it or where hooks or redirection would be used.

> The nesting of batches is essentially a tree structure for the batches. It may be necessary/useful for WeeChat to somehow work with batches in a tree data structure, either internally to process them or somehow to also expose it.

My thought is to use a hashtable to group messages related to a batch in a queue of messages associated with that batch (reference-tag). If there is a nested batch, we include it in the hashtable and add a reference to it in the queue of the batch it references.

That way, after receiving the end of the batch, it could be processed like a tree. Starting from the outermost batch, a pointer to the hashtable would be node that has childs to be processed and messages in the queue would be leaf nodes.

> it could be useful to be able to somehow hook into handling of batches to be able to control how they're processed (message by message or together at the end)

As I understand it, a batch can only be processed after we receive its ending (except for a BATCH command, I'm not sure there are other commands we have to process immediately even though it is part of a batch) . So we could do something at this point to:
1. Decide if this batch will be processed at that point (if it is an inner batch, it may be delayed)
2. Decide how the messages in the batch will be traversed
3. Process the batch according to its type

I'm not sure if it could be done either by weechat itself or by a script.

> Doing batch and especially nested batch bookkeeping ad-hoc only in WeeChat or separately by each script wanting to use them is ugly.

I did not get the idea here.

> Maybe an IRC redirections-like mechanism could also be used for requesting batch processing at once at end, e.g. for outputting a single netsplit message.

I did not get the idea here.

**Comment by flashcode** [comment]
Information about features added:

- messages BATCH are processed
- all messages received in BATCH are stored and processed at the end of BATCH (as if they were normal messages)
- nested batches should be properly handled (internally not with a tree, but each BATCH has a parent reference)
- batches are processed sequentially; in case of nested batches, the order is not guaranteed (outer batch should be processed at the end)
- modifier `irc_batch` is added to modify the list of messages contained in the batch, see doc here: https://weechat.org/files/doc/weechat/devel/weechat_plugin_api.en.html#hook_modifier_irc_batch
- batch reference and type are added as tag in messages, for example (with `/debug tags`) if batch reference is `ref` and type is `example`:

```
alice | this is a test [irc_privmsg,irc_tag_batch_ref,irc_batch_type_example,notify_message,prefix_nick_green,nick_alice,log1]
```

The changes don't include (which could come soon):

- support of BATCH netsplit/netjoin specific display
- support of other capabilities depending on BATCH
