### ISSUE TITLE
set read marker on xterm FocusOut

### ISSUE THREAD

**Issue by delan** [weechat/weechat#1295]
## Feature description

Some terminal emulators can tell the application when the containing window gains and loses focus (see vim/vim#609). This could be used to improve the behaviour of the read marker.

**Comment by flashcode** [comment]
Hi,

You can already do that: some special key codes are sent by xterm to WeeChat when the terminal is unfocused or focused.

For example, you can try:

    /key bind meta2-I /print -core focus
    /key bind meta2-O /print -core unfocus

And then if that's working, you can bind `meta2-I` on: `/input set_unread`.

If that's OK for you, I can close the issue.

**Comment by flashcode** [comment]
I use i3, but I think the window manager has nothing to do with that.

I tried with "xterm" (the xterm package in Debian Sid):

    $ xterm -v
    XTerm(343)

**Comment by delan** [comment]
WeeChat works as long as I [opt in](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Functions-using-CSI-_-ordered-by-the-final-character_s_) first:

```sh
% printf '\033[?1004h'
```

![screenshot_at_2019-01-27-20-53-54](https://user-images.githubusercontent.com/465303/51799631-1fb23e00-226f-11e9-8572-720045e27bb8.png)

i thought WeeChat would do that on its own, but either way, thanks for your help!

**Comment by flashcode** [comment]
You can send such string to the terminal when WeeChat is starting, using this option:

    /set weechat.startup.command_after_plugins "/print -stdout \033[?1004h\n"

**Comment by flashcode** [comment]
I'll add this in the user's guide (and/or FAQ).

**Comment by delan** [comment]
Cheers!

**Comment by delan** [comment]
By the way, if you’re documenting both the `command_after_plugins` and the key binding, you might want to do the `set_unread` on `meta2-O` rather than `meta2-I` (the latter moves the marker when you focus WeeChat).

**Comment by ar1a** [comment]
```/set weechat.startup.command_after_plugins "/print -stdout \033[?1004h\n"
/key bind meta2-O /input set_unread
/key unbind meta2-I
/save```

**Comment by flashcode** [comment]
Oh, nothing to do, I already added that in the FAQ 5 years ago: https://weechat.org/files/doc/devel/weechat_faq.en.html#terminal_focus :wink:
