### ISSUE TITLE
weechat git: v2.3-105-gb38b2abe3 sigsegv during the night

### ISSUE THREAD

**Issue by hggdh** [weechat/weechat#1297]
I am not yet sure what causes it. This is the third such crash since last updates to devel (2.4-dev, git: v2.3-105-gb38b2abe3). Crash log attached. Please feel free to contact me either here or on Freenode's #weechat (nick: hggdh).

[weechat_crash_20190130_882.log](https://github.com/weechat/weechat/files/2813582/weechat_crash_20190130_882.log)

**Comment by flashcode** [comment]
Hi,

There is not enough in this file, the backtrace at the end is incomplete.

You could compile with debug symbold and enable core files on your system, so you'll be able to send a backtrace using gdb in case of a new crash.
See the user's guide for more info: https://weechat.org/files/doc/devel/weechat_user.en.html#report_crashes

**Comment by weechatter** [comment]
Also a list of installed scripts would be fine:
/script list -o

**Comment by ersuniljoshi** [comment]
I got the same issue, I have the core as well. Js let me know how to  copy bt full ouput to a file.
@flashcode

**Comment by hggdh** [comment]
partial backtrace:

#4  <signal handler called>                                               
No locals.                              
#5  __strlen_sse2 () at ../sysdeps/x86_64/multiarch/../strlen.S:120                                                                                                                                                            
No locals.                                  
#6  0x00007f81dc87a9ae in __GI___strdup (s=0x0) at strdup.c:41
        len = <optimized out>                                                                                                             
        new = <optimized out>                           
#9  0x00007f81ce8b2e03 in irc_modelist_item_new (modelist=0x561f9bd31b30, mask=0x0, setter=0x561f9bfbc5c0 "el!el@freenode/staff/el", datetime=1548914197) at /home/cerdea/weechat/src/plugins/irc/irc-modelist.c:272
        new_item = 0x561f9c115f30                 
#8  0x00007f81ce8b243c in irc_mode_channel_set (server=0x561f9a81f440, channel=0x561f9bd2af50, host=0x561f9bfbc5c0 "el!el@freenode/staff/el", modes=0x561f9c119c20 "+q") at /home/cerdea/weechat/src/plugins/irc/irc-mode.c:480
        pos_args = 0x0                                
        str_modes = 0x561f9bd43cc0 "+q"                                                                      
        set_flag = 43 '+'                       
        argv = 0x0                                                     
        pos = 0x561f9bd43cc1 "q" 
        ptr_arg = 0x0                                          
        chanmode_type = 65 'A'                                     
        argc = 0                                      
        current_arg = 0                                                
        update_channel_modes = 0                        
        channel_modes_updated = 0                          
        smart_filter = 0                                  
        ptr_nick = 0x561f9c02f120
        ptr_modelist = 0x561f9bd31b30                  
        ptr_item = 0x23000000000000                                       
#9  0x00007f81ce8be436 in irc_protocol_cb_mode (server=0x561f9a81f440, date=0, nick=0x561f9b868fd0 "el", address=0x561f9c117740 "el@freenode/staff/el", host=0x561f9bfbc5c0 "el!el@freenode/staff/el",
    command=0x7f81ce9036e0 "mode", ignored=0, argc=5, argv=0x561f9b852fb0, argv_eol=0x561f9c148fa0) at /home/cerdea/weechat/src/plugins/irc/irc-protocol.c:1411
        pos_modes = 0x561f9c119c20 "+q"                                  
        pos_modes_args = 0x561f9c106960 "$a:l3os3mili3"               
        smart_filter = 0                                 
        local_mode = 5                                    
        ptr_channel = 0x561f9bd2af50                               
        ptr_nick = 0x561f9bcaabb9                                             
        ptr_buffer = 0x561f9bcaab80                     
#10 0x00007f81ce8d24d0 in irc_protocol_recv_command (server=0x561f9a81f440, irc_message=0x561f9c1265f0 ":el!el@freenode/staff/el MODE #freenode +q $a:l3os3mili3", msg_command=0x561f9c0c9780 "MODE",
    msg_channel=0x561f9c038f00 "#freenode") at /home/cerdea/weechat/src/plugins/irc/irc-protocol.c:6486
        i = 10                                                  
        cmd_found = 10                                                    
        return_code = 0                                                 
        argc = 5                                                             
        decode_color = 1                                          
        keep_trailing_spaces = 0                                          
        message_ignored = 0                                              
        message_colors_decoded = 0x561f9c121d80 ":el!el@freenode/staff/el MODE #freenode +q $a:l3os3mili3"
        pos_space = 0x561f9c1425e7 ""                
        tags = 0x561f9bfc1c20 "\377\377\377\377\037V"
        ptr_channel = 0x561f9bd2af50                            
        cmd_recv_func = 0x7f81ce8be1f2 <irc_protocol_cb_mode>
        cmd_name = 0x7f81ce9036e0 "mode"               
        ptr_msg_after_tags = 0x561f9c1265f0 ":el!el@freenode/staff/el MODE #freenode +q $a:l3os3mili3"                                                                                                                  
        date = 0                                                                                                                                                                                            
        nick1 = 0x7f81ceb11860 <nick> "el"           
        address1 = 0x7f81ceb118e0 <address> "el@freenode/staff/el"
        host1 = 0x561f9c1265f1 "el!el@freenode/staff/el MODE #freenode +q $a:l3os3mili3"
        nick = 0x561f9b868fd0 "el"                    
        address = 0x561f9c126a00 "el@freenode/staff/el"    
        address_color = 0x561f9c117740 "el@freenode/staff/el"                                                                                                                                             
        host = 0x561f9c1425d0 "el!el@freenode/staff/el"                                                           
        host_no_color = 0x561f9c139d30 "el!el@freenode/staff/el"                                                                                                                                                                
        host_color = 0x561f9bfbc5c0 "el!el@freenode/staff/el"                              
        argv = 0x561f9b852fb0                              
        argv_eol = 0x561f9c148fa0                                         
        hash_tags = 0x0
