### ISSUE TITLE
Rename "aspell" plugin to "spell"

### ISSUE THREAD

**Issue by flashcode** [weechat/weechat#1299]
The "aspell" plugin should be renamed to "spell", since it supports aspell but also enchant.

The following things must be renamed:

- source directory src/plugins/apell --> src/plugins/spell
- sources: aspell-\*.[ch] --> spell-\*.[ch] (+ doc)
- plugin aspell --> spell
- file aspell.conf --> spell.conf
- options aspell.* --> spell.*
- command /aspell --> /spell
- default key alt-s: /mute aspell toggle --> /mute spell toggle
- bar item aspell_dict --> spell_dict
- bar item and local variable aspell_suggest --> spell_suggest
- info aspell_dict --> spell_dict

The following "official" scripts must be updated accordingly:

- iset.pl: example in `/help iset`
- spell_menu.pl
- spell_correction.py

**Comment by weechatter** [comment]
spell_correction.py 0.8 supports aspell / spell plugin

**Comment by weechatter** [comment]
spell_menu.pl 0.5 supports aspell / spell plugin

**Comment by flashcode** [comment]
Done.
