### ISSUE TITLE
Problem using websocket from a python script

### ISSUE THREAD

**Issue by trygveaa** [weechat/weechat#1305]
## Question

I'm maintaining the slack script, which uses a websocket connection. Recently, multiple users have experienced the websocket connection not working, and now I experience it too. What happens is that I get a `[Errno 4] Interrupted system call` exception when I try to connect. I don't know what the cause of it is, it just suddenly started happening without any changes to my system.

Here is a simple script reproducing the issue. Though, it might not happen for you, as it seems to only be a problem on some machines.

```
from websocket import create_connection
import weechat

if __name__ == '__main__':
    weechat.register('websocket-test', 'trygveaa', '0.1', 'MIT', 'websocket test', '', '')
    ws = create_connection('wss://echo.websocket.org')
```

If I run this script outside of weechat (removing import weechat and register), it works fine.

The only thing I find when searching for this issue is people saying I should retry connecting, such as https://stackoverflow.com/questions/14136195/what-is-the-proper-way-to-handle-in-python-ioerror-errno-4-interrupted-syst. However, if I try that, the issue just keeps happening (and weechat hangs while it tries). It never connects, no matter how many times I retry.

Here is the stack trace of the error, if that's interesting:

```
18:42 python: stdout/stderr (websocket-test): Traceback (most recent call last):
18:42 python: stdout/stderr (websocket-test):   File "/home/trygve/.weechat/python/websocket-test.py", line 6, in <module>
18:42 python: stdout/stderr (websocket-test):     ws = create_connection('wss://echo.websocket.org')
18:42 python: stdout/stderr (websocket-test):   File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 511, in create_connection
18:42 python: stdout/stderr (websocket-test):     websock.connect(url, **options)
18:42 python: stdout/stderr (websocket-test):   File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 220, in connect
18:42 python: stdout/stderr (websocket-test):     options.pop('socket', None))
18:42 python: stdout/stderr (websocket-test):   File "/usr/lib/python2.7/site-packages/websocket/_http.py", line 120, in connect
18:42 python: stdout/stderr (websocket-test):     sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
18:42 python: stdout/stderr (websocket-test):   File "/usr/lib/python2.7/site-packages/websocket/_http.py", line 186, in _open_socket
18:42 python: stdout/stderr (websocket-test):     raise error
18:42 python: stdout/stderr (websocket-test): socket.error: [Errno 4] Interrupted system call
```

I see that [websocket-client](https://pypi.org/project/websocket-client/) has an example for "Long-lived connection" which doesn't use `create_connection`. However, that uses threads, and I'm not sure if that's possible inside weechat? If I try it, weechat dies with `Fatal Python error: Py_EndInterpreter: not the last thread` when I unload the script. Maybe I could stop the thread before unloading, but it seems problematic that weechat would die if I don't stop the thread properly.

Do you have any idea as to what could cause this issue? Should I connect to the websocket in a different way?

Related wee-slack issues: https://github.com/wee-slack/wee-slack/issues/676, https://github.com/wee-slack/wee-slack/issues/671 and https://github.com/wee-slack/wee-slack/issues/656

---

- WeeChat version: 2.3
- OS, distribution and version: Arch Linux, fully updated

**Comment by trygveaa** [comment]
Oh, that script in isolation doesn't trigger the issue. It only happens after a script (the same, or another one) has done a http request. So if I run that script right after starting weechat, the issue doesn't happen. However, if I run this script first, then the script in the first post fails as described:

```
import weechat

def callback_http(data, command, return_code, out, err):
    weechat.prnt('', 'http request completed')
    return weechat.WEECHAT_RC_OK

if __name__ == "__main__":
    weechat.register('http-test', 'trygveaa', '0.1', 'MIT', 'http test', '', '')
    weechat.hook_process_hashtable('url:https://weechat.org', {}, 60000, 'callback_http', '')
```

Or if I run only this script, which first does a http request and then connects to a websocket, it fails:

```
from websocket import create_connection
import weechat

def callback_connect(data, command, return_code, out, err):
    ws = create_connection('wss://echo.websocket.org')
    return weechat.WEECHAT_RC_OK

if __name__ == '__main__':
    weechat.register('websocket-test', 'trygveaa', '0.1', 'MIT', 'websocket test', '', '')
    weechat.hook_process_hashtable('url:https://weechat.org', {}, 60000, 'callback_connect', '')
```

**Comment by sim642** [comment]
Looking at wee-slack's code it seems to correctly make the socket non-blocking and `hook_fd` it for asynchronous use. But that is done _after_ a successful `connect`, which itself is still a blocking operation within the websocket library. To be completely correct it seems to me that the `connect` call should also happen non-blockingly and be handled asynchronously because it is not an instant operation. Working around the websocket library to get that to happen may not be so simple though.

Blind retrying of `connect` doesn't help if the connection establishment takes too long on every single attempt while Weechat receives another signal in that duration. The coincidence of that happening around `hook_process` is that the latter involves some process signaling, I think.

**Comment by trygveaa** [comment]
Thanks for the info! Unfortunately, I'm not aware of any async websocket clients for python 2. Not sure how much work it would be to make websocket-client async capable either. Maybe we can use websockets (which use asyncio) when we move to python 3.

Having the websocket-client library retry the connection, instead of retrying the whole `create_connection` seems to work, as shown in https://github.com/websocket-client/websocket-client/issues/527. However, with that we still have the issue that the `create_connection` could hang weechat.

**Comment by trygveaa** [comment]
I submitted a PR against websocket-client for retrying on EINTR: https://github.com/websocket-client/websocket-client/pull/528

That fixes the issue for me. Though, weechat still hangs on connect (only a short while on good internet connections, but longer on poor). But I guess making websocket-client async might be a fair amount of work.

**Comment by trygveaa** [comment]
Sorry, I forgot to close this. The PR mentioned in the last comment has been merged and released, so this issue is solved.
