### ISSUE TITLE
Spellchecking applied to tab completed nicks

### ISSUE THREAD

**Issue by longtimelongtime** [weechat/weechat#1306]
## Bug summary

After running the command `/set weechat.completion.nick_completer ": "`, spellchecking is now applied to tab completed nicks (first word on line). This was not the case in previous WeeChat releases.

---

- WeeChat version: 2.4
- OS, distribution and version: Ubuntu 18.04

**Comment by sim642** [comment]
This issue might be the actual cause of the `colorize_nicks.py` behavior change between 2.3 and 2.4 I thought I noticed but couldn't really explain. I did some more comparative testing in the light of this issue.
The results are in the following table (default choices in **bold**):

| `nick_completer` | 2.3 | 2.4 |
| --- | --- | --- |
| `":"` | **No spelling error (one space)** | No spelling error (no space) |
| `": "` | Spelling error (two spaces) | **Spelling error (one space)** |
| `","` | No spelling error (one space) | No spelling error (no space) |
| `", "` | Spelling error (two spaces) | Spelling error (one space) |

As the table shows, the spelling error behavior for tab completion didn't actually change between the versions at all, but it's instead influenced by whether `nick_completer` ends with a space or not. The bug only appeared now when the space behavior of `nick_completer` and its default got changed in 2.4.

This explains the change I saw regarding spellchecking and `colorize_nicks.py`. So the script didn't somehow break, WeeChat just spellchecks the tab completed nick in 2.4, but didn't before and hence the difference. (Nevertheless, the script still is problematic in that regard and should still work too but that's unrelated.)

**Comment by sim642** [comment]
Also forgot to mention that it doesn't only apply to tab completing nicks. When manually writing the exact same text that would be completed (with the `nick_completer` that would be added), the same difference is observed depending on whether `nick_completer` ends with a space or not.

**Comment by flashcode** [comment]
I think the bug it not caused by WeeChat, could you please confirm @longtimelongtime?
If possible, you could try with version 2.3 and 2.4, without any scripts loaded, to confirm there's the same behavior on spell checking.
Thanks.
