### ISSUE TITLE
Won't install python plugin on CentOS 7

### ISSUE THREAD

**Issue by aewens** [weechat/weechat#1310]
## Bug summary

When building either WeeChat 2.3 or 2.4 from source on CentOS 7, WeeChat will not build the python plugin even though both python and python-devel are installed on the system in their default locations.

## Current behavior

WeeChat loads with:
`Plugins loaded: alias, buflist, charset, exec, fifo, fset, irc, logger, perl, php, relay, script, trigger, xfer`
When attempting to install a python plugin (e.g. colorize_nicks.py) the following error occurs:
`script: script "colorize_nicks.py" can not be installed because plugin "python" is not loaded`

## Steps to reproduce

1. `mkdir -p /opt/weechat-2.4` 
1. `wget https://weechat.org/files/src/weechat-2.4.tar.xz` 
1. `tar -xvf weechat-2.4.tar.xz` 
1. `cd weechat && mkdir build && cd build`
1. `cmake .. -DCMAKE_INSTALL_PREFIX=/opt/weechat-2.4`
1. `make`
1. `make install`
1. `/opt/weechat-2.4/bin/weechat`

## Desired behavior

Install the Python plugin into weechat so plugins written in Python will install / work in general.

## Suggested solutions

N/A

## Additional information

The version of Python installed is 2.7.5

---

- WeeChat version: 2.3 and 2.4
- OS, distribution and version: CentOS Linux release 7.6.1810

**Comment by flashcode** [comment]
What's the output of `cmake -LA .. | grep -i python`?
Where is python binary (python2.7) on your system, and libpython2.7.so?

**Comment by aewens** [comment]
```
$ cmake -LA .. -DCMAKE_INSTALL_PREFIX=/opt/weechat-2.4 | grep -i python
ENABLE_PYTHON:BOOL=ON
ENABLE_PYTHON3:BOOL=OFF
PYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2.7
PYTHON_INCLUDE_PATH:PATH=/usr/include/python2.7
PYTHON_LIBRARY:FILEPATH=/usr/lib64/python2.7/config/libpython2.7.so

$ python -V
Python 2.7.5

$ which python
/usr/bin/python

$ ls -la /usr/bin/python
lrwxrwxrwx. 1 root root 7 Dec  6 11:21 /usr/bin/python -> python2

$ ls -la /usr/bin/python2
lrwxrwxrwx. 1 root root 9 Dec  6 11:21 /usr/bin/python2 -> python2.7

$ locate libpython2.7.so
/usr/lib64/libpython2.7.so
/usr/lib64/libpython2.7.so.1.0
/usr/lib64/python2.7/config/libpython2.7.so
```

**Comment by flashcode** [comment]
So it seems Python is properly detected by cmake.
After the make install, can you check in WeeChat plugins directory if python.so is there?
(`make install` should display the files installed, with their location)

**Comment by aewens** [comment]
I'm a bit confused now. I have not changed anything since the last time I tried this, but upon re-installing it again it seems to be working now...

Sorry to waste your time, you can close this ticket.
