### ISSUE TITLE
Change in behavior: nick completion no longer adds space

### ISSUE THREAD

**Issue by craigmaloney** [weechat/weechat#1314]
## Question

It seems that with weechat 2.4 I'm no longer getting a space whenever I tab-complete a nick.

Before I would get the following (spaces are denoted with "`b`")

`cm[tab]` would expand to "`cmaloney:b`"

now I get:

`cm[tab]` expands to "`cmaloney:`" 

The space was present in previous versions, but for some reason it seems to have changed.

Is there a setting that I'm overlooking to set the behavior back to adding the space after the colon?

(Thanks in advance)

---

- WeeChat version: 2.4
- OS, distribution and version: Ubuntu 14.04 (using Weechat PPA)

**Comment by Mikaela** [comment]
I think you are missing

> core: do not automatically add a space when completing "nick:" at the beginning of command line (the space can be added in option `weechat.completion.nick_completer`)

From the changelog https://weechat.org/files/changelog/ChangeLog-2.4.html

**Comment by craigmaloney** [comment]
Ah. That's the one. Thanks.

Curious why this changed in between releases. :grin:

**Comment by flashcode** [comment]
@craigmaloney: this has been changed to be more flexible. You can choose to add a space or not, but the space remains the default; this is just not automatically set automatically on upgrade, see: https://weechat.org/files/releasenotes/ReleaseNotes-devel.html#v2.4_nick_completer
