### ISSUE TITLE
I have not access to weechat.org from my country (Russia)

### ISSUE THREAD

**Issue by whoizit** [weechat/weechat#1315]
`script: downloading list of scripts...`

`178.63.0.0/16;;;��������������;27-31-2018/��2971-18;2018-04-16`

Just check this out, actual data about blocking. 
17mb file https://raw.githubusercontent.com/zapret-info/z-i/master/dump.csv

maybe possible change publishing system for plugins, in github for example? I belive, they can't permanent block github

**Comment by flashcode** [comment]
Hi,
The scripts list is download from weechat.org, which is not hosted on github.
The problem may not be related to site blocked, it can be a HTTPS certificate issue too, check this question in FAQ: https://weechat.org/files/doc/devel/weechat_faq.en.html#scripts_update

**Comment by whoizit** [comment]
I can open site over proxy, but `curl weechat.org` nothing return. Do you still thinking it's https cert related problem? I have certs in my Void Linux and it's properly sets in weechat options. I have no errors about certs, Site IP subnet is totally blocked in my country and you can double checked it's on goverment site https://blocklist.rkn.gov.ru if you don't belive link with actual information I posted above, but you need russian proxy for this, cause it's not accesseble from other countries, for example http://cmle.ru and also google translater or something like this. I think you can post plugins.*.gz file in github file uploads. Or maybe change program logic, to checkout plugins from github directly or something

**Comment by flashcode** [comment]
If weechat.org is blocked in Russia, you should see that with your provider to fix this problem, I can not help with sites blocked in some countries.
And I'm sorry, but I don't plan to move this file elsewhere because of weechat.org being blocked, this is not the right solution for me.
I see no reason to block weechat.org, it's completely free software, no politic here or whatever. Maybe an issue with the name which is similar to WeChat, the Chinese chat app (and which has nothing to do with WeeChat)?

**Comment by whoizit** [comment]
I wrote above, blocked subnet 178.63.0.0/16, ofcourse it's not about weechat and not about WeChat. A lot of different services can be served on this subnet or they have blocked the entire hosting provider with holy war vs. Telegram chat, because they can.

**Comment by flashcode** [comment]
Then maybe you can submit a request to unblock WeeChat IP addresses:

- IPv4: 178.63.40.67
- IPv6: 2a01:4f8:120:2066::2

**Comment by whoizit** [comment]
do you want me to go to court? not

**Comment by weechatter** [comment]
https://downforeveryoneorjustme.com/weechat.org

**Comment by whoizit** [comment]
> https://downforeveryoneorjustme.com/weechat.org

please read, I wrote above, I can open site over proxy

**Comment by flashcode** [comment]
If you can use a proxy, then please use a proxy in WeeChat, see `/help weechat.network.proxy_curl`.

This is not a WeeChat neither weechat.org issue for me, so I close the issue.

**Comment by Mikaela** [comment]
Would you be open for offering Tor/Onion, Yggdrasil, Cjdns or I2P mirror to WeeChat.org? I think it would resolve this and those would be a lot more difficult to censor.

> https://downforeveryoneorjustme.com/weechat.org

I think a better link would be https://isitblockedinrussia.com/?host=weechat.org

![screenshot from 2019-02-24 13-24-29](https://user-images.githubusercontent.com/831184/53298503-f2818d00-3826-11e9-98d7-e9af7d370afa.png)

**Comment by whoizit** [comment]
https://reestr.rublacklist.net/visual/
![2019-02-24-231706_1112x955_scrot](https://user-images.githubusercontent.com/359276/53304832-ff37cc80-388a-11e9-8f5f-175f67686f23.png)
