### ISSUE TITLE
Homebrew installation instructions for build flags are out of date

### ISSUE THREAD

**Issue by mattsmithdatera** [weechat/weechat#1317]
## Bug summary

Installing weechat on OSX with python support (or any other option support such as ruby) fails.

With the 2.0.0 release of Homebrew, build flags have been completely disabled across the board.  The only way to build with a build flag is to put it in the default formula.

## Steps to reproduce

1. Update to the latest version of homebrew
2. Run `brew install weechat --with-python`

## Current behavior
You get the error:
```
Error: invalid option: --with-python
```

## Expected behavior
Installation proceeds as normal and weechat builds with python support

## Suggested solutions

1. Update the installation instructions for building on OSX with python to not suggest Homebrew because building with flags is no longer possible
2. Update the formula for weechat in Homebrew to build all optional features by default.

## Additional information

---

- WeeChat version: NA
- OS, distribution and version: OSX Mojave, Homebrew

**Comment by flashcode** [comment]
I could remove the Homebrew command in doc and just link to the Homebrew page with instructions then? (I don't know which URL should be linked)

**Comment by mattsmithdatera** [comment]
Here's the link in the english docs:
https://github.com/weechat/weechat/blob/master/doc/en/weechat_user.en.adoc#22-source-package

I think we should update the docs to suggest building from source just like linux because that's the only way I know of to get the python plugin functionality on OSX now that Homebrew doesn't allow build flags.

**Comment by flashcode** [comment]
Fixed by commit 31d0742aed370dc77f143539c120bb403b8abd3f.
