### ISSUE TITLE
Number of unread messages from bash script

### ISSUE THREAD

**Issue by tdehaeze** [weechat/weechat#1321]
## Question

Hi everyone, 
I there any way to get the number of unread messages from a bash script?

I would like to integrate the number of unread message that I have reveiced on weechat into my status bar.

Thank you very much
---

- WeeChat version: 2.4
- OS, distribution and version: Manjaro Linux

**Comment by tdehaeze** [comment]
Thanks I'll have a look

**Comment by weechatter** [comment]
You're welcome. better and faster support is available on freenode.#weechat ;-)
