### ISSUE TITLE
/secure passphrase warning above 1023 characters

### ISSUE THREAD

**Issue by tya99** [weechat/weechat#1323]
## Bug summary
I was messing around with this as a part of https://github.com/weechat/weechat/issues/1286

I what I discovered is you can set a `/secure passphrase <password>` to any length, however when you load weechat up the password must be < 1024 characters to work.

I tested this in termite and urxvt-unicode

## Steps to reproduce

1. `pwgen -1 1024`
2. /secure passphrase <password that is 1024 characters>
3. /secure set some data
4. Quit weechat and try to enter password, will always be wrong
5. If the password was less than 1024 characters ie 1023 characters it will work.
6. If you enabled a passphrase_file ie `/set sec.crypt.passphrase_file` then it must be less than 1025 characters (1024 maximum) to work.

## Suggested solutions
Maybe not allow a person to set a password longer than 1023 characters. My guess is the limit is 1024, but there's a new line character when you hit return on the password screen when weechat starts.

This might be why weechat allows a password of 1024 characters when using a passphrase_file.

I haven't looked at the source, this was from blackbox testing.

---

- WeeChat version: 2.4
- OS, distribution and version: Arch Linux

**Comment by flashcode** [comment]
Hi,
Yes there's a hardcoded limit to 1024: https://github.com/weechat/weechat/blob/master/src/core/wee-secure-config.c#L57
I'll increase this limit and display an error in `/secure passphrase` when the passphrase is too long.

**Comment by flashcode** [comment]
The max length is now 4096 chars, and you can really use a passphrase of exactly 4096 chars (length ≥ 4097 is rejected).

**Comment by flashcode** [comment]
And thanks for the good bug report, very clear! :+1:

**Comment by tya99** [comment]
> And thanks for the good bug report, very clear! +1

No problems..
