### ISSUE TITLE
Connection fails to relay using SSL

### ISSUE THREAD

**Issue by michaelelleby** [weechat/weechat#1326]
## Bug summary
Connection is suddenly failing to weechat client from glowing-bear.org using Firefox on Windows 10 and using Android client Glowing-Bear on Android 8.0.0

## Steps to reproduce

1. Install weechat 2.4-1 on Raspbian stetch
2. Install Let's Encrypt certificates
2. Enable SSL relay
3. Connect using https://www.glowing-bear.org

## Current behavior
Connection refused and weechat logs a message, saying `error -12 A TLS fatal alert has been received.`

## Expected behavior
Being ablel to connect from https://www.glowing-bear.org

## Additional information

---

- WeeChat version: WeeChat 2.4 [compiled on Feb 17 2019 13:53:50]
- OS, distribution and version: Raspbian 9.8
`Linux raspberrypi 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux`

**Comment by flashcode** [comment]
Hi,

How did you install certificates, what settings did you change in WeeChat?
Did you issue the command `/relay sslcertkey` after this setup?

**Comment by michaelelleby** [comment]
Turns out my SSL certificate was expired. Renewing it fixed the issue.
