### ISSUE TITLE
Weechat-Headless Crash When Trying To Reload Relay Plugin From Glowing Bear

### ISSUE THREAD

**Issue by vectr0n** [weechat/weechat#1327]
## Bug summary
When I issued ```/plugin reload relay``` while connecting to the relay with Glowing Bear, weechat-headless crashes and produces a crash log and core file.

## Steps to reproduce

1. /plugin reload relay 

## Current behavior

Weechat-headless crashes when issuing ```/plugin reload relay``` from Glowing Bear.

## Expected behavior
Relay plugin gets reloaded.

## Additional information

(gdb) bt full
#0  0x00000008007f245a in thr_kill () from /lib/libc.so.7
No symbol table info available.
#1  0x00000008007f0844 in raise () from /lib/libc.so.7
No symbol table info available.
#2  0x0000000800763079 in abort () from /lib/libc.so.7
No symbol table info available.
#3  0x000000000023ccbf in ?? ()
No symbol table info available.
#4  0x00000008006264c4 in ?? () from /lib/libthr.so.3
No symbol table info available.
#5  0x0000000800625a22 in ?? () from /lib/libthr.so.3
No symbol table info available.
#6  <signal handler called>
No symbol table info available.
#7  0x000000080296b00a in ?? ()
No symbol table info available.
#8  0x0000000803b6ff00 in ?? ()
No symbol table info available.
#9  0x00007fffffffe900 in ?? ()
No symbol table info available.
#10 0x00007fffffffe930 in ?? ()
No symbol table info available.
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

---

- WeeChat version: 2.4
- OS, distribution and version: FreeBSD 12.0-RELEASE-p3

**Comment by weechatter** [comment]
On ubuntu / raspbian, i can not reproduce:
/plugin reload relay

22:51 		relay: Socket wurde für weechat (Port 9033) geschlossen
22:51 		relay: Trennung von Client 1/weechat/127.0.0.1
22:51 		Erweiterung "relay" wurde beendet
22:51 		relay: Lausche am Port 9033 (Relay: weechat,IPv4, Max.: 3 Clients)
22:51 		Erweiterung "relay" wurde installiert
22:51 		relay: neuer Client an Port 9033: 1/weechat/127.0.0.1

glowing-bear and weechat-android:
22:58 		relay: Socket wurde für weechat (Port 9033) geschlossen
22:58 		relay: Trennung von Client 2/weechat/127.0.0.1
22:58 		relay: Trennung von Client 1/weechat/192.168.178.99
22:58 		Buffer geschlossen: relay.relay.list
22:58 		Erweiterung "relay" wurde beendet
22:58 		relay: Lausche am Port 9033 (Relay: weechat,IPv4, Max.: 3 Clients)
22:58 		Erweiterung "relay" wurde installiert
22:58 		relay: neuer Client an Port 9033: 1/weechat/192.168.178.99
22:58 		relay: neuer Client an Port 9033: 2/weechat/127.0.0.1

**Comment by flashcode** [comment]
I can reproduce the crash when doing the command in Glowing Bear, on FreeBSD only (no crash on Linux).
I'll investigate the problem.
