### ISSUE TITLE
Add the ability to squash lines when pasting several lines

### ISSUE THREAD

**Issue by oakkitten** [weechat/weechat#1329]
When pasting several lines with the bracketed paste, WeeChat ask if I want to paste the lines as-is:

    Paste 2 lines? [ctrl-Y] Yes [ctrl-N] No

Which is usually what I want, but often the text is a copy from a pdf or other sources containing unwanted line breaks, and what I want to paste is not `Hello\nWorld` but `Hello World`. I propose the ability to squash the lines like this:

    Paste 2 lines? [ctrl-Y] Yes [ctrl-N] No [ctrl-S] Squash

Pressing ctrl-S would cancel the prompt and put `Hello World` into the input field.

***

Additionally, it would be useful to manipulate the pending paste. For instance, I'd like to be able to type `>` and then paste (input looking like this `Paste 2 lines? [ctrl-Y] Yes [ctrl-N] No >`), which would result in all lines prefixed with `>` in an email/greentext kind of quote (`>Hello\n>World`). As I understand, it's not possible to achieve this in a non-hacky way right now.

**Comment by flashcode** [comment]
Closing this issue, as #1502 has been merged in 4.0.0, and now you are able to edit the input before sending lines.
