### ISSUE TITLE
irc: error: Error in the pull function

### ISSUE THREAD

**Issue by shibumi** [weechat/weechat#1330]
## Bug summary

I have the following setup:
Host A has a weechat instance running tmux and is serving two relays. One IRC Relay and one Weechat Relay.

Host B is my laptop and I use my weechat to connect to the IRC relay. On this IRC relay I have configured two IRC servers: hackint and freenode.

Connecting to it works fine and everything works as expected,  until my internet connection crashes.

When my internet connection crashes, I timeout. Then my connection comes back again I use `/reconnect -all` to reconnect to the IRC relays again. For the hackint IRC relay this works fine, but for the freenode IRC relay I get errors like this:
```
18:25:49 freenode_relay  -- | irc: reconnecting to server...
18:25:49 freenode_relay  -- | irc: connecting to server nullday.de/9002 (SSL)...
18:25:49 freenode_relay =!= | irc: TLS handshake failed
18:25:49 freenode_relay =!= | irc: error: Error in the pull function.
18:25:49 freenode_relay  -- | irc: reconnecting to server in 20 seconds
18:26:09 freenode_relay  -- | irc: reconnecting to server...
18:26:09 freenode_relay  -- | irc: connecting to server nullday.de/9002 (SSL)...
18:26:09 freenode_relay =!= | irc: TLS handshake failed
18:26:09 freenode_relay =!= | irc: error: Error in the pull function.
18:26:09 freenode_relay  -- | irc: reconnecting to server in 40 seconds
18:26:49 freenode_relay  -- | irc: reconnecting to server...
18:26:49 freenode_relay  -- | irc: connecting to server nullday.de/9002 (SSL)...
18:26:49 freenode_relay =!= | irc: TLS handshake failed
18:26:49 freenode_relay =!= | irc: error: Error in the pull function.
18:26:49 freenode_relay  -- | irc: reconnecting to server in 1 minute, 20 seconds
18:28:09 freenode_relay  -- | irc: reconnecting to server...
18:28:09 freenode_relay  -- | irc: connecting to server nullday.de/9002 (SSL)...
18:28:09 freenode_relay =!= | irc: TLS handshake failed
18:28:09 freenode_relay =!= | irc: error: Error in the pull function.
18:28:09 freenode_relay  -- | irc: reconnecting to server in 2 minutes, 40 seconds
18:30:49 freenode_relay  -- | irc: reconnecting to server...
18:30:49 freenode_relay  -- | irc: connecting to server nullday.de/9002 (SSL)...
18:30:49 freenode_relay =!= | irc: TLS handshake failed
18:30:49 freenode_relay =!= | irc: error: Error in the pull function.
18:30:49 freenode_relay  -- | irc: reconnecting to server in 5 minutes, 20 seconds
18:36:09 freenode_relay  -- | irc: reconnecting to server...
18:36:09 freenode_relay  -- | irc: connecting to server nullday.de/9002 (SSL)...
18:36:09 freenode_relay =!= | irc: TLS handshake failed
18:36:09 freenode_relay =!= | irc: error: Error in the pull function.
18:36:09 freenode_relay  -- | irc: reconnecting to server in 10 minutes
```
Note: The connection recovers faster when I close weechat completely and wait around 5min and then connect instead of trying reconnecting over minutes.

I am unable to reconnect to my freenode IRC relay.
Then after around 20 min my weechat reconnects again as expected and everything works fine.
This bug is super annoying. On my Weechat Android Client I don't have such behavior.

On my server (Host A) I have setup the following parameter:
` weechat.network.gnutls_ca_file             string   "/home/chris/hackint_rootca.crt`
I guess the bug has something todo with this. It's basically my local rootca chain + the hackint root CA. This seems to affect the freenode relay at some point. The hackint relay is fine.

## Steps to reproduce

0. Set a custom ca file for hackint
1. Setup a Host with weechat and IRC relays for Freenode and Hackint
2. stop your internet connection (pull the ethernet cable or just turn off your router/AP)
3. Try to reconnect

## Current behavior

See above

## Expected behavior

I should be able to reconnect without the need to wait more than 20 minutes..

## Suggested solutions

-

## Additional information

-

---

- WeeChat version: 2.4
- OS, distribution and version:  Arch Linux

**Comment by flashcode** [comment]
Hi,
Do you still have the issue with the latest version, 4.0.4 or 4.1.0-dev?
