### ISSUE TITLE
libdir is hard-coded in weechat.pc

### ISSUE THREAD

**Issue by orbea** [weechat/weechat#1341]
## Bug summary

The `weechat.pc` file has a hard-coded `libdir`.

On my system using `weechat-2.4`.
```
prefix=/usr
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: weechat
Description: Weechat plugins headers
Version: 2.4
Cflags: -I${includedir}/weechat
```

I have a 64-bit system which installs weechat libs to `/usr/lib64/weechat/` so I assume it should be `libdir=${exec_prefix}/lib64/weechat`?

`libdir` is set here.

https://github.com/weechat/weechat/blob/38535686f841c107cb95ff618f7b152af98a8ff4/weechat.pc.in#L3

And here.

https://github.com/weechat/weechat/blob/38535686f841c107cb95ff618f7b152af98a8ff4/CMakeLists.txt#L264

## Steps to reproduce

1. Build weechat using cmake with: `-DLIBDIR=/usr/lib64`
2. Look at `weechat.pc` in the build directory which doesn't reflect the correct lib directory.

## Current behavior

The `weechat.pc` file has a hard-coded `libdir`.

## Expected behavior

The `weechat.pc` file should show the correct `libdir` as defined by the `LIBDIR` cmake variable.

## Suggested solutions

It probably should be fixed here by removing `${PROJECT_NAME}`.

https://github.com/weechat/weechat/blob/38535686f841c107cb95ff618f7b152af98a8ff4/CMakeLists.txt#L62

But I think this will require changing `LIBDIR` accordingly in a lot of other places.

## Additional information

N/A

---

- WeeChat version: `weechat-2.4`
- OS, distribution and version: `Slackware64-current`

**Comment by ryan-farley** [comment]
Going off the autotools build setup, the fix would be to use the variable `WEECHAT_LIBDIR` instead of `LIBDIR` in CMakeLists.txt. It's not actually used in all that many places.
