### ISSUE TITLE
Package aditional icon sizes

### ISSUE THREAD

**Issue by lovesegfault** [weechat/weechat#1347]
## Feature description
Right now, at least on Gentoo, Weechat only packages a 32x32 png icon. Since more and more screens are becoming HiDPI, that icon size is becoming really tiny. 

It would be really nice if Weechat packages additional icon sizes, such as 64x64, 96x96, and 128x128.

**Comment by flashcode** [comment]
OK, I'll add that.

**Comment by flashcode** [comment]
In the meanwhile, if you need larger icons, you can find the logo there: https://weechat.org/files/logo/

**Comment by lovesegfault** [comment]
Thank you!

**Comment by flashcode** [comment]
I added 16x16, 32x32, 64x64, 128x128, 256x256 and 512x512, not sure if other sizes are really needed (since these ones can easily be rescaled to a smaller size if needed).

**Comment by lovesegfault** [comment]
I think that selection will work perfectly for most people
