### ISSUE TITLE
Japanese mozc input offsets nick list divider

### ISSUE THREAD

**Issue by SnowyLea** [weechat/weechat#1350]
## Bug summary

when typing Japanese text via mozc in lubuntu 18.10 (32-bit) the blue bar | dividing chat from nick list gets pushed to the right superimposed on nicks

## Steps to reproduce

1. install mozc japanese input
2. install weechat from muon package manager in lubuntu 18.10 (32-bit)
3. send message in freenode chat room in japanese

## Current behavior

pushes dividing bar to the right over nick list; see [this screenshot](https://x0.at/cx-.jpg)

## Expected behavior

does not affect bar dividing chat from nick list

## Additional information

---

- WeeChat version: 2.2
- OS, distribution and version: lubuntu 18.10, 32-bit

**Comment by weechatter** [comment]
its a common problem. please check FAQ first:
https://weechat.org/files/doc/stable/weechat_faq.en.html#display

**Comment by flashcode** [comment]
This could be related to your glibc version or the terminal used.
You could try with the latest WeeChat release (version 2.4), a newer Ubuntu version (19.04) or another terminal.

**Comment by flashcode** [comment]
Closing the issue (no reply).
