### ISSUE TITLE
/exec -sh should use user’s shell

### ISSUE THREAD

**Issue by treyharris** [weechat/weechat#1356]
## Bug summary

`/exec -sh` runs its commands by invoking the value of `exec.command.shell` (by default, `sh`), no matter what the user’s configured shell is; the configuration `exec.command.shell` can be changed, but not to a dynamic value that will track the configured shell.

## Steps to reproduce

1. `/exec -sh echo SHELL=$SHELL cmd=$0`

## Current behavior
(Without specific configuration):

```
SHELL=/bin/zsh cmd=sh
```

## Expected behavior

```
SHELL=/bin/zsh cmd=/bin/zsh
```

## Suggested solutions

If backwards compatibility seems necessary or desirable, either:
- change the behavior of `exec.command.shell` so that it still defaults to `sh`, and, if set, will be used as the shell for `/exec -sh`, but, if unset/set to the empty string, will result in `$SHELL` being used
- an `exec.command.use_default_shell` boolean that, when set, will cause `/exec -sh` to use `$SHELL`, ignoring `exec.command.shell`

## Additional information

`sh` on many platforms is a shell such as Dash with extremely limited capabilities compared to the shell which likely called WeeChat in the first place.

Note that a config variable that must be set to the shell command (such as the current implementation of `exec.command.shell` with default `sh` that I could change to `/bin/zsh`) is _not_ acceptable by itself, since it would not follow changes to the user’s shell made via the `chsh` command, or correctly deal with cases where on different hosts or platforms the same shell may have different names or paths. Some ability to dynamically follow the value of `$SHELL` is necessary.

---

- WeeChat version:  2.5
- OS, distribution and version: Ubuntu 18.04 LTS

**Comment by flashcode** [comment]
Done, the new default value of option is `${env:SHEL}` (and then the option is now evaluated).
