### ISSUE TITLE
Improve relay log messages

### ISSUE THREAD

**Issue by kraem** [weechat/weechat#1358]
## Feature description

After scanning through the log to see if unauthorised connection attempts were more than just attempts I found the logging a bit confusing.

It is sometimes unclear if a connection attempt was successful and later disconnected, or if it just was an attempt to authenticate but failed.

## Suggestion

When a client first tries to connect log a message stating that the relay is waiting for authentication and indicate if the authentication was successful:
```
relay: new client on port 12345: 1/weechat/127.0.0.1 (waiting for authentication)
relay: client 1/weechat/127.0.0.1: authentication OK
relay: disconnected from client 1/weechat/127.0.0.1
```

#### Examples
**Connection not made by me**
```
06:25:48 |   | relay: new client on port 9001: 2/ssl.weechat/x.x.x.x
06:25:54 | =!= | relay: reading data on socket for client 2/ssl.weechat/x.x.x.x: error 0 (connection closed by peer)
06:25:54 |   | relay: disconnected from client 2/ssl.weechat/x.x.x.x
```

**Random disconnect from my mobile phone**
```
17:35:16 |   | relay: new client on port 9001: 1/ssl.weechat/x.x.x.x  
17:36:15 | =!= | relay: reading data on socket for client 1/ssl.weechat/x.x.x.x: error -110 The TLS connection was non-properly terminated.
17:36:15 | =!= | relay: sending data to client 1/ssl.weechat/x.x.x.x: error -10 The specified session has been invalidated for some reason.
17:36:15 |   | relay: disconnected from client 1/ssl.weechat/x.x.x.x 
```

**Comment by flashcode** [comment]
Done.

In addition to this, I added a new option `relay.network.auth_timeout` to automatically disconnect clients that are not quickly authenticated (using the new status "waiting_auth"). See commit b947512c9a59e615f8dc9cf15428a18e135808f9.
