### ISSUE TITLE
Default /log command or alias for easy toggling buffer logging

### ISSUE THREAD

**Issue by koobs** [weechat/weechat#1359]
As a quality-of-life improvement, particularly for new users (but even for some seasoned users, like me) who have never delved deeply into weechat's powerful logging features via config, or having to go searching for the /logger command, I propose the following out of the box command, making it easy, fast and intuitive (guessable) to enable/disable logging for the buffer that is active.

Use cases for this feature are mostly privacy/security (information disclosure) oriented, such as preventing logs, which may be shipped off-local-machine to a third-party host, or made accessible in some way more publicly, to prevent certain sections of conversation from appearing there. One may be doing it as a courtesy to someone you're conversing with in /privmsg (which is where this feature request originated)

```
[log] /log
      /log enable
      /log disable

 enable: Enable logging on current buffer, with default loglevel
disable: Disable logging on current buffer (note: loglevel is reset)
```

Options/considerations:

 * Include `on` and `off` as supported aliases to `enable` and `disable` respectively. (please!)
 * To reduce duplication, make /log just default aliases to corresponding /logger commands. If the commands could/should diverse sufficiently down the track, they can be decoupled then.
 * Have `/log` (without arguments), display current setting/status in active buffer (only if allowed by weechat guidelines/policy)
 * Alternatively, have `log` (without arguments) toggle (switch) the status based on the current value
 * Include Log/Logger status appear somewhere useful like status bar, or allow its status to be used as a template variable as I assume other things are.

**Comment by weechatter** [comment]
in my opinion it can be easily done with an script. And for the log-level iten see: 
https://github.com/weechat/weechat/wiki/Miscellaneous#show-loglevel-for-current-buffer-item-name-loglevel

**Comment by koobs** [comment]
I understood in advance that it could be scripted as most things can, or added (mostly) in as an alias, but the main motivation for this is as an out-of-the-box quality of life improvement, specifically for !expert users

weechat is (thankfully) very flexible and very powerful, but a consequence of this is a huge wall of a learning that users face when they come on board. Even seasoned users like me who have used weechat for years can feel like they only know a fraction of what can be known.

I don't think power and convenience/usability are or should be mutually exclusive, but yes, it is 'harder' for a project to do and be both.

**Comment by weechatter** [comment]
script can be found here, with most important functions like enable/on/disable/off/toggle. log level for current buffer will be printed to the buffer.
https://weechat.org/scripts/pending/

**Comment by flashcode** [comment]
The script has been uploaded in the official scripts repository: https://weechat.org/scripts/source/log.py.html/ (available via `/script install log.py` from WeeChat).
