### ISSUE TITLE
TLS handshake issue

### ISSUE THREAD

**Issue by jcpro** [weechat/weechat#1361]
## Bug summary
In 2.5 when connecting to freenode now getting TLS handshake failure, error in cert.

## Steps to reproduce

1. Connect to Freenode as per normal
2. Notice error
3. Come to Github to report error

## Current behavior
Unable to connect to Freenode

## Expected behavior
Should be able to connect to Freenode with TLS.

## Suggested solutions
n/a

## Additional information
n/a

---

- WeeChat version: 2.5
- OS, distribution and version: Cygwin Windows 10 1903

**Comment by flashcode** [comment]
Hi,
Thanks for reporting the problem, could you please provide more information, like the error in the certificate, that WeeChat should display on the server buffer?
Thanks.

**Comment by jcpro** [comment]
```
09:38:26 freenode  -- |  - certificate[1] info:
                             │09:38:26 freenode  -- |    - subject `CN=weber.freenode.net', issuer `CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US', serial 0x03eaf9852ddda56790ad8e31f306c86c8bbe, RSA key 4096 bits, signed using RSA-SHA256, activated `2019-06-03
                             │                      | 05:04:38 UTC', expires `2019-09-01 05:04:38 UTC', pin-sha256="aB8n4a9u10zW+UfXS+6aqpJzVNPFIA6rOjwP1CDaRQU="
                             │09:38:26 freenode  -- |  - certificate[2] info:
                             │09:38:26 freenode  -- |    - subject `CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US', issuer `CN=DST Root CA X3,O=Digital Signature Trust Co.', serial 0x0a0141420000015385736a0b85eca708, RSA key 2048 bits, signed using RSA-SHA256,
                             │                      | activated `2016-03-17 16:40:46 UTC', expires `2021-03-17 16:40:46 UTC', pin-sha256="YLh1dUR9y6Kja30RrAn7JKnbQG/uEtLMkBgFF2Fuihg="
                             │09:38:26 freenode =!= | gnutls: peer's certificate is NOT trusted
                             │09:38:26 freenode =!= | gnutls: peer's certificate issuer is unknown
                             │09:38:26 freenode =!= | irc: TLS handshake failed
                             │09:38:26 freenode =!= | irc: error: Error in the certificate.
                             │09:38:26 freenode  -- | irc: reconnecting to server in 10 seconds
                             │09:38:36 freenode  -- | irc: reconnecting to server...

```
I connected to Freenode without any issues on 2.4 right before upgrading to 2.5

**Comment by jcpro** [comment]
I'm really unsure how to resolve this, the only thing I did was upgrade to Weechat 2.5, gnutls et al all same versions.  I authenticate with SASL, never had to specify a certificate.

**Comment by flashcode** [comment]
Can you please try again with WeeChat 2.4, to check if it's an issue with the version 2.5?

For me it's not related to changes in WeeChat, but changes on your system (check this option: `/set weechat.network.gnutls_ca_file`).

**Comment by jcpro** [comment]
I turned off SSL verification and that seems to work, not super happy about that workaround though.  As this is cygwin, I'll probably move over to an actual posix system at some point.
