### ISSUE TITLE
Right clicking output @item(input_text):button2 instead of showing menu

### ISSUE THREAD

**Issue by evilgawd** [weechat/weechat#1368]
## Bug summary

Setup is Fedora 30 running weechat 2.4.1 in roxterm 3.7.3 . 

## Steps to reproduce

1. Run weechat
2. Right click anywhere , it will either do : 
     1- nothing 
     2-output some of the following : @bar(status):button1@item(input_text):button2@item(input_text):button2@item(input_text):button2
     3- If you right click several times fast and you are lucky, you will see the menu appear 

## Expected behavior
Show the menu with a single right click

## Additional information

---

- WeeChat version: 
- OS, distribution and version:

**Comment by weechatter** [comment]
What menu? WeeChat don't have a menu!

**Comment by evilgawd** [comment]
Hrmm ok must be roxterm menu, I assumed /mouse enable , enabled this little menu . 
Please close

**Comment by evilgawd** [comment]
Hi sorry to re-open this , let me know if you want me to open a new bug for this. I just tried with gnome-terminal, each time i click the text bar it output what I was talking about ex: @bar(input):button2

I do want mouse enable and did not get this behavior before upgrading from Fedora 28 to 30  but since its affecting 2 different terminals , Im thinking it may be more related to weechat 

Any ideas ? 

Thanks

**Comment by flashcode** [comment]
If the mouse is enabled in WeeChat (key to toggle: `alt-m`), you can bypass the mouse with some keyboard modifier, see the FAQ: https://weechat.org/files/doc/devel/weechat_faq.en.html#mouse_select_paste

If the mouse is not enabled in WeeChat, there should be no problem, and then it could be an issue with your terminal.

**Comment by evilgawd** [comment]
When I disable the mouse , it stop outputing the @bar output , but I prefer to have the mouse on ,so its not a good solution. 

Also note, it has the same behavior with both ROXterm and gnome-terminal

**Comment by bar** [comment]
@evilgawd actually, please stop using my handle :) thanks!

**Comment by weechatter** [comment]
@bar, "@bar" is an output from the irc client weechat. so, he and others can not stop using it, because its part of the software. bad luck for you :-D

**Comment by bar** [comment]
@weechatter that's fine, I don't get notified by weechat but by github comments like these :)

**Comment by weechatter** [comment]
i know, but nothing we can't do against it :-)

**Comment by trygveaa** [comment]
You should code tags, then he won't be notified, like this: `@bar`.

**Comment by bar** [comment]
^^ exactly

**Comment by evilgawd** [comment]
That is all great but doesn't help me with my issue

**Comment by weechatter** [comment]
@evilgawd:
`/key unbindctxt mouse @bar(input):button2`
