### ISSUE TITLE
Can I ignore people based on their usernames or hostnames (not nickname)?

### ISSUE THREAD

**Issue by Al-Caveman** [weechat/weechat#1373]
## Question

Can I `/ignore add nickname[!~username][@hostname]`?  Or am I only limited to `/ignore add nickname[@hostname]`?

---

- WeeChat version: 19:45     WeeChat 2.5 [compiled on Jun 11 2019 10:01:45]
- OS, distribution and version: Linux 5.1.15-arch1-1-ARCH #1 SMP PREEMPT Tue Jun 25 04:49:39 UTC 2019 x86_64 GNU/Linux

**Comment by flashcode** [comment]
Hi,
Yes you can, there are some examples in `/help ignore`. You could also use a regex for the ignore.
If you still have problem, please show your ignore value, the result, and the expected result.

**Comment by Al-Caveman** [comment]
Thanks.  However, still unclear to me how to specify the username.  I read that `/help ignore` before asking here, and all it says is `nickname@hostname`.  I see no syntax specification of how to plug the username there.  E.g. `nickname!~username@hostname`.

I tried all these but didn't work:

    /ignore add *!~username@*
    /ignore add *~username@*
    /ignore add username@*

Only this worked:

    /ignore add *username@*

But that which worked is ambigious, and also ignores:

* Other usernames, such as `ANOTHERusername`.
* Nicknames, such as `NICKNAMEENDSBYusername`

Leading to ignore some innocents:

    NICKNAMEENDSBYusername!~dude@domain.com.
    poorNick!~ANOTHERusername@domain.com.
    NICKNAMEENDSBYusername!~ANOTHERusername@domain.com.

**Comment by Al-Caveman** [comment]
Worked with:

    /ignore add *!username@*

Didn't know that the separator is `!`  :-p.   `/whois nickname` shows the username like `(~username@domain)`, which confused me.

**Comment by flashcode** [comment]
For me the ignore feature is working as expected, I tested, no problems.
I added some tests on IRC ignore functions in commit 82a92bd4e9bc2330b9c25cc1a54be658bff1312e.
