### ISSUE TITLE
my nick changed to ":mynick" in 2.5

### ISSUE THREAD

**Issue by juanfra684** [weechat/weechat#1376]
## Question
I don't know if this is a bug, so I'm opening this report as question.

I'm using weechat to connect to an irc proxy which connects to a different protocol. I've been using the same config for years with no problems. Recently, I updated weechat to 2.5 and now my nickname in that network is `:mynick` instead of `mynick`. I've checked the logs saved by the server and the nick prefixed with the colon is there too, so the problem is not local.

I've seen also to another user with the same problem and it started the same day which he was testing weechat 2.5. I've read the 2.5 changelog and I can't find any reference to this change or a new option related to it.

Any idea?.

---

- WeeChat version:  2.5 (2.4 worked fine)
- OS, distribution and version: OpenBSD and Linux

**Comment by danieljakots** [comment]
Isn't it because of https://github.com/weechat/weechat/commit/77a9322bbfbf9e3705adf9a2208675ca39f5ae0e cc @phy1729 ?

**Comment by phy1729** [comment]
Seems likely, but any software that doesn't strip the colon is in violation of the [RFC](https://tools.ietf.org/html/rfc2812#section-2.3.1) so the bug lies with the other software.

**Comment by flashcode** [comment]
Yes it seems related to this commit.

I think then we could be smarter when sending the NICK message: add the ":" only if a ":" is actually present in the nickname, and use old behavior for all other cases, so this shouldn't break with non-compatible servers.
