### ISSUE TITLE
Do you officially support the Matrix protocol?

### ISSUE THREAD

**Issue by Mikaela** [weechat/weechat#1386]
## Question

Do you officially support the [Matrix protocol](https://matrix.org/)? I am under impression that WeeChat is purely a IRC client, until you add a Matrix *plugin* to the main codebase which I think would put Matrix in an equal position with IRC.

I am aware that there is a *script* or two for adding Matrix support into WeeChat, but I am unable to find them [from the official scripts repository](https://github.com/weechat/scripts) and I would personally not consider them as official support even if they were listed in that repository, as they still wouldn't be a part of WeeChat regardless of the `/script` command.

I am asking this, because during the time I have been using the [Matrix protocol](https://matrix.org/) I have at times seen comparsions including "WeeChat" (that I find unfair due to WeeChat not attempting to support it as far as I can see) and requests to recommend WeeChat as a more private Matrix client than [Riot](https://riot.im/), most recently in https://github.com/privacytoolsIO/privacytools.io/pull/1048#issuecomment-514814929 and I am not open to accepting these proposals without your approval.

---

- WeeChat version: N/A
- OS, distribution and version: N/A

**Comment by flashcode** [comment]
Matrix is not natively supported, neither with an "official" script.

There are only external scripts you mentioned, but they were not submitted for the "official scripts repository", so they're not available via the `/script` command.
I know some people use them, so I think they work fine though (not tested personally).

**Comment by Mikaela** [comment]
Thank you for the quick answer, I am going to take it that Matrix protocol is not officially supported.

Native support would mean a (C) plugin, wouldn't it?

**Comment by poljar** [comment]
Please don't recommend the Matrix protocol scrips for Weechat, the older one written in [lua](https://github.com/torhve/weechat-matrix-protocol-script) does not support encryption.

The newer [python](https://github.com/poljar/weechat-matrix) based one does support encryption but the support is not fully done and the script never got a release. While I'm aware that a bunch of people successfully use the script It's not really ready for non-adventurous people.

The python based script is not submitted to the scrips repo for two reasons:

-  There was no release
- The scrip consists of multiple files while the repo requires scripts to be a single file

The long term goal for the python script is to be ported to rust turning it into a Weechat plugin and maybe getting it upstreamed if @flashcode is interested in such a thing. But this goal is still quite far away.

**Comment by Mikaela** [comment]
@poljar Is your above comment from 2019 still the case? Do you have any plans for a Libera.Chat channel where people could ask for support with the script instead of coming to #weechat which cannot help with it?

**Comment by poljar** [comment]
The Rust rewrite is well and alive, albeit a bit slow due to IRL reasons, over at https://github.com/poljar/weechat-matrix-rs.

It is usable but it doesn't yet have feature parity with the Python script, if people want to test stuff that's fine but I can't claim that the plugin is production ready or done.

As for Libera.Chat, sure we could bridge the Matrix room to Libera once bridging is available.

**Comment by Mikaela** [comment]
Thanks :)

Bridging is available either through the manage integrations menu or contacting support@matrix.org
