### ISSUE TITLE
PRIVMSG splitting incorrectly estimates size of prefix

### ISSUE THREAD

**Issue by fndax** [weechat/weechat#1387]
Weechat's estimate of the prefix (:nick!user@host ) size for deciding when to split privmsgs has a few issues:

- Doesn't account for the username/ident field at all. No, it's not included in the "host" line (unlike the way other parts of weechat source use the term "host"), because the 63 bytes allowance there comes from RFC2812, where "host" just means the actual hostname or IP.

- Doesn't make use of the ISUPPORT parameters HOSTLEN or USERLEN (but does seem to support NICKLEN)

- Could probably parse numeric 396 and IRCv3 CHGHOST to determine the actual prefix (which can change over time) and use its length, instead of using a theoretical maximum. This should probably be split out into a feature request; I expect it'd require more work than the first two bullets and I'm not convinced it's worth doing.

Additionally, the overall estimate of message length doesn't account for identify-msg or statusmsg (specifically freenode cmode +z statusmsgs; normal ones are accounted for because the @ or + is in the channel name when sending the privmsg) usage on the recipient side so should probably add a couple more bytes of overhead for things like that.

There doesn't seem to be any standardized default USERLEN to fall back on if it's not specified in ISUPPORT. freenode allows up to 10 bytes in that field (plus 1 byte for the @ symbol), and a quick review of others suggests that may be a sane guess.

https://github.com/weechat/weechat/blob/master/src/plugins/irc/irc-message.c#L1089

https://tools.ietf.org/html/rfc2812#section-2.3.1

**Comment by flashcode** [comment]
Done, with the following remarks:

- now USERLEN and HOSTLEN are used if received from the server in 005 (default values when a message is split are 10 for USERLEN and 63 for HOSTLEN)
- the IRCv3 CHGHOST has not been implemented (if really needed, please open a separate feature request)
- the `@` or `+` that could be added to the channel name has not been implemented. When the message is split (so on sender side), these prefix are missing and added by the server for the receiver? Or they are already present on the sender side? (in which case the current split is already OK).

**Comment by fndax** [comment]
> When the message is split (so on sender side), these prefix are missing and added by the server for the receiver?

`@` and `+` are present on the sender side for normal STATUSMSG and not present (added by the server) for freenode cmode +z use of STATUSMSG ( bottom part of https://freenode.net/news/seven-118 ).

identify-msg's + and - are not present on the client and are added by the server in all cases.

I was mainly using them as examples of why we might want a couple of bytes of "padding" for weird things ircds do by themselves.

**Comment by oakkitten** [comment]
I mentioned this several times already, but anyways

there's a solution to all of this that, while not ideal, is so simple and works so well that it could be at least optional—send a message to oneself, add a byte if it doesn't start with `:+` and you can precisely calculate how much you can send.
