### ISSUE TITLE
Python scripts cannot use hooks that may return invalid utf-8 with python 3

### ISSUE THREAD

**Issue by tribut** [weechat/weechat#1389]
## Bug summary

When a hook sends non-utf8 data to python, a UnicodeDecodeError is immediately triggered. There is no way for the script to handle this.

## Steps to reproduce

1. Load [test.py](https://gist.github.com/tribut/b761ae84b8448935fa23657ba3ec4a12)
2. Send a non-utf8 message from another client
3. Observe error

## Current behavior

Any non-utf8 data cannot be processed by a python(3) script.

## Expected behavior

Non-utf8 data is passed as `bytes`.

---

- WeeChat version: v2.5-89-g210e86489
- OS, distribution and version: Ubuntu disco

**Comment by sim642** [comment]
There's a related issue: https://github.com/weechat/weechat/issues/1220. While it is regarding a different signal (which got fixed to call with valid UTF-8), it also contains an extensive overview of the situation, including the `bytes` suggestion.
