### ISSUE TITLE
how to get list of hostnames of nicknames in a channel/server?

### ISSUE THREAD

**Issue by Al-Caveman** [weechat/weechat#1391]
## Question

how to get list of hostnames of nicknames in a channel/server?  the scenario is:  i'm in a channel with some nicknames in, and i want to code a weechat script in python that analyzes their hostnames.

ideally, i want a list in this format `nick!~user@host`, but i'm OK if i only get the `host` part.

---

- WeeChat version: WeeChat 2.5 [compiled on Jun  6 2019 20:12:10]
- OS, distribution and version: ubuntu xenial lts

**Comment by weechatter** [comment]
use weechat.infolist_get()

please read the API docs before opening issues. I'll close this
