### ISSUE TITLE
${current_buffer} in buflist.look.display_conditions has no effect

### ISSUE THREAD

**Issue by oakkitten** [weechat/weechat#1393]
## Bug summary

`${current_buffer}` in `buflist.look.display_conditions` has no effect even though the documentation [says](https://weechat.org/files/doc/stable/weechat_user.en.html#buflist_commands) it should.

## Steps to reproduce

1. run `/set buflist.look.display_conditions "${current_buffer}"`

## Current behavior

Nothing shows in buflist

## Expected behavior

Current buffer shows

## Suggested solutions

Fix this

## Additional information

I think these bug templates are kinda dumb

---

- WeeChat version: a906afc3d7281683799f8b32ca5d5bc06df75f8f
- OS, distribution and version: Raspbian GNU/Linux 9 (stretch) Linux 4.19.42-v7+ armv7l GNU/Linux

**Comment by flashcode** [comment]
In fact, the doc is wrong. The conditions are evaluated without extra variables, because these variables are defined after, only if conditions are met, for speed reasons (computing all variables has a cost, and if conditions is false, it's better to not set them).
So I'll fix the `/help buflist`.

**Comment by flashcode** [comment]
Reopening the issue, I'll finally use all the variables in the option `buflist.look.display_conditions`. This will just be a bit slower in case a buffer is not defined, but it should rarely happen.
