### ISSUE TITLE
segfault when starting weechat

### ISSUE THREAD

**Issue by isgy** [weechat/weechat#1401]
## Bug summary
whenever I try to start weechat, it crashes the first 3 times and then starts normally..
## Steps to reproduce

1. type weechat in the console
2. type weechat in the console
3. type weechat in the console

https://asciinema.org/a/MxltwcxHadM1WzxgxBIhmxyno

---

- WeeChat version:  2.5
- OS, distribution and version:  archlinux 5.2.9

**Comment by isgy** [comment]
fixed it by freeing up disk space, but still, I'm not sure this is expected behavior

**Comment by weechatter** [comment]
for me it looks more like a problem with an "perl" script. You run for example the outdated buffers.pl script. But without core file, its not possible to trace down...
