### ISSUE TITLE
Cannot compile Weechat with Ruby 1.8

### ISSUE THREAD

**Issue by moggers87** [weechat/weechat#1404]
## Bug summary

Cannot compile Weechat 2.6 with Ruby 1.8

## Steps to reproduce

1. Have Ruby 1.8 installed
2. Checkout v2.6 tag in git
3. Compile Weechat 2.6 from source

## Current behavior

Compiling fails with the following errors:
```
[ 68%] Building C object src/plugins/ruby/CMakeFiles/ruby.dir/weechat-ruby-api.c.o
weechat/src/plugins/ruby/weechat-ruby-api.c: In function ‘weechat_ruby_api_ngettext’:
weechat/src/plugins/ruby/weechat-ruby-api.c:287: error: ‘SIGNED_VALUE’ undeclared (first use in this function)
weechat/src/plugins/ruby/weechat-ruby-api.c:287: error: (Each undeclared identifier is reported only once
weechat/src/plugins/ruby/weechat-ruby-api.c:287: error: for each function it appears in.)
weechat/src/plugins/ruby/weechat-ruby-api.c:287: error: ‘RUBY_FIXNUM_FLAG’ undeclared (first use in this function)
weechat/src/plugins/ruby/weechat-ruby-api.c:287: error: implicit declaration of function ‘RB_TYPE_P’
…
```
These errors repeat multiple times

## Expected behavior

Weechat compiles with Ruby as advertised

## Suggested solutions

I started on a fix [here](https://github.com/moggers87/weechat/commit/ada835d78ea4aad66ae898ce57a3ba55ace153de), which allows Weechat to compile. However, it does not solve the issue completely as I'm unable to load any Ruby scripts.

Alternatively, increasing the required version of Ruby to something that compiles without these changes would also fix this issue (I don't actually use any Ruby scripts and didn't know that I could do `-DENABLE_RUBY=off` to solve my problem :laughing: )

## Additional information

- Ruby version: ruby 1.8.7 (2013-06-27 patchlevel 374) [i386-linux]

---

- WeeChat version: WeeChat 2.6
- OS, distribution and version: CentOS release 6.10 (Final)

**Comment by flashcode** [comment]
With the latest fix in ruby plugin (commit 156d855787475deab27833219a188a4accf42558), WeeChat ruby plugins now requires Ruby ≥ 1.9.1.
Since Ruby 1.8 is ~16 years old, I think it's waste of time to try to be compatible with such an old version (which is not maintained any more since a long time).
So I'll update the user's guide to mention the min Ruby version.
