### ISSUE TITLE
[IRCv3] Support account-tag

### ISSUE THREAD

**Issue by lord-re** [weechat/weechat#1422]
## Feature description
Add support for account-tag

It's already supported by those ircd : Charybdis, Inspircd, Oragono and Unrealircd.
https://ircv3.net/specs/extensions/account-tag-3.2

**Comment by sim642** [comment]
The big question is: what exactly should this support be? The spec doesn't require anything from the client so technically it's already supported.

You can already request account-tag on a compatible ircd and WeeChat will receive and allow triggers/scripts access the IRCv3 message tags.

I suppose one use would be updating `account` field of `t_irc_nick` struct:
https://github.com/weechat/weechat/blob/3a03184d7a5b8fda4890423b8d86470c5ea16899/src/plugins/irc/irc-nick.h#L41
AFAIK that's just something kept internally and not used by any user-facing functionality. Scripts can access that so the few ones that actually do (I didn't check) would benefit from the up-to-date value.

**Comment by ksu-0** [comment]
User's guide incorrectly claims `account-tag` to be requested by default.

> The big question is: what exactly should this support be? The spec doesn't require anything from the client so technically it's already supported.

One use of it was enabled by #1680.

**Comment by flashcode** [comment]
Available since WeeChat 3.5 (#1680).
