### ISSUE TITLE
join 0 open buffer before join

### ISSUE THREAD

**Issue by dylnmc** [weechat/weechat#1429]
## Bug summary

`/join 0` with option `irc.look.buffer_open_before_join` results in user joining channel `0`. Some servers adhere to [the rfc](https://tools.ietf.org/html/rfc2812#section-3.2.1), but apparently some do not. Nonetheless, `0` is never a valid channel. Maybe some sort of filtering can be implemented for `buffer_open_before_join`. It's not a big deal.

I did `/join 0` and I think I got into a weird state, though. So, maybe that can be tested. I tried to join `irc://chat.freenode.net/#weechat` after running `/join 0` on my freenode server, and then when I tried to send a message, it said "unable to send message" with `404` error. I don't know what that was about, but I couldn't reproduce it easily.

## Steps to reproduce

1. `/connect some-server`
2. `/set irc.look.buffer_open_before_join on`
3. `/join 0`

## Current behavior

joins channel `0`

## Expected behavior

don't

## Suggested solutions

filter some(?) invalid channels

---

- WeeChat version: 2.6
- OS: arch linux

**Comment by flashcode** [comment]
Fixed, see the commit message: some invalid channel names can still be opened by WeeChat, but that's the normal behavior: WeeChat opens the buffer anyway, and the server should reply an error if the name is not valid.
