### ISSUE TITLE
Reject relay init commands with totp when totp is not enabled

### ISSUE THREAD

**Issue by AStove** [weechat/weechat#1435]
## Feature description
Reject relay init commands that have a totp argument when no totp is required by weechat. https://weechat.org/files/doc/stable/weechat_relay_protocol.en.html#command_init

If you don't reject this, the user gets a false sense of security. And the relay client has no way of knowing if totp is required or not. 
Also it would probably be even better to first do an init command without totp, and then having weechat send back a request for a totp, but this would be breaking.

**Comment by flashcode** [comment]
You're right, I'll implement that.
And I'll do the same for the password: if a client sends a password but the password is empty in WeeChat (really not recommended!), it will be rejected.
