### ISSUE TITLE
 weechat-perl : Depends: libperl5.24 (>= 5.24.0) but it is not installable

### ISSUE THREAD

**Issue by yutayu** [weechat/weechat#1437]
## Bug summary
I cannot install weechat raspbian buster from repo.

## Steps to reproduce

1. Install weechat According to this,https://weechat.org/download/debian/
2. 
3. 

## Current behavior
pi@raspberrypi:~ $ sudo apt-get install weechat-curses weechat-plugins weechat-python weechat-perl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 weechat-perl : Depends: libperl5.24 (>= 5.24.0) but it is not installable
E: Unable to correct problems, you have held broken packages.

## Additional information

---

- WeeChat version: 
newest.2.7.1
- OS, distribution and version: 
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux

**Comment by flashcode** [comment]
@yutayu: what's the content of your sources.list (with weechat.org URLs) and the output of `cat /etc/debian_version` ?

**Comment by yutayu** [comment]
deb https://weechat.org/raspbian buster main

pi@raspberrypi:/etc/apt/sources.list.d $ cat /etc/debian_version
10.2

**Comment by yutayu** [comment]
apt show weechat
Package: weechat
Version: 2.3-1

This is from raspbian  repo,it is enought to use :)

**Comment by flashcode** [comment]
@weechatter: any idea about this dependency problem with libperl5.24 on Raspbian Buster?

**Comment by weechatter** [comment]
I can not reproduce. i can easily install weechat and weechat-devel on my raspbian-buster (only original repositories):
Linux raspberrypi 4.19.58-v7l+ #1245 SMP Fri Jul 12 17:31:45 BST 2019 armv7l GNU/Linux

apt policy libperl5.24
does not exists under buster!

therefore i would say, install latest weechat version and don't try to install older weechat versions. i don't know where this weechat 2.3-1 come from. for me its:
Package: weechat
Version: 2.7-1

**Comment by yutayu** [comment]
your pi's kernel is old and 2.3-1 is from original repo.

**Comment by flashcode** [comment]
It seems the dependency for Raspbian Buster should be `libperl5.28` instead of `libperl5.24`, so something is wrong in the package.

**Comment by flashcode** [comment]
Packages are being rebuilt for Raspbian Buster.

**Comment by flashcode** [comment]
@yutayu: please try again (`apt-get update` then install of packages).
Now dependencies should be OK.

**Comment by yutayu** [comment]
pi@raspberrypi:~ $ sudo apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  weechat-core weechat-curses weechat-perl weechat-plugins weechat-python weechat-ruby
6 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 1,670 kB of archives.
After this operation, 64.5 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 https://weechat.org/raspbian buster/main armhf weechat-ruby armhf 2.7-1 [107 kB]
Get:2 https://weechat.org/raspbian buster/main armhf weechat-python armhf 2.7-1 [104 kB]
Get:3 https://weechat.org/raspbian buster/main armhf weechat-plugins armhf 2.7-1 [193 kB]                        
Get:4 https://weechat.org/raspbian buster/main armhf weechat-perl armhf 2.7-1 [124 kB]                           
Get:5 https://weechat.org/raspbian buster/main armhf weechat-curses armhf 2.7-1 [367 kB]                         
Get:6 https://weechat.org/raspbian buster/main armhf weechat-core armhf 2.7-1 [776 kB]                           
Fetched 1,670 kB in 18s (91.2 kB/s)                                                                              
Reading changelogs... Done
(Reading database ... 116485 files and directories currently installed.)
Preparing to unpack .../0-weechat-ruby_2.7-1_armhf.deb ...
Unpacking weechat-ruby (2.7-1) over (2.3-1) ...
Preparing to unpack .../1-weechat-python_2.7-1_armhf.deb ...
Unpacking weechat-python (2.7-1) over (2.3-1) ...
Preparing to unpack .../2-weechat-plugins_2.7-1_armhf.deb ...
Unpacking weechat-plugins (2.7-1) over (2.3-1) ...
Preparing to unpack .../3-weechat-perl_2.7-1_armhf.deb ...
Unpacking weechat-perl (2.7-1) over (2.3-1) ...
Preparing to unpack .../4-weechat-curses_2.7-1_armhf.deb ...
Unpacking weechat-curses (2.7-1) over (2.3-1) ...
Preparing to unpack .../5-weechat-core_2.7-1_armhf.deb ...
Unpacking weechat-core (2.7-1) over (2.3-1) ...
Setting up weechat-core (2.7-1) ...
Setting up weechat-curses (2.7-1) ...
Setting up weechat-perl (2.7-1) ...
Setting up weechat-ruby (2.7-1) ...
Setting up weechat-python (2.7-1) ...
Setting up weechat-plugins (2.7-1) ...
Processing triggers for man-db (2.8.5-2) ...

update has done and no error occurs.
