### ISSUE TITLE
Hook_process returns garbage when headless weechat is run with stdout redirected

### ISSUE THREAD

**Issue by Lucius-Q-User** [weechat/weechat#1441]
## Bug summary
If weechat-headless is run with stdout/stderr redirected to /dev/null, first invocation of hook_process gets the weechat startup banner ("WeeChat is running in headless mode (Ctrl-C to quit).") prepended to the command output.

## Steps to reproduce

1.  Run weechat-headless >/dev/zero 2>/dev/zero
2. Run any plugin that uses hook_process. 
3. Observe the output.

## Current behavior
The weechat startup banner is prepended to command output.

## Expected behavior
The weechat startup banner should not be prepended.

## Suggested solutions

Remove the startup banner entirely.

- WeeChat version: 2.7
- OS, distribution and version: Linux, gentoo, latest

**Comment by flashcode** [comment]
Hi,
I tried to reproduce the problem (with `/exec` or a script), without success.
Can you tell me which script causes this problem?
Or could you please give me an example of short script to reproduce the problem?

**Comment by Lucius-Q-User** [comment]
I was using the wee-slack (https://github.com/wee-slack/wee-slack) script to reproduce this error, if run in a headless environment, the script failed to connect due to response being garbled, while running it without redirections makes it work properly.
Make sure you completely restart weechat before attempting to reproduce


I can try writing a minimal reproducer if it is needed.

**Comment by flashcode** [comment]
Yes, a little script to reproduce is welcome.

I wonder how this can happen, since hook_process forks the current weechat process, so the message which is displayed at startup should never be part of the process output.
The only way it could happen is that hook_process run weechat-headless command, which would be weird.

**Comment by Lucius-Q-User** [comment]
```
import weechat
def unload_fn(*args, **kwargs):
    pass


    

weechat.register("SCRIPT_NAME", "SCRIPT_AUTHOR", "SCRIPT_VERSION", "SCRIPT_LICENSE", "SCRIPT_DESC", "unload_fn", "")
weechat.hook_process_hashtable("url:http://detectportal.firefox.com/success.txt", {}, 600, "callback", "")

def callback(data, command, return_code, out, err):
    open("out.txt", "w").write(repr(out))
```
1. Make sure you have no other plugins or scripts.
2. Run weechat as `weechat-headless 2>/dev/zero /dev/zero`
3. Load the script above.
4. Observe the out.txt file having the weechat banner prepended

**Comment by flashcode** [comment]
I'm still not able to reproduce the problem with your script.

I did that:

1. Run weechat, setup a weechat relay.
2. Run weechat-headless (your command).
3. Connect to weechat using glowing bear.
4. Load your test script.

The result is a file out.txt with this content:

    'success\n'

**Comment by Lucius-Q-User** [comment]
I have recorded the exact steps i am using to reproduce the issue https://www.youtube.com/watch?v=B1d1JUBeI14&feature=youtu.be

**Comment by flashcode** [comment]
Is your WeeChat compiled with Python 2 or 3? (which version exactly would help too)
You can check with `/python version`.

**Comment by Lucius-Q-User** [comment]
python: 3.7.6

**Comment by flashcode** [comment]
I'm still not able to reproduce, and I'm out of ideas about what to test...

**Comment by Lucius-Q-User** [comment]
I can try tar-ing up the whole system and sending it to you if that is helpful

**Comment by flashcode** [comment]
Weird, same OS/version and I can reproduce the bug on another machine.
I'm fixing.

**Comment by flashcode** [comment]
Please confirm me if it's OK for you, when you can compile development version.

**Comment by Lucius-Q-User** [comment]
I can confirm that the scripts are working now
