### ISSUE TITLE
publish official docker container

### ISSUE THREAD

**Issue by ssbarnea** [weechat/weechat#1446]
It would be extremely useful to publish a container and document its use as this became the standard multi-platform way to distribute apps. The biggest benefit is that users would not have bother to compile it locally and it would be very easy and fast to start or update.

**Comment by flashcode** [comment]
What do you mean by "container"?

**Comment by weechatter** [comment]
https://github.com/shymega/weechat-docker

**Comment by ssbarnea** [comment]
>  This repository has been archived by the owner. It is now read-only. 

I think that the banner on the repo explains my concerns. The idea is to have an official docker image that is updated by CI on each release/prerelease. Some do push a new image on each commit to master.

Without official part, you depend on a single person, which may and will get bored of maintaing it at some point. Also there is the security risk.

**Comment by flashcode** [comment]
Hi,

I'm closing this issue as I just added a new repository to build WeeChat container images: https://github.com/weechat/weechat-container.
