### ISSUE TITLE
Make --no-connect argument available to scripts

### ISSUE THREAD

**Issue by trygveaa** [weechat/weechat#1453]
## Feature description

As far as I can see, a script cannot know or check if weechat was started with `--no-connect`. This would be useful e.g. for the wee-slack script to know if it should connect to the slack servers or not.

**Comment by flashcode** [comment]
Done.

See the release notes for the proper way to check the new info `auto_connect` and stay compatible with old releases where this info didn't exist: https://weechat.org/files/releasenotes/ReleaseNotes-devel.html#v2.8_auto_connection_to_servers
