### ISSUE TITLE
Add scalable icon

### ISSUE THREAD

**Issue by sorairolake** [weechat/weechat#1454]
## Feature description
If a desktop environment support the SVG format, I think it is better to use this. Because, vector graphics does not degrade the quality even on HiDPI displays.

So, I suggest adding an icon in the SVG format to WeeChat.

**Comment by flashcode** [comment]
Hi,
Good idea by I don't have any scalable format for the icon, which I made with GIMP.
I only have larger sizes available here: https://weechat.org/files/logo/ (the max size is 437x437).
If someone feels like making a SVG logo which is the same as the current bitmap image, contribution is welcome :)

**Comment by sorairolake** [comment]
I see. I will create a scalable icon that is almost the same as PNG icons (make exactly the same quality is difficult).

**Comment by flashcode** [comment]
Done via #1456.
