### ISSUE TITLE
AUTHENTICATE does not properly split data

### ISSUE THREAD

**Issue by shuffle2** [weechat/weechat#1459]
## Bug summary
When sending data via `AUTHENTICATE`, weechat does not split the resulting base64 encoded data into 400byte chunks.

## Steps to reproduce

1. Enable SASL on some server config with very long sasl_password (try 'A' * 2000 or so)
2. Connect to server advertising SASL
3. Observe data received server-side is > 400bytes and missing trailing CRLF

## Suggested solutions
Implement the spec:
https://ircv3.net/specs/extensions/sasl-3.1.html
> The response is encoded in Base64 (RFC 4648), then split to 400-byte chunks, and each chunk is sent as a separate AUTHENTICATE command. Empty (zero-length) responses are sent as AUTHENTICATE +. If the last chunk was exactly 400 bytes long, it must also be followed by AUTHENTICATE + to signal end of response.

Not familiar with weechat codebase, but looks like `answer` should be split into multiple messages here: https://github.com/weechat/weechat/blob/f33cfc89a06d01883aa4067868ecdcc8b095273d/src/plugins/irc/irc-protocol.c#L293

## Additional information
I've run into this while trying to implement a SASL scheme which sends an oauth token to the server via the sasl_password field (using PLAIN mechanism). I was hoping to find a way to staple oauth onto irc without requiring client changes (just server-side modifications to treat the "password" as a token).

twitch.tv apparently does this via `PASS` instead of SASL, which I haven't tried yet, but I think will have other drawbacks. The token I want to use is a jwt of ~2000bytes.

**edit** yes, hexchat silently truncates the string when passed in this way, so it won't be a portable solution. twitch's token is only ~30 bytes.
**edit2** hexchat also truncates in the same manner if the password is sent inside `AUTHENTICATE`, so it seems neither way is usable :/

---

- WeeChat version: 2.6
- OS, distribution and version: ubuntu 19.10

**Comment by flashcode** [comment]
I'll add a split on 400 bytes and send an extra empty `AUTHENTICATE +` if the last message is exactly 400 bytes (so if the response length is a multiple of 400 bytes).
The split of message is performed in irc-message.c.

**Comment by flashcode** [comment]
Done.
Please let me know if you still have problems with this fix.
