### ISSUE TITLE
spec file for CentOS-8

### ISSUE THREAD

**Issue by scottro11** [weechat/weechat#1464]
## Feature description
Currently the spec file included in git is for SuSE and won't build on CentOS-8 saying it can't find man or doc, even with all dependencies installed.  There is a request for a CentOS/RHEL-8 package but it seems to be being ignored. https://bugzilla.redhat.com/show_bug.cgi?id=1753203
The specfile included there does build, but lacks python support making it impossible to use the wee_slack python plugin. I'm not sure if this a reasonable request or should just be made to the EPEL people, but a spec file that would build on CentOS-8 would be welcomed. (I've tried rebuilding srpms for various Fedora versions as well as CentOS-7.x but had no luck)

**Comment by flashcode** [comment]
Hi,

I'm not sure we should have files to build WeeChat on many distros, this is more a job of the distros themselves.
I know there's already a .spec file, but this is for historical reasons, and it was not removed.
I try to maintain only a few distros builds in WeeChat (mainly Debian and Cygwin), I think for the other distros they can maintain that out of this repository, or it will become bloated (and a lot of time is needed to maintain these files up-to-date).
