### ISSUE TITLE
Ram usage grows speedily due to rapid repeated syscalls.

### ISSUE THREAD

**Issue by sig-abrt** [weechat/weechat#1469]
## Bug summary

Whilst using the buflist_hotlist as defined at https://gist.github.com/pascalpoitras/8406501/7b81f9fbe9326aafaf4931378751a223f4d89c44 on FreeBSD 12.1 with a manually built weechat 2.8 (using python 3.8) and locale settings as below:

```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_ALL=
```

weechat would repeatedly open `/usr/share/locale/en_US.UTF-8/{LC_COLLATE,LC_CTYPE}` then fstat, then mmap, then close. The result of this would be that RAM utilization skyrocketed, in minutes.

## Steps to reproduce

1. Duplicate the config linked above.
2. Set locale settings as mentioned above.
3. Open weechat and connect to multiple networks.
3.  Use top or htop or so forth to watch ram utilization.

## Current behavior

Repeated rapid syscalls involving the files cause ram utilization to skyrocket.

## Expected behavior

I believe that those 2 files need only be opened once most likely. It is my assumption that doing so will mean that the ram utilization will not skyrocket and will hover within a normative range.

## Suggested solutions

Still looking through the code but being unfamiliar with the code base I can only explain at a high level for now to only open locale related files once during the program's initialization probably.

## Additional information

I was unable to get this to duplicate on linux. valgrind does not work on FreeBSD currently. Using `truss` I was able to attach and watch syscalls on the PID of a running weechat with skyrocketing memory utilization. If necessary I can provide a `truss` output.  The four repeated syscalls were absent whilst the buflist_hotlist was hidden but present when it was shown are. The log generated by `truss` was 2.4M in size.

Running weechat with the command like `LC_COLLATE="C.UTF-8" LC_CTYPE="C.UTF-8" $weechat $args` does not exhibit the behavior defined as a bug and is in fact how I'm running weechat currently as a workaround.

---

- WeeChat version: 2.8
- OS, distribution and version: FreeBSD 12.1-RELEASE-p3 

I use my own pkg repository so the packages won't necessarily align with FreeBSD's main pkg repositories. The biggest difference between my own repositories and FreeBSD's is I used python 3.8 instead of a lower version.

**Comment by sim642** [comment]
I don't think WeeChat is opening the locale files directly itself. I suspect some C library function is internally doing that. It might help to use gdb to locate from which function these calls leading to locale file opening are taking place. It being a bug in FreeBSD's libc or something might explain why it doesn't happen on linux.

**Comment by sig-abrt** [comment]
Backtrace where mmap is hit over and over due to a setlocale call.

[weechat.bt.txt](https://github.com/weechat/weechat/files/4443886/weechat.bt.txt)

**Comment by de-vri-es** [comment]
We traced it to probably this: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=243195 .  In summary, FreeBSD setlocale() leaks the memory. A fix has been committed but not yet released.

Regardless, it might still make sense to try to avoid `setlocale()` for performance reasons.

**Comment by flashcode** [comment]
I'm rewriting the function `calc_format_result` to remove the calls to `setlocale` and to not use snprintf to format directly the double value.
