### ISSUE TITLE
weechat-headless should log to stdout rather than weechat.log

### ISSUE THREAD

**Issue by tomfitzhenry** [weechat/weechat#1475]
I'm running a weechat-headless service on a server. Currently, logs are written to `$WEECHAT_HOME/weechat.log`. This works, but is difficult for two reasons:

1. weechat-headless requires special config to hook into log management (rotation/indexing/...). If weechat-headless logged to stdout, it'd easily integrate with process supervision logging tools (e.g. systemd, journald) that expect services to write to stdout.
2. For security and config management reasons, I mount config (such as `$WEECHAT_HOME`) as read-only, but since `weechat.log` is written to `$WEECHAT_HOME/weechat.log`, I cannot mount this as read-only. (I already have `logger.file.path` set to `/var/log/weechat`, for the channel logs).

**Comment by flashcode** [comment]
Done, with a new command line option in weechat-headless binary: `--stdout`.
So the default behavior is unchanged: write log messages in log file.
