### ISSUE TITLE
Two completion templates can't start with the same first argument

### ISSUE THREAD

**Issue by trygveaa** [weechat/weechat#1481]
## Bug summary

I'm trying to write a completion template which has an optional argument, but can't figure out how. Since I haven't found any way to set an argument as optional, I'm trying to use `||` to separate one template which has the argument and one which does not. However, when doing this, the second template doesn't work.

## Steps to reproduce

1. Call `hook_command` with `completion` set to `teams||reply -alsochannel test||reply test`.
2. Write `/command_name reply -` in the input field
3. Press tab

## Current behavior

Nothing happens.

## Expected behavior

`-alsochannel` should be completed.

## Additional information

This is for completions in [wee-slack](https://github.com/wee-slack/wee-slack). `reply` is a subcommand of `/slack` to reply to a thread by thread id. So the command completes thread ids, but also allows the option `-alsochannel`. In the example here I removed most of the other subcommands and replaced thread ids with `test` for simplicity.

If I use `teams||reply -alsochannel|%(threads) %(threads)`, it works, but this allows you to autocomplete two thread ids when not using `-alsochannel`, which is not supported in the command, so I don't want to use this.

Is there another way to specify optional arguments, that I have not found?

---

- WeeChat version: 2.8
- OS, distribution and version: Arch Linux

**Comment by flashcode** [comment]
This is not really a bug but was designed like that.

The first argument of a command should be considered as a sub-command and then you can not have two times the same word, otherwise it would be hard for WeeChat to choose the completion template to use.

I'm not even sure there's an easy way to implement that.

**Comment by trygveaa** [comment]
So is there another way to specify optional arguments? If I can specify the correct arguments for `reply` without using multiple templates, I won't need multiple templates with the same first argument.

**Comment by flashcode** [comment]
No, there's currently no way in completion templates to specify optional arguments.

But you could define your own completion and look at completion arguments, and customize the completion according to what the user typed. For example the completion of option values do that, see here: https://github.com/weechat/weechat/blob/master/src/core/wee-completion.c#L1053

**Comment by trygveaa** [comment]
Right, yeah, that should work, thanks.

Would be nice to have support for optional arguments though, so one doesn't have to implement custom logic for each command that needs it. Anyways, I'll close this issue.
