### ISSUE TITLE
Add a "completion" command in relay protocol

### ISSUE THREAD

**Issue by flashcode** [weechat/weechat#1484]
## Feature description

Purpose is to let clients use WeeChat completion mechanism to get a list of possible completions.

The client must send this info in the completion command:

1. the buffer (name or pointer)
2. the position of cursor in the string (we can complete anywhere, not only the end); if -1, the completion is made at the end
3. the input string

Examples:

- `(id) completion core.weechat 10 /help filt` (completion: `/help filter`)
- `(id) completion core.weechat -1 /help filt` (completion: `/help filter`)
- `(id) completion irc.freenode.#weechat 5 /quernick` (cursor is on `n`, completion: `/query nick`)

The response is a hdata with the following info:

- `position_replace` (integer): index of the first char to replace with possible words (starts to 0); the end char to replace is before the cursor position sent by the client
- `add_space` (char): 1 if a space must be added after completion, 0 otherwise
- `words` (array): list of words found for completion (strings)

This will make easier to implement completion in relay clients, like glowing-bear/glowing-bear#372.

**Comment by AStove** [comment]
In addtion to the 'add_space' (weechat.completion.nick_add_space) could you also send the nick completer character? weechat.completion.nick_completer? And then it would probably be nice to know if the comletion item is a nick or not so we know to add the nick completion character etc.

**Comment by flashcode** [comment]
I'll make tests, but the nick completer should already be part of the completion words.

If needed I can add the completion "context", which can be: null (unknown), command, command_arg or auto.
