### ISSUE TITLE
time_for_each_line set to 1 for buffers without timestamps

### ISSUE THREAD

**Issue by AStove** [weechat/weechat#1485]
## Bug summary
It seems that for buffers without timestamps such as 'relay.relay.list' and 'fset.fset' still have time_for_each_line = 1. While for such buffers I would expect this to be 0. I wanted to use this to hide timestamps in relay client for buffers that don't need it.

## Steps to reproduce

1. As a relay client get request buffer hdata with time_for_each_line key
2. Get response

## Current behavior
All buffers including 'relay.relay.list' and 'fset.fset' have time_for_each_line set to 1.

## Expected behavior
Buffers that don't use timestamps have time_for_each_line set to 0

## Additional info
Explaination for this field is here: https://weechat.org/files/doc/stable/weechat_plugin_api.en.html
time_for_each_line | "0" or "1" | "0" to hide time for all lines in buffer, "1" to see time for all lines (default for a new buffer).

How we do it now, is we look at the buffer type, but for fset the buffertype is null. For relay buffer this works fine though.

- WeeChat version: 2.8
- OS, distribution and version: Raspbian GNU/Linux 10 (buster)

**Comment by flashcode** [comment]
This flag `time_for_each_line` is used only on buffers with free content.

So as you said, you must use this flag only on a buffer with free content, like fset or relay whose type should be the same.

I tried and it seems ok for me, type is 0 (formatted) for core.weechat and 1 (free content) for fset.fset and relay.relay.list:

    <-- infolist buffer
    --> size: 1723/7651 (78%), id='', objects:
    inl: name: buffer
      item 1:, pointer: '0x56289121a040', current_buffer: 0, plugin: '0x0', plugin_name: 'core', number: 1, layout_number: 1, layout_number_merge_order: 0, name: 'weechat', full_name: 'core.weechat', old_full_name: None, short_name: 'weechat', type: 0, notify: 3, num_displayed: 0, active: 1, hidden: 0, zoomed: 0, print_hooks_enabled: 1, day_change: 1, clear: 1, filter: 1, closing: 0, first_line_not_read: 0, lines_hidden: 0, prefix_max_length: 0, time_for_each_line: 1, (...)
      item 2:, pointer: '0x562891cbddd0', current_buffer: 0, plugin: '0x5628912d63f0', plugin_name: 'fset', number: 2, layout_number: 0, layout_number_merge_order: 0, name: 'fset', full_name: 'fset.fset', old_full_name: None, short_name: 'fset', type: 1, notify: 3, num_displayed: 0, active: 1, hidden: 0, zoomed: 0, print_hooks_enabled: 1, day_change: 1, clear: 0, filter: 1, closing: 0, first_line_not_read: 0, lines_hidden: 0, prefix_max_length: 0, time_for_each_line: 1, (...)
      item 3:, pointer: '0x562891f4b530', current_buffer: 1, plugin: '0x5628912e22e0', plugin_name: 'relay', number: 3, layout_number: 0, layout_number_merge_order: 0, name: 'relay.list', full_name: 'relay.relay.list', old_full_name: None, short_name: 'relay.list', type: 1, notify: 3, num_displayed: 1, active: 1, hidden: 0, zoomed: 0, print_hooks_enabled: 1, day_change: 1, clear: 0, filter: 1, closing: 0, first_line_not_read: 0, lines_hidden: 0, prefix_max_length: 0, time_for_each_line: 1, (...)

**Comment by AStove** [comment]
So, if I understand you correctly:
This flag is only to be used on buffers with free content => ✔️ fset and relay.list are free content buffers so we can use the `time_for_each_line` flag.

Then why is `time_for_each_line` set to 1? These buffers should not have a time for each line.

**Comment by trygveaa** [comment]
I think @flashcode misspoke, and meant that `time_for_each_line` is only used on buffers with formatted content. I don't think free buffers have timestamps for lines at all.

**Comment by AStove** [comment]
In that case I understand. Though, why would it not default to 0 for free format buffers. It doesn't make sense that you need to look at multiple properties to figure out if time is needed or not.

**Comment by flashcode** [comment]
I'll set it to 0 on buffers with free content if that makes life easier for relay clients.

**Comment by flashcode** [comment]
Hmm I understand why it's 1 by default.
It's because when you create a buffer in WeeChat, it is always "formatted" by default. So time_for_each_line is 1, which is correct.
And then you must change the type of buffer to "free", but time_for_each_line is not changed.
If I set it to 0 here, there's just a problem in case you change again the type to "formatted", because I would have to put 1 again, but this property can be changed by the user (whatever the type of buffer is).
Though it should be very rare to change the type to "free" then back to "formatted".

**Comment by flashcode** [comment]
Done.

**Comment by AStove** [comment]
Thanks!
