### ISSUE TITLE
Python script plugin warning, while importing decimal module, causing UI glitches

### ISSUE THREAD

**Issue by int3l** [weechat/weechat#1486]
## Bug summary
Warning from cpython, when importing the decimal module

## Steps to reproduce

1. Load example plugin with /script or /python load test.py
2. Unload and load the test.py script again.
3. Observe the warning displayed via the `stderr` - bug outs the weechat's text UI layout.

## Current behavior
Messes up the current text UI layout upon loading of the plugin.

## Expected behavior
Catch and print the warning inside the core weechat buffer or something like this instead of causing text UI layout glitches.

## Suggested solutions
This error seems to show up, when something tries to reinitialize the decimal module internals for a second time. This is the place where the warning fires: [_decimal/libmpdec/context.c](https://github.com/python/cpython/blob/e42b705188271da108de42b55d9344642170aa2b/Modules/_decimal/libmpdec/context.c#L54)

Error msg for search reference:
```
warning: mpd_setminalloc: ignoring request to set MPD_MINALLOC a second time
```

## Additional information
Example snippet that triggers the error:
```python
# test.py
import weechat
import decimal

if weechat.register('test', 'author', '1', 'license', 'desc', '', ''):
    buf = weechat.buffer_search('irc', '')
    weechat.prnt(buf, 'Test')
```

---

- WeeChat version: 2.8 [compiled on Mar 29 2020 11:39:07]
- OS, distribution and version: Windows 10, Cygwin, python 3.6.9 (or equivalent Ubuntu 18.04 LTS)

**Comment by int3l** [comment]
Closing since it seems that this is only reproducible inside **Windows Terminal** app.
The `stderr` output is not shown while running weechat from inside **mintty**.

**Comment by int3l** [comment]
Here is a screenshot of the visual glitches:
![weechat_glitch](https://user-images.githubusercontent.com/1278836/80320411-e6280400-881e-11ea-9c08-a650cce7036c.png)

**Comment by knghtbrd** [comment]
I can reproduce this bug by having a script that imports the requests module and reloading that script. If I replace the "human friendly" requests module, I expect the problem will go away. But requests is so nice …

**Comment by trygveaa** [comment]
@knghtbrd: A bit besides this issue, but you shouldn't use `requests` in WeeChat scripts as `requests` does blocking requests and WeeChat scripts run in the UI thread, so you will block the whole UI while any request is running. You should instead use the [WeeChat Plugin API](https://weechat.org/files/doc/stable/weechat_plugin_api.en.html#_hook_url).

As for this issue, I can't reproduce it with a script importing either `decimal` or `requests` (and reloading the script) on Arch Linux with Python 3.11.6.
