### ISSUE TITLE
Cleanup configuration

### ISSUE THREAD

**Issue by adrian-maurin** [weechat/weechat#1487]
## Question
Hi,
I was trying to cleanup my config lately and I noticed that some entries where probably obsolete (deleted script or from previous weechat versions).

So now I am wondering if it is possible to "clean" the config, removing entries that are not used by any script or weechat itself?

---

- WeeChat version: 2.8
- OS, distribution and version: Arch Linux

**Comment by flashcode** [comment]
Hi,

Yes you can remove old script options, there's even a script to help doing this: https://weechat.org/scripts/source/unset_unused.pl.html/ (use with caution!).

WeeChat options are automatically updated on upgrade (and removed if they don't exist any more) so you should not have such options.
