### ISSUE TITLE
buffer_nicklist_count includes nicklist groups

### ISSUE THREAD

**Issue by trygveaa** [weechat/weechat#1506]
## Question

I'm not sure if this is intentional or not, but I've always found it strange that the `buffer_nicklist_count` bar item counts both nicks and groups instead of just nicks.

The description for `gui_bar_item_buffer_nicklist_count_cb` says "Bar item with number of nicks in buffer nicklist.", so from that it seems that it should only count the number of nicks. However, that function uses the property `nicklist_visible_count` and the description for that in the documentation is "number of nicks/groups displayed", so there's an inconsistency there.

The wee-slack script uses groups to separate nicks into the ones present and the ones away, which means that `buffer_nicklist_count` is always two more than the number of nicks in the channel.

I would think the information that is useful to show in the status bar is the number of nicks. However, I don't know what groups are used for other places. Is there anytime it's useful to count them?

---

- WeeChat version: 2.8
- OS, distribution and version: Arch Linux

**Comment by flashcode** [comment]
You're right, so currently we have: `buffer_nicklist_count` == visible groups + nicks.

To stay compatible with existing config, I propose such changes:

- `buffer_nicklist_count` (existing item) == visible nicks only
- `buffer_nicklist_count_groups` (new item) == visible groups only
- `buffer_nicklist_count_all` (new item) == visible groups + nicks

**Comment by trygveaa** [comment]
Thanks!
