### ISSUE TITLE
add tr/// to trigger regex

### ISSUE THREAD

**Issue by pascalpoitras** [weechat/weechat#1510]
## Feature description

Sometimes someone join #weechat and ask if this is possible to mimic tr in a trigger, tr/// instead of s///. It would be nice if we could use a prefix before the delimiter to specify the desired behavior, for example tr/abc/ABC/ and s/hi/hello/ and when there is no prefix, fallback to s///. But I just created a trigger with a letter as delimiter and the trigger is valid so I guess it's not possible this way since a delimiter can be a letter?

**Comment by flashcode** [comment]
Hi,
What would do `tr` compared to `s`, can you please give examples of both to see the differences?

**Comment by pascalpoitras** [comment]
tr/// would replace the first character in pattern by first character in replacement, second character in pattern by second character in replacement and so on. For example: tr/abc/ABC/ will replace a by A, b by B and c by C. On the other hand, s/abc/ABC/ will replace any occurence of abc by ABC

`/exec -sh echo 'allo' | tr 'abc' 'ABC'`           => Allo (occurence of a)
`/exec -sh echo 'allo' | sed 's/abc/ABC/'`     => allo (no occurence of abc)

**Comment by sim642** [comment]
This starts simple but begs a question how many features this should support. For example, GNU `tr` also supports regex-like character ranges and character classes. The former might be quite useful for this feature but also significantly complicates the implementation compared to one `strchr` and string indexing.

**Comment by sim642** [comment]
Also, I forgot to mention but `sed` also supports tr-like operations, although under the name y/// not tr///, e.g. `sed 'y/abc/ABC/'`. So there's also the choice for which name to use for such prefix: the name of a command line tool or the name of an analogous sed expression.

**Comment by pascalpoitras** [comment]
y/// could be an "alias" to tr/// so anyone can pick the prefix they're used to
good point for the GNU version of tr, of course this is very useful but even a tr without this would be very useful to reduce the length and complexity of some trigger

**Comment by flashcode** [comment]
Hi,

I schedule this for v3.8 and I've written a specification, your feedback is welcome: https://specs.weechat.org/specs/001510-trigger-regex-commands.html

**Comment by flashcode** [comment]
Implemented.

So be careful with old triggers which could have an incompatible regex format, and would then be ignored on upgrade (they must be fixed before upgrading WeeChat).
