### ISSUE TITLE
[Question] Change fset selected text color background

### ISSUE THREAD

**Issue by drselump14** [weechat/weechat#1512]
## Question

Hi, I'm wondering how to change the background color of selected value in fset buffer.
Sorry for a silly question, have no litle experience with weechat.

regards

---

- WeeChat version:  2.8
- OS, distribution and version:  macOS Catalina

**Comment by sim642** [comment]
The option `fset.color.line_selected_bg1` should change that.

**Comment by drselump14** [comment]
nice.. thanks @sim642 !
