### ISSUE TITLE
Weechat removing whitespace from the end of messages, breaking IRC art

### ISSUE THREAD

**Issue by acidvegas** [weechat/weechat#1513]
## Bug summary
IRC Art is breaking on weechat users because most IRC art doesnt have a ^O at the end of each line, so when you have art that is just something like "^C02,04TEST" with a bunch of spaces after it for a solid background color, it will not show it, because it is trimming the whitespace at the end.

Picture of the same ascii on weechat vs irssi: https://imgur.com/a/ENI6ccy
Link to original ascii file: https://raw.githubusercontent.com/ircart/ircart/master/mircart/gantgorbilla.txt
---

- WeeChat version: 2.8
- OS, distribution and version: Linux hostname 5.6.11-arch1-1 #1 SMP PREEMPT Wed, 06 May 2020 17:32:37 +0000 x86_64 GNU/Linux

**Comment by flashcode** [comment]
Thanks for reporting the issue, it is a regression introduced in WeeChat 2.5 (commit 2b70d71aa1c891f2f251aa775cf239e5611576d5), where I added new flags for API function `string_split`.

**Comment by acidvegas** [comment]
No problem. Status on unbanning me from #weehcat, lol

**Comment by weechatter** [comment]
no status. Banned for good reasons. lol
