### ISSUE TITLE
sort-option for list-command: /list -sort

### ISSUE THREAD

**Issue by klartext** [weechat/weechat#1516]
## Feature description
Sorting the result of the list-command when using switch '-sort'.
For long result lists of channels that would be very helpful.

Sorting should use the active locale-settings.

**Comment by weechatter** [comment]
there are at least two scripts to sort the output from /list command

**Comment by flashcode** [comment]
As @weechatter said, there are two scripts: https://weechat.org/scripts/tag/list/
I think this feature is not really needed in irc plugin itself, a script is enough.
