### ISSUE TITLE
Cannot specify case-sensitive ignore regex

### ISSUE THREAD

**Issue by lluchs** [weechat/weechat#1518]
## Bug summary

The documentation on `/ignore` says:
>nick: nick or hostname (can be a POSIX extended regular expression if "re:" is given or a mask using "*" to replace zero or more chars)
>Note: the regular expression can start with "(?-i)" to become case sensitive.

...but `/ignore add re:(?-i)xyz` prints the error message `irc: error adding ignore`

## Steps to reproduce

1. Run `/ignore add re:(?-i)xyz`
2. Observe error message

---

- WeeChat version: 2.8
- OS, distribution and version: Arch Linux

**Comment by flashcode** [comment]
This is caused by `^` and`$` that are automatically added at the beginning/end of regex, so `(?-i)xyz` is transformed into `^(?-i)xyz$` instead of `(?-i)^xyz$`.
