### ISSUE TITLE
solution to ACCOUNT trailing parameter is insufficient

### ISSUE THREAD

**Issue by jesopo** [weechat/weechat#1526]
weechat/weechat@d0ae0fea498750a2630c220798430fcdc9e3bce9

this solution supposes that you can receive one of three `ACCOUNT` formats:

- `:user ACCOUNT accountname`
- `:user ACCOUNT :accountname`
- `:user ACCOUNT *`

but there's a fourth which can happen and does happen on modern InspIRCd versions:
- `:user ACCOUNT :*`

**Comment by flashcode** [comment]
OK, I'll fix accordingly.

**Comment by jesopo** [comment]
really appreciate all the work you do. cheers
