### ISSUE TITLE
How to disable colours?

### ISSUE THREAD

**Issue by steadysupply** [weechat/weechat#1527]
## Question

Is there a way to turn off colours entirely in WeeChat?

---

- WeeChat version: 2.8
- OS, distribution and version: 
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal
```

**Comment by flashcode** [comment]
Hi,

There's no global setting to disable all colors, so you have 2 solutions:

1. Run with a TERM variable that forces monocolor: for example `TERM=xterm-mono`
2. Change color options in weechat, you can browse most color options with `/fset color`

**Comment by trygveaa** [comment]
> Run with a TERM variable that forces monocolor: for example TERM=xterm-mono

Note that setting TERM to a value not supported by the terminal emulator may break various stuff. Make sure to check that the terminal emulator you use support xterm-mono before setting this.

**Comment by steadysupply** [comment]
Cool, thanks.
