### ISSUE TITLE
irc_is_nick info does not support utf8 nickname

### ISSUE THREAD

**Issue by pascalpoitras** [weechat/weechat#1528]
## Bug summary

the irc_is_nick info does not works well with network that supports utf8 nickname

## Steps to reproduce

1.  /eval -n ${info:irc_is_nick,で}

## Suggested solutions

add support for [rfc8265](https://github.com/DanielOaks/ircv3-specifications/blob/master+rfc7700/documentation/rfc8265.md) and then allow a second arguments to this info (a server name). Something like this:

1. /eval -n ${info:irc_is_nick,で,my_oragono_server}

you can connect to the oragono testnet to test (testnet.oragono.io)

---

- WeeChat version: WeeChat 2.9-dev (git: v2.8-196-g99a324b76)
- OS, distribution and version: Debian 10

**Comment by flashcode** [comment]
If the server is added, it would be added as first argument and optional, ie:

    /eval -n ${info:irc_is_nick,alice}
    /eval -n ${info:irc_is_nick,freenode,alice}

**Comment by flashcode** [comment]
The value of `UTF8MAPPING` should be used as well: https://github.com/DanielOaks/ircv3-specifications/blob/master+rfc7700/documentation/rfc8265.md
