### ISSUE TITLE
change how /exit works when in a channel

### ISSUE THREAD

**Issue by yancyribbens** [weechat/weechat#1532]
## Feature description
I frequently want to leave a channel, so I type "/exit" in the channel by accident instead of /close.  This kicks me out of all the servers and channels and closes weechat.  It seems to me that /exit should only work in the weechat buffer and not the channel buffer.

**Comment by flashcode** [comment]
Instead of doing that (exiting from everywhere has always been there and is a feature, not a bug), you have an option to prevent accidental quit of weechat:

    /set weechat.look.confirm_quit on

See `/help weechat.look.confirm_quit` for more information.

Is that OK for you?

**Comment by yancyribbens** [comment]
yes, thanks @flashcode!

**Comment by weechatter** [comment]
also /EXIT is an alias, simply change the alias to: /alias add /EXIT /buffer close

problem solved ;-)
