### ISSUE TITLE
'Make' phase failed while compiling weechat 2.8, need help please.

### ISSUE THREAD

**Issue by scottcarter2020** [weechat/weechat#1533]
Hello,

I have installed all the dependencies needed to compile weechat 2.8 but I faced the following error in the ($ make) phase.

I'm currently new to compiling, so please consider that what caused the error is an irrelevant fault from a total beginner.

Scanning dependencies of target python
[ 65%] Building C object src/plugins/python/CMakeFiles/python.dir/weechat-python.c.o
[ 65%] Building C object src/plugins/python/CMakeFiles/python.dir/weechat-python-api.c.o
[ 65%] Linking C shared module python.so
/usr/bin/ld: /usr/local/lib/libpython3.8.a(_warnings.o): relocation R_X86_64_PC32 against symbol `_PyRuntime' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
src/plugins/python/CMakeFiles/python.dir/build.make:103: recipe for target 'src/plugins/python/python.so' failed
make[2]: *** [src/plugins/python/python.so] Error 1
CMakeFiles/Makefile2:1620: recipe for target 'src/plugins/python/CMakeFiles/python.dir/all' failed
make[1]: *** [src/plugins/python/CMakeFiles/python.dir/all] Error 2
Makefile:154: recipe for target 'all' failed
make: *** [all] Error 2

Thanks.

**Comment by flashcode** [comment]
Hi,

As you can see in the bug report template, extra info is needed: your OS, distribution and its version.

WeeChat should compile fine with Python 3.8, but I notice in your output that the path is `/usr/local/lib/libpython3.8.a`, this seems to be a custom installation of Python and you may have a problem if you compile with a given Python version and link with another version.

Could you try to use only Python installed with your package manager?

**Comment by scottcarter2020** [comment]
Hi Sébastien,

OS: Linux
Distribution: Ubuntu
Version: 18.04 LTS

I have installed Python 3.8.3 using this tutorial, option 2

https://phoenixnap.com/kb/how-to-install-python-3-ubuntu

I have also learned to create a virtual python environment, do you recommend this as solution ?

**Comment by flashcode** [comment]
Please try to install Python 3.8 with official Ubuntu packages, this will make WeeChat compilation easier.

By the way, there are builds of WeeChat for almost all Ubuntu versions here, easier to install than compiling: https://weechat.org/download/debian/.

**Comment by scottcarter2020** [comment]
> Please try to install Python 3.8 with official Ubuntu packages

I didn't understand this, is there anything with that online tutorial that is wrong ?

I would like to continue compiling please as I have learnt a lot and still want to learn more, if this is OK with you for sure.

**Comment by flashcode** [comment]
If you really want to compile Python and WeeChat yourself, this makes things a bit harder, you'll have to give paths for the custom Python in WeeChat CMake options, see the output of this command:

    cmake .. -LA | grep -i python

If you're not expert with compilation/linking of software, paths to libraries, etc., I highly recommend to install only Debian packages with apt, it's a lot easier.

For me the only advantage of compiling software if is you want to use development/unreleased version of software (but even WeeChat has Debian/Ubuntu nightly builds, so you can still install Debian packages).

**Comment by scottcarter2020** [comment]
I have a good news, I have downloaded and successfully run the latest weechat version using the ready builds.

I guess it's not the right time now to compile from source code, still a new learner over here.

I have two questions please then I will close this issue.

- I already have an issue with gtk-weechat, can I open a new issue here about it or it's a must to open at it's github repo. ?

- When a new version of weechat is out, how do I upgrade it ?

**Comment by flashcode** [comment]
> I have a good news, I have downloaded and successfully run the latest weechat version using the ready builds.
> 
> I guess it's not the right time now to compile from source code, still a new learner over here.

Great, OK.

> 
> I have two questions please then I will close this issue.
> 
>     * I already have an issue with gtk-weechat, can I open a new issue here about it or it's a must to open at it's github repo. ?

gtk-weechat is a completely separate project, so please open any issue in their repository.

> 
>     * When a new version of weechat is out, how do I upgrade it ?

If you installed Ubuntu packages, when a new version is released, just upgrading your packages is enough (ie: `apt update` then `apt upgrade`).

**Comment by weechatter** [comment]
and after the binary upgrade (with apt) is done, run /upgrade command in weechat.
