### ISSUE TITLE
add $key to allchan

### ISSUE THREAD

**Issue by pascalpoitras** [weechat/weechat#1536]
## Feature description

would be useful to have $key pointing to the key (+k) of the channel for /allchan

**Comment by flashcode** [comment]
I'll add evaluation of the command on each server/channel, so you'll able to read all variables from IRC server and channel using hdata.

For example:

    ${irc_server.name}
    ${irc_channel.name}
    ${irc_channel.key}

This will be available for the following commands:

    /allserv
    /allchan
    /allpv

**Comment by weechatter** [comment]
cool!

**Comment by flashcode** [comment]
For testing purposes, waiting for a merge in master branch (after release of version 2.9), I pushed a branch [issue-1536](/weechat/weechat/tree/issue-1536).

Note that in this branch I added evaluation of the command, but I also removed the automatic add of "/" in front of command if a command char is missing.
That means this command is now OK to say "hello" in all channels:

    /allchan hello

Before this change, you had to do (this still works if the `/` is present before `msg`):

    /allchan /msg * hello

**Comment by pascalpoitras** [comment]
works perfectly, now autojoinem.py can add all channel even if there's a key

`/allchan /autojoinem add ${irc_server.name} ${irc_channel.name}${if:${irc_channel.key}? -key ${irc_channel.key}}`

@weechatter we should update the help for the script

**Comment by pascalpoitras** [comment]
today I forgot that the syntax is -include=#channel, I did -include #channel and this send a message to all channels. Before this branch I would have receive lots of "unknown command /-include" but now that the / is no more added at the beginning of a message that does not contain one, this send the message everywhere. Also, I am almost certain lots of user will complain that they send message everywhere because they were relying on the fact that / is auto appended. I was relying on that fact so I change my configuration to add the /. Is that possible to still append the / when the message does not contain one ?
