### ISSUE TITLE
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)

### ISSUE THREAD

**Issue by GideonWolfe** [weechat/weechat#1539]
## Bug summary

When weechat is left open, this error breaks the program and prints to the terminal

## Steps to reproduce

1. Open weechat
2. Wait

## Current behavior

After letting weechat sit for a while, this occurs
![Screen Capture_select-area_20200705121825](https://user-images.githubusercontent.com/32942052/86540378-a97d2680-beb9-11ea-8df9-a854e553e52d.png)

## Expected behavior

This does not occur

## Suggested solutions

The problem seems to fix itself when I restart `i3`.

## Additional information

When I exit `weechat` when it is in this state and attempt to restart it, I get this:

```
Error: unable to create/append to log file (weechat.log)
If another WeeChat process is using this file, try to run WeeChat
with another home using the "--dir" command line option.
```

So I do a `pkill -9 weechat`

When I relaunch weechat, channels that usually are loaded up in a few seconds load at a snails pace. 1+ minutes for all my channels to spawn in. After, I can use it as normal until the error occurs again.

---

- WeeChat version: 2.8
- OS, distribution and version:  `archlinux 5.7.7`

**Comment by flashcode** [comment]
Hi,
For me the problem is related to your window manager, WeeChat is a pure terminal app and makes no calls to X functions.
So you should report the issue to the i3 team.
By the way I'm using i3 for years now with WeeChat on Debian (unstable and testing), without any problem.

**Comment by GideonWolfe** [comment]
Hmm, interesting. I haven't experienced this with any other programs. It must be related to some sort of update, because the same issue started happening on my friends arch system last week. I don't think i3 has been updated recently.

I'll see what the i3 people think, thanks.

**Comment by trygveaa** [comment]
This is most likely caused by a script which calls X, for instance `lnotify.py`.

If the error is what I think it is, weechat isn't in a broken state, and you can clear the error messages by pressing ctrl-l.

**Comment by weechatter** [comment]
i agree with trygveaa, i also guess its an script. @GideonWolfe: /script list

**Comment by GideonWolfe** [comment]
yes, I do have `lnotify.py`. I'll see if removing it fixes the issue. It's been working previously, curious what broke. What is another option for desktop notifications?

**Comment by GideonWolfe** [comment]
I have migrated from `notify-osd` to `dunst`, and am now happily using `anotify.py` without issue.
