### ISSUE TITLE
Spaces in passwords

### ISSUE THREAD

**Issue by NightcoreSergeant** [weechat/weechat#1541]
It would be nice to add feature that enables not to have password bounded by the space.

**Comment by flashcode** [comment]
@NightcoreSergeant: could you please give an example, I'm not sure to understand the need?

**Comment by NightcoreSergeant** [comment]
for example in bitlbee to add an account there is a function(not accurate):

`add facebook my@emal.com password`


if you have a password with spaces, every substring between spaces counts as different argument for the add function. I don't know any other case where this feature might be useful. Maybe if irc server had password with spaces (if that is possible)

**Comment by flashcode** [comment]
So you want to support passwords with spaces, or **not** support them?

**Comment by trygveaa** [comment]
Bitlbee has its own command parsing, you just send messages from weechat, so weechat can't do anything in regards to those commands. To use spaces in password in bitlbee, you have to use quotes, see https://bugs.bitlbee.org/ticket/565.

**Comment by NightcoreSergeant** [comment]
i **want** to support password with spaces. 
Thank you for the info @trygveaa , the feature still might be useful with the other example.

**Comment by trygveaa** [comment]
IRC channel keys can't contain spaces as far as I can see. See https://tools.ietf.org/html/rfc2812

```
  key        =  1*23( %x01-05 / %x07-08 / %x0C / %x0E-1F / %x21-7F )
                  ; any 7-bit US_ASCII character,
                  ; except NUL, CR, LF, FF, h/v TABs, and " "
```

And for passwords set in weechat options, such as server and sasl passwords, you can just use space like any other character in the `/set` command.

So what are you asking for?

**Comment by NightcoreSergeant** [comment]
Thank you for clarifying. There is no such feature needed.
