### ISSUE TITLE
Reloading spell plugin messes up input modifier trigger

### ISSUE THREAD

**Issue by oakkitten** [weechat/weechat#1547]
### Bug summary

Reloading the spell plugin (or doing `/upgrade`) can mess up input modifier trigger. 

### Steps to reproduce

1.  Run weechat: 
    ```
    $ weechat -d /tmp/foo
    ```
2.  Add a trigger that makes text in backticks gray: 
    ```
    /trigger add input_backtick modifier "500|input_text_display" "" "/(^| )(`[^`]+)($|(`)($|[,.?!:; ]))/${re:1}${color:,darkgray}${re:2}${re:4}${color:,default}${re:5}/" "" "" "none"
    ```
3.  Turn on spellchecking:
    ```
    /set spell.check.default_dict en
    /set spell.check.enabled on
    ```

4.  Type `` `foo``, observe changed background

5.  Reload `spell`:
    ```
    /plugin reload spell
    ```

6.  Type `` `foo``, observe the mess (``B02`foo``)

Readding the trigger or reloading the trigger plugin fixes the issue.

---

- WeeChat version: WeeChat 3.0-dev (git: v2.9-14-g9262720a6)
- OS, distribution and version: Raspbian GNU/Linux 10 (buster), Linux 5.4.51-v7+

**Comment by flashcode** [comment]
Hi,

This is not a bug: you are using the priority "500" which is the same as the priority of the modifier hook created by spell plugin to update the input (spell plugin uses a priority of 500 to be sure it's executed before any other modifier with default priority, which is 1000).

Using the same priority makes the order of the modifiers unpredictable and it depends which modifier is loaded before the other one.

So you should use a higher priority for your trigger (for example 300), and it will always work fine, even if you reload the spell plugin:

    /trigger add input_backtick modifier "300|input_text_display" "" "/(^| )(`[^`]+)($|(`)($|[,.?!:; ]))/${re:1}${color:,darkgray}${re:2}${re:4}${color:,default}${re:5}/" "" "" "none"

**Comment by oakkitten** [comment]
oh, that explains some of it!

still, i'm only setting the background color with the trigger. spell seems to be trying to set the foreground color... i don't think these should conflict with each other?

**Comment by flashcode** [comment]
OK, I'll inspect the spell modifier, maybe I can improve things to not conflict with other modifiers.

**Comment by flashcode** [comment]
@oakkitten: could you please tell me the steps to reproduce the problem with the script `color_popup.pl`, I just tried it seems OK for me.

**Comment by oakkitten** [comment]
on a fresh copy of weechat run
```
/script install color_popup.pl
/set spell.check.enabled on
/set spell.check.default_dict en
```
then type <kbd>^c</kbd> <kbd>c</kbd> ``03hello`` <kbd>Space</kbd>
