### ISSUE TITLE
Alt + n behavior

### ISSUE THREAD

**Issue by Hannu1** [weechat/weechat#1550]
### Question ### 
Is it possible to disable toggling to the previously active buffer when using alt + n to choose the buffer? I swapped over from irssi recently and keep typing to the wrong channel, because I'm used to pressing "alt + n" before typing and not really reading the channel name. Now in weechat, if the buffer was already active, it jumps to the previously active buffer. Is there a way to configure weechat so that it only changes the buffer, if the current buffer is not n?

**Steps to reproduce:**
1. Connect to an irc server and open two channels. 
2. Let's assume these channels get buffer numbers 2 and 3. 
3. Go to buffer 2 with alt + 2.
3. Go to buffer 3 with alt + 3.
4. Press alt + 3 again.

**Actual result:** Active buffer changes to buffer 2.
**Expected result:** Nothing happens.

Not a bug, but figured the steps + results might help explain it better.

**Comment by flashcode** [comment]
Hi,

You could try: `/set weechat.look.jump_current_to_previous_buffer off`, so that alt+N always jumps only to buffer N, and it does not come back to previous buffer if you press again alt+N on the buffer N.

Is that what you're looking for?

**Comment by Hannu1** [comment]
That is exactly what I was looking for. Thank you. This issue can be closed.

Sorry for the late reply. Didn't have email notifications set up. Also thanks for weechat. Loving it so far. :)
