### ISSUE TITLE
tg_prefix is not colored with highlight colors

### ISSUE THREAD

**Issue by pascalpoitras** [weechat/weechat#1564]
## Bug summary

in a print trigger, tg_prefix contains the nickname colored as expected but when a message contains a highlight, tg_prefix doesn't have the color for highlight (weechat.color.chat_highlight and weechat.color.chat_highlight_bg).

## Steps to reproduce

1. `/set weechat.color.chat_highlight lightred`
2. `/trigger add p print "" "${tg_highlight}" "" "/print -core ${tg_prefix}"`
3. highlight yourself

## Current behavior

tg_prefix is colored with the color for the nick even when there is a highlight

## Expected behavior

tg_prefix should be colored with the color in weechat.color.chat_highlight (and weechat.color.chat_highlight_bg if set)

---

- WeeChat version: WeeChat 3.0-dev (git: v2.9-31-g7dd5abd62)
- OS, distribution and version: Debian 10

**Comment by flashcode** [comment]
Hi,
This is not a bug, but the normal behavior: the highlight color is dynamically applied on the prefix only when WeeChat displays the line (according to the `highlight` flag in the line).
So the prefix has no specific color when there's a highlight. This lets for example any relay client display the highlight the way he wants (it's possible to highlight differently, not on the prefix).

**Comment by pascalpoitras** [comment]
oh I see, thanks!
