### ISSUE TITLE
Handle /exec stderr output gracefully

### ISSUE THREAD

**Issue by ManDay** [weechat/weechat#1566]
`/exec` treats `stderr` as just an appendix to `stdout`. This can often be undesireable, e.g. if used as `/exec -o` and there are (unpredicted) errors, possibly many of them, you involuntarily end up flooding the channel.

**Comment by flashcode** [comment]
I think stderr was annoying only when you send text to a buffer (with `-o` or `-oc`), so I added a new option `-oerr` to force output of stderr to the buffer, which is now disabled by default.
