### ISSUE TITLE
add a variable containing the name of the trigger

### ISSUE THREAD

**Issue by pascalpoitras** [weechat/weechat#1567]
## Feature description

Is it possible to add a variable containing the name of the trigger (in my case a print trigger but this can be useful in any type)? I have two very similar triggers and I would like to do something like `/.*/${plugins.var.${trigger_name}.something}/my_val` instead of `/.*/${plugins.var.trigger_1.something}/my_val` in the first one and `/.*/${plugins.var.trigger_2.something}/my_val` in the last one.

**Comment by sim642** [comment]
I wonder what the best name for such variable would be. Many trigger-specific variables have a `tg_` prefix, so maybe `tg_name`? Although maybe that's too ambiguous and should be `tg_trigger_name`?

**Comment by pascalpoitras** [comment]
@sim642 

I prefer tg_trigger_name because as you said it is less ambiguous
