### ISSUE TITLE
Pasting single line ending with newline does not respect paste_max_lines setting

### ISSUE THREAD

**Issue by louipc** [weechat/weechat#1569]
## Bug summary
When setting paste_max_lines to 0 a single line text can still automatically be sent to channel if the text ends in a newline.

## Steps to reproduce
1. /set weechat.look.paste_max_lines 0
2. Copy a line of text, including the newline, but not the first character of the next line.
3. Paste into the input buffer

## Current behavior
Paste contents will be sent to channel.
If there are multiple newlines at the end of the text, only the leading text is sent, not the extra newlines.

## Expected behavior
Prompt asking to Paste 1 lines
[Paste 1 lines? [ctrl-Y] Yes [ctrl-N] No]

## Suggested solutions
weechat.look.paste_max_lines = 0 should prevent any paste being sent without confirmation
If paste_max_lines == 0 and text has terminating newline(s) prompt user before sending.

---
WeeChat 2.9 [compiled on Jul 19 2020 06:32:47]
Linux, Arch Linux, 2020-10-11

**Comment by flashcode** [comment]
Hi,

I can not reproduce your problem, I tried with devel and 2.9 versions: if I paste one line with a single newline at the end, the text is in the input but not sent to the channel.
And if weechat.look.paste_max_lines is set to 0, weechat asks to copy 1 line, and if I accept it's still not sent immediately, you have to press Enter.

What's your terminal and are you using a terminal multiplexer (screen, tmux, …)?

**Comment by louipc** [comment]
Oh good point. I am using rxvt-unicode and screen

**Comment by louipc** [comment]
I can also reproduce the bug on rxvt-unicode without screen and on termite 15 (https://github.com/thestinger/termite/) without screen.

**Comment by louipc** [comment]
Tried this with a fresh config and weechat behaves as expected.

**Comment by flashcode** [comment]
So you could make a diff between configs, maybe some options have been changed.

**Comment by trygveaa** [comment]
You had probably disabled `weechat.look.paste_bracketed`.

**Comment by louipc** [comment]
I think my config was old enough to where paste_bracketed was default to off.
Setting to on now I get the prompt. This behaviour is more desirable, but seems
the newline is stripped when accepting the prompt. Not sure if this is a bug or not
but I think my main issue is resolved.

I'll leave to you whether its still something that should be investigated or not.

**Comment by louipc** [comment]
Update: I was able to bypass paste_bracketed = on by detaching from screen then reattaching in a different terminal.
Reattaching to screen in the same terminal will still respect paste_bracketed = on.

**Comment by louipc** [comment]
I'll close this for now. I notice some other strange behaviours regarding terminals and paste that will need to be resolved first.
Escape codes being pasted to one terminal but not another, etc. Thanks.
