### ISSUE TITLE
a couple of questions about colors

### ISSUE THREAD

**Issue by pascalpoitras** [weechat/weechat#1572]
## Question

I have a couple of questions about colors

1) I have two block of text with background colors, I want to determine if they have both the same background color because i want to use a different separator between those when they are the same and another one when they are not the same. Currently I use something like this in a trigger ${color:${my_first_bg}}==${color:${my_second_bg}} and it works but there is a issue. White and 15 doesn't generate the same underlying code (i guess because white is a "basic" color and 15 is "extended" but they are visually equivalent but not as far as weechat is concerned so the wrong separator is choose. Is there a way around this other than creating a lot of alias with /color alias?

2) to the previous question, if there is a way, should I avoid it ? i mean, is it possible that a terminal show a difference between color 3 and yellow ? or they are guaranteed to be exactly equivalent?

3) weechat-android and glowing bear doesn't support reverse video so how to reverse the default bg color with the default fg color ? I don't want to use ${color:reverse} because i want it to be displayed correctly in these relay client. Is there something like ${color:defaultbg,defaultfg} ?

---

- WeeChat version: WeeChat 3.0-dev (git: v2.9-57-g72fdd689a)
- OS, distribution and version: Debian 10

**Comment by flashcode** [comment]
My answers:

1. There's no reliable way to compare internal color codes. Multiple color codes can give the same color, so you can not compare them like that to check if it's the same color or not.

2. See answer to 1.

3. If reverse color does not work in relay client, the relay client should be fixed to support it, any color code should display fine in the relay client. There's no other way to reverse color in WeeChat (remember: reverse does not mean it's using default bg/fg, it reverses the colors currently displayed, so the result of `${color:reverse}` depends on the colors fg/bg currently displayed).

**Comment by pascalpoitras** [comment]
thanks !
