### ISSUE TITLE
Allow using `/script list` with script.scripts.download_enabled set to off

### ISSUE THREAD

**Issue by wlhlm** [weechat/weechat#1574]
## Feature description

After updating my copy of weechat with the changes to fix #1548, I was surprised that running `/script list` to show my currently loaded scripts required me to enable `script.scripts.download_enabled`. It looks like the command updates the remote list of scripts to show which of the locally loaded scripts can be updated. While I think this functionality is neat to have (and I'm not worried about weechat "phoning home"), I think it would be helpful if `/script list` could work without having `script.scripts.download_enabled` enabled (for example when only working with local scripts).

**Comment by flashcode** [comment]
Hi,

I understand your need, but the `list` sub-command starts by downloading the repository file (if too old).
It would be weird for me to have a different behavior and output, depending on the option `script.scripts.download_enabled`.
More generally, this option must be enabled when you want to use the script plugin (any command).

Note: the scripts can still be listed by the command of each language: `/python`, `/perl`, etc. (these commands just list loaded scripts and ignore the script origin).

**Comment by wlhlm** [comment]
I see that `/script` is meant to be used with the script repository, but I think treating it as a "frontend" to the various language plugins that works with and without the repository would also be worthwhile.

Of course, `/script install` and `/script upgrade` don't make sense in "offline" mode, but `/script [load|unload|reload|show|autoload|list]` are local operations and wouldn't strictly need the script repository to work as intended. In fact, with the exception of `/script autoload` and `/script list`, the rest of these commands currently work with `script.scripts.download_enabled` set to off. So, saying "More generally, this option must be enabled when you want to use the script plugin (any command)." is not entirely correct.

> Note: the scripts can still be listed by the command of each language: /python, /perl, etc. (these commands just list loaded scripts and ignore the script origin).

There are two aspects that the `/script` command does better than the individual language commands:
1. It shows the autoload status of the scripts which I don't think `/python`, or `/perl` do.
2. The language plugins don't seem to provide a way to enable autoload for scripts. You'd have to move the script into the autoload directory. `/script autoload` can create symlinks.

> It would be weird for me to have a different behavior and output, depending on the option script.scripts.download_enabled.

I would say the primary function of `/script list` is to show *locally* loaded scripts across *all* language plugins. This is followed by its function of displaying the status of each scripts in relation with the script repository (installed, held, popularity status, update available). I'm not requesting to change the former behaviour in any way, and for the latter aspect, of course it's impossible to show some of these aspects without the script repository, but `/script list` already has output for scripts that are not in the script repository:

```
16:11 Scripts loaded:
16:11   ?     foobar.pl 0.2 (Lorem ipsum)
16:11    ia   pushover.pl 2.0 (Send push notifications to your mobile devices using Pushover)
16:11  * ia   autojoin.py 0.3.1 (Configure autojoin for all servers according to currently joined channels)
```

You can see that it shows '?' for the unknown script. I think it makes sense to just reuse this output when in "offline" mode. In that case all scripts would be treated as unknown and all would just show the question mark. All of this doesn't look like new output, nor like new behaviour to me.

**Comment by flashcode** [comment]
OK, I agree with you.

I'll implement this, and when you run `/script list` there will be 3 cases:

1. You have a repository file up-to-date, list is displayed as usual.
2. You have an outdated repository file: the script status is based on this outdated file.
3. You don't have a repository file at all: status will always be `?`.

The commands `/script autoload` and `/script noautoload` will still work even without repository file.

**Comment by wlhlm** [comment]
Thank you very much for considering this and for the prompt implementation. And in general, thank you for this excellent piece of Free Software! :heart:
