### ISSUE TITLE
`/who *`, executed in #channel, will execute in the last channel/buffer in buffer list.

### ISSUE THREAD

**Issue by sijanec** [weechat/weechat#1578]
## Bug summary
When executing `/who *`, weechat will execute this for the channel that is last in the channel list, not the channel that has focus.

## Steps to reproduce

1. /join #channel
2. /join #unrelated-somestring
3. put focus on #channel
4. /who *

## Current behavior
5. In the server buffer you will see that the command got executed on #unrelated-somestring instead of #channel.

## Expected behavior
`/who *` should be executed in the buffer/channel that is focused.

## Suggested solutions
None.

## Additional information
* Tested on IRCNet and freenode.

* Is this really a bug?

---

- WeeChat version: at least 2.3 and 2.9
- OS, distribution and version: Linux host 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux
- Terminal: LXTerminal
- Terminal multiplexer (screen/tmux/…/none): Screen version 4.06.02 (GNU) 23-Oct-17

**Comment by flashcode** [comment]
Hi,

When you do `/who *`, the message `WHO *` is sent to the server, so there's no context (it's not an issue with the active buffer in WeeChat).

In practice, the server replies with the WHO on the latest channel you joined. I'm not sure this can be considered wrong, and anyway it's a server decision, not a WeeChat issue for me.

That means for me the command `/who *` doesn't make sense.

**Comment by sijanec** [comment]
Ok, please close.
