### ISSUE TITLE
add support for hook_completion for trigger

### ISSUE THREAD

**Issue by pascalpoitras** [weechat/weechat#1581]
## Feature description

Would it be easy to add support for creating hook_completion via trigger, I would like to be able to create a completion similar to %(config_options) that will allow an argument (a option name with * and ? allowed) but that return not the full option name (file.section.option) but only the option part. Something like %(config_options_name:plugins.var.something*).

**Comment by flashcode** [comment]
Completion is a complex mechanism and is not easy at all to implement in a trigger: the completion must build a list based on the user input.
So please use a script to implement a new custom completion, there's everything you need in the API.
