### ISSUE TITLE
force eval -c using ${eval_c:}

### ISSUE THREAD

**Issue by pascalpoitras** [weechat/weechat#1582]
## Feature description

I would like to be able to use the `/eval -c` form in the replacement part of a regex in the regex option of a trigger, but only the conditions option is treated as `/eval -c`. Would it be hard to add something like `${eval_c:3==3}` and this give `1` (even without using `-c`) for example 

`/trigger set mytest regex "/.*/${eval_c:3==3}/is_true"`

this will be useful even for something like this

`/eval -n 3 == 3 ? ${eval_c:3==3}`

I know i can use ${if: but I would like to be able to evaluate a condition in an option and this conditions is not in the if form, ok I can probably just wrap the option between ${if:} like this 

```
/set plugins.var.mycond ${info:version} =~ 3.0
/eval -n ${if:${plugins.var.mycond}?yes:no}
```

but still, eval_c would be better

**Comment by pascalpoitras** [comment]
thanks!

**Comment by flashcode** [comment]
Done, the new format is: `${eval_cond:xxx}`.

**Comment by pascalpoitras** [comment]
I just want to add a note on why ${eval_cond:...} is a very nice addition even if we have ${if:...}

${if:...} use the ? as the termination of the condition so you can't use it in a regex, and it use : to separate true and false so the following is broken

`/eval -n ${if:https://=~https?://?yes:no}`

you can use eval_cond to fix it

`/eval -n ${if:${eval_cond:https://=~https}?yes:no}`
