### ISSUE TITLE
Segmentation fault, core dumped when quitting from a non-connected server

### ISSUE THREAD

**Issue by TinCanTech** [weechat/weechat#1583]
## Bug summary
Segmentation fault, core dumped when quitting from a non-connected server.

## Steps to reproduce

1. Try to connect to a server but fail due to network error. (I tried to connect to freenode but due to my routing being incorrect at the time weechat could not find the server)
2. Wait for the second attempt to connect.
3. `/quit` weechat

## Current behavior
Sometimes the fault occurs.

## Additional information
`irc.server.freenode.weechatlog`:
```
2020-11-07 18:17:12	--	irc: connecting to server chat.freenode.net/6697 (SSL)...
2020-11-07 18:18:12	=!=	irc: timeout
2020-11-07 18:18:12	--	irc: reconnecting to server in 10 seconds
2020-11-07 18:18:22	--	irc: reconnecting to server...
2020-11-07 18:18:22	--	irc: connecting to server chat.freenode.net/6697 (SSL)...

*** The fault occurred here when I used /quit but was not logged ***

2020-11-07 18:18:39	--	irc: connecting to server chat.freenode.net/6697 (SSL)...
2020-11-07 18:18:39	--	gnutls: connected using 2048-bit Diffie-Hellman shared secret exchange
2020-11-07 18:18:39	--	gnutls: receiving 2 certificates
```
No further details in `core.weechat.weechatlog`

---

- WeeChat version: WeeChat 2.8-1 (Apr  4 2020 09:01:45)
- OS, distribution and version: Linux Mint 20 Cinnamon
- Terminal: GNOME Terminal 3.36.1.1
- Terminal multiplexer (screen/tmux/…/none): None

**Comment by flashcode** [comment]
Hi,
If you can reproduce the crash, please follow instructions here to report a complete backtrace: https://weechat.org/files/doc/devel/weechat_user.en.html#report_crashes

**Comment by TinCanTech** [comment]
I just tested a couple more times and it seems to happen every time.  You don't even need to wait for the second connection attempt, simply `/quit` before a connection is made.

**Comment by flashcode** [comment]
I can not reproduce (such bug woud have been fixed long time ago if it's every time you quit).
So if you can reproduce, I really need the backtrace to start investigations.
Thanks.

**Comment by TinCanTech** [comment]
> I can not reproduce (such bug woud have been fixed long time ago if it's every time you quit).

I agree. I tested thoroughly and it happened every time. If this was still a bug in your source code then I think it would have been noticed by now.

> So if you can reproduce, I really need the backtrace to start investigations.

The essential problem with this is that I have installed the Linux Mint distro version and I do not have the source for this version to build it myself.

I will close this issue because I agree that what ever the bug is, it is not in your source code.
(I may report this to Linux Mint)

**Comment by flashcode** [comment]
It can still be an issue in WeeChat or one of its plugins (or it could be a compilation issue with one of the plugins).

You could try to find the guilty plugin by asking to WeeChat to load only one or some plugins, eg:

    weechat -P irc
    weechat -P irc,python
    weechat -P irc,python,perl
