### ISSUE TITLE
Can not compile: passing argument 2 of ‘iconv’ from incompatible pointer type

### ISSUE THREAD

**Issue by m3Lith** [weechat/weechat#1588]
Trying to compile version 3.0 on Debian bullseye. This is my `CMakeError.log` after running `cmake .. -DCMAKE_INSTALL_PREFIX=/home/user/.local`:

```
Performing C SOURCE FILE Test ICONV_2ARG_IS_CONST failed with the following output:
Change Dir: /home/user/.local/src/weechat-3.0/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_149a9/fast && /usr/bin/make  -f CMakeFiles/cmTC_149a9.dir/build.make CMakeFiles/cmTC_149a9.dir/build
make[1]: Entering directory '/home/user/.local/src/weechat-3.0/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_149a9.dir/src.c.o
/usr/bin/cc   -fsigned-char -Wall -Wextra -Werror-implicit-function-declaration -DICONV_2ARG_IS_CONST -Werror -o CMakeFiles/cmTC_149a9.dir/src.c.o -c /home/user/.local/src/weechat-3.0/build/CMakeFiles/CMakeTmp/src.c
/home/user/.local/src/weechat-3.0/build/CMakeFiles/CMakeTmp/src.c: In function ‘main’:
/home/user/.local/src/weechat-3.0/build/CMakeFiles/CMakeTmp/src.c:9:17: error: passing argument 2 of ‘iconv’ from incompatible pointer type [-Werror=incompatible-pointer-types]
    9 |     iconv(conv, &in, &ilen, &out, &olen);
      |                 ^~~
      |                 |
      |                 const char **
In file included from /home/user/.local/src/weechat-3.0/build/CMakeFiles/CMakeTmp/src.c:2:
/usr/include/iconv.h:42:54: note: expected ‘char ** restrict’ but argument is of type ‘const char **’
   42 | extern size_t iconv (iconv_t __cd, char **__restrict __inbuf,
      |                                    ~~~~~~~~~~~~~~~~~~^~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [CMakeFiles/cmTC_149a9.dir/build.make:85: CMakeFiles/cmTC_149a9.dir/src.c.o] Error 1
make[1]: Leaving directory '/home/user/.local/src/weechat-3.0/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:140: cmTC_149a9/fast] Error 2


Source file was:

  #include <iconv.h>
  int main(){
    iconv_t conv = 0;
    const char* in = 0;
    size_t ilen = 0;
    char* out = 0;
    size_t olen = 0;
    iconv(conv, &in, &ilen, &out, &olen);
    return 0;
  }
```

**Comment by flashcode** [comment]
Hi,
I can not reproduce the issue, and I compile every night on Debian Bullseye without problems.
Did you try to build WeeChat from an empty build directory?

**Comment by m3Lith** [comment]
Yep, tried it with a clean cloned repo.. Maybe the error is related to one of the dependencies? If using a shared shell service, and some packages might be outdated. But no idea which one to look at from the error.

**Comment by flashcode** [comment]
If you're running Debian Bullseye, please check if these packages are installed:

    $ apt list --installed libc6 libc6-dev
    Listing... Done
    libc6-dev/testing,now 2.31-4 amd64 [installed,automatic]
    libc6/testing,now 2.31-4 amd64 [installed]

**Comment by m3Lith** [comment]
```
Listing... Done
libc6-dev/now 2.31-3 amd64 [installed,upgradable to: 2.31-4]
libc6/now 2.31-3 amd64 [installed,upgradable to: 2.31-4]
```

**Comment by flashcode** [comment]
OK, almost the same version.

What's your compiler and its version?

    $ cc --version
    cc (Debian 10.2.0-16) 10.2.0
    Copyright (C) 2020 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by m3Lith** [comment]
`cc (Debian 10.2.0-5) 10.2.0`

**Comment by flashcode** [comment]
As I can not reproduce on the same OS with almost same software, would it be possible for me to have an access on this machine to make tests?

**Comment by m3Lith** [comment]
I could share my user access, but it has no root privileges (shared shell service, as I've mentioned). If that's OK, should I contact you via email?

**Comment by flashcode** [comment]
Yes, no root is not a problem if all required WeeChat dependencies are already installed.
You can contact me on IRC / freenode (nick FlashCode), or email if you prefer.
I can give you a public SSH key if needed.

**Comment by m3Lith** [comment]
So after extremely quick help from @flashcode (big thanks again!), the problem appeared to be missing dependencies for script plugins.

If anyone has a similar issue: either compile with scripts disabled (`-DENABLE_SCRIPTS=OFF -DENABLE_SPELL=OFF`), or disable only those that you know you don't have.

**Comment by flashcode** [comment]
For the record, the iconv error was just in file `CMakeFiles/CMakeError.log` and is actually not blocking for compilation.
