### ISSUE TITLE
crash when trying to set background color in message

### ISSUE THREAD

**Issue by c-14** [weechat/weechat#1589]
## Bug summary

WeeChat crashes after entering the ',' when trying to specify a background color code.

## Steps to reproduce

1. /set spell.check.enabled on
2. /set spell.check.default_dict en (I don't think it's specific to the english dictionary, any should probably do)
3. /connect server
4. /join some_channel
5. ^C c 00,

## Current behavior

WeeChat crashes after entering the ',' in the color code

## Expected behavior

WeeChat doesn't crash, I can set a color code and it's correctly sent to the server

## Additional information

```
001  /home/radiocarbon/dev/foss/weechat/src/core/wee-backtrace.c:167 [function weechat_backtrace]
002  /home/radiocarbon/dev/foss/weechat/src/core/wee-debug.c:184 [function debug_sigsegv]
003  sigaction.c:? [function __restore_rt]
004  ??:? [function spell_skip_color_codes]
005  ??:? [function spell_modifier_cb]
006  /home/radiocarbon/dev/foss/weechat/src/core/hook/wee-hook-modifier.c:116 [function hook_modifier_exec]
007  /home/radiocarbon/dev/foss/weechat/src/gui/gui-bar-item.c:886 (discriminator 4) [function gui_bar_item_input_text_cb]
008  /home/radiocarbon/dev/foss/weechat/src/gui/gui-bar-item.c:400 [function gui_bar_item_get_value]
009  /home/radiocarbon/dev/foss/weechat/src/gui/gui-bar-window.c:611 [function gui_bar_window_content_build_item]
010  /home/radiocarbon/dev/foss/weechat/src/gui/gui-bar-window.c:667 [function gui_bar_window_content_get]
011  /home/radiocarbon/dev/foss/weechat/src/gui/gui-bar-window.c:739 [function gui_bar_window_content_get_with_filling]
012  /home/radiocarbon/dev/foss/weechat/src/gui/curses/gui-curses-bar-window.c:483 [function gui_bar_window_draw]
013  /home/radiocarbon/dev/foss/weechat/src/gui/gui-bar.c:579 [function gui_bar_draw]
014  /home/radiocarbon/dev/foss/weechat/src/gui/curses/gui-curses-main.c:447 (discriminator 2) [function gui_main_refreshes]
015  /home/radiocarbon/dev/foss/weechat/src/gui/curses/gui-curses-main.c:550 [function gui_main_loop]
016  /home/radiocarbon/dev/foss/weechat/src/gui/curses/normal/main.c:44 [function main]
017  ??:? [function __libc_start_main]
018  ??:? [function _start]
```
The GDB backtrace on the core dump is rather large, so I uploaded that as a [gist](https://gist.github.com/c-14/948ac68c5e3f78e4cc81d64b1766e13a)

---

- WeeChat version: 3.0 and latest git a2266e4e3f9
- OS, distribution and version: Linux, Gentoo (rolling release)
- Terminal: rxvt-unicode
- Terminal multiplexer (screen/tmux/…/none): none

**Comment by flashcode** [comment]
This is annoying when such bug is introduced in the latest "stable" release (2.9 has no problem with such color codes, it was introduced by the fix of the issue #1547). :confused: 

If the release process was quick and automatic I would release a 3.0.1 now.
I'll wait a bit to check if other problems are detected on version 3.0 and then release a 3.0.1.

**Comment by flashcode** [comment]
@c-14: and I forgot to thank you for reporting this crash!

I was able to reproduce only by building with the address sanitizer (I suppose crash was somewhat random).

**Comment by c-14** [comment]
Thanks for the fix, that appears to have fixed the issue (once I got weechat to load the new spell.so instead of the old one)
