### ISSUE TITLE
Non-headless weechat should not reload on SIGHUP

### ISSUE THREAD

**Issue by ncfavier** [weechat/weechat#1595]
#1478 is actually a problem for me, because tmux sends SIGHUP to its child processes when a session is closed. My use case is running weechat in a persistent tmux session in a systemd service, and right now when I `systemctl stop` that service, weechat gets SIGHUP and reloads its config before saving.

I think we should either make it SIGUSR1/2 instead, or make this behaviour configurable, or only do this for weechat-headless as originally requested in #1476.

**Comment by trygveaa** [comment]
Note that this isn't specific to tmux. All terminal emulators send SIGHUP when they are closed. So if you close a terminal emulator with WeeChat now, the configuration is not saved.

> only do this for weechat-headless as originally requested in #1476.

This is probably the best solution (alternatively in combination with SIGUSR1/2), because that's how other programs usually behave. I.e. daemons reload, while interactive programs exit.

**Comment by ncfavier** [comment]
> Note that this isn't specific to tmux. All terminal emulators send SIGHUP when they are closed. So if you close a terminal emulator with WeeChat now, the configuration is not saved.

That doesn't seem to be the case for me with urxvt.

**Comment by trygveaa** [comment]
What part, urxvt not sending SIGHUP or WeeChat not saving the configuration? How did you test it?

**Comment by ncfavier** [comment]
I changed some configuration value from urxvt, closed the window, reopened weechat, the value was still modified. The same test with xterm shows the value rolled back to its previous setting.

**Comment by trygveaa** [comment]
Hm, if I change a value in WeeChat and close urxvt, the change is not saved. This script also confirms that urxvt sends SIGHUP when it is closed:

```
trap "echo got sighup > /tmp/sighup-test" SIGHUP
sleep 60
```

**Comment by ncfavier** [comment]
Yup, that also confirms it for me. Weird. I'll look into this tomorrow.

**Comment by ncfavier** [comment]
OK, a few updates:

- Terminals don't send SIGHUP, the kernel does when the controlling terminal goes missing. So it happens with urxvt just like it happens with xterm.
- I can't reliably reproduce what I observed yesterday (config changes being saved after closing urxvt). The behaviour occurs about once every 10 times, so I guess there must be some sort of race condition at play.

This is all unrelated to the issue I opened, of course.

**Comment by ncfavier** [comment]
OK, a few updates:

- [urxvt sends SIGHUP](https://github.com/exg/rxvt-unicode/blob/master/src/main.C#L206) just like xterm does. (Ignore the first version of this comment, I jumped to conclusions.)
- I can't reliably reproduce the behaviour I observed yesterday (config changes being saved when closing urxvt). It occurs about one in 10 times, so I guess there must be some sort of race condition at play.

This is unrelated to the issue I opened, of course.

**Comment by flashcode** [comment]
Hi,

I'm thinking about a flexible way to customize commands on signals received (not only SIGHUP), with different default values for `weechat` and `weechat-headless` binaries.

For example the default commands could be (`SIGUSR1` and `SIGUSR2` are new):

Binary           | Signal  | Default command
---------------- | ------- | ---------------
weechat          | SIGUSR1 | (none)
weechat          | SIGUSR2 | (none)
weechat          | SIGHUP  | (none)
weechat          | SIGQUIT | `/quit -yes`
weechat          | SIGTERM | `/quit -yes`
weechat-headless | SIGUSR1 | (none)
weechat-headless | SIGUSR2 | (none)
weechat-headless | SIGHUP  | `/reload`
weechat-headless | SIGQUIT | `/quit -yes`
weechat-headless | SIGTERM | `/quit -yes`

Since any command can be used, you can for example use the `/upgrade` command on a SIGHUP signal.

Note: there's also the `SIGWINCH` signal handled by WeeChat when the terminal is resized, but I'm not sure customizing this one is useful.

What do you think?

**Comment by ncfavier** [comment]
Sounds good!

**Comment by trygveaa** [comment]
> weechat | SIGHUP | (none)

weechat should run `/quit -yes` on SIGHUP too, otherwise it will terminate non-gracefully like it does now when it looses its terminal.

Apart from that it sounds good, though maybe a bit overkill.

**Comment by ncfavier** [comment]
Actually I think it exits gracefully now if the terminal is lost:

https://github.com/weechat/weechat/blob/b2d1f37782fad795855eb6380a439919c160158d/src/gui/curses/gui-curses-key.c#L534-L545

**Comment by trygveaa** [comment]
Hm, why isn't the config saved then?

**Comment by ncfavier** [comment]
Because the reloading logic happens *before* the terminal is lost. So the config is first reloaded, then saved.

**Comment by trygveaa** [comment]
Ah, that makes sense. Then I guess it wouldn't matter much in practice if weechat quits or does nothing on SIGHUP. For consistency with other programs it's still probably better to quit though.

**Comment by ifohancroft** [comment]
For me, currently, on Weechat 3.0.1, when running in XTerm(366) by assigning a keyboard shortcut to 'xterm -class weechat -xrm "xterm*iconHint: weechat" -e weechat', Weechat doesn't close on SIGHUP, it just reloads the config. What's the current state of things? Like is this supposed to happen?

**Comment by ncfavier** [comment]
That's what this issue is about.

**Comment by ifohancroft** [comment]
> That's what this issue is about.

Reading it, at first, I got the impression that this is no longer the case, but I believe I misread. I'd look into it, see if I can implement the fix and I'll open a PR if I succeeded.

**Comment by ncfavier** [comment]
@flashcode Any progress on this?

**Comment by ifohancroft** [comment]
Opened a PR #1617 with a fix. If running as headless or daemon, the config should be reloaded on SIGHUP, otherwise Weechat should exit.

**Comment by flashcode** [comment]
Thanks @ifohancroft for the PR, but the purpose of my proposal is to add a completely new way to customize the signals in WeeChat, with a different behavior for headless binary.

I schedule this for WeeChat 3.2.

**Comment by flashcode** [comment]
So here's what will be implemented and this shows the difference between the old and new behavior for each signal and WeeChat binary:

Binary           | Signal  | Old behavior | New behavior
---------------- | ------- | --------------- | ---------------
weechat          | SIGUSR1 | _Not available_ | (none)
weechat          | SIGUSR2 | _Not available_ | (none)
weechat          | SIGHUP  | `/reload` | (none, change asked by this issue)
weechat          | SIGQUIT | `/quit -yes` | `/quit -yes`
weechat          | SIGTERM | `/quit -yes` | `/quit -yes`
weechat-headless | SIGUSR1 | _Not available_ | (none)
weechat-headless | SIGUSR2 | _Not available_ | (none)
weechat-headless | SIGHUP  | `/reload`  | `/reload`
weechat-headless | SIGQUIT | `/quit -yes` | `/quit -yes`
weechat-headless | SIGTERM | `/quit -yes` | `/quit -yes`

Unlike what is proposed by PR #1617, I propose to have no action on SIGHUP for `weechat` binary. If terminal is lost, WeeChat should already quit in a clean way (as mentioned by comments above).

**Comment by trygveaa** [comment]
@flashcode: As mentioned by @ifohancroft, xterm doesn't close when you try to close it when run it with `xterm -e weechat` and weechat doesn't quit on SIGHUP. So I don't think you can rely on falling back to the terminal being lost, I think you have to close weechat on SIGHUP. Any reason you don't want to do that?

**Comment by ncfavier** [comment]
I agree with @trygveaa. Note that the default action for unhandled SIGHUP is to terminate the process.

**Comment by flashcode** [comment]
@trygveaa: the legacy behavior (before WeeChat 2.9) was to quit. You're right, I can restore this behavior by default.

Which gives:

Binary           | Signal  | Old behavior | New behavior
---------------- | ------- | --------------- | ---------------
weechat          | SIGUSR1 | _Not available_ | (none)
weechat          | SIGUSR2 | _Not available_ | (none)
weechat          | SIGHUP  | `/reload` | `/quit -yes` (change asked by this issue, behavior of WeeChat ≤ 2.8)
weechat          | SIGQUIT | `/quit -yes` | `/quit -yes`
weechat          | SIGTERM | `/quit -yes` | `/quit -yes`
weechat-headless | SIGUSR1 | _Not available_ | (none)
weechat-headless | SIGUSR2 | _Not available_ | (none)
weechat-headless | SIGHUP  | `/reload`  | `/reload`
weechat-headless | SIGQUIT | `/quit -yes` | `/quit -yes`
weechat-headless | SIGTERM | `/quit -yes` | `/quit -yes`

**Comment by flashcode** [comment]
By the way I wonder if `weechat-headless` (running in foreground without interface) should have a different behavior from `weechat-headless --daemon` (running in background)?

In foreground the behavior could be the same as `weechat`, ie quit on SIGHUP?

**Comment by ncfavier** [comment]
I don't think that's a good idea: one may want to run `weechat-headless` in the foreground inside a systemd service, leaving the daemonising to systemd. It should still behave as a daemon then.

**Comment by ncfavier** [comment]
I guess we could test whether we're running as a daemon by checking whether stdin is a terminal, or something like that.

**Comment by flashcode** [comment]
But I think you're right, the condition could just be if `weechat-headless` is executed, whatever it's a daemon or not.
It does not make really sense to run `weechat-headless` in foreground (in a real terminal), except for testing purposes.

**Comment by flashcode** [comment]
So I'm adding these 5 options (evaluated when they are used by WeeChat):

Option | Type | Default value
--- | --- | ---
weechat.signal.sighup | string | `${if:${info:weechat_headless}?/reload:/quit -yes}`
weechat.signal.sigquit | string | `/quit -yes`
weechat.signal.sigterm | string | `/quit -yes`
weechat.signal.sigusr1 | string | (empty string)
weechat.signal.sigusr2 | string | (empty string)

When a signal SIGHUP / SIGQUIT / SIGTERM / SIGUSR1 / SIGUSR2 is received:

1. Send WeeChat signal `signal_xxx` (for example `signal_sighup`). If return code is `WEECHAT_RC_OK_EAT`, we stop here.
2. Command defined in option is evaluated. If evaluated command is empty, we stop here.
3. Multiple commands are split on semicolon separator.
4. All commands are executed on core buffer.

Note: I'm also adding an info `weechat_daemon` which is `1` if running in headless **and** daemon mode (in addition to `weechat_headless` which is `1` if running in headless mode, daemonized or not).

**Comment by ifohancroft** [comment]
> It does not make really sense to run `weechat-headless` in foreground (in a real terminal), except for testing purposes.

I'd like to disagree with that.

I feel like there are many times and reasons you might run something in a real terminal yourself and later foreground it and/or just leave it be or daemonize it (if possible to be done later), which if you expect the headless to behave like the daemon does, you won't have an option other than to quit it and restart it as a daemon. So I'd like to propose the following, which I believe will save development time and would make for sane defaults:

- normal should run how @flashcode has proposed it should run in WeeChat ≥ 3.2
- headless (foreground) and headless daemon (background) show run how @flashcode has currently proposed headless daemon (background) should work in WeeChat ≥ 3.2

Then with what would be the newly added ability to change the behavior for the different signals in each state, you can change headless (foreground) to behave differently from daemon if you need to. I feel like this way, there would be less cases of needing to change headless (foreground) than if headless (foreground) and daemon behave differently.

**Comment by flashcode** [comment]
@ifohancroft: so you agree with my proposal which is `${if:${info:weechat_headless}?/reload:/quit -yes}` for sighup? (ie reload config if you're in headless mode, daemon or not).

For headless and daemon, the info reflect the state of 2 internal variables:

- `weechat_headless`: true if the binary `weechat-headless` is running (daemon or not)
- `weechat_daemon`: true if `weechat-headless` is running with `--daemon` (this option is only available with `weechat-headless` binary, that means if it's true, that means `weechat_headless` is true as well)

So you can check if WeeChat is headless in foreground (no daemon) with this condition: `${weechat_headless} && !${weechat_daemon}`.

The new info `weechat_daemon` is there just in case for example in headless mode without daemon you want to quit, like the normal mode, instead of reloading configuration. That's not default, but you are able to setup like this.

I think your comment says this proposal is OK for you, am I right?

**Comment by ifohancroft** [comment]
> @ifohancroft: so you agree with my proposal which is `${if:${info:weechat_headless}?/reload:/quit -yes}` for sighup? (ie reload config if you're in headless mode, daemon or not).

Yes. This seems perfect.


> For headless and daemon, the info reflect the state of 2 internal variables:
> 
>     * `weechat_headless`: true if the binary `weechat-headless` is running (daemon or not)
> 
>     * `weechat_daemon`: true if `weechat-headless` is running with `--daemon` (this option is only available with `weechat-headless` binary, that means if it's true, that means `weechat_headless` is true as well)
> 
> 
> So you can check if WeeChat is headless in foreground (no daemon) with this condition: `${weechat_headless} && !${weechat_daemon}`.
> 
> The new info `weechat_daemon` is there just in case for example in headless mode without daemon you want to quit, like the normal mode, instead of reloading configuration. That's not default, but you are able to setup like this.
> 
> I think your comment says this proposal is OK for you, am I right?

Sorry, I misunderstood something and I thought there is a second weechat_daemon variable that is 1 only when weechat_headless and weechat_daemon are 1.

What you are describing sounds perfect to me.
