### ISSUE TITLE
weechat.hook_modifier not executing callback on relay

### ISSUE THREAD

**Issue by soratobukuroneko** [weechat/weechat#1596]
## Question

I'm learning to write script for weechat and I want to intercept every privatemsg and modify them.
I'm running weechat-headless as a relay and using glowing bear and weechat android as clients.

To read the messages, I can successfully use `hook_signal on *,irc_in2_privmsg`. But with weechat.hook_modifier, the callback seems to be never executed. I have the following minimal code:

```python
import weechat

SCRIPT_NAME = "Test"
SCRIPT_AUTHOR = "me"
SCRIPT_VERSION = "0"
SCRIPT_LICENCE = "WTFPL"
SCRIPT_DESCRIPTION = "Prepend > to incoming messages"

def on_privmsg(data, modifier, modifier_data, string):
	weechat.prnt("on_privmsg")
	string = "> " + string
	return string

weechat.register(SCRIPT_NAME, SCRIPT_AUTHOR, SCRIPT_VERSION, SCRIPT_LICENCE,
	SCRIPT_DESCRIPTION, "", "")
weechat.hook_modifier("*,irc_in2_privmsg", "on_privmsg", "")
```

the `weechat.prnt("on_privmsg")` is never executed, or at least I don't see anything in the weechat buffer.

---

- WeeChat version: 3.0
- OS, distribution and version: Linux Ubuntu 20.10

**Comment by flashcode** [comment]
Hi,

The arguments for `weechat.prnt` are: buffer, message. So here `"on_privmsg"` is considered as a buffer and is invalid and then nothing is displayed.

You could try this to display the message on core buffer (with an empty string, WeeChat displays on core buffer):

    weechat.prnt("", "on_privmsg")
