### ISSUE TITLE
Fails to build with ruby 3 and latest clang: '__declspec' attributes are not enabled

### ISSUE THREAD

**Issue by iMichka** [weechat/weechat#1605]
## Bug summary

Homebrew maintainer here. weechat fails to build with latest clang and ruby 3.
The error is:
`'__declspec' attributes are not enabled`

The fix is to add the `-fdeclspec` flag to CMAKE_C_FLAGS when clang is used.

## Steps to reproduce

1. Run cmake and make on a latest Mac OS.

## Current behavior

Fails to build

## Expected behavior

Build without failure

## Suggested solutions

Add `-fdeclspec` flag to CMAKE_C_FLAGS, maybe only conditionally.

## Additional information

`vim` for example fixed it like this:
https://github.com/vim/vim/commit/864a28b6a6ae4f1a56e230be26bc6d13e3f8b3d9

Related issues:
https://github.com/Homebrew/homebrew-core/pull/67898
https://github.com/Homebrew/homebrew-core/pull/67676

---

- WeeChat version: 3/0
- OS, distribution and version: macOS Big Sur
- Terminal:all
- Terminal multiplexer (screen/tmux/…/none): none

**Comment by flashcode** [comment]
Thanks for the issue.
For now, WeeChat can not compile with Ruby 3.0.
As soon as this version is available in Debian uunstable I'll make tests with WeeChat (to ensure everything is OK in the API) and fix the compilation with clang.

**Comment by flashcode** [comment]
Ruby 3.0 support has just been added in WeeChat, and for your information, I'll preferably add flag "-fms-extensions" which is compatible with gcc as well and works everywhere.
