### ISSUE TITLE
Relay configuration

### ISSUE THREAD

**Issue by ArchontPL** [weechat/weechat#1606]
Is this possible to configure Weechat as IRC Relay in order to read old messages (which were received by i.e. VPS), just like it is when using weechat protocole (with i.e. Android app)? Currently I'm able just to rejoin to channel using IP of VPS, but I cannot read old messages.

**Comment by flashcode** [comment]
Hi @ArchontPL,

There are some settings for IRC Relay backlog, you can browse them with `/fset relay.irc`.
