### ISSUE TITLE
There is no option to override set irc.server_default.proxy

### ISSUE THREAD

**Issue by Mikaela** [weechat/weechat#1608]
## Bug summary

When `irc.server_default.proxy` is set, a network cannot be connected without proxy.

## Steps to reproduce

1. `/proxy add tor socks5 127.0.0.1 9050 WeeChatarhyq3146 WeeChat24615`
2. `/set  irc.server_default.proxy tor`
3. `/server add localhost 127.0.0.1/6667 -nossl`

## Current behavior

Connection to 127.0.0.1 fails as `irc.server.localhost.proxy` is `null` and gets mapped into `tor` and there is no option to not use proxy.

## Expected behavior

127.0.0.1 can be connected with or without proxy.

## Suggested solutions

* Option to set addresses where to not use proxy
* A pseudo `/proxy` which when set means no proxy is used.

## Additional information

I would like to use Tor everywhere by default excluding it only for scenarios such as localhost.

---

- WeeChat version: WeeChat 3.0 [compiled on Nov 11 2020 10:54:44]
- OS, distribution and version: Debian GNU/Linux 10 (buster)
- Terminal: Windows Terminal Version: 1.4.3243.0
- Terminal multiplexer (screen/tmux/…/none): tmux

**Comment by flashcode** [comment]
Hi,

The `null` value inherits the value from the parent option (from `irc.server_default.xxx`), instead you can use "" (empty string), which forces to disable the proxy for a specific server.
