### ISSUE TITLE
add no_eval

### ISSUE THREAD

**Issue by pascalpoitras** [weechat/weechat#1611]
## Feature description

? and : have special meaning in ${if:...} so we run into problem when we use them for their literal sense.

`/eval -n ${if:https://=~https?://?yes:no}`

one way to fix this is to embed the condition in a ${eval:...} or a ${eval_cond:...}

```
/eval -n ${if:${eval:https://=~https?://}?yes:no}
/eval -n ${if:${eval_cond:https://=~https?://}?yes:no}
```

but ${eval:...} will add another level of indirection, so if the arguments to ${eval:...} contains a variable, that variable's content will also be evaluated

what would be nice would be something like ${no_eval:...} which only return the arguments without any modification. So for example

```
/set plugins.var.a ${plugins.var.b}
/set plugins.var.b hello
/eval -n ${no_eval:${plugins.var.a}}
```

will return ${plugins.var.b}

**Comment by flashcode** [comment]
I'll add `${raw:xxx}` which returns non-evaluated text `xxx`, eg: `/eval -n ${raw:${plugins.var.a}}` returns `${plugins.var.a}`.

**Comment by pascalpoitras** [comment]
as discussed with flashcode, ${raw:...} will not does what this issue describe

this is still great because when you escape a ${ nested in another ${, the } of the nested ${ (which is escaped) close the outter ${, for example, if you want to compute the length of the ${plugins.var.test}test (without evaluating plugins.var.test)
`
/eval -n ${length:\${plugins.var.test}test}`

will output 19test}

you must remplace the } after plugins.var.test to ${\x7d}

`/eval -n ${length:\${plugins.var.test${\x7d}test}`

with raw you should be able to do it instead:
`
/eval -n ${length:${raw:${plugins.var.test}test}`

**Comment by flashcode** [comment]
Yes, I confirm this will work like this.

**Comment by pascalpoitras** [comment]
in fact, we can even do what the issue was describing

`/eval -n ${eval:${raw:${plugins.var.a}}}`

will gives ${plugins.var.b}}}

**Comment by pascalpoitras** [comment]
the last eval in my comment doesn't work anymore with how ${if:...} now works, you now have to use eval_cond

so instead of 

`/eval -n ${if:${raw:https://=~https?://}?yes:no}`

use this

`/eval -n ${if:${eval_cond:https://=~https?://}?yes:no}`
