### ISSUE TITLE
relay's _buffer_moved/_buffer_merged only notifies the client of a single buffer movement

### ISSUE THREAD

**Issue by oakkitten** [weechat/weechat#162]
if i have buffers #1 and #2 and #3 and #4 and #6, and buffer #3 is merged to position 2, only get one message. it's not clear what i should do with other buffers, especially when buffers can have gaps. i.e. should i move bufer #4 to #3 in this case? and in case of movement, should i move buffer #6?

**Comment by azizLIGHT** [comment]
Workaround is to disconnect/reconnect w-a to weechat to get the updated buffer list
