### ISSUE TITLE
Add a way to save weechat sessions files

### ISSUE THREAD

**Issue by mumixam** [weechat/weechat#1630]
Add a way to save a weechat session file without upgrading the binary ```/upgrade``` or ```/upgrade -quit```

This would be a nice feature to have to be able to restore our weechat sessions in case of a crash or unexpected reboot (vps host maintence)

**Comment by flashcode** [comment]
I reverted the changes.
This is not so easy to implement: it requires saving state of plugins, and plugins like irc can not save the connected state (except in a real upgrade case where the sockets are still valid after exec of the new binary).

**Comment by flashcode** [comment]
Hi,

I'm working again on this topic, here's what I am implementing:

- Add of a parameter "-save" in command `/upgrade` to save the session without quitting (and with no disconnections from servers), like the first attempt (commit reverted).
- After `/upgrade -save`, files **.upgrade* are written in the WeeChat data directory (*~/.local/share/weechat* or the legacy directory *~/.weechat*). They can be used lated to restart WeeChat at this state with: `weechat --upgrade`.
- The session is saved and is transparent for the user (no disconnection, even with TLS connection): IRC servers and relay clients are saved in "disconnected state" (for the IRC servers, a reconnection is scheduled and happens immediately after the upgrade, ie the new start of WeeChat with `weechat --upgrade`).
- No major changes in Xfer plugin, the active chats and files are not yet saved in session file. The only change is to not disconnect any xfer (chat/file) on `/upgrade -save` (they are disconnected on `/upgrade` or `/upgrade -quit`).

**Comment by mumixam** [comment]
I have tested this a few times and everything seems to be working with no issues or crashes.

Thanks and great work.

**Comment by flashcode** [comment]
Hi,

Yes it works only with `/upgrade` (without parameters to upgrade now), because in this case the temporary servers are saved to config file irc.conf, but this is not the case when you quit manually WeeChat with `/quit` or even if you do `/save`.

I wonder if it would be better to completely remove the "temporary" server feature, ie when you `/connect` to an address, this creates a real server that is not temporary and is saved in all cases?

**Comment by JinxDojo** [comment]
Thank you for the detailed response. Unfortunately, any "add-then-remove" alternative method still saves the servers to a file (other than the session file), and a crash/reboot/power outage won't have a chance to run such a trigger. I wish the "re-associate method" had been possible.

My knowledge/understanding is not sufficient to propose another method that isn't equivalent to a "temporary server".

On a personal note: I'm used to mIRC where all servers were "temporary" unless saved in the servers dialog. I'm afraid the loss of temporary servers is probably a deal-breaker for me. I'll likely stick with an older version (or try to get a Windows server again so I can run mIRC 24-7 again). I've really tried to adapt to Weechat and I appreciate the work that you do and time that you take to help people, but, when I take a step back: "making things work for me" on Weechat has just taken far too much time/effort. Hopefully others (who are probably more experienced in Linux) have less trouble.

Thank you again for the work you do.
