### ISSUE TITLE
WeeChat autojoin sends JOIN message with no parameters

### ISSUE THREAD

**Issue by ChaiTRex** [weechat/weechat#1638]
## Bug summary

Weechat sends `JOIN` message with no parameters.

## Steps to reproduce

1. Set up WeeChat to connect to [Libera IRC](https://libera.chat/guides/connect).
2. `/set irc.server.libera.autojoin "#libera,#libera-offtopic,##math,##typetheory,##dependent,##categorytheory,##algorithms,#proglangdesign,##smt,##java,#haskell,#haskell-beginners,#numerical-haskell,##rust,##adventofcode,##adventofcode-help,##adventofcode-spoilers,##DinosaursEatingNachos"`
3. Connect to Libera Chat
4. Receive message that `JOIN: Not enough parameters`

## Current behavior

WeeChat autojoin sends one `JOIN` command with no parameters.

## Expected behavior

WeeChat autojoin sends one or more `JOIN` commands with autojoin channels.

## Additional information

Raw log:

<details>
<summary>More of connection log</summary>

    17:28:06   <-- libera │ CAP LS 302
    17:28:06   <-- libera │ NICK ChaiTRex
    17:28:06   <-- libera │ USER ChaiTRex 0 * :Chai T. Rex
    17:28:06   --> libera │ :ruthenium.libera.chat NOTICE * :*** Checking Ident
    17:28:06   --> libera │ :ruthenium.libera.chat NOTICE * :*** Looking up your hostname...
    17:28:06   --> libera │ :ruthenium.libera.chat NOTICE * :*** No Ident response
    17:28:06   --> libera │ :ruthenium.libera.chat NOTICE * :*** Couldn't look up your hostname
    17:28:06   --> libera │ :ruthenium.libera.chat CAP * LS :account-notify away-notify chghost extended-join multi-prefix sasl=PLAIN,ECDSA-NIST256P-CHALLENGE,EXTERNAL tls
                          │ userhost-in-names account-tag cap-notify echo-message solanum.chat/identify-msg solanum.chat/realhost
    17:28:06   <-- libera │ CAP REQ :sasl
    17:28:06   --> libera │ :ruthenium.libera.chat CAP ChaiTRex ACK :sasl
    17:28:06   <-- libera │ AUTHENTICATE EXTERNAL
    17:28:06   --> libera │ AUTHENTICATE +
    17:28:06   <-- libera │ AUTHENTICATE +
    17:28:06   --> libera │ :ruthenium.libera.chat 900 ChaiTRex ChaiTRex!ChaiTRex@user/chaitrex ChaiTRex :You are now logged in as ChaiTRex
    17:28:07   --> libera │ :ruthenium.libera.chat 903 ChaiTRex :SASL authentication successful
    17:28:07   <-- libera │ CAP END
    17:28:07   --> libera │ :ruthenium.libera.chat 001 ChaiTRex :Welcome to the Libera.Chat Internet Relay Chat Network ChaiTRex

</details>

    17:28:07   <-- libera │ JOIN

<details>
<summary>More of connection log</summary>

    17:28:07   --> libera │ :ruthenium.libera.chat 002 ChaiTRex :Your host is ruthenium.libera.chat[2a01:4f9:c011:417c::1/7000], running version solanum-1.0-dev
    17:28:07   --> libera │ :ruthenium.libera.chat 003 ChaiTRex :This server was created Thu May 20 2021 at 07:23:44 UTC
    17:28:07   --> libera │ :ruthenium.libera.chat 004 ChaiTRex ruthenium.libera.chat solanum-1.0-dev DGQRSZaghilopsuwz CFILMPQSbcefgijklmnopqrstuvz bkloveqjfI
    17:28:07   --> libera │ :ruthenium.libera.chat 005 ChaiTRex KNOCK SAFELIST ELIST=CTU WHOX CALLERID=g MONITOR=100 FNC ETRACE CHANTYPES=# EXCEPTS INVEX
                          │ CHANMODES=eIbq,k,flj,CFLMPQScgimnprstuz :are supported by this server
    17:28:07   --> libera │ :ruthenium.libera.chat 005 ChaiTRex CHANLIMIT=#:250 PREFIX=(ov)@+ MAXLIST=bqeI:100 MODES=4 NETWORK=Libera.Chat STATUSMSG=@+ CASEMAPPING=rfc1459 NICKLEN=16
                          │ MAXNICKLEN=16 CHANNELLEN=50 TOPICLEN=390 DEAF=D :are supported by this server
    17:28:07   --> libera │ :ruthenium.libera.chat 005 ChaiTRex TARGMAX=NAMES:1,LIST:1,KICK:1,WHOIS:1,PRIVMSG:4,NOTICE:4,ACCEPT:,MONITOR: EXTBAN=$,ajrxz CLIENTVER=3.0 :are supported by
                          │ this server
    17:28:07   --> libera │ :ruthenium.libera.chat 251 ChaiTRex :There are 31 users and 11945 invisible on 12 servers
    17:28:07   --> libera │ :ruthenium.libera.chat 252 ChaiTRex 30 :IRC Operators online
    17:28:07   --> libera │ :ruthenium.libera.chat 253 ChaiTRex 7 :unknown connection(s)
    17:28:07   --> libera │ :ruthenium.libera.chat 254 ChaiTRex 10757 :channels formed
    17:28:07   --> libera │ :ruthenium.libera.chat 255 ChaiTRex :I have 195 clients and 1 servers
    17:28:07   --> libera │ :ruthenium.libera.chat 265 ChaiTRex 195 198 :Current local users 195, max 198
    17:28:07   --> libera │ :ruthenium.libera.chat 266 ChaiTRex 11976 12190 :Current global users 11976, max 12190
    17:28:07   --> libera │ :ruthenium.libera.chat 250 ChaiTRex :Highest connection count: 199 (198 clients) (858 connections received)
    17:28:07   --> libera │ :ruthenium.libera.chat 375 ChaiTRex :- ruthenium.libera.chat Message of the Day -
    17:28:07   --> libera │ :ruthenium.libera.chat 372 ChaiTRex :- Welcome to libera.chat, the IRC network for free & open-source software
    17:28:07   --> libera │ :ruthenium.libera.chat 372 ChaiTRex :- and peer directed projects.
    17:28:07   --> libera │ :ruthenium.libera.chat 372 ChaiTRex :-
    17:28:07   --> libera │ :ruthenium.libera.chat 372 ChaiTRex :- Please visit us in #libera for questions and support.
    17:28:07   --> libera │ :ruthenium.libera.chat 376 ChaiTRex :End of /MOTD command.
    17:28:07   --> libera │ :ChaiTRex MODE ChaiTRex :+RZi
    17:28:07   --> libera │ :SaslServ!SaslServ@services.libera.chat NOTICE ChaiTRex :Last login from: \x02~ChaiTRex@[REDACTED]\x02 on May 20 21:28:05 2021 +0000.

</details>

    17:28:13   --> libera │ :ruthenium.libera.chat 461 ChaiTRex JOIN :Not enough parameters

---

- WeeChat version: 3.1-1 (from https://weechat.org/ubuntu)
- OS, distribution and version: Ubuntu 18.04.5 LTS
- Terminal: xfce4-terminal to Mosh to tmux to bash to WeeChat
- Terminal multiplexer (screen/tmux/…/none): tmux

**Comment by trygveaa** [comment]
I can't reproduce. I followed your steps and it works fine for me.

**Comment by ChaiTRex** [comment]
Apparently it was intermittent. Restarting WeeChat seems to have resolved it.

**Comment by ksu-0** [comment]
I am not sure this it is the same issue, but here are steps to reproduce:

- `/connect` to a server
- `/join` a channel
- `/part` all channels
- `/disconnect`
- `/connect` again

The bug was introduced by commit `0cc5df664955cafab8334d7abc3dfd6dc8bc77cd`.
