### ISSUE TITLE
cmake configuration error in ubuntu 20.04

### ISSUE THREAD

**Issue by m4v** [weechat/weechat#1639]
- WeeChat version: 3.1 and 3.2-dev
- OS, distribution and version: Ubuntu 20.04.2 LTS
- Terminal: gnome-terminal
- Terminal multiplexer (screen/tmux/…/none): none 

Trying to configure with cmake fails with an error I can't solve, using autotools works and I was able to compile weechat.

Output of "cmake .."

> ╭─m4v at deimos in ~/dev/src/weechat/weechat-3.1/build-cmake 
> ╰─○ cmake ..      
> -- The C compiler identification is GNU 9.3.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Looking for include file langinfo.h
> -- Looking for include file langinfo.h - found
> -- Looking for include file sys/resource.h
> -- Looking for include file sys/resource.h - found
> -- Looking for mallinfo
> -- Looking for mallinfo - found
> -- Looking for eat_newline_glitch
> -- Looking for eat_newline_glitch - found
> -- Looking for include file libintl.h
> -- Looking for include file libintl.h - found
> -- Looking for dgettext
> -- Looking for dgettext - found
> -- Found Intl: /usr/include  
> -- Found GCRYPT: -L/usr/lib/x86_64-linux-gnu -lgcrypt  
> -- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
> -- Looking for iconv_open
> -- Looking for iconv_open - found
> -- Performing Test ICONV_2ARG_IS_CONST
> -- Performing Test ICONV_2ARG_IS_CONST - Failed
> -- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.68.0")  
> -- Looking for flock
> -- Looking for flock - found
> -- Looking for backtrace
> -- Looking for backtrace - found
> -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
> -- Checking for module 'python3-embed'
> --   Found python3-embed, version 3.8
> -- Checking for one of the modules 'ruby-2.7;ruby-2.6;ruby-2.5;ruby-2.4;ruby-2.3;ruby-2.2;ruby-2.1;ruby-2.0;ruby-1.9'
> CMake Error at src/plugins/CMakeLists.txt:116 (message):
>   Ruby not found
> 
> 
> -- Checking for one of the modules 'lua5.3;lua-5.3;lua53;lua5.2;lua-5.2;lua52;lua5.1;lua-5.1;lua51;lua-5.0;lua5.0;lua50;lua'
> CMake Error at src/plugins/CMakeLists.txt:125 (message):
>   Lua not found
> 
> 
> -- Found Tclsh: /bin/tclsh (found version "8.6") 
> -- Could NOT find TCL (missing: TCL_INCLUDE_PATH) 
> -- Could NOT find TCLTK (missing: TCL_INCLUDE_PATH TK_INCLUDE_PATH) 
> -- Could NOT find TK (missing: TK_INCLUDE_PATH) 
> CMake Error at src/plugins/CMakeLists.txt:134 (message):
>   Tcl not found
> 
> 
> -- Checking for one of the modules 'guile-3.0;guile-2.2;guile-2.0'
> CMake Error at src/plugins/CMakeLists.txt:143 (message):
>   Guile not found
> 
> 
> -- Checking for one of the modules 'php7'
> CMake Warning at cmake/FindPHP.cmake:61 (message):
>   Could not find libphp7.  Ensure PHP >=7.0.0 development libraries are
>   installed and compiled with `--enable-embed`.  Ensure `php-config` is in
>   `PATH`.  You may set `-DCMAKE_LIBRARY_PATH=...` to the directory containing
>   libphp7.
> Call Stack (most recent call first):
>   src/plugins/CMakeLists.txt:157 (find_package)
> 
> 
> CMake Error at src/plugins/CMakeLists.txt:161 (message):
>   Php not found
> 
> 
> -- Looking for aspell_version_string
> -- Looking for aspell_version_string - found
> -- Checking for one of the modules 'ncursesw'
> -- Looking for include file ncursesw/ncurses.h
> -- Looking for include file ncursesw/ncurses.h - found
> -- Configuring incomplete, errors occurred!
> See also "/home/m4v/dev/src/weechat/weechat-3.1/build-cmake/CMakeFiles/CMakeOutput.log".
> See also "/home/m4v/dev/src/weechat/weechat-3.1/build-cmake/CMakeFiles/CMakeError.log".

[CMakeError.log](https://github.com/weechat/weechat/files/6519187/CMakeError.log)
[CMakeOutput.log](https://github.com/weechat/weechat/files/6519188/CMakeOutput.log)

If I try in current master branch I get a similar error:

> ╭─m4v at deimos in ~/dev/src/weechat/client/build-master on master✔ 
> ╰─± cmake ..       
> -- The C compiler identification is GNU 9.3.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Looking for include file langinfo.h
> -- Looking for include file langinfo.h - found
> -- Looking for include file sys/resource.h
> -- Looking for include file sys/resource.h - found
> -- Looking for mallinfo
> -- Looking for mallinfo - found
> -- Looking for mallinfo2
> -- Looking for mallinfo2 - not found
> -- Looking for eat_newline_glitch
> -- Looking for eat_newline_glitch - found
> -- Looking for include file libintl.h
> -- Looking for include file libintl.h - found
> -- Looking for dgettext
> -- Looking for dgettext - found
> -- Found Intl: /usr/include  
> -- Found GCRYPT: -L/usr/lib/x86_64-linux-gnu -lgcrypt  
> -- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
> -- Looking for iconv_open
> -- Looking for iconv_open - found
> -- Performing Test ICONV_2ARG_IS_CONST
> -- Performing Test ICONV_2ARG_IS_CONST - Failed
> -- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.68.0")  
> -- Looking for flock
> -- Looking for flock - found
> -- Looking for backtrace
> -- Looking for backtrace - found
> -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
> -- Checking for module 'python3-embed'
> --   Found python3-embed, version 3.8
> -- Checking for one of the modules 'ruby-2.7;ruby-2.6;ruby-2.5;ruby-2.4;ruby-2.3;ruby-2.2;ruby-2.1;ruby-2.0;ruby-1.9'
> CMake Error at src/plugins/CMakeLists.txt:116 (message):
>   Ruby not found
> 
> 
> -- Checking for one of the modules 'lua5.3;lua-5.3;lua53;lua5.2;lua-5.2;lua52;lua5.1;lua-5.1;lua51;lua-5.0;lua5.0;lua50;lua'
> CMake Error at src/plugins/CMakeLists.txt:125 (message):
>   Lua not found
> 
> 
> -- Found Tclsh: /bin/tclsh (found version "8.6") 
> -- Could NOT find TCL (missing: TCL_INCLUDE_PATH) 
> -- Could NOT find TCLTK (missing: TCL_INCLUDE_PATH TK_INCLUDE_PATH) 
> -- Could NOT find TK (missing: TK_INCLUDE_PATH) 
> CMake Error at src/plugins/CMakeLists.txt:134 (message):
>   Tcl not found
> 
> 
> -- Checking for one of the modules 'guile-3.0;guile-2.2;guile-2.0'
> CMake Error at src/plugins/CMakeLists.txt:143 (message):
>   Guile not found
> 
> 
> -- Checking for one of the modules 'php7'
> CMake Warning at cmake/FindPHP.cmake:61 (message):
>   Could not find libphp7.  Ensure PHP >=7.0.0 development libraries are
>   installed and compiled with `--enable-embed`.  Ensure `php-config` is in
>   `PATH`.  You may set `-DCMAKE_LIBRARY_PATH=...` to the directory containing
>   libphp7.
> Call Stack (most recent call first):
>   src/plugins/CMakeLists.txt:157 (find_package)
> 
> 
> CMake Error at src/plugins/CMakeLists.txt:161 (message):
>   Php not found
> 
> 
> -- Looking for aspell_version_string
> -- Looking for aspell_version_string - found
> -- Checking for one of the modules 'ncursesw'
> -- Looking for include file ncursesw/ncurses.h
> -- Looking for include file ncursesw/ncurses.h - found
> -- Configuring incomplete, errors occurred!
> See also "/home/m4v/dev/src/weechat/client/build-master/CMakeFiles/CMakeOutput.log".
> See also "/home/m4v/dev/src/weechat/client/build-master/CMakeFiles/CMakeError.log".

[CMakeError.log](https://github.com/weechat/weechat/files/6519204/CMakeError.log)
[CMakeOutput.log](https://github.com/weechat/weechat/files/6519205/CMakeOutput.log)

Again using autotools.sh and configure works.

**Comment by flashcode** [comment]
Hi @m4v,

You should consider CMake is the right behavior here.

Since version 2.7, with CMake, any missing dependency is now an error, so you have to explicitly disable the missing dependency, for example to disable PHP plugin:

    cmake .. -DENABLE_PHP=OFF

See #916 and #956 for more information.
This was done like this to not surprise users where everything can be compiled but once you run WeeChat, you notice many plugins are missing because they were not found, and just a warning was displayed by CMake, that you can miss.

I think this hasn't been done in configure script, it should be done here as well, but autotools will be removed one day and is NOT the recommended way to compile WeeChat any more since 10+ years now.

I keep this issue open, but the bug is in configure, not CMake files.

**Comment by m4v** [comment]
I see, it wasn't immediately obvious to me that I had to disable the optional plugins to get it to work. 

It works now.
