### ISSUE TITLE
Command splitting must be done before evaluation

### ISSUE THREAD

**Issue by RaitoBezarius** [weechat/weechat#1643]
## Bug summary

Command splitting is done after expansion of variables, therefore, if your password contains a `;`, it fails to send the password completely and consider it as another command.

## Steps to reproduce

1. Set for example: `/oper Raito ${sec.data.password}`
2. Set `/secure set password a;b;c`
3. See that `/oper Raito a; b; c` gets sent as separate commands.

## Current behavior

Commands are split after evaluation.

## Expected behavior

Commands are split before evaluation, according to @flashcode

## Suggested solutions

Split must be done before evaluation.

---

- WeeChat version: 3.0
- OS, distribution and version: NixOS unstable
- Terminal: kitty
- Terminal multiplexer (screen/tmux/…/none): tmux

**Comment by flashcode** [comment]
As a side note, there is the same problem there, that must be fixed:

- Evaluation of commands on startup (`weechat --run-command …`')
- Commands executed when a signal is received (options `weechat.signal.*`).

**Comment by flashcode** [comment]
Done!
