### ISSUE TITLE
Mouse suddenly get disabled

### ISSUE THREAD

**Issue by danisztls** [weechat/weechat#1644]
## Bug summary
Mouse suddenly get disable when browsing fset options. AFAIK only happened at fset buffer and it happens frequently. And as I'm using vimode-plugin, I have to manually edit the config to reenable it.

## Steps to reproduce
Browse fset options with mouse.

## Current behavior
`weechat.look.mouse` is set to off on config.

## Expected behavior
Nothing happens.

---

- WeeChat version: 3.1
- OS, distribution and version: Arch Linux 
- Terminal: alacritty
- Terminal multiplexer (screen/tmux/…/none): tmux

**Comment by weechatter** [comment]
I can not reproduce. Try without vimode script, if its still happening.

**Comment by flashcode** [comment]
@danisztls: did you press `alt-m` by mistake?
WeeChat itself never disables mouse withtou an explicit action such as default key `alt-m`, which toggles mouse.

**Comment by danisztls** [comment]
Thanks @weechatter @flashcode I haven't had problems since I disabled vimode. Probably was `alt-m`. Which I unsucessfuly tried to use to reenable and later disable mouse.  On normal and command mode it doesn't work but apparently it would work on insert mode which I didn't expected.
