### ISSUE TITLE
Support for message-tags / TAGMSG

### ISSUE THREAD

**Issue by Mikaela** [weechat/weechat#1654]
## Feature description

* https://ircv3.net/specs/extensions/message-tags

I have heard it said that supporting message-tags only requires the client to not crash upon getting weird messages from the server and in that sense, WeeChat already supports them and `server-time` is supported.

Using WeeChat + [Ergo IRCd](https://ergo.chat/) I am mainly seeing these tags in server buffer

* `draft/typing` sent by KiwiIRC users
* `draft/react` sent by Palaver users

```
2021-153 12:46:02 EEST =!= irc: command "TAGMSG" not found:
2021-153 12:46:02 EEST =!= @time=2021-06-02T09:46:02.975Z;account=Mikaela;msgid=jzpyq4ek9t64jsum3bsrasdm62;+draft/reply=7zxciyew7igmfvtqjxj9qvt9ta;+draft/react=👍 :Mikaela!~u@mikaela.info TAGMSG #test
...
2021-153 12:57:34 EEST =!= irc: command "TAGMSG" not found:
2021-153 12:57:34 EEST =!= @time=2021-06-02T09:57:34.093Z;msgid=b37wswrnbycfpneiu5pmzetzys;+draft/typing=active :kiwi-n13!~u@faniae4cabq6w.etro TAGMSG #test
2021-153 12:57:36 EEST =!= irc: command "TAGMSG" not found:
2021-153 12:57:36 EEST =!= @time=2021-06-02T09:57:36.095Z;msgid=jretmkspqh65inb4iufath7zde;+draft/typing=active :kiwi-n13!~u@faniae4cabq6w.etro TAGMSG #test
```

I need to keep `message-tags` enabled regardless of their support status so that in `/server raw` I will see the `msgid`s that can be used for removing messages from server-side storage of Ergo using HistServ. `2021-153 13:12:55 EEST --> etro @account=R-66Y;msgid=ev3bkg4ygz2a65u7t5jgim2b5a;draft/bot;time=2021-06-02T10:12:55.832Z :R-66Y!~u@limnoria.mikaela.info PRIVMSG #test :pong`

* WeeChat 3.2-dev (git: v3.1-186-gf8872c415) [compiled on Jun 1 2021 23:07:55]
* Debian GNU/Linux 11 (bullseye)

Related: https://github.com/weechat/weechat/issues/1422 possibly https://github.com/weechat/weechat/issues/1619

**Comment by flashcode** [comment]
I'm scheduling this for v3.3.

In addition, this should be added/changed for a complete support of `message-tags`:

- escape/unescape values of tags (currently not done)
- client-only tags must be put after server tags
- add a new command `/tagmsg` (is this really needed?)
- take care about specific case for length of tags in the whole IRC message size limit
- read CLIENTTAGDENY from RPL_ISUPPORT (005)
