### ISSUE TITLE
Invalid cross-device link errors when installing scripts inside Firejail

### ISSUE THREAD

**Issue by ilmaisin** [weechat/weechat#1667]
## Bug summary

When using a firejail with a restrictive profile, it is impossible to load scripts, since ~/.local and ~./cache might be on different devices

## Steps to reproduce

1. Set up a firejail with following profile:
```
whitelist ~/.config/weechat
whitelist ~/.cache/weechat
whitelist ~/.local/share/weechat
```
2. Run weechat in firejail
3. Try to load a Python script

## Current behavior

One gets error message `python: failed to move script /home/il/.cache/weechat/script/autojoin.py to /home/il/.local/share/weechat/python/autojoin.py (Invalid cross-device link)`

## Expected behavior

The script should load

## Suggested solutions

Use a method that works accross devices to move the script

## Additional information

firejail - version 0.9.62

---

- WeeChat version: 3.2
- OS, distribution and version: `Linux sh1.laiho.me 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux` (Ubuntu 20.04 LTS)
- Terminal: Windows Terminal
- Terminal multiplexer (screen/tmux/…/none): tmux

**Comment by flashcode** [comment]
This is because the `rename` function is used to move the file, and it can fail to copy on a different file system.
I'll add a function in WeeChat API to copy a file, and the original file will be removed once the file is properly copied.

**Comment by flashcode** [comment]
Hi,

It should be fixed.
I didn't test with firejail though, could you please confirm it's now OK?
Thanks.

**Comment by ilmaisin** [comment]
@flashcode Yes, it seems to work.
