### ISSUE TITLE
Is Perl 5.34 not yet supported?

### ISSUE THREAD

**Issue by ifohancroft** [weechat/weechat#1670]
## Bug summary

Unable to load plugin "/home/ifohancroft/Downloads/weechat-build/lib/weechat/plugins/perl.so": libperl.so: cannot open shared object file: No such file or directory
If you're trying to load a script and not a C plugin, try command to load scripts (/perl, /python, ...)

## Steps to reproduce

1. Update Perl to 5.34
2. Remove Perl 5.32
3. Start WeeChat

## Current behavior

WeeChat says: Unable to load plugin "/home/ifohancroft/Downloads/weechat-build/lib/weechat/plugins/perl.so": libperl.so: cannot open shared object file: No such file or directory
If you're trying to load a script and not a C plugin, try command to load scripts (/perl, /python, ...)

## Expected behavior

WeeChat loads the Perl plugin

---

- WeeChat version: WeeChat 3.2-dev (git: v3.1-79-gde3d541e5) [compiled on May  2 2021 19:26:05]
- OS, distribution and version: Manjaro Linux x86_64
- Terminal: Termite
- Terminal multiplexer (screen/tmux/…/none): None

**Comment by trygveaa** [comment]
You most likely need to recompile the perl plugin for WeeChat after upgrading perl. perl 5.34.0 is working fine in WeeChat for me.

**Comment by ifohancroft** [comment]
Thank you! Will recompile later today and report back the results.

**Comment by ifohancroft** [comment]
It all seems fine after a recompilation so I am closing this.
