### ISSUE TITLE
Typing doesn't check for CLIENTTAGDENY= in ISUPPORT

### ISSUE THREAD

**Issue by Mikaela** [weechat/weechat#1671]
## Bug summary

Typing plugin should check for presense of `CLIENTTAGDENY=` and not send typing notifications if the server refuses them.

## Steps to reproduce

1. Enable typing notifications
2. Connect to Snoonet
3. Type a message in query or channel

## Current behavior

WeeChat will send typing notifications and status changes receiving error `No tags to send` in the server buffer.

## Expected behavior

WeeChat will see `CLIENTTAGDENY=*` and not send typing notifications at all.

## Suggested solutions

Checking for ISUPPORT and following it.

## Additional information

* https://ircv3.net/specs/extensions/message-tags#rpl_isupport-tokens

---

- WeeChat version: WeeChat 3.3-dev (git: v3.2-89-g6052c1a5c) [compiled on Jul  8 2021 23:07:49]
- OS, distribution and version: Debian 11
- Terminal: MATE-Terminal
- Terminal multiplexer (screen/tmux/…/none): tmux

**Comment by flashcode** [comment]
Fixed by 8e676edd1a5a1ab91279d55a2181757ad36b5ced.
