### ISSUE TITLE
weechat don't works with bnc?

### ISSUE THREAD

**Issue by niponic** [weechat/weechat#1674]
## Question
 i'm trying to use weechat with a bnc but I have problems. After connecting to bnc i can reattach the bnc connection active with irc server but when i try to send any msg or command i receive msg saying i am not connected to the irc server. (irc: you are not connected to the server)

my steps:
1) /server add mybnc ip/port
2) /connect mybnc
3) /quote pass mypassword 
4) /quote reattach 1  
Ok! Reattached! 
So far so good, but when i type any message in the channels window i get the warning saying i am not contacted to the server.
I tried it with hexchat and it works normally, hexchat understands me as connected and my messages are sent normally but weechat not

Do I need to type any additional commands in weechat to work? 

---

- WeeChat version: 3.2
- OS, distribution and version: Debian 10 Stable

**Comment by flashcode** [comment]
Hi,

WeeChat assumes you're connected to the server once the message 001 is received from the server.

Can you look at `/server raw` and paste the messages exchanged with the server upon connection? (please hide everything private like user names and passwords).

In order to reproduce the problem, could you please tell me which bouncer you are using and its version?

Thanks.

**Comment by niponic** [comment]
Hi, for the ease, i use a bnc made in perl.
To reproduce, here it is: https://pastebin.com/raw/M1KvVAS7
To run, just run the file in perl, the configured password is death and port 31212 (it's okay for me to share this data because my password and the port is different)

The procedure more detailed is:
1) perl bnc.pl
2) Open weechat, then: /server add bnc IP/PORT
3) /connect bnc
4) /quote pass *****
5) /quote conn irc.freenode.org and after join my channels
6) /quote detach   
7) After Close weechat (So far everything works, I can send messages normally)
8) Now I open weechat again and connect to my bnc, then I ask to list the connections I left in detach:
9) /quote listids
10) /quote reattach 1    (In this step the problem happens, I get the reattach on the connection but when I try to send messages the weechat says I'm not connected to the irc server.)

Below are the messages from /server raw

IRC raw messages | Filter: *
  weechat  │11:16:52 <-- bnc | NICK Guest9856
2.irc_raw  │11:16:52 <-- bnc | USER Guest9856 0 * :Guest9856
3.  #testchannel│11:16:52 --> bnc | NOTICE AUTH :*** [BNC 1.5 por 0ldW0lf - Atrix Team]
           │11:16:52 --> bnc | NOTICE AUTH :*** Digite /QUOTE PASS <senha>
           │11:16:56 <-- bnc | pass *******
           │11:16:56 --> bnc | NOTICE AUTH :*** Senha aceita.
           │11:16:56 --> bnc | NOTICE AUTH :*** Digite /QUOTE CONN <servidor[:porta]>
           │11:16:56 --> bnc | NOTICE AUTH :*** Para lista os comandos da BNC digite /QUOTE BHELP
           │11:17:11 <-- bnc | listids
           │11:17:11 --> bnc | :BNC!0ldW0lf@AtrixTeam NOTICE Guest9856 : \x02- Listando IDs -\x02
           │11:17:11 --> bnc | :BNC!0ldW0lf@AtrixTeam NOTICE Guest9856 :
           │11:17:11 --> bnc | :BNC!0ldW0lf@AtrixTeam NOTICE Guest9856 :\x021\x02 -> Guest9856@irc.freenode.org:6667 (Detached)
           │11:17:19 <-- bnc | reattach 1
           │11:17:19 --> bnc | :BNC!0ldW0lf@AtrixTeam NOTICE Guest9856 :OK! Reatachando :)
           │11:17:19 --> bnc | :Guest9856!BNC@atrixteam JOIN #testchannel
           │11:17:19 --> bnc | :BNC!0ldW0lf@AtrixTeam NOTICE Guest9856 :Reattachado!
           │11:17:19 --> bnc | :avalanche.freenode.net 353 Guest9856 = #testchannel :@Guest9856
           │11:17:19 --> bnc | :avalanche.freenode.net 366 Guest9856 #testchannel :End of /NAMES list.
           │11:17:20 --> bnc | :avalanche.freenode.net 331 Guest9856 #testchannel :No topic is set.

**Comment by flashcode** [comment]
Hi,

So as I thought, the server doesn't send a `001` message.

The question is: is it OK to rely on message `001` to consider the server accepts the connection?

The spec [RFC 2812](https://datatracker.ietf.org/doc/html/rfc2812#section-5.1) is not very clear on this subject (is the message always sent by the server?):

    - The server sends Replies 001 to 004 to a user upon
      successful registration.

**Comment by flashcode** [comment]
Additional note: WeeChat checked message `004` in past (versions < 0.2.0), and it was changed to `001` in this commit: 507ae028c5cfd8800d08e32109611f9381563537 ([savannah bug #16760](https://savannah.nongnu.org/bugs/?16760)).
Anyway neither `001` nor `004` are sent by the bnc script mentioned in this issue.

**Comment by flashcode** [comment]
As the pastebin has expired, could you please give me another link of your bnc, so that I can test with other IRC clients?

**Comment by niponic** [comment]
yes, here: http://www.geocities.ws/hackercupu_cupu06/cbn.txt
I used a lot this bnc with bitchx and xchat and it always worked perfectly.
the port configured is 31212 and password is death

**Comment by flashcode** [comment]
I recommend to update the bnc to send `001` as first message upon client connection, so that WeeChat will not disconnect after 1 minute (by default) when the 001 is not received.

This is something standard all IRC servers should do, I think the solution is not to make WeeChat more permissive against non compliant servers.

So I close as won't fix.
