### ISSUE TITLE
SETNAME output is confusing when other users change their names

### ISSUE THREAD

**Issue by Mikaela** [weechat/weechat#1676]
## Bug summary

When someone else changes their name, WeeChat reports that I have changed my name.

## Steps to reproduce

1. Connect to server with SETNAME
2. See someone else change their name
3. Be confused on the message

## Current behavior

Mysterious messages like:

* `2021-W29-5 05:28:26 +0300 -- Real name set to: ♥ `
* `2021-W29-5 00:18:59 +0300 -- Real name set to: Mara "marina" R. B.`

## Expected behavior

WeeChat tells me clearly when I change my name vs when someone else changes their name.

## Additional information

I have seen teh messages on snoonet.net and liberta.casa in that order. I haven't triggered this issue manually yet.

---

- WeeChat version: WeeChat 3.3-dev (git: v3.2-96-g88d59de94) [compiled on Jul 21 2021 23:07:57]
- OS, distribution and version: Debian GNU/Linux 11 (bullseye)
- Terminal: MATE Terminal
- Terminal multiplexer (screen/tmux/…/none): Tmux

**Comment by flashcode** [comment]
Related to #1653
