### ISSUE TITLE
Either allow me to encode and decode UTF-8 only or suggest that I can unload and blacklist the charset plugin

### ISSUE THREAD

**Issue by Mikaela** [weechat/weechat#1682]
`2021-W31-7 19:18:36 +0300 =!= charset: UTF-8 is not allowed in charset decoding options (it is internal and default charset: decode of UTF-8 is OK even if you specify another charset to decode)` is not helpful. I don't want to encode/decode anything else than UTF-8, I don't care about it being OK.

**Comment by flashcode** [comment]
To use only UTF-8, you can do: `/set charset.default.decode ""`.
