### ISSUE TITLE
Command to close parted buffers

### ISSUE THREAD

**Issue by Mikaela** [weechat/weechat#1685]
## Feature description

> Is there a command to mass close parted buffers? Context being that I have several networks via integrated/bouncers and manage the leaving state from Palaver for which the option to autorejoin channels is global instead of network specific, so it keeps joining my WeeChat to channels too if I close channels from WeeChat. Additionally autojoin.py doesn't sometimes seem to notice when I have left a channel

**Comment by flashcode** [comment]
Done, it's now possible with the command: `/allchan -parted /close` (see `/help allchan` for the new option `-parted` and the example).
