### ISSUE TITLE
variable containing the current iteration for a regex in a trigger

### ISSUE THREAD

**Issue by pascalpoitras** [weechat/weechat#1689]
## Feature description

It would be nice to be able to know the current iteration in a regex. It's a bit hard to explain so let me explain with an example

for example imagine ${my_variable} value is apple,banana,orange and I would like to put a number in front of each items
`
/[^,]+/${match_number}.${re:0}/my_variable`

would replace the content in my_variable to 

1.apple,2.banana,3.orange

so here match_number would contain the current iteration number for the current regex

**Comment by flashcode** [comment]
Done, with `${re:repl_index}`.
