### ISSUE TITLE
Buffer remains hotlisted after join and close

### ISSUE THREAD

**Issue by nwf** [weechat/weechat#1690]
## Bug summary

Joining two buffers and closing one can result in incorrect hotlisting behavior.

## Steps to reproduce

I'm not quite sure, since I only notice after something has already gone wrong, but I think the sequence of operations is...

1. Open two IRC buffers
2. `/buffer join` them together
3. `/buffer close` one of them
4. Receive a message in the still open buffer that causes it to become highlighted / active
5. Focus on that buffer
6. Focus away

## Current behavior

After the above sequence, the still-open buffer will remain hotlisted despite having no new messages.

Hotlisting can be cleared using `/input hotlist_clear`, but that doesn't actually solve the problem; the sticky hotlisting will be back on the next message to the buffer.

## Expected behavior

Hotlist status should continue to behave as it did before joining buffers.

## Additional information

This _may_ be due to having a relay client connected?  I don't think so, but I do have one almost always hooked up, so.

---

- WeeChat version: WeeChat 2.8 [compiled on Apr  4 2020 09:01:45]
- OS, distribution and version: Ubuntu Focal 20.04.3
- Terminal: `urxvt`
- Terminal multiplexer (screen/tmux/…/none): `tmux`

Please let me know if there is additional information I can provide that would be useful.

**Comment by weechatter** [comment]
Did you check option weechat.look.hotlist_add_conditions ? What is the value from option?
PS: Its also recommended to update to latest stable version.

**Comment by nwf** [comment]
Thanks for the reply; no, I hadn't thought to check.  Weechat helpfully informs me that I have strictly fewer conditions for adding to the hotlist than default:
```
weechat.look.hotlist_add_conditions = "${away} || ${buffer.num_displayed} == 0"  (default: "${away} || ${buffer.num_displayed} == 0 || ${info:relay_client_count,weechat,connected} > 0")
```
FWIW, I also have `weechat.look.hotlist_remove = merged` (apparently the default).

P.S. `2.8-1` is the latest version packaged in Ubuntu Focal (their current LTS release).  I see that they have 2.9 in Groovy and 3.0.1 in Hirsute and Impish.  If there's significant reason to upgrade, perhaps that should be chased a bit?

**Comment by oakkitten** [comment]
might this #215 be the same issue?

**Comment by nwf** [comment]
Oh huh, I swear I looked to see if there were related issues already open, but I guess my search keywords were not up to the task.  In any case, I think I have only ever seen this happen specifically after _closing_ a merged buffer (I'm not sure about unmerging, since I rarely do so, but that could also be a trigger).  I haven't, so far as I remember, seen a merged buffer (or group thereof) remain hotlisted incorrectly unless one was closed.  Still, could be related; thank you for finding it!

**Comment by weechatter** [comment]
@nwf 
try with : /set weechat.look.hotlist_add_conditions "${buffer.num_displayed} == 0"

and use the official weechat repository to always have the latest version: https://weechat.org/download/debian/

https://weechat.org/files/changelog/ChangeLog-3.2.html#v3.2

**Comment by flashcode** [comment]
Hi,
Do you still have the issue with latest version, 3.8?

**Comment by flashcode** [comment]
Closing old issue, if you still have the problem, please add a comment.
