### ISSUE TITLE
reordering or sorting filters

### ISSUE THREAD

**Issue by ksu-0** [weechat/weechat#1695]
It would be nice if it was possible to reorder or sort the filters. The best way to achieve this is probably to simply have them always sorted by name, as is the case with the triggers.

**Comment by ksu-0** [comment]
I just tested v3.6-104-g528492170 and it works great, thank you! One minor issue remaining is that filters are not re-sorted after `/filter rename`.

**Comment by flashcode** [comment]
Thanks for testing and reporting it, it's now fixed!
