### ISSUE TITLE
disable spell checker for particular buffer

### ISSUE THREAD

**Issue by ksu-0** [weechat/weechat#1699]
An option to disable spell checker for particular buffer could be useful.

It is possible to do:
```
/set spell.dict.irc en
/set spell.dict.irc.irc_raw ""
```
It works, and is even saved to `spell.conf`, but on plugin reload the `spell.dict.irc.irc_raw` option disappears.

It is also possible to set `spell.dict.irc.irc_raw` to a non-empty string that is not a dictionary. It works, and survives plugin reload, but the plugin complains on every load and the string is visible in the `spell_dict` bar item.

**Comment by weechatter** [comment]
maybe i don't get the point. but when i do (for example in #weechat-de) /spell deldict de_DE    there is no spell checking in this buffer (if there is no other dict than de_DE).

and in the /server raw buffer i did:
/spell setdict de_DE
/save
/close
/plugin reload spell
/server raw

 after opening the raw buffer, there is still my dict "de_DE"

**Comment by ksu-0** [comment]
The point is to have spell checking in irc buffers in general, or in some server in general, but disable it for particular buffer, for an example a private conversation with a bot which is not carried in a human language.

Setting or changing the dictionary works, but removing it when it is defined at a higher level does not.

**Comment by weechatter** [comment]
You can specify a dictionary for a group of buffers, eg. english for all channels on libera IRC server
/set spell.dict.irc.libera en

to disable it for private conversation use an trigger or an script. i think your use-case is very special

**Comment by ksu-0** [comment]
> You can specify a dictionary for a group of buffers, eg. english for all channels on libera IRC server
> /set spell.dict.irc.libera en

That's what I do in the original post. It sets the default dictionary for all irc buffers to `en`.

> to disable it for private conversation use an trigger or an script. i think your use-case is very special

You may be right. :)

**Comment by ksu-0** [comment]
I suspect that with #1761 merged, it can be fixed by setting the default value of `spell.dict.*` options to `NULL` in `spell_config_dict_create_option`.
