### ISSUE TITLE
expanding space bar item

### ISSUE THREAD

**Issue by ksu-0** [weechat/weechat#1700]
It would be nice to have an expanding space bar item to move some of the bar items to the right. With the `item1,item2,expanding_space,item3` items, a bar of size 0 and max_size 0 would look like this:

left bar:
```
│item1 item2 item3│
```

top bar, window of width 24:
```
│item1 item2        item3│
```

top bar, window of width 24:
```
│item1 looooooooooooooooo│
│ongitem2           item3│
```

**Comment by weechatter** [comment]
alignment for bars would be a great feature :-D

**Comment by flashcode** [comment]
Hi,

I wrote a spec for this feature: https://specs.weechat.org/specs/001700-bar-spacer.html

Note that there's a limitation compared to the proposed feature: it works only with bars whose size is exactly 1 (so no dynamic size). Supporting spacers with dynamic size would lead to a very complex algorithm.

See chapter "Restrictions" and examples in the spec.

Comments on this spec are welcome here.

**Comment by pascalpoitras** [comment]
even with the limitation this is still pretty nice, I look forward to this and text_item builtin
