### ISSUE TITLE
'lag is high, reconnecting to server' not followed by attempt to reconnect

### ISSUE THREAD

**Issue by ksu-0** [weechat/weechat#1708]
## Bug summary

With `-autoreconnect=off`, on high lag the server is disconnected with `reconnecting to server` message, but reconnect is never attempted.

## Steps to reproduce

* `/server add test irc.libera.chat/6697 -autoreconnect=off`
* `/connect test`
* increase lag over the value of `irc.network.lag_reconnect`

## Current behavior

The server is disconnected with the following message:
```
irc: lag is high, reconnecting to server test
irc: disconnected from server
```
No reconnect is ever attempted.

## Expected behavior

The client should not claim to be reconnecting without trying to reconnect.

## Suggested solutions

I am not really sure what the behavior should be here. Reconnect? Disconnect with different message? Disconnect on lag over `irc.network.lag_max`, with different message? Don't disconnect? Each solution is wrong from certain point of view.

## Additional information

- WeeChat version: 3.4-dev (git: v3.3-8-g9548a4cf7)
- OS, distribution and version: Linux, Debian testing
- Terminal: xfce4-terminal
- Terminal multiplexer (screen/tmux/…/none): none

**Comment by flashcode** [comment]
I fixed by displaying always the same message, which is now: `lag is high, disconnecting from server xxx`.

If option `autoreconnect` is `on` (default and recommended value), another message will be displayed after saying a reconnection is scheduled.
