### ISSUE TITLE
channel join error

### ISSUE THREAD

**Issue by LUEshi42** [weechat/weechat#1717]
## Bug summary
irc: cannot create new channel "#sauvonslespiedsdegabrieletsonminusculepenisphimoserainsiquesafigurehideuseaussifaudraisluitrouverpsypourquiisseconsulterpisprobablementluiprescriredemedicamenspispteteueprothesepousonpenis!AB/close"
irc: failed to parse command "join" (please report to developers): "@time=2021-11-05T22:13:01.024Z :XXXXXX!~XXXXX@XXXXX.users.undernet.org JOIN #sauvonslespiedsdegabrieletsonminusculepenisphimoserainsiquesafigurehideuseaussifaudraisluitrouverpsypourquiisseconsulterpisprobablementluiprescriredemedicamenspispteteueprothesepousonpenis!AB/close"

## Steps to reproduce

1.  connect to undernet
2.  join a channel with a very very long name
3.  profit

## Additional information

---

- WeeChat version:   WeeChat 3.4-dev (git: v3.3-134-gf03622d14) [compiled on Nov  3 2021 00:06:13]
- OS, distribution and version:  WSL debian on windows 11
- Terminal:  PowerShell 7
- Terminal multiplexer (screen/tmux/…/none):  none

**Comment by flashcode** [comment]
Hi,
I can join such channel without issue on irc.undernet.org.
Could you please tell me the exact server you are using, and the complete join command you do, in order to reproduce the problem on my side?
Thanks.

**Comment by LUEshi42** [comment]
11:04 =!= irc: cannot create new channel "#sauvonslespiedsdegabrieletsonminusculepenisphimoserainsiquesafigurehideuseaussifaudraisluitrouverpsypourquiisseconsulterpisprobablementluiprescriredesmedicamentspispteteuneprothesepoursonpenis!!!!"
11:04 =!= irc: failed to parse command "join" (please report to developers): "@time=2021-11-06T15:04:41.036Z :LUEshi!~LUEshi@LUEshi.users.undernet.org JOIN #sauvonslespiedsdegabrieletsonminusculepenisphimoserainsiquesafigurehideuseaussifaudraisluitrouverpsypourquiisseconsulterpisprobablementluiprescriredesmedicamentspispteteuneprothesepoursonpenis!!!!"
11:04 -- Nicks #sauvonslespiedsdegabrieletsonminusculepenisphimoserainsiquesafigurehideuseaussifaudraisluitrouverpsypourquiisseconsulterpisprobablementluiprescriredesmedicamentspispteteuneprothesepoursonpenis!!!!: [@LUEshi]
11:04 -- #sauvonslespiedsdegabrieletsonminusculepenisphimoserainsiquesafigurehideuseaussifaudraisluitrouverpsypourquiisseconsulterpisprobablementluiprescriredesmedicamentspispteteuneprothesepoursonpenis!!!!: End of /NAMES list.

with "/join #sauvonslespiedsdegabrieletsonminusculepenisphimoserainsiquesafigurehideuseaussifaudraisluitrouverpsypourquiisseconsulterpisprobablementluiprescriredesmedicamentspispteteuneprothesepoursonpenis!!!! "

on : " Madrid.ES.EU.Undernet.Org "

thanks for having a look, not a big deal but I saw the message about letting the devs know.

**Comment by flashcode** [comment]
It's important to look at such issue, because I made large changes in the way IRC message parameters are parsed in the devel version (that you are using), so it can be a regression since latest stable (3.3).

Can you please test with latest stable (3.3) and tell me if you have the same issue?

Thanks.

**Comment by flashcode** [comment]
Thanks for the messaged displayed, could you please paste here the command you typed in the command line, ie: "/join ...".
And a paste of raw messages exchanged with the server could help as well: `/server raw`

**Comment by LUEshi42** [comment]
seems to work perfectly after rolling back to weechat 3.3 on debian

1126     │ WeeChat 3.3 [compiled on Sep 19 2021 11:50:23]

**Comment by LUEshi42** [comment]
actually correct that, the same issue seems to be cropping up on 3.3

https://i.imgur.com/8AWxawP.png

**Comment by LUEshi42** [comment]
I use ZNC as a bouncer, this might be an issue with ZNC, throwing this out there.

**Comment by flashcode** [comment]
OK, found the problem there: https://github.com/weechat/weechat/blob/master/src/plugins/irc/irc-buffer.c#L91, a 128-byte buffer is used to build the buffer name, which is not enough.

So this is not related to recent parser changes.
