### ISSUE TITLE
typing indicator remains on forever after nick change

### ISSUE THREAD

**Issue by ksu-0** [weechat/weechat#1718]
## Bug summary

If remote user changes nick while typing, typing indicator in the local client remains on forever.

## Steps to reproduce

local and remote user:
* `/set irc.look.typing_status_nicks on`
* `/set irc.look.typing_status_self on`
* `/set typing.look.enabled_nicks on`
* `/set typing.look.enabled_self on`
* `/join` the same channel

remote user:
* type enough characters for the typing indicator to appear in the status bar of local client
* immediately switch to another buffer and change nick

## Current behavior

Typing indicator remains turned on forever.

## Expected behavior

Typing indicator is cleared.

## Additional information

- WeeChat version: 3.4-dev (git: v3.3-8-g9548a4cf7)
- OS, distribution and version: Linux, Debian testing
- Terminal: xfce4-terminal
- Terminal multiplexer (screen/tmux/…/none): none

**Comment by ksu-0** [comment]
The same problem appears if remote user is kicked from the channel while typing.

**Comment by flashcode** [comment]
Hi,

I'm not able to reproduce with nick change or kick.
When the nick changes, I see both nick typing (which is a bug and can be fixed), but the typing indicator of old nick disappears shortly after nick change (some seconds).

Am I missing something?

**Comment by ksu-0** [comment]
Interesting, I saw it remain for days. I'll try to experiment.

**Comment by ksu-0** [comment]
Testing with trigger monitor confirms that while the `typing_set_nick("*;off;*")` signal is sent on `/part` and `/quit`, it is not sent on `/kick` or `/nick` change.

**Comment by ksu-0** [comment]
Wouldn't `irc_nick_change`, `irc_nick_free`, `irc_nick_free_all` be better place than `IRC_PROTOCOL_CALLBACK` to send typing signals?

**Comment by ksu-0** [comment]
To reproduce:

* `/server fakerecv @+typing=active :test!~test@test TAGMSG #weechat`
* `/server fakerecv :test KICK #weechat test test`

**Comment by flashcode** [comment]
@ksu-0: when I do these commands, I see the typing indicator for about 6-8 seconds and then it's properly cleared (this matches the default value of 6 in the option `typing.look.delay_purge_typing`).

So I'm not able to reproduce like this.

Are you using default values for typing settings?
I mean these ones (except the booleans which are `off` by default):

    irc.look.typing_status_nicks    boolean  on   (default: off)
    irc.look.typing_status_self     boolean  on   (default: off)
    typing.look.delay_purge_paused  integer  30
    typing.look.delay_purge_typing  integer  6
    typing.look.delay_set_paused    integer  10
    typing.look.enabled_nicks       boolean  on   (default: off)
    typing.look.enabled_self        boolean  on   (default: off)
    typing.look.input_min_chars     integer  4
    typing.look.item_max_length     integer  0

**Comment by ksu-0** [comment]
With `typing.look.enabled_self on`, I see the same behavior as you. To reproduce the problem, `typing.look.enabled_self` needs to be `off`. Apparently I made a mistake in the original post?
