### ISSUE TITLE
Emoji will duplicate the first 3 chars of word in message when sent

### ISSUE THREAD

**Issue by Mrfiregem** [weechat/weechat#1731]
## Bug summary

Joining a channel and typing, e.g.

```
💀 hello world
💀hello world
💀 helloworld
 💀 hello world
hello 💀 world
```

Will result in output that looks like

```
2021-12-19 21:28:12 @cheer 💀 hello worworld
2021-12-19 21:28:21 @cheer 💀hello world
2021-12-19 21:28:28 @cheer 💀 helloworld
2021-12-19 21:28:32 @cheer  💀 helhello world
2021-12-19 21:35:26 @cheer hello 💀 worworld
```

It seems to have something to do with the number of spaces in the message.

## Steps to reproduce

1. Join a channel. I made temp channels on libera.chat to test this.
2. Type in a message consisting of an emoji, followed by a space and text, and send it.

## Current behavior

3 letters of a random word are duplicated on output.

## Expected behavior

The message should be sent as-is.

## Additional information

Using a plugin like `emojize.py` or another plugin that converts `:shortcodes:` works as expected when sending messages with emoji, but having to memorize shortcodes is a more of a hassle than typing them directly using external programs.

---

- WeeChat version: 3.3
- OS, distribution and version: Arch Linux
- Terminal: Foot, Alacritty
- Terminal multiplexer (screen/tmux/…/none): None

**Comment by weechatter** [comment]
i can not reproduce. message sent to server is:
PRIVMSG #testchan :💀 hello world

I guess you may have a script (not plugin!) installed, that will do this.
/script list -o

Try without any scripts.

**Comment by Mrfiregem** [comment]
You're right, this is actually being caused by the `emojize.py` script. I forgot to consider such a thing because I haven't sent a message with emoji until after installing it. I'll open an issue there instead.
