### ISSUE TITLE
changing weechat.look.hotlist_sort clears hotlist_priority in buflist

### ISSUE THREAD

**Issue by ksu-0** [weechat/weechat#1733]
## Bug summary

Changing the value of `weechat.look.hotlist_sort` sets `hotlist_priority` of all buffers in the buflist to `none`. As a consequence, all buffers in the buflist lose their hotlist highlight.

Refreshing the buflist does not help. The `hostlist` bar item is not affected. Further additions to the hotlist are highlighted normally.

## Steps to reproduce

* wait until hotlist is populated
* `/set weechat.look.hotlist_sort group_number_asc`

## Current behavior

All buffers in the buflist lose their hotlist highlight.

## Expected behavior

Buflist is not affected.

## Additional information

- WeeChat version: 3.4
- OS, distribution and version: Linux, Debian testing
- Terminal: xfce4-terminal
- Terminal multiplexer (screen/tmux/…/none): none

**Comment by trygveaa** [comment]
I can't reproduce this. I tried with a clean weechat by running it like this:

```
weechat -t -r '/buffer add 2; /print -buffer core.2 test; /set weechat.look.hotlist_sort group_number_asc'
```

And the second buffer appears in the hotlist after this. Maybe you have a script which affects this? Please provide the list of scripts you have installed.

**Comment by ksu-0** [comment]
> `weechat -t -r '/buffer add 2; /print -buffer core.2 test; /set weechat.look.hotlist_sort group_number_asc'`

This command reproduces the bug for me: buffer 2 is displayed in default color in the buflist instead of white.

> Maybe you have a script which affects this? Please provide the list of scripts you have installed.

The bug is present with no script installed.

**Comment by trygveaa** [comment]
Oh, sorry, I must have misread. I somehow thought you meant it was removed from the hotlist. What you said reproduces for me.

**Comment by flashcode** [comment]
Thanks for reporting, this should now be fixed.
