### ISSUE TITLE
Raw 344 (geo) used by Unreal-6.0.x showed as channel reop

### ISSUE THREAD

**Issue by crazycatdevs** [weechat/weechat#1736]
## Bug summary
UnrealIrcd 6.0.x now integrates the geo, which uses raw 344.
In weechat, raw 344 is assigned to channel reop

## Steps to reproduce
1. Be ircop on unreal 6.0.x server (or with geo information right)
2. whois an user
3. see the result

## Current behavior
13:40:46  Zeolia -- Reop canal Raspdrop : FR :is connecting from France

## Expected behavior
13:40:46  Zeolia -- [Raspdrop] is connecting from France (FR)

## Suggested solutions
Modify irc-protocol.c

Faulty parts:
https://github.com/weechat/weechat/blob/08e0d3912ad37f9faf600ab9d2049792b236516e/src/plugins/irc/irc-protocol.c#L4954
https://github.com/weechat/weechat/blob/08e0d3912ad37f9faf600ab9d2049792b236516e/src/plugins/irc/irc-protocol.c#L7149
---

- WeeChat version: 3.3
- OS, distribution and version: raspbian 5.10
- Terminal: mobaxterm
- Terminal multiplexer (screen/tmux/…/none): screen

**Comment by crazycatdevs** [comment]
Raw response from unrealircd:
`16:11:26 --> Zeolia :gatoloco.zeolia.net 344 CrazyCat CrazyCat FR :is connecting from France`

**Comment by flashcode** [comment]
And on IRCnet (for example `irc.ircnet.com`) such message is received in response to `/mode #channel R`:

    --> ircnet | :openirc.snt.utwente.nl 344 nick #channel jdoe!*@*
