### ISSUE TITLE
A newly introduced issue in parsing of /whois response

### ISSUE THREAD

**Issue by softmix** [weechat/weechat#1737]
## Bug summary
When a user does `/whois <own nick>` on Rizon they get this message as part of the output:

```
irc: too few parameters received in command "338" (received: 3, expected: at least 4)
irc: failed to parse command "338" (please report to developers): ":irc.uworld.se 338 <own nick> <own nick> :is actually ~<username>@<address> [<address>]"
```

## Steps to reproduce

1. Connect to Rizon IRC network.
2. Do /whois on your own nick.
3. Look at the output in the server window.

## Current behavior

Error in parsing `:is actually` line (338, RPL_WHOISACTUALLY).

## Expected behavior

No parsing errors.

## Suggested solutions

The issue was introduced in this commit: https://github.com/weechat/weechat/commit/0e9710de8114d214a314b21ac4716bc7c94a678f

It seems the numbers decribing where to expect parameters and how many of them, are incorrect.

## Additional information

Nothing else.

---

- WeeChat version: 3.4-1
- OS, distribution and version: Arch Linux
- Terminal: gnome-terminal
- Terminal multiplexer (screen/tmux/…/none): none

**Comment by flashcode** [comment]
Thanks for reporting, this is now fixed.
