### ISSUE TITLE
triggers with a name containing non ascii character doesn't get disabled

### ISSUE THREAD

**Issue by pascalpoitras** [weechat/weechat#1739]
## Bug summary

Triggers seems to works well with non ASCII character, except when you disable them (this is not urgent to fix I usually name my trigger with ASCII letter only but I was testing something and found this)

## Steps to reproduce

1. /trigger add e print "" "${tg_message} =~ test" "" "/print -core e"
2. /print -core test
3. e is printed
4. /trigger disable e
5. /print -core test
6. e is not printed
7. but not let's use an accented letter
8. /trigger add é print "" "${tg_message} =~ test" "" "/print -core é"
9. /print -core test
10. é is printed
11. /trigger disable é
12. /print -core test
13. é is still printed

## Current behavior

triggers with non-ascii character does not really got disabled even if they show as it in /trigger list

---

- WeeChat version: 3.5
- OS, distribution and version: Debian Stable
- Terminal: urxvt
- Terminal multiplexer (screen/tmux/…/none): tmux

**Comment by flashcode** [comment]
Fixed.
There was similar issues with the calls to API functions `strncasecmp` and `strncasecmp_range` in core and other plugins, they are fixed as well in separate commits.
