### ISSUE TITLE
add tags mechanism to free content buffers

### ISSUE THREAD

**Issue by pascalpoitras** [weechat/weechat#1746]
## Feature description

I remember a few years ago, FlashCode were not against adding tags to free content buffer but I never created any issue for this
I ended up using a formatted buffer for something because I needed tags but a free content buffer would be more appropriate

**Comment by flashcode** [comment]
Should then filters apply on these buffers as well?

**Comment by pascalpoitras** [comment]
it is not needed for what I was doing but it can be useful I guess, if it's not too hard to add support for that, it would be good.

**Comment by pascalpoitras** [comment]
Would it be possible to update the tags as well when we do /print -free -newbuffer mybuffer -tags mytags -y 1 text, so for example if I ran this command two time with differents tags, the tags changes ?

**Comment by flashcode** [comment]
Yes, this will be the case.

**Comment by flashcode** [comment]
Precision: the filters already applies to buffers with free content, but today tags are not used since there are no tags in lines (they will be as soon as tags are stored in lines).
