### ISSUE TITLE
Add support for $XDG_STATE_HOME

### ISSUE THREAD

**Issue by rpdelaney** [weechat/weechat#1747]
## Feature description

Background: Support for the XDG base directory spec was recently closed in #1285. 

Also recently, freedesktop.org has [extended the spec](https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html) to add support for `$XDG_STATE_HOME`:

> $XDG_STATE_HOME defines the base directory relative to which user-specific state files should be stored. If $XDG_STATE_HOME is either not set or empty, a default equal to $HOME/.local/state should be used.
>
> The $XDG_STATE_HOME contains state data that should persist between (application) restarts, but that is not important or portable enough to the user that it should be stored in $XDG_DATA_HOME. It may contain:
>
> * actions history (logs, history, recently used files, …)
>
>  * current state of the application that can be reused on a restart (view, layout, open files, undo history, …)

**Comment by trygveaa** [comment]
What do you propose to move from `$XDG_STATE_HOME` to `$XDG_STATE_HOME`? The only thing I can think of that fits that description is the `weechat.log` file.

I don't think the buffer logs should be moved there, as I definitely consider those important, and I don't think that's the kind of logs they're referring to in the description.

**Comment by rpdelaney** [comment]
Well, I don't read the spec to be saying that the stuff in `$XDG_STATE_HOME` is necessarily _un_important. However, buffer logs are probably not [i]portable[/i].

wechat.log is also candidate for sure. If I recall correctly there are some circumstances were weechat may create files session keys in some circumstances, although I'm not seeing anything of such locally at the moment.

**Comment by trygveaa** [comment]
> Well, I don't read the spec to be saying that the stuff in `$XDG_STATE_HOME` is necessarily _un_ important. However, buffer logs are probably not _portable_.

Why do you think they aren't portable? They are just plain text files which would work perfectly fine on any machine you copy them to, so I would say they are as portable as they can get.

**Comment by rpdelaney** [comment]
If I copy logs from one machine to another, does weechat guarantee that I can't over-write files that have data in them that is not also in their replacement?

**Comment by ksu-0** [comment]
A buffer log is never overwritten, entries can only be appended to it.

The `weechat.log` file is overwritten on program start, entries produced by previous run are deleted.

**Comment by trygveaa** [comment]
> Unless I'm copying the buffer logs from one place to another, right? How should I resolve merge conflicts?

Just append one log to the other and sort by time. Seems easier than merging config, unless I'm missing something.

**Comment by rpdelaney** [comment]
Alright, I don't have a considered opinion that buffer logs fit better in STATE_HOME than DATA_HOME, so I won't die on that hill. `weechat.log` does seem like it belongs there, though, no?

**Comment by trygveaa** [comment]
> `weechat.log` does seem like it belongs there, though, no?

Yes, that I agree with.

**Comment by 62832** [comment]
@flashcode Might want to close this issue now that the relevant PR has been merged in.

**Comment by flashcode** [comment]
Yes, implemented via #2106.
