### ISSUE TITLE
recursion in triggers

### ISSUE THREAD

**Issue by pascalpoitras** [weechat/weechat#1748]
## Feature description

I would like to use recursion in one of my command trigger, I wonder if it would be possible to add a mechanism so that if an option is on (off by default) the trigger can call itself

for example if my trigger is called test and trigger.trigger.test.recursion is on then I can call my command from the trigger

for example the following would be executed twice (the second time the conditions will be false). For now it is executed just once (visible in trigger monitor)

`/trigger add cmd command cmd "${plugins.var.test}==" "" "/set plugins.var.test 1;/cmd"`
`/cmd`

instead of trigger.trigger.test.recursion to be a on/off value it could be a number that tell how many time a trigger can call itself too

and command priorities (for example cmd and 2000|cmd) doesn't work for what I want, If I call cmd from 2000|cmd nothing happens since recursion is not allowed (and I most call cmd from 2000|cmd because the arguments to the command change but a command trigger doesn't update any variable so the cmd trigger would not receive the new arguments [14.6. Regular expression]https://weechat.org/files/doc/devel/weechat_user.en.html#trigger_regex))

**Comment by flashcode** [comment]
Hi,

I could add a mechanism to allow and limit the recursion of a trigger with a hardcoded max number of times a trigger is running, likes it's done for eval, see #1183.

For eval, the max recursion count is 32, would this be enough for triggers?

Trigger plugin would display a warning if the limit is reached (maybe only if debug is enabled?).

I'm not sure the user should have a way to modify such limit or even allow/disallow trigger recursion.

**Comment by pascalpoitras** [comment]
yes this will be enough
yes if debug is enabled is fine

**Comment by flashcode** [comment]
Hi,

After some tests, it can cause infinite loops and all hooks (except commands) have a mechanism to prevent any recursion.

As it can be dangerous to introduce such recursion, and it was discussed with @pascalpoitras, we agreed to close this issue as "won't fix".

For such advanced needs, writing a script is recommended over using a trigger.
