### ISSUE TITLE
using both define and parenthese in a conditions return true everytime

### ISSUE THREAD

**Issue by pascalpoitras** [weechat/weechat#1753]
## Bug summary

Using both ${define:...} and parenthese seems to return 1 everytime in conditions evaluation

## Steps to reproduce

1. `/eval -n -c -d ${define:test,test}(0 && 1) || (0 && 1)`
2. return 1 (should be 0)
3. `/eval -n -c -d (0 && 1) || (0 && 1)`
4. return 0 (works)

debug (with define):
```

>> ${define:test,test}(0 && 1) || (0 && 1)
== [1]
1:eval_expression("${define:test,test}(0 && 1) || (0 && 1)")
  2:eval_expression_condition("${define:test,test}(0 && 1) || (0 && 1)")
    3:eval_expression_condition("${define:test,test}(0 && 1)")
      4:eval_replace_vars("${define:test,test}(0 && 1)")
        5:eval_replace_vars_cb("define:test,test")
        5:== ""
      4:== "(0 && 1)"
    3:== "(0 && 1)"
  2:== "1"
1:== "1"
```

debug (without define)

```
 >> (0 && 1) || (0 && 1)
 == [0]
 1:eval_expression("(0 && 1) || (0 && 1)")
   2:eval_expression_condition("(0 && 1) || (0 && 1)")
     3:eval_expression_condition("(0 && 1)")
       4:eval_expression_condition("0 && 1")
         5:eval_expression_condition("0")
           6:eval_replace_vars("0")
           6:== "0"
         5:== "0"
       4:== "0"
     3:== "0"
     7:eval_expression_condition("(0 && 1)")
       8:eval_expression_condition("0 && 1")
         9:eval_expression_condition("0")
           10:eval_replace_vars("0")
           10:== "0"
         9:== "0"
       8:== "0"
     7:== "0"
   2:== "0"
 1:== "0"
```

a way to fix it is to start the conditions with something else than a parenthese but not just a space

`/eval -n -c -d ${define:test,test} 1 && (0 && 1) || (0 && 1)`

---

- WeeChat version: 3.5-dev
- OS, distribution and version: Debian 11
- Terminal: urxvt
- Terminal multiplexer (screen/tmux/…/none): tmux

**Comment by flashcode** [comment]
Hi,

This can not be easily fixed because we first split on parentheses to evaluate the condition.
If instead we eval first, this could add parentheses that should not be taken in account in the condition.

There are 2 ways to make it work anyway:

1. Use the define first (which itself is false because returning an empty string), then add a "OR" operator:

````
>> ${define:test,test} || (0 && 1) || (0 && 1)
== [0]
````

2. Use the define inside the first parenthese:

````
>> (${define:test,test}0 && 1) || (0 && 1)
== [0]
````
