### ISSUE TITLE
Strikethrough text

### ISSUE THREAD

**Issue by subnut** [weechat/weechat#1757]
## Feature description
Support for text like this -   
~strikethrough text~

**Comment by trygveaa** [comment]
I think this is blocked by ncurses not supporting strikethrough.

**Comment by flashcode** [comment]
Yes I was about to answer the same thing, but maybe there's a workaround, see: https://stackoverflow.com/questions/61021837/strikethrough-text-in-ncurses

I'll make some tests.

**Comment by poljar** [comment]
There is a workaround, weechat-matrix supports strikethroughs: https://github.com/poljar/weechat-matrix-rs/blob/master/src/room/mod.rs#L447

You append `\u{0336}` to every character.

**Comment by subnut** [comment]
ping @flashcode 

Any updates?

**Comment by flashcode** [comment]
I tested the workaround, which works.

But if it had to be implemented, it would add a lot of complicated stuff to the way messages are displayed to add a specific char before all chars displayed.

Compared to the benefit to have this feature, for now this is a no-go, until there's a better/clean solution in future to display such text in the terminal (ie an attribute char like bold, underline, colors, …).
And as WeeChat relies on ncurses, this should be supported here as well.

If you really need this, you can still write a script that does something similar to weechat-matrix.
