### ISSUE TITLE
Trouble with RAW 901 : not enough parameters

### ISSUE THREAD

**Issue by crazycatdevs** [weechat/weechat#1758]
## Bug summary
When doing a `/msg nickserv logout`, I get an error message:
irc : trop peu de paramètres reçus dans la commande "901" (reçu : 3, attendu : au moins 4)

## Steps to reproduce

1. Be registered on services
2. Do /msg NickServ logout

## Current behavior

- Using unrealircd 6.0.1 and anope 2.0.10
- client capability: unrealircd.org/link-security=2 unrealircd.org/plaintext-policy=user=allow,oper=deny,server=deny unrealircd.org/history-storage=memory away-notify invite-notify extended-join userhost-in-names multi-prefix cap-notify sasl=EXTERNAL,PLAIN setname tls chghost account-notify message-tags batch server-time account-tag echo-message labeled-response draft/chathistory draft/extended-monitor unrealircd.org/json-log
> irc : trop peu de paramètres reçus dans la commande "901" (reçu : 3, attendu : au moins 4)

> échec d'analyse de la commande "901" (merci de reporter ce problème aux développeurs) : ":gatoloco.zeolia.net 901 CrazyCat CrazyCat!crazycat@127.0.0.1 :You are now logged out."

## Additional information

---

- WeeChat version: 3.4
- OS, distribution and version: Raspbian 5.10.20
- Terminal: 
- Terminal multiplexer (screen/tmux/…/none): screen

**Comment by flashcode** [comment]
Thanks for reporting the issue, now fixed.

A regression was introduced in version 3.4 (with the major rewrite of IRC parser), but anyway even in older versions the message was not properly parsed (no error displayed, but the message was truncated).
