### ISSUE TITLE
add variable tg_hook

### ISSUE THREAD

**Issue by pascalpoitras** [weechat/weechat#1765]
## Feature description

I wonder if you could add a variable tg_hook common to all triggers (like tg_trigger_name) which contain the name of the hook. For now I can use `${trigger.trigger.${tg_trigger_name}.hook}` but a `${tg_hook}` would be neat

Of course I'm aware that we can create var using `/.*/${trigger.trigger.${tg_trigger_name}.hook}/tg_hook` and `${define:tg_hook,${trigger.trigger.${tg_trigger_name}.hook}}` but having `tg_hook` built in would be great.

**Comment by flashcode** [comment]
Done, variable is `${tg_hook_type}`.
