### ISSUE TITLE
Allow scripts to request additional IRCv3 caps

### ISSUE THREAD

**Issue by emersion** [weechat/weechat#1767]
Right now the only way (?) for scripts to request additional IRCv3 capabilities is to override `irc.server_default.capabilities`. This works fine, but is saved to the config file when the use does `/save` (or `/quit`). If the script is unloaded/uninstalled, or if it migrates to a new cap, the saved caps are still requested and enabled.

It would be nicer to add an API to allow scripts to request additional caps, and not save these into the config file.

**Comment by weechatter** [comment]
isn't it possible to request capabilities using the irc /cap command?
weechat.command(weechat.buffer_search("irc", "servername"), "/cap req my_capability")

just an idea!

**Comment by emersion** [comment]
Hm but I'd need to request caps for all servers right when connecting -- can `/cap req` do that? If `/cap req` just sends a `CAP REQ` IRC message and nothing else that doesn't quite seem what I'm looking for.

**Comment by flashcode** [comment]
I added the modifier "irc_cap_sync_req", that can be used in trigger or script, see the doc here: https://weechat.org/files/doc/weechat/devel/weechat_plugin_api.en.html#hook_modifier_irc_cap_sync_req
