### ISSUE TITLE
How does weechat determine terminal size

### ISSUE THREAD

**Issue by Strykar** [weechat/weechat#1769]
## Question
I have an issue starting weechat in a kitty terminal tab where it does not go full width unless I Alt + L or Ctrl +C.
I am trying to understand if the issue is in weechat or the kitty terminal.

I have tried `/set weechat.startup.command_before_plugins /eval -n ${env:COLUMNS}` and while `echo $COLUMNS` evaluates properly in shell, there is no output for the command in weechat,

How does weechat determine terminal size / width?
- WeeChat version: 3.4.1
- OS, distribution and version: Arch Linux

**Comment by flashcode** [comment]
Hi,

The terminal size is read in the function `gui_window_read_terminal_size` here: https://github.com/weechat/weechat/blob/master/src/gui/curses/gui-curses-window.c#L98

So it calls either `resizeterm` or `getmaxyx` functions, which are in ncurses lib.

**Comment by Strykar** [comment]
@flashcode It's been suggested that weechat may not be _putting the sigwinch handler in place *before* it checks the screen size for the first time_.
See https://github.com/kovidgoyal/kitty/discussions/4877

**Comment by flashcode** [comment]
Hi,

This is already an issue, just tagged as question, but I can update it if this is confirmed to be an issue.

I tried to reproduce with Kitty 0.76.0.8 under Windows 7 or Windows 10 and I have no such issue.

How are you able to reproduce, what's your configuration? And are you running WeeChat under screen or tmux (I did not in my tests)?

**Comment by Strykar** [comment]
I'm on Arch linux, Kitty 0.24.4
Try: `kitty --start-as fullscreen --session=~/weechat.session`

```
$ cat ~/weechat.session
new_tab irc
WEECHAT_PASSPHRASE=whatever weechat
new_tab test
```

**Comment by trygveaa** [comment]
> I tried to reproduce with Kitty 0.76.0.8 under Windows 7 or Windows 10 and I have no such issue.

That's a different terminal emulator. The one in question here only supports Linux and macOS. It's this one: https://sw.kovidgoyal.net/kitty/

**Comment by flashcode** [comment]
For anyone having the issue, could you please this patch:

```patch
diff --git a/src/gui/curses/gui-curses-main.c b/src/gui/curses/gui-curses-main.c
index 12b400cca..bb36c64fa 100644
--- a/src/gui/curses/gui-curses-main.c
+++ b/src/gui/curses/gui-curses-main.c
@@ -409,7 +409,10 @@ gui_main_loop ()
 
     /* catch SIGWINCH signal: redraw screen */
     if (!weechat_headless)
+    {
+        gui_signal_sigwinch_received = 1;
         signal_catch (SIGWINCH, &gui_main_signal_sigwinch);
+    }
 
     /* hook stdin (read keyboard) */
     if (weechat_headless)
```


Thanks.

**Comment by Strykar** [comment]
Just build Weechat (3.5rc1.r6.g5f543f26c-1) with this patch and it does indeed fix the issue.
Weechat starts full width as expected.
