### ISSUE TITLE
irc.server_default.autojoin_dynamic ignores channels joined through IRC relay

### ISSUE THREAD

**Issue by Mikaela** [weechat/weechat#1771]
## Bug summary

When `irc.server_default.autojoin_dynamic` is `on`, channels joined through a IRC relay aren't stored and after restart aren't joined.

## Steps to reproduce

1. Add a IRC relay
2. Set `/set irc.server_default.autojoin_dynamic on`
3. Join channels through IRC relay (I used Palaver)
4. `/save`
5. `/quit -yes`

## Current behavior

WeeChat doesn't autojoin channels I joined using relay, which I notice due to Palaver showing them as not joined.

## Expected behavior

WeeChat autojoins channels I joined through the IRC relay.

## Suggested solutions

Count /join as join for `irc.server_default.autojoin_dynamic` also through IRC relay.

## Additional information

---

- WeeChat version: WeeChat 3.6-dev (git: v3.5-3-g95d0b89d1) [compiled on Mar 28 2022 23:05:37]
  - I don't have version string for the version I `/quit` due to not using `logger` and rebooting in the middle-
- OS, distribution and version: Debian 11 (bullseye)
- Terminal: mate-terminal 1.26.0
- Terminal multiplexer (screen/tmux/…/none): tmux

**Comment by flashcode** [comment]
Thanks for reporting, I fixed the `/part` command as well.
