### ISSUE TITLE
Is Android supported?

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [weechat/weechat#1775]
## Question
I want to utilise whichever IRC client is able to support the most operating-systems. This project appears to be the best at this, but https://github.com/irssi/irssi/blob/master/INSTALL appears to demonstrate that https://github.com/irssi/irssi suppors Android, which this project appears to not.

**Comment by weechatter** [comment]
you can install weechat in termux on android as well. I recommend using the weechat-android frontend.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Understood. I intended to utilise Termux, or a derivative of it, if I was unable to, but that does not provide notificative ability, so to compile it natively for Android would be superior.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@trygveaa, I am thankful.
