### ISSUE TITLE
Installed scripts are empty.

### ISSUE THREAD

**Issue by a1eaiactaest** [weechat/weechat#1776]
## Bug summary
Installing any script with `/script install <name>`, doesn't install full script. In `$WEECHAT_HOME/script/` directory there is `plugins.xml.gz` file, but the rest of the files are size 0 bytes.
```
total 256
-rw-r--r--  1 a1eaiactaest  staff       0 Apr 13 18:33 autosort.py
-rw-r--r--  1 a1eaiactaest  staff       0 Apr 11 18:04 colorize_nicks.py
-rw-r--r--  1 a1eaiactaest  staff  127363 Apr 11 17:10 plugins.xml.gz
```

## Steps to reproduce

1.  Open weechat.
2. Enable scripts download: `/set script.scripts.download_enabled on`.
3. Run `/script install <name>`.

## Current behavior

Nothing happens, after going into `$WEECHAT_HOME/script` you can see empty files for earlier installed scripts.

## Expected behavior

After going into `$WEECHAT_HOME/script`, there should be source files for installed scripts.

## Additional information

`/debug dirs` output:
```
                │18:42:27 weechat     | Directories:
                │18:42:27 weechat     |   home:
                │18:42:27 weechat     |     config: /Users/a1eaiactaest/.weechat
                │18:42:27 weechat     |     data: /Users/a1eaiactaest/.weechat
                │18:42:27 weechat     |     cache: /Users/a1eaiactaest/.weechat
                │18:42:27 weechat     |     runtime: /Users/a1eaiactaest/.weechat
                │18:42:27 weechat     |   lib: /opt/homebrew/Cellar/weechat/3.4.1/lib/weechat
                │18:42:27 weechat     |   lib (extra): -
                │18:42:27 weechat     |   share: /opt/homebrew/Cellar/weechat/3.4.1/share/weechat
                │18:42:27 weechat     |   locale: /opt/homebrew/Cellar/weechat/3.4.1/share/locale
```

---

- WeeChat version: `3.4.1`
- OS, distribution and version: `macOS Monterey 12.2.1 (21D62)`
- Terminal: macOS default terminal
- Terminal multiplexer (screen/tmux/…/none): doesn't matter

**Comment by a1eaiactaest** [comment]
This workaround didn't work in my case: https://github.com/weechat/weechat/issues/1723#issuecomment-995164130

**Comment by flashcode** [comment]
Could you please paste the output of `/debug certs`?
Thanks.

**Comment by a1eaiactaest** [comment]
`/debug certs`:
```
                │09:41:13 weechat     | 199 certificates loaded (system: 199, user: 0)
```

**Comment by flashcode** [comment]
OK, so this is not an issue with certificates.
For now I have no idea why scripts have a size of 0 bytes on macOS.

**Comment by a1eaiactaest** [comment]
Installed `3.6-dev`, same thing happens. 

I've tried to replicate issue on Ubuntu, everything works correctly there. The bug is probably Mac's thing

**Comment by luigi370** [comment]
Still happening.

**Comment by flashcode** [comment]
If someone can give me access to a Mac where I can compile WeeChat, please tell me, so I'll try to investigate.
I can not reproduce this issue on any system where I can test (and I have no access to a Mac).

**Comment by flashcode** [comment]
Closing the issue as I can not reproduce myself.

Feel free to comment if you have additional info or can give me access to a machine with the issue.
Thanks.

**Comment by PBHDK** [comment]
Am I the only one for whom the suggested fixes don't work? Not seeing any change in behaviour when setting the suggested environment variable(s). Any pointers?

**Comment by flashcode** [comment]
Hi,
I added a different way to download scripts using threads, this should fix the issue.
See my comment here: https://github.com/weechat/weechat/issues/1723#issuecomment-1711448127
Please try, your feedback is important.
If the problem is fixed, this is going to be merged.
Thanks!
