### ISSUE TITLE
Old messages are not shown

### ISSUE THREAD

**Issue by melisa-malvina** [weechat/weechat#1779]
## Question - Old messages are not shown

Hi everyone,

I searched guides and through the search engines, but didn't meet any solution or question.

I setup my weechat instance with tmux and systemd. And I set autoconnect and server commands for auto joining after restarting the weechat. Everything seems work but when I attach tmux weechat instance, the old messages(approximately more than 20 line) are not showing even they are exists in logs.

How I restore chat from logs, or any solution?

---

- WeeChat version: 3.5
- OS, distribution and version: Ubuntu 20.04.4 LTS

also

- WeeChat version: 3.4
- OS, distribution and version: Fedora Linux 35 (Workstation Edition)

**Comment by trygveaa** [comment]
> Everything seems work but when I attach tmux weechat instance, the old messages(approximately more than 20 line) are not showing even they are exists in logs.

Do you mean that only 20 lines from the logs are shown? This is the default, it's controlled by the `logger.look.backlog` option.

**Comment by melisa-malvina** [comment]
Thanks! I was looking for this.
