### ISSUE TITLE
 catch specific signals at once, using hook_signal

### ISSUE THREAD

**Issue by weechatter** [weechat/weechat#1780]
## Feature description
with hook_signal you can catch one signal or you can use a wildcard to catch more signals at once.
But it would be fine to catch only specific signals, e.g. window_switch;buffer_switch

hook = weechat.hook_signal("window_switch;buffer_switch", "my_signal_cb", "")

**Comment by flashcode** [comment]
I'm implementing this and doing it as well for `hook_hsignal` which works exactly the same way.

In future it could be possible to do it as well on these functions, but I doubt there are real use cases:

* `hook_config`
* `hook_modifier`
* `hook_info`
* `hook_info_hashtable`
