### ISSUE TITLE
minor `autojoin_dynamic` improvements

### ISSUE THREAD

**Issue by ncfavier** [weechat/weechat#1784]
The added `autojoin_dynamic` feature in 3.5 is nice, but it lacks two important features for me to make it worth using over [autojoin.py](https://weechat.org/scripts/source/autojoin.py.html/) (actually [my modified version](https://github.com/ncfavier/config/blob/792276275033fbb8ec1fc48fc14c8fa3ed200424/modules/server/weechat/autojoin.py)):

1. Channels should be removed from the autojoin list when they are exited with `/close`
2. I like my channel lists to be maintained in sorted order to make configuration changes easier to review. `/autojoin sort` exists, but it can apparently only operate on one server at a time. We could also have an setting to optionally sort the autojoin lists every time they're modified.

**Comment by weechatter** [comment]
1. does it for me, with "autojoin_dynamic on", no matter if i do /CLOSE or /buffer close (/CLOSE is an alias from /buffer close, of course!)
2. /allserv /autojoin sort

you can create a trigger to sort the autojoin list, every time they are modified.

**Comment by flashcode** [comment]
Hi,

For your information, the problem of `autojoin_dynamic` option not being updated on `/close` or `/buffer close` has been fixed in the devel version (3.6-dev), in this commit: d4d8117461c20b075332bb3d2a1fc8493d92a9d7.

**Comment by ncfavier** [comment]
Thanks!
