### ISSUE TITLE
`autojoin_dynamic` not triggered by `/join` without arguments

### ISSUE THREAD

**Issue by ncfavier** [weechat/weechat#1786]
## Bug summary

Issuing `/join` without arguments (for example to rejoin the current channel after a `/part`) does not modify the autojoin list.

## Steps to reproduce

1. Enable `autojoin_dynamic`
2. `/join #foo`
3. Switch to the `#foo` buffer
4. `/part`
5. `/join`

## Current behavior

`#foo` is not in the autojoin list

## Expected behavior

It should be

---

- WeeChat version: 3.5
- OS, distribution and version: NixOS unstable
- Terminal: alacritty
- Terminal multiplexer (screen/tmux/…/none): tmux

**Comment by flashcode** [comment]
Hi,
Thanks for reporting the issue.
This is already fixed in devel version (commit 4d8df89bb5b56bd3ca7b281726722f9d21fefdf8), so I'm closing the issue.

**Comment by ncfavier** [comment]
Thanks!
