### ISSUE TITLE
Empty quit messages cause an empty pair of parentheses

### ISSUE THREAD

**Issue by NetSysFire** [weechat/weechat#1797]
## Bug summary

```
<-- Someone (~blah@blah) has quit ()
```

Caused by `/quote quit :`, this appears to happen a lot with irssi users who do not set a quit message.

This behavior has begun in 3.4 and is probably a regression. It appears to work fine in 3.3.

## Steps to reproduce

1. Connect to libera.chat (this is important because it will not work on e.g hackint)
2. Wait for 5 minutes (otherwise you will hit https://github.com/solanum-ircd/solanum/blob/860187d02895fc953de3475da07a7a06b9380254/modules/core/m_quit.c#L94).
3. Do `/quote quit :`

## Current behavior

```
<-- Someone (~blah@blah) has quit ()
```

## Expected behavior

```
<-- Someone (~blah@blah) has quit
```

## Suggested solutions

n/a

## Additional information

Discussed in #weechat. Others could reproduce

---

- WeeChat version: 3.6
- OS, distribution and version: Appears on both Arch Linux and Ubuntu LTS.
- Terminal: Not relevant.
- Terminal multiplexer (screen/tmux/…/none): none

**Comment by BillingCode** [comment]
How to filter these GitHub emails properly in Gmail?
