### ISSUE TITLE
Way to disable highlights based on glob and/or regex

### ISSUE THREAD

**Issue by PeGaSuS-Coder** [weechat/weechat#1798]
## Feature description
I've quickly skimmed through the issues I didn't find any related to my feature request (I might have overlooked).

While currently we have a way to disable highlights from a specific nick (we have examples on the [users guide](https://weechat.org/files/doc/stable/weechat_user.en.html#max_hotlist_level_nicks)), we have no way to stop highlights from relay bots, i.e, that relay messages in the format `<PeGaSuS@Libera> Hi`.

This would be useful to stop our own messages to ping us (when using the same nick in different networks) but still be highlighted if the message is formatted like `<OtherNick@Network> PeGaSuS: can you help me figuring this out?`

This way we could use a regex expression like [this one](https://regex101.com/r/i36AhP/5) to prevent un-needed highlights.

Currently, I know only one IRC client that has this feature and I do find it very useful.

Cheers!

**Comment by flashcode** [comment]
Done with new option `weechat.look.highlight_disable_regex`, can also be set as a buffer property ("highlight_disable_regex").

See the user's guide for more information: https://weechat.org/files/doc/devel/weechat_user.en.html#highlights_disable
