### ISSUE TITLE
Easy way to add background colour for own messages for easy distinction

### ISSUE THREAD

**Issue by PeGaSuS-Coder** [weechat/weechat#1800]
## Feature description
I was thinking about something like `weechat.look.self_message_color "${color:default,gray}"`, so when we're scrolling in the backlog to copy some message that someone didn't see, we can easily see which are our messages.

**Comment by weechatter** [comment]
you can use script colorize_lines.pl to have this feature or use an trigger.
backlog (from /logger plugin) does not have colors by default. you can use logger.file.color_lines to save lines with ANSI color-codes.

**Comment by PeGaSuS-Coder** [comment]
Meanwhile, I've decided to make `weechat.color.chat_nick_self` to be **`*white`** and therefore more noticeable to me.

Closing this as solved.
