### ISSUE TITLE
How to do multi-line configs? Is it possible to include a custom config file in the weechat config file?

### ISSUE THREAD

**Issue by pvonmoradi** [weechat/weechat#1802]
#### 1-How to do multi-line configs?
Use-case:
I want to split `chat_nick_colors` (which is a long line) into multiple lines.

#### 2- Is it possible to include a custom config file in the weechat config file?
Use-case:
I was wondering if I could include another *sub*-config file to override main config file. For example this way I can programmatically change `chat_nick_colors`.

- WeeChat version: 3.6
- OS, distribution and version: Ubuntu

**Comment by flashcode** [comment]
Hi @pvonmoradi,

Both features you mentioned are not available today.
