### ISSUE TITLE
info debug_time

### ISSUE THREAD

**Issue by pascalpoitras** [weechat/weechat#1806]
## Feature description

It would be nice to have an info that use debug_display_time_elapsed of wee-debug.c

I would like to do something like that

`/trigger set test regex "/.*/${date:%s}/my_start_time ....lots of other regex... /.*/${info:debug_time,${my_start_time}}/tg_info"`

so the first regex record the time and the last regex return the time between now and the time recorded in my_start_time

this way you can try to optimize a trigger and see if it worked

or instead of this info, showing the time taken by the trigger in trigger monitor would be great since it will also take into account the time spent for the conditions and the command

or better both of this.

would be also useful for other things than optimization

for example, do something only if the elapsed time is not too big

`/trigger set test regex /.*/${date:%s}/my_start_time ...lots of other regex... /.*/${info:debug_time,${my_start_time}}/my_elapsed_time /.*/${if:${split:1,.,,${my_elapsed_time}}=~[01]$?and it was fast}/my_do_something /.*/you did it! ${my_do_something}/tg_info"`

print you did it! and it was fast if it take less than two seconds
print you did it! otherwise

**Comment by flashcode** [comment]
Hi @pascalpoitras,

As adding measures in trigger for each step can slow down a bit, I propose to add timings in the trigger monitor buffer, but only if debug is set for trigger plugin (debug level ≥ 1).
I think most users don't need to see these measures by default.

This would give something like that:

```
modifier | cmd_pass (5000|input_text_display;5000|history_add;5000|irc_command_auth)
         |   pointers:
         |   extra_vars:
         |     tg_trigger_name: "cmd_pass"
         |     tg_modifier: "input_text_display"
         |     tg_modifier_data: "0x55ff76647000"
         |     tg_string: "jjj"
         |     tg_string_nocolor: "jjj"
         |   regex 1 (tg_string): "jjj"
         |   elapsed: init=0.000874s, conditions=0.000000s, regex=0.000106s, command=0.000001s, total=0.000981s 
```

Measures are in seconds, with microsecond precision.
In the example, the modifier "cmd_pass" takes almost 1 millisecond to execute, and most of time is passed in the init phase (preparation of hash tables for the next steps).

As it's enabled in debug only, I don't plan to make these timings available in the evaluated expressions (conditions, regex, command), is that really needed?
If really needed, I could make the elapsed time until start of command (ie: init + conditions + regex) available in the command itself, eg: `${if:${trigger_elapsed_time} > 0.01?slow:fast}`.

**Comment by pascalpoitras** [comment]
yes in trigger monitor is plenty enough, thank you

**Comment by flashcode** [comment]
I will also add a trigger context id for each trigger run, because sometimes trigger command runs other triggers, so the "elapsed" message can be displayed later, and it becomes difficult to know which trigger it refers to.

This trigger id will be displayed in the prefix of each message displayed in monitor buffer.
A new option "trigger.color.identifier" controls the color of this identifier (cyan by default).

For example:

![image](https://user-images.githubusercontent.com/1776783/184609299-c31ec5be-e111-4693-a2ae-428f167f8f24.png)

In this example, the second "elapsed" line (id 131) refers to a command trigger that started a few lines above (not on the screenshot).
