### ISSUE TITLE
irc_server_isupport fails on WHOX

### ISSUE THREAD

**Issue by KoraggKnightWolf** [weechat/weechat#1807]
## Bug summary

When using /eval -n ${info:irc_server_isupport,localhost,WHOX} on an UnrealIRCd 6.0.3 network, which supports and advertises WHOX in 005, this keeps on returning the empty value. However when trying on e.g. KNOCK which is also supported and has no parameters in its token, the expected output 1 is generated. Potentially related to https://github.com/weechat/weechat/pull/1793 although the network also has account-notify and away-notify and both are enabled when using /cap list.

## Steps to reproduce

1. Connect to a network with WHOX support (and account-notify and away-notify to bypass https://github.com/weechat/weechat/pull/1793) (tested on UnrealIRCd-6.0.3)
2. Execute /eval -n ${info:irc_server_isupport,localhost,WHOX} (replacing localhost with the actual server name)
3. Observe the result being an empty value
4. Execute /eval -n ${info:irc_server_isupport,localhost,KNOCK} (replacing localhost again with the actual server name, Unreal supports KNOCK and WHOX)
5. Observe the result being 1.

## Current behavior

When using irc_server_isupport to retrieve information about 005 tokens it seems to fail on the WHOX token but work on others. 

## Expected behavior

irc_server_isupport should also return 1 on WHOX when it is advertised in 005.

## Additional information

---

- WeeChat version: 3.7-dev
- OS, distribution and version: Ubuntu 22.04
- Terminal: Konsole
- Terminal multiplexer (screen/tmux/…/none): Tmux

**Comment by flashcode** [comment]
Right, this is caused by an item being at the end of isupport and without value.
I'll improve the search in isupport to fix this.
