### ISSUE TITLE
weird behavior when both an input_text_display modifier trigger and debug for trigger plugin are enabled

### ISSUE THREAD

**Issue by pascalpoitras** [weechat/weechat#1810]
## Bug summary

Weird issue (that has nothing to do with #1806 because it also happens in 3.6). When you enable debug for trigger, if you have any input_text_display modifier, the monitor buffer will open automatically and you will not be able to close it. It might does that for other modifier but at least not for weechat_print

## Steps to reproduce

1. weechat -t
2. `/debug set trigger 1`
3. monitor buffer should open automatically because cmd_pass is a input_text_display modifier
4. press 'q' in the monitor buffer 
5. can't close it
6. `/trigger disable -all`
7. press 'q' in the monitor buffer
8. works now
9. `/trigger enable beep`
10. monitor buffer will not open
11. `/trigger enable cmd_pass`
12. monitor buffer will now open

## Current behavior

weird behavior, I mean, maybe it's normal to display the monitor buffer when debug is set to 1 since the monitor buffer is all about debugging your trigger, but if that's the case, why it works only for that modifier

---

- WeeChat version: 3.7
- OS, distribution and version: deb 11
- Terminal: kitty
- Terminal multiplexer (screen/tmux/…/none): tmux

**Comment by pascalpoitras** [comment]
finally I'm wrong, it's not about default vs custom (It doesnt do that for the beep trigger, and if you copy cmd_pass to cmd_pass2 it does the same) it seems to do that only for the input_text_display modifier

**Comment by flashcode** [comment]
When debug is enabled, the monitor buffer is opened as soon a trigger is running, there's no difference between a default trigger and a user trigger (by the way trigger just creates some triggers by default, but they run exactly like your own triggers).

So this is the right behavior for me.
Did I miss something?

**Comment by pascalpoitras** [comment]
ah I got it, thanks
