### ISSUE TITLE
Cannot receive DCC in Termux

### ISSUE THREAD

**Issue by ImperialXeno** [weechat/weechat#1811]
## Bug summary
I am using termux. 
When receiving DCC it returns following error:
`xfer: invalid address "96747949": error 8 hostname nor servname provided, or not known`

## Additional information
I have forced ipv4 since ipv6 gave the same error but with different address. 

- WeeChat version: 3.6

**Comment by flashcode** [comment]
Hi,

Interesting, I can reproduce.

This seems specific to termux, it works fine on desktop to receive a file (I tested with Debian Sid).
