### ISSUE TITLE
Only the first /wait in irc.server.<server>.command executes

### ISSUE THREAD

**Issue by killerrabbit** [weechat/weechat#1813]
## Bug summary

Only the first /wait in irc.server.\<server\>.command executes. Any after the first are ignored.

## Steps to reproduce

1. Set a server to use multiple waits in a command setting. E.g. 
```irc.server.bitlbee.command = "/wait 10 /msg &bitlbee acc telegram-tdlib on;/wait 20 /msg &bitlbee acc steam on"```
2. Connect to that server

## Current behavior

Only the first wait command is executed

## Expected behavior

Both wait commands to be executed

## Additional information

---

- WeeChat version: 3.5
- OS, distribution and version: Arch Linux
- Terminal: konsole
- Terminal multiplexer (screen/tmux/…/none): screen

**Comment by flashcode** [comment]
Hi,

I tested with exactly your command with versions 3.6 and 3.5, it works fine for me: first command executed after 10 seconds, the other after 20 seconds.

Can you please double check that the commands are actually executed?
You can also check in IRC raw messages: `/server raw`.

**Comment by killerrabbit** [comment]
It is working correctly. Had a filter that was filtering the 2nd message and didn't realize it.
