### ISSUE TITLE
numeric 350 is not formatted properly.

### ISSUE THREAD

**Issue by KoraggKnightWolf** [weechat/weechat#1815]
## Bug summary

It appears that weechat does not format irc_350 properly (RPL_WHOISGATEWAY). This is mainly used by InspIRCd-3 when users are connecting via a webircgateway (clients that negotiated WEBIRC successfully).

## Steps to reproduce

1. Connect to an InspIRCd-3 network with weechat which has the cgiirc module loaded and configured for a WEBIRC client e.g. KiwiIRC
2. Connect a test client over a client which has WEBIRC enabled for that network 
3. Have weechat run /whois on the testuser
4. Observe how the RPL_WHOISGATEWAY is not properly formatted (yet appears correctly along in the WHOIS response numerics)
## Current behavior

weechat does not properly format irc_350 in the "style" of other WHOIS responses, even though it is correctly grouped with them

## Expected behavior

Have irc_350 also formatted in the "style" of the regular WHOIS response output.

## Additional information

a RAW 350 aka RPL_WHOISGATEWAY has the following raw IRC format:

22:29 --> pounce-icq-chat @time=2022-09-02T20:29:16.562Z :irc-ca01.icq-chat.com 350 Koragg blahodat * * :is connected via the webircgateway WebIRC gateway

As pointed out in https://defs.ircdocs.horse/defs/numerics.html#rpl-whoisgateway-350 the first * represents the user's real hostmask and the second * the user's real IP address. as a regular user, one cannot see those, only opers can, and regular users see a * for each instead. Also the token webircgateway above is the name of the actual webirc gateway the client is utilizing.

---

- WeeChat version: v3.6-73-g223eefef6
- OS, distribution and version: Ubuntu 22.04.1
- Terminal: Konsole
- Terminal multiplexer (screen/tmux/…/none): tmux

**Comment by flashcode** [comment]
Proposed change (the displayed message has host coloring between square brackets):

```
# only stars
--> :test.ircd 350 nick bob * * :is connected via the test WebIRC gateway
[bob] is connected via the test WebIRC gateway

# only real hostmask
--> :test.ircd 350 nick bob host.example.com * :is connected via the test WebIRC gateway
[bob] (host.example.com) is connected via the test WebIRC gateway

# only real IP
--> :test.ircd 350 nick bob * 1.2.3.4 :is connected via the test WebIRC gateway
[bob] (1.2.3.4) is connected via the test WebIRC gateway

# real hostmask + real IP
--> :test.ircd 350 nick bob host.example.com 1.2.3.4 :is connected via the test WebIRC gateway
[bob] (host.example.com@1.2.3.4) is connected via the test WebIRC gateway
```

**Comment by flashcode** [comment]
Finally a comma is used to separate the real hostmask from real IP:

```
# real hostmask + real IP
--> :test.ircd 350 nick bob host.example.com 1.2.3.4 :is connected via the test WebIRC gateway
[bob] (host.example.com, 1.2.3.4) is connected via the test WebIRC gateway
```
