### ISSUE TITLE
How to change the color of the hotlist_low buffer number in the hotlist?

### ISSUE THREAD

**Issue by lifepillar** [weechat/weechat#1818]
## Question

After:

    /set buflist.format.hotlist_low "${color:red}"

I see that the buffer with hotlist level “low” (weechat) in the buffer list changes to red. But the color of the buffer number in the hotlist does not change (see attached screenshot). How do I customize that part of the hotlist?
<img width="379" alt="hotlist-low" src="https://user-images.githubusercontent.com/1193314/188509394-be4224ca-8d94-49d5-8dd6-b1f6edc9c80c.png">

---

- WeeChat version: 3.5

**Comment by flashcode** [comment]
Hi,

You can configure the hotlist colors via these options:

```
weechat.color.status_count_highlight  color  magenta     
weechat.color.status_count_msg        color  brown       
weechat.color.status_count_other      color  default     
weechat.color.status_count_private    color  green       
weechat.color.status_data_highlight   color  lightmagenta
weechat.color.status_data_msg         color  yellow      
weechat.color.status_data_other       color  default     
weechat.color.status_data_private     color  lightgreen  
```

**Comment by lifepillar** [comment]
`weechat.color.status_data_other` is the setting. I thought I had tried that, too, but probably I had missed it. Thanks!
