### ISSUE TITLE
Add support for cap-notify

### ISSUE THREAD

**Issue by Mikaela** [weechat/weechat#182]
* https://github.com/ircv3/ircv3-specifications/blob/master/extensions/cap-notify-3.2.md

> The cap-notify client capability allows a client to be notified when the client capability offering (i.e. capabilities listed in CAP LS) on a server changes.

> When enabled, the server MUST notify clients about all new capabilities and about existing capabilities that are no longer available via the messages specified in this document.

If I have understood correctly, cap-notify must be supported by IRCd and client before ZNC can add support for capabilities like account-notify, away-notify account-tag etc.

* https://github.com/znc/znc/issues/315#issuecomment-50795331
* https://github.com/znc/znc/issues/607#issuecomment-50371439

**Comment by maxteufel** [comment]
Temporary solution as a script (not tested with a real IRCd/bouncer due to lack of support): <https://raw.githubusercontent.com/maxteufel/code/master/irc/weechat/cap-notify.py>

**Comment by Mikaela** [comment]
Cap-notify is becoming more important now as it's required by SASL3.2 which introduces SASL REAUTH.
* https://github.com/ircv3/ircv3-specifications/blob/master/extensions/sasl-3.2.md

IRCv3.2 is expected to be released at end of this month.

**Comment by Mikaela** [comment]
ZNC has PR on cap-notify now https://github.com/znc/znc/pull/957.

**Comment by Mikaela** [comment]
And ZNC has merged https://github.com/znc/znc/pull/957 so for WeeChat to be able to use `away-notify` and similar capabilities, WeeChat must add support for `cap-notify`

`cap-notify` is also required for SASL 3.2 (REAUTH) https://github.com/weechat/weechat/issues/413 which would also be important.

**Comment by Mikaela** [comment]
Extended-join https://github.com/znc/znc/commit/6246899c56e7b69797bd000b68eda0d503fcd73d and account-notify https://github.com/znc/znc/commit/d070a6e644349dd75222b32f24c06168db777181 are in ZNC master now and also require cap-notify in order to be enabled.

**Comment by maxteufel** [comment]
<https://github.com/maxteufel/weechat/tree/feature/cap-notify> should work, but I'd like some feedback before I open a pull request. Doesn't support SASL Reauth.

**Comment by flashcode** [comment]
Pull request: #477

**Comment by Mikaela** [comment]
It looks like https://github.com/weechat/weechat/pull/477 was finally merged.

Thanks @FlashCode :smile:
