### ISSUE TITLE
colored filter list

### ISSUE THREAD

**Issue by ksu-0** [weechat/weechat#1820]
It would be nice if `/filter list` marked filter components and enabled/disabled status of filters with colors, like `/trigger list` does.

**Comment by flashcode** [comment]
Done with two new options:

- weechat.color.chat_status_disabled (default: `red`)
- weechat.color.chat_status_enabled (default: `green`)

The trigger plugin is now using these two options for trigger statuses, so these two options are removed:

- trigger.color.trigger
- trigger.color.trigger_disabled
