### ISSUE TITLE
Close buffer and window, but only if it's not the only one

### ISSUE THREAD

**Issue by lifepillar** [weechat/weechat#1822]
## Question

I have this key binding:

    /key bind meta-q /buffer close; /window close

I typically use this on a split window, to close both the window and its buffer. The key binding works also when there is only one window, except that `/window close` logs an error message in the weechat buffer. Is it possible to change the key binding so that `/window close` is executed only if there is more than one window?

---

- WeeChat version: 3.7-dev

**Comment by flashcode** [comment]
Hi @lifepillar,

An alternate solution is to mute the command so that the error is never displayed: `/mute /window close`.

**Comment by lifepillar** [comment]
Thanks, that does it!

Out of curiosity, is there a way to get the number of open windows?

**Comment by flashcode** [comment]
Yes you can display the number of windows in the current buffer with this command:

    /eval -n ${window[last_gui_window].number}

You can also run the close command only if there are more than one window, and run `/mute` in the other case (it does nothing):

    /eval ${if: ${window[last_gui_window].number}>1?/window close:/mute}

**Comment by lifepillar** [comment]
Super cool, thanks. Those two lines teach me quite a lot!
