### ISSUE TITLE
Disabling highlights on one nick in one buffer?

### ISSUE THREAD

**Issue by ncfavier** [weechat/weechat#1829]
## Question

I have `weechat.look.highlight` set to `foo,bar,qux`. In the channel `irc.libera.#qux`, which mentions `qux` a lot, I'd like not to get pinged on the word `qux`. My first thought was to use `/buffer set highlight_words_del qux` (and automate that with `buffer_autoset`), but that does not seem to work because the default value of `highlight_words` is `$nick`, not `foo,bar,qux`. I would have to `set highlight_words foo,bar`, which is unpleasant.

What is the intended way to remove words from `highlight_words` on a specific buffer?

---

- WeeChat version: 3.6
- OS, distribution and version: NixOS

**Comment by flashcode** [comment]
Hi,

In version 3.7 (in dev, release scheduled soon), a new option has been added: `weechat.look.highlight_disable_regex`, as well as a local buffer variable `highlight_disable_regex` to disable highlights based on a regex, I think this is exactly what you're looking for.

See #1798.

**Comment by ncfavier** [comment]
Perfect, thanks.
