### ISSUE TITLE
Is search text in buffer FAQ entry still correct?

### ISSUE THREAD

**Issue by balazser** [weechat/weechat#1845]
## Question
With the default `weechat` keybindings, I'm following the hints in the FAQ about searching.
For some reason, jumping to the next/prev highlights does not work, according to the FAQ.
Is the FAQ outdated, or do I misunderstand something?

```
3.18. How can I search text in buffer (like /lastlog in irssi)?

The default key is Ctrl+r (command is: /input search_text_here). And jump to highlights: Alt+p / Alt+n.
```
**Steps**
1. I search for a phrase using `ctrl + r` that works.
2. Try to go to the next/previous match, which got highlighted using `Alt+p / Alt+n`

---

- WeeChat version: 3.7.1
- OS, distribution and version: Debian GNU/Linux 11 (bullseye)

**Comment by trygveaa** [comment]
It's a bit unclear wording here. It's about two different things. You can search with Ctrl+r, and in search context these key bindings apply: https://weechat.org/files/doc/stable/weechat_user.en.html#key_bindings_search_context

But you can also jump to highlights without searching. What is meant by highlights is not the search results, but the lines highlighted according to your config (typically when your nick is mentioned). So Alt+p/n is meant to be pressed when not in a search.

**Comment by balazser** [comment]
I see. Thank you for your quick reply, @trygveaa.
