### ISSUE TITLE
a signal emitted when the input and close callback are triggered

### ISSUE THREAD

**Issue by pascalpoitras** [weechat/weechat#1848]
## Feature description

As discussed with FlashCode, I would like to be able to catch a signal when the input and close callback are triggered

Using a input_text_for_buffer modifier is kind of ugly, spamming the trigger monitor buffer

**Comment by flashcode** [comment]
Done with two new signals, sent for buffers created with `/buffer add <name>`:

* `buffer_user_input_<name>`
* `uffer_user_closing_<name>`

For more information: https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#hook_signal_buffer_user_input_xxx
