### ISSUE TITLE
Package missing error dispite being installed on Fedora

### ISSUE THREAD

**Issue by pcroland** [weechat/weechat#1851]
## Bug summary

`cmake ..` fails with the following error messages:
![img](https://telegra.ph//file/bc67c4802675aada5c065.png)

## Steps to reproduce

1. Be on Fedora 36
2. Install every dependency including recommended ones
3. `cmake ..`

## Additional information

```
Last metadata expiration check: 3:16:36 ago on Mon 14 Nov 2022 05:16:32 PM CET.
Package php-8.1.12-1.fc36.x86_64 is already installed.
Package php-devel-8.1.12-1.fc36.x86_64 is already installed.
Package aspell-devel-12:0.60.8-9.fc36.x86_64 is already installed.
Package enchant-aspell-1:1.6.0-30.fc36.x86_64 is already installed.
Package enchant2-aspell-2.3.2-5.fc36.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
```

---

- WeeChat version: latest
- OS, distribution and version: Fedora 36
- Terminal: `zsh 5.8.1 (x86_64-redhat-linux-gnu)`
- Terminal multiplexer (screen/tmux/…/none): `tmux 3.3a`

**Comment by flashcode** [comment]
Hi,

I don't know on Fedora, but on Debian you also have a package called `libphp8.1-embed`, is there such package in Fedora repository?

**Comment by pcroland** [comment]
```sh
sudo dnf install php-embedded
```
Solved this issue, but sub-command regex one stayed:
![img](https://telegra.ph//file/e22b3a8de135f37685dca.png)

**Comment by flashcode** [comment]
What's your CMake version?

**Comment by pcroland** [comment]
```sh
cmake --version
cmake version 3.24.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by pcroland** [comment]
`perl-ExtUtils-Embed` solved it. thanks for the helps.

**Comment by flashcode** [comment]
OK, so I close the issue.

**Comment by pcroland** [comment]
Would you create a Fedora section on the building wiki if I were to gather all the packages needed?
