### ISSUE TITLE
Bouncer with letsencrypt certificate is not trusted

### ISSUE THREAD

**Issue by hgl** [weechat/weechat#1853]
## Bug summary
My bouncer uses letsencrypt certificate, and when I tried to connect to it, weechat complained that `gnutls: peer's certificate is NOT trusted`. I think I know why it was not trusted. Let me explain:

The certificate chain is like this

```
Certificate < – R3 < – ISRG Root X1 < – DST Root CA X3
```

My system CAs don't contain `DST Root CA X3`, but do contain `ISRG Root X1`. I think it's very likely that `gnutls` only tries to find the former, but not the later.

When I access the bouncer via https, the browser shows the certificate chain stopping at `ISRG Root X1`.

Is it possible to ask `gnutls` to find the trust anchor in the middle of the chain?

---

- WeeChat version: 3.7.1
- OS, distribution and version:  nixos
- Terminal: 
- Terminal multiplexer (screen/tmux/…/none):

**Comment by ksu-0** [comment]
What is your GnuTLS version? What does `gnutls-bin` complain about when connecting to the bouncer? What, if anything, does `openssl s_client` complain about when connecting to the bouncer?
