### ISSUE TITLE
read marker 1 char too short

### ISSUE THREAD

**Issue by ksu-0** [weechat/weechat#1862]
## Bug summary

With right bar (such as nicklist) present, read marker is one character too short.

## Steps to reproduce

* `/set weechat.look.read_marker_always_show on`
* `/set weechat.color.chat_read_marker_bg yellow`
* switch to buffer with nicklist

## Current behavior

Read marker is one character too short.

## Expected behavior

Read marker extends to the right bar.

## Additional information

- WeeChat version: 3.8-dev (git: v3.7-64-g5b9b1e175)
- OS, distribution and version: Debian testing
- Terminal: xfce4-terminal
- Terminal multiplexer (screen/tmux/…/none): none

**Comment by flashcode** [comment]
In fact not only the read marker but also messages in chat area stop one char before the bar separator (here nicklist):

![image](https://user-images.githubusercontent.com/1776783/208179029-252bd883-c703-456f-9393-4915b47346d2.png)

If I remember, I did that to let you select text without selecting separator and nicklist (when you double click a word):

![image](https://user-images.githubusercontent.com/1776783/208179157-df9f7372-ce6c-4c40-8c1c-f6f30f62c14e.png)

Anyway it seems recent terminals are able to properly select text, even if no space is there.

Here is the code doing this: https://github.com/weechat/weechat/blob/master/src/gui/curses/gui-curses-chat.c#L49

```C
/*                                                                                                   
 * Gets real width for chat.                                                                         
 *                                                                                                   
 * Returns width - 1 if nicklist is at right, for good copy/paste (without                           
 * nicklist separator).                                                                              
 */
   
int
gui_chat_get_real_width (struct t_gui_window *window)
{
    if ((window->win_chat_width > 1)
        && (window->win_chat_x + window->win_chat_width < gui_window_get_width ()))
        return window->win_chat_width - 1;
    else
        return window->win_chat_width;
}
```

Question is: when should WeeChat display a space before the bar separator:

* never?
* only the text and not the read marker?
* both text and read marker? (current behavior)

**Comment by ksu-0** [comment]
I think that the combination of conditions where final word in line appearing next to the bar separator is an issue for the user is far too rare and easy to workaround to effectively not use the final column of the chat area.

**Comment by flashcode** [comment]
So you suggest to always use the last char, for both text and read marker?

**Comment by ksu-0** [comment]
Yes, I would suggest so.

**Comment by flashcode** [comment]
Done with a new option `weechat.look.chat_space_right`.
Default is `off`, so that the space is not displayed any more by default, toggling the option to `on` restores the old behavior.
