### ISSUE TITLE
WeeChat 3.8 crashes when using go.py if typing status is enabled for self messages

### ISSUE THREAD

**Issue by multiplexd** [weechat/weechat#1869]
## Bug summary

I upgraded to WeeChat 3.8 earlier today, and since upgrading I've had reliable crashes when using go.py interactively when the typing status plugin is enabled.

## Steps to reproduce

1. Install go.py in WeeChat 3.8.
2. Enable typing status for self messages (i.e. `/set typing.look.enabled_self on`).
3. Ensure that WeeChat has multiple buffers open (e.g. joined to multiple IRC channels).
4. Invoke `/go` without arguments to start interactive buffer selection, and then press the tab key (which triggers the comand `/input complete_next`).

## Current behavior

Pressing tab within the `/go` interactive buffer selection causes WeeChat 3.8 to crash with a segfault.

## Expected behavior

Pressing tab within the `/go` interactive buffer selection moves the highlight to the next candidate buffer.

## Additional information

I was able to get a core file, and it appears that the typing status plugin tries to dereference an invalid pointer. The offending stack frame (taken from a WeeChat build with debug symbols) looks like this:

```
(gdb) up 5
#5  0x00007fd866e9e3d2 in typing_input_text_changed_signal_cb (pointer=0x0, data=0x0, signal=0x7fd8651097e0 "input_text_changed", type_data=0x7fd8650ad0a0 "string", 
    signal_data=0x7fd8653066a0) at typing.c:124
124         input_valid = (ptr_input && ptr_input[0]) ?
(gdb) info locals
text_search = 0
input_valid = 32728
ptr_input = 0x2 <error: Cannot access memory at address 0x2>
ptr_input_for_buffer = 0x560717c028e2 ""
ptr_buffer = 0x7fd8653066a0
ptr_typing_status = 0x7fd8651097e0
```
Note that `ptr_input` (retrieved from `signal_data` as a GUI buffer struct) is 2, which is invalid. I suspect that the GUI buffer structure passed into the hook handler is invalid.

I had some free time, so I ran a git bisect, and first commit in which this behaviour is observable is bab73cfaa5db96494a1b96b85c9eac9e7680854d. This commit introduces a new `next_line_id` member to `struct t_gui_buffer`, so it seems that changes to the struct layout might be causing this issue somehow.

---

- WeeChat version: 3.8 (installed from weechat.org Debian repository)
- OS, distribution and version: Debian 11
- Terminal: LXTerminal
- Terminal multiplexer (screen/tmux/…/none): Reproduced both inside and outside of tmux.

**Comment by flashcode** [comment]
Hi,

I checked the commit you pointed, which seems OK (nothing seems forgotten in structures and functions using them).
Also I can not reproduce the crash.
Are you sure you use the same version for WeeChat and the typing plugin?

Can you please try with a default config, and give me the exact steps to reproduce (all the commands)?

Thanks.

**Comment by multiplexd** [comment]
> I checked the commit you pointed, which seems OK (nothing seems forgotten in structures and functions using them). Also I can not reproduce the crash, even with the address sanitizer. Are you sure you use the same version for WeeChat and the typing plugin?

As far as I can tell the typing plugin version should match. I've reproduced this issue with both the upstream Debian packages published under the repo at https://weechat.org/debian (`weechat`, `weechat-core`, `weechat-curses`, `weechat-plugins`, and `weechat-python` are what I have installed), and with a source build of WeeChat installed to a temporary directory.

> Can you please try with a default config, and give me the exact steps to reproduce (all the commands)?

Minimal reproduction instructions:
1. Run `weechat -t` to run WeeChat with an ephemeral home directory (and default settings).
2. `/set script.scripts.download_enabled on`
3. `/script install go.py`
4. `/set typing.look.enabled_self on`
5. `/go`
6. Press the tab key.

This reliably causes a segfault for me.

**Comment by flashcode** [comment]
I can reproduce, but only with the package installed from weechat.org, not by compiling sources, which makes not debug easy.

Which kind of cmake build are you doing, debug or release?

**Comment by flashcode** [comment]
If you are able to reproduce with a custom build and have a core file, please join #weechat on libera I'll assist you with commands to dig into the core file and find the possible guilty pointer (according to what you reported, I think the bug is somewhere and it crashes here because you have garbage data in the buffer).

**Comment by multiplexd** [comment]
Ah, I was building with autotools (both with and without `--with-debug`); building with cmake I can reproduce the crash with both `Release` and `Debug` builds (though I'm not very familiar with cmake's build profile functions). I'll drop by on IRC.

**Comment by flashcode** [comment]
So the main bug was in script go.py, which does not send the buffer pointer with signal "input_text_changed", and typing was relying on this buffer pointer, without checking:

```python
        weechat.hook_signal_send('input_text_changed',                   
                                 weechat.WEECHAT_HOOK_SIGNAL_STRING, '') 
```

Must be replaced by (2 occurences):

```python
        weechat.hook_signal_send('input_text_changed',                    
                                 weechat.WEECHAT_HOOK_SIGNAL_POINTER, buf)

```

Scripts go.py and histsearch.py have been updated accordingly in the repository, and an extra protection has been added in typing plugin.
