### ISSUE TITLE
Make most WeeChat identifiers case sensitive

### ISSUE THREAD

**Issue by flashcode** [weechat/weechat#1872]
## Feature description

Many WeeChat identifiers are currently case insensitive, for example: configuration files/sections/options, command names and parameters, completion, etc.

Most of them should be case sensitive so that for example an alias `/AWAY` would be different from the `/away` command, or a parameter in upper case would be different as well, eg: `/test -o` is different from `/test -O`.

Specification: https://specs.weechat.org/specs/2023-001-case-sensitive-identifiers.html

**Comment by weechatter** [comment]
I like the idea of having two different command like, /AWAY and /away. Autocompletion should be more strict, as described in the specs.
