### ISSUE TITLE
A way of putting the password AND the nick used in authentication before starting the program

### ISSUE THREAD

**Issue by AmyAmie** [weechat/weechat#1896]
## Feature description
For example, using a flag, "-n" for the nick, and "-p" for the password, for example, so the command could be:
`weechat -n "User" -p "SuperSecretPassword!483841"`

**Comment by flashcode** [comment]
Hi,

User and password for IRC? IRC is just a plugin, so there's no global flag for this, and it's not planned to add such flags.

What's your use case?

By the way there's already a syntax to directly connect to an IRC server by specifying nick and password:

    irc://nick:password@irc.libera.chat/#weechat

By the way, command-line parameter `-p` is already used (to run without loading plugins).
