### ISSUE TITLE
Problem/Question: can't add client certificate because it thinks it is from a server

### ISSUE THREAD

**Issue by AmyAmie** [weechat/weechat#1897]
## Question

So, I'm trying to add a client certificate with "/quote ns cert add [myUsername] [myFingerprint]", but it says "Your not using a client certificate", I already tried to convert it to base64 but it didn't worked. What can I do?

---

- WeeChat version: 3.8
- OS, distribution and version: GNU/Linux, Arch Linux, build 18 Mar 2023,

**Comment by flashcode** [comment]
Hi,
You could check the IRC server documentation or this one in WeeChat (it was tested with OFTC only): https://weechat.org/files/doc/devel/weechat_user.en.html#irc_connect_oftc_with_certificate

**Comment by flashcode** [comment]
Closing the issue, feel free to comment if needed.
