### ISSUE TITLE
Automatically scroll less frequently seen buffers to bottom

### ISSUE THREAD

**Issue by tatokis** [weechat/weechat#1899]
## Feature description

Every now and then, I scroll up on a buffer, switch to a different one and forget about it, until sometimes a few days later. When I switch back to said buffer to see new messages, having forgotten it was scrolled up, I assume that the messages I am seeing are new, when they actually are not. This can get confusing sometimes.

The idea is to only autoscroll buffers all the way down after not having looked at them for a certain period of time. Ideally this threshold will be configurable.

A possible implementation (assuming, for good user experience, it doesn't result in the scrolling action being visible on buffer change) could be:

1. Store a monotonic timestamp that is associated with a buffer every time the user explicitly scrolls.
    * When they stop scrolling, the field will have the most recent timestamp stored.
    * If there is an event that is fired when a user switches away from a buffer, if the buffer is not scrolled down, that can be used to store the timestamp instead.
2. On buffer change, compare the previously recorded timestamp with the current monotonic timestamp for the new active buffer.
3. If the buffer is not scrolled all the way down, and the difference is above the user-set threshold, automatically scroll to the bottom.

**Comment by flashcode** [comment]
Hi @tatokis,

I just realized there's already an option to do that, but with no configurable delay:

    /set weechat.look.scroll_bottom_after_switch on

After each buffer switch, if the buffer has formatted content, it is auto scrolled to the bottom.

Is it enough for you?

If not, this option could be transformed to integer with the possible following values:

- `-1`: never scroll to bottom (like the option to `off`)
- `0`: scroll to bottom with no delay (on each buffer switch) (like the option to `on`)
- any positive integer: number of seconds after which WeeChat will auto-scroll to bottom, for example `300` = scroll to bottom if the buffer has been scrolls at least 5 minutes ago (or more).

The new default value needs to be chosen.
If we want to keep the same behavior, `-1` would be the default value (as the current option is `off` by default).
But I think a positive integer would be nice to have as well. Maybe `300` (5 minutes) would be a good default value? After 5 minutes, we can consider the user has finished any scroll and forgot to scroll to bottom.

**Comment by trygveaa** [comment]
> The new default value needs to be chosen.

IMO, it should definitely not scroll by default. I think it would be very confusing for users if their buffers were suddenly scrolled to the bottom for no apparent reason.

The way i use it is that I keep it scrolled up if there's something I haven't finished reading, and then go back to it to read the rest later, so personally I would never want it to scroll automatically. I would guess that's a more common case than forgetting that a buffer is scrolled up, but don't have anything to base that guess on.
