### ISSUE TITLE
Support building docs without all plugins 

### ISSUE THREAD

**Issue by kattjevfel** [weechat/weechat#1901]
## Feature description

As of 6dbfb638c6586905b3b29df9cf1e41d9166546ef all plugins are now required to build docs. However at least on arch linux it seems impossible to make weechat find php (it has been disabled in the arch repo packge [since 2019](https://github.com/archlinux/svntogit-community/commit/d1a10ceebeccdceb1b1b5918efb8126fe7dc1ccd) because of this) and thus it has been disabled. 

Building the docs have been fine until the above mentioned commit, but now I'd have to disabled building docs or possibly patch out `OR NOT ENABLE_PHP`, which I'm not sure would even produce great results.

Not sure if this should be a feature request or bug report, so correct me if I set it wrong :)

**Comment by trygveaa** [comment]
Hm, I can build with php fine on Arch Linux. Do you have `php-embed` installed?

**Comment by flashcode** [comment]
Now the auto-generated files are built during compilation (using `weechat-headless`), that means WeeChat must be running with all plugins loaded.

If some plugins are not loaded, the files will be incomplete, and the doc will lack for example PHP command and options (I also enabled an option in asciidoctor to make the build fail if any included file is missing, but I can revert this).

So, two points:

1. If PHP is disabled, this should be fixed, this is a separate issue.
2. If you really want incomplete docs, I can make asciidoctor ignore warnings and remove checks on enabled plugins in CMake. But I'm not very fan of this, you'll have incomplete info in docs (only user's guide and Plugin API reference are concerned, but the new way to build docs prevents all docs from building if at least one plugin is missing).

**Comment by kattjevfel** [comment]
> Hm, I can build with php fine on Arch Linux. Do you have `php-embed` installed?

That gets it to at least detect php, but fails nevertheless, either way that is a separate issue, I do want incomplete docs.

**Comment by flashcode** [comment]
Then maybe I could introduce an option to force this.
I prefer the build to fail by default instead of having incomplete docs and not being warned.

Something like this:

    cmake -DENABLE_PHP=OFF -DENABLE_DOC=ON -DENABLE_DOC_INCOMPLETE=ON

Would that be OK for you?

**Comment by flashcode** [comment]
Hmm… that's not so easy, as the new CMake target doc-autogen depends on the build of all plugins (they must be built before `weechat-headless` is executed).

And not easy to have dynamic "depends" here.

**Comment by flashcode** [comment]
I managed to do it, the option has been added.
So by giving the option, you are aware you'll have incomplete docs.
