### ISSUE TITLE
Cannot connect to relay after upgrading Letsencrypt certificate from RSA to ECDSA 

### ISSUE THREAD

**Issue by jmui** [weechat/weechat#1919]
## Bug summary

Cannot connect to relay after upgrading Letsencrypt certificate from RSA to ECDSA using certbot. Not sure about the reason. Followed the same steps for years renewing and installing Letsencrypt certificates every 3 months.

## Steps to reproduce

1. Renew Letsencrypt RSA certificate using certbot
2. Choose option to update certificate to use ECDSA key type
3. cat {privkey,fullchain}.pem > relay.pem
4. Copy relay.pem into appropriate directory
5. /relay sslcertkey

## Current behavior

When I try connecting to the relay using GlowingBear, I receive the error: ""Secure connection error A secure connection with the WeeChat relay could not be initiated. This is most likely because your browser does not trust your relay's certificate. Please read the encryption instructions below!""

In my terminal in Weechat, I am getting this error: "relay: TLS handshake failed for client 1/ssl.weechat/(IP Address): error -87 No supported cipher suites have been found."

## Expected behavior

I should be able to connect to the relay using GlowingBear.

## Suggested solutions

Unsure of the solution. Would downgrading the certificate back to RSA work? I am at my limits for Letsencrypt renewal and cannot retry for a couple days.

---

- WeeChat version: 3.8
- OS, distribution and version: Ubuntu 22.04.2 LTS
- Terminal: MobaXterm v22.1
- Terminal multiplexer (screen/tmux/…/none): screen

**Comment by flashcode** [comment]
Hi,
Could please paste the output of `/debug libs` in WeeChat? (to check your version of GnuTLS)
Did you try a full restart of WeeChat, or at least `/upgrade`, and check after? (just in case `/relay sslcertkey` is not enough — but it should be).

**Comment by flashcode** [comment]
Can you try to set this (which is the default value of the option):

    /set relay.network.ssl_priorities "NORMAL:-VERS-SSL3.0"

**Comment by jmui** [comment]
That fix worked, thank you! Was SECURE256 excluding something that makes it not work with ECDSA certificates?

**Comment by flashcode** [comment]
I think so, 128 or 192 bits is a common length for Elliptic Curve algorithm, and it's considered as very secure. And "SECURE256" probably exclude these lengths.

And by looking at the GnuTLS doc, I'm not sure if another priority could match your ECDSA key: https://gnutls.org/manual/gnutls.html#Priority-Strings

Anyway, I think keeping the default value there is just safe as you control the WeeChat key (server side of relay).

Then I close the issue.
