### ISSUE TITLE
cannot switch between buffers

### ISSUE THREAD

**Issue by youngunix** [weechat/weechat#1921]
## Bug summary
Ctrl+X no longer works to switch between buffers.

## Steps to reproduce

1. start weechat
2. join a channel(s)
3. press Ctrl+X to switch between buffers

## Current behavior
Ctrl+X no longer works to switch between buffers.

## Expected behavior
pressing Ctrl+X should switch between buffers.

## Suggested solutions
none

## Additional information

---

- WeeChat version: 3.8
- OS, distribution and version: Gentoo 17.1
- Terminal: Terminator v2.1.2 & xfce4-terminal v1.0.4
- Terminal multiplexer (screen/tmux/…/none): none

**Comment by flashcode** [comment]
Hi,
The key ctrl-x works only on buffers which are merged, and channels are not.
Try to go to buffer #1 (alt-1), then press ctrl-x, this should switch between core buffer (core.weechat) and the IRC server buffer (and press again to switch to the next merged buffer).
I just tested with version 3.8, it works fine.

**Comment by youngunix** [comment]
Hi, 

That worked for me! However, what changed since it was working before the last update?

**Comment by flashcode** [comment]
This has not changed, ctrl-x has still the same behavior.

**Comment by youngunix** [comment]
I wasn't talking about the function of Ctrl+X, I was referring to any patches to the code that might have affected this function. Anyway, I'm closing this issue as solved.
