### ISSUE TITLE
Add support of IRCv3 draft/multiline capability

### ISSUE THREAD

**Issue by flashcode** [weechat/weechat#1923]
## Feature description

Add support of IRCv3 draft/multiline capability, spec: https://ircv3.net/specs/extensions/multiline

Development branch: https://github.com/weechat/weechat/tree/irc-multiline

Planned changes:

- All IRC channels and private buffers are multiline, ie `input_multiline` is set to `1` (even if draft/multiline is not enabed, because it's not safe to switch from enabled/disabled state); that means paste of multiple commands in a single message is not possible any more on these buffers. It remains possible at least on core buffer and IRC server buffers (and any buffer where `input_multiline` is not set to `1`).
- Capability `draft/multiline` relies on `batch` (already implemented via #1292) and is enabled by default, if the server advertises it upon connection (like all other capabilities).
- Multiline messages are sent immediately (no anti-flood mechanism, otherwise it could take a lot of time to send all messages).
- Color codes are kept as-is, if a multiline message is split into multiple batches, any active color/attribute will stop at the end of first batch and not go on with the next one.
- Action messages sent with `/me` command are **NEVER** sent as multiline, but separate action messages (the spec does not mention this yet, and it's a bit difficult to cut such messages in different batches, when max-bytes or max-lines is reached).

Could be implemented later (tracked in separate issue):

- A way to visually see if we are sending one or more commands or messages. The way to send multiple commands or lines depends on `input_multiline` and it's not easy in a buffer to know what WeeChat would send when pressing Enter. This could be one of:
  - Status bar item displayed as soon as there's a newline (`\n`) in input, like: `[cmd:3]` for 3 commands to send, `[msg:1]` for a single message to send.
  - Color in input for command names (like spell does for misspelled words).

**Comment by pascalpoitras** [comment]
also, on any buffers, no matter the value of input_multiline, you can force the input to be treated as differents lines by using `/input split_return`, so for example, if you paste a bunch of command on an IRC channel, use `/input split_return` to send these as multiple different lines
