### ISSUE TITLE
IRCv3 draft/multiline starting another line than the first with color doesn't work

### ISSUE THREAD

**Issue by pascalpoitras** [weechat/weechat#1928]
## Bug summary

If any lines other than the first start with a color code, it doesn't work

## Steps to reproduce

1. use ergo testnet
2. type the following in the input bar (in a channel)
3. <ctrl-c c 4>hello
4. alt+enter
5. <ctrl-c c 5>test
6. enter

## Current behavior

the second line is in color 4 too but it should be 5. It works if the color is not the first thing in the line tho

---

- WeeChat version: 4.0.0-dev
- OS, distribution and version: Debian 11
- Terminal: kitty
- Terminal multiplexer (screen/tmux/…/none): tmux

**Comment by flashcode** [comment]
This is not specific to irc-multiline and can be reproduce with these 2 commands on core buffer:

    /buffer set input_multiline 1
    /eval /print ${color:red}red${\n}${color:blue}blue

Both lines are in red, while the second one should be in blue.
