### ISSUE TITLE
How to mute output of all text in some channel?

### ISSUE THREAD

**Issue by d3vn0t** [weechat/weechat#1931]
## Question

Is there a way to mute all output in a channel? I thought that `/mute` command is for that, but I tried it and its not working. This is useful for XDCC channels were you have tons of output every second. If this is not possible with command maybe a simple python script example? Thanks.

---

- WeeChat version: 3.8
- OS, distribution and version: Linux

**Comment by flashcode** [comment]
Hi,

If by "mute" you mean you don't want the buffer to be part of the hotlist (the "H: …" item in status bar), then you should change the notify level of the buffer, see this doc: https://weechat.org/files/doc/weechat/stable/weechat_user.en.html#notify_levels

**Comment by flashcode** [comment]
All docs are here: https://weechat.org/doc/, see the Plugin API reference for more information.

**Comment by trygveaa** [comment]
If you want to filter all lines in a buffer:

```
/filter add buffer <buffer_full_name> * .*
```

If you really want to delete all the lines, so nothing can be printed to the buffer:

```
/trigger add filter_buffer line "" "${buffer.full_name} == <buffer_full_name>" "/.*//buffer"
```

Replace `<buffer_full_name>` with the full buffer name. Run `/buffer` to list all the full buffer names.

**Comment by trygveaa** [comment]
As for the scripts, you can't modify the lines with `hook_print` or `hook_signal`, you need to use `hook_line` or `hook_modifier` (but it's not necessary to write a script for this, as shown in the previous comment).

**Comment by trygveaa** [comment]
@d3vn0t: The `irc_in_privmsg` signal just gets the IRC message as sent by the server, so you'd need to parse it to find the channel name, and then map that to the buffer. Definitely not the easiest/best way to do this. I gave you the exact command you need, why not just use that?

**Comment by trygveaa** [comment]
The trigger command can be directly translated to a script:

```
from typing import Dict

import weechat


def my_line_cb(data: str, line: Dict[str, str]) -> Dict[str, str]:
    return {"buffer": ""}


if weechat.register("buffer_filter", "trygveaa", "0.1", "MIT", "", "", ""):
    weechat.hook_line("", "<buffer_full_name>", "", "my_line_cb", "")
```

**Comment by trygveaa** [comment]
I forgot about the function to parse IRC messages. That definitely makes your approach easier than I was thinking it would be.

> But is there a shorter command to get channels?

You mean get the channel for the signal in the callback? No, I don't think there is.

**Comment by trygveaa** [comment]
> Plus your code does not work, I just checked it like this. I still get output with your code.

As I said, you need to use the full buffer name, which can be listed by `/buffer`. That would start with `irc.`.

> Also how can I do similar with something like hook_print for example =) Is it even possible in weechat? In hexchat I used hook_print instead of hook_signal.

`hook_line` is what you would use, i.e. the script I posted. `hook_print` can't edit lines. See https://weechat.org/files/doc/stable/weechat_plugin_api.en.html#_hook_line which explains the difference.
