### ISSUE TITLE
How to remove buflist tabs padding on the right?

### ISSUE THREAD

**Issue by d3vn0t** [weechat/weechat#1932]
## Question

Is it possible to make buflist tabs not use padding on the right? So tabs will wrap around the names and take less space. Thanks.

---

- WeeChat version: 3.8
- OS, distribution and version: Linux

**Comment by flashcode** [comment]
Hi,
What do you call "tabs" in buflist? There are no "tabs" in this bar item.
Could you please provide a screenshot to explain what you want?
Thanks.

By the way feel free to ask directly on #weechat (irc.libera.chat), it's much faster to get an answer to your questions than on GitHub.

**Comment by flashcode** [comment]
This depends on the "filling" of the bar: if it has columns, the size of each column is the same, so there's no way to remove these spaces.

If the filling is "horizontal", there are no spaces, but no word wrapping in the bar, so this is not recommended either.

If you want a custom display, you can still write your own bar item in a script and display yourself the list of buffers.
