### ISSUE TITLE
Custom Time Toggle Not Working Properly

### ISSUE THREAD

**Issue by TheCaptainJackSparrow** [weechat/weechat#1936]
## Bug summary

Custom time format is not saved when `/toggle` option is used to set an option.

## Steps to reproduce

1. `/alias add time /mute /toggle weechat.look.buffer_time_format "${color:240}%I:%M:%S.%p"`
2. `/time` (will hide custom time format)
3. `/time` (when run again it will just reset to default time format `"%H:%M:%S"`

## Current behavior

Alias does not save custom time format when `/toggle` is used on `weechat.look.buffer_time_format`.

## Expected behavior

Save and restore custom time format.

## Suggested solutions

No idea!

## Additional information

None.

---

- WeeChat version: 3.8
- OS, distribution and version: i3-wm 4.22 on Linux
- Terminal: Terminator 2.1.3
- Terminal multiplexer (screen/tmux/…/none): none

**Comment by flashcode** [comment]
Hi,

What do you want to do?
If you want to toggle between different values, you must give all values to the `/toggle` command, like this:

    /toggle option value1 value2 ...

If you give only one value, then it toggles between this value and the default value of the option.

For me the command works as expected.

**Comment by flashcode** [comment]
No, this is not possible to customize time per buffer.
