### ISSUE TITLE
Interactive FSET Options

### ISSUE THREAD

**Issue by d3vn0t** [weechat/weechat#1937]
## Feature description

Ability to change options inside `fset` by simply pressing enter and typing the value. This eliminates the need typing long options by hand.

**Comment by flashcode** [comment]
Press `alt+enter` to edit the selected option (if that does not work, try `Esc` then `enter`).
Please see default key bindings here: https://weechat.org/files/doc/weechat/devel/weechat_user.en.html#key_bindings_fset_buffer

Please read the docs before opening issues on GitHub.
