### ISSUE TITLE
Blink Background or Foreground Color of BufList Tab on Private Message Received

### ISSUE THREAD

**Issue by d3vn0t** [weechat/weechat#1938]
## Feature description

Request for few options to have colors blink/flash on private message received. This can be achived with options like `weechat.bar.buflist.blink_color_bg` and `weechat.bar.buflist.blink_color_fg`. This can be optional of course, but once this options are set it will blink the private message tab (or button, whatever you want to call it) in buflist it will blink the colors. After you click on it, it should stop blinking. This can be similar to bash text blink. [1]

[1] https://misc.flogisoft.com/bash/tip_colors_and_formatting

**Comment by flashcode** [comment]
Buflist uses evaluated expressions, so you can already do that without new options, with for example this string in a buflist format option: `${color:blink}${format_name}`.
