### ISSUE TITLE
How to make weechat title blink on new private messages?

### ISSUE THREAD

**Issue by TheCaptainJackSparrow** [weechat/weechat#1940]
## Question

Is it possible to make weechat blink on new private message received? I'm having a hard time seen when some one pm's me when I'm in another workspace in i3wm. In hexchat whenever someone pm'd me title blinked and I seen a workspace number highlighted. Any ideas on how to do similar in weechat? Thank you.

---

- WeeChat version: 3.8
- OS, distribution and version: i3wm, Linux

**Comment by flashcode** [comment]
By default there's a "beep" trigger that sends an alert to the terminal in case of highlight.
You can then configure the behavior in your terminal, when this alert is received.

Please stop adding questions as issues in this repository, as they're used to track real bugs and new features.
The "question" type is only for questions that could be new features, not basic usage of WeeChat (and you should be able to find yourself the answers in docs / FAQ).
For such questions, please ask on #weechat, irc.libera.chat (sometimes you just have to wait some hours for answers). Hundreds of people can help you on IRC.
Thanks.
