### ISSUE TITLE
How to hide all modes in all channels?

### ISSUE THREAD

**Issue by TheCaptainJackSparrow** [weechat/weechat#1941]
## Question

How to hide all modes given to users like this in channels?

```
Mode #ChannelName +v UserName by UserName
Mode #ChannelName +h UserName by UserName
```

---

- WeeChat version: 3.8
- OS, distribution and version: Linux

**Comment by flashcode** [comment]
To hide all modes: `/filter add irc_mode *  irc_mode *`
Toggle filters with `alt+=`.
