### ISSUE TITLE
Hide "user has identified as user"?

### ISSUE THREAD

**Issue by L3RN3W** [weechat/weechat#1958]
## Question

How do you hide modes like;

`[user] has identied as [user]`

and 
 
`[user] [host] has changed host to [host]` ?

I have this filter enabled now but its not working to hide this too above.

`/filter add mute * irc_join,irc_part,irc_quit,irc_mode,irc_nick,irc_nick_back,irc_topic *`

---

- WeeChat version: 3.8
- OS, distribution and version: Linux

**Comment by L3RN3W** [comment]
What am I missing here? Everything seems to be on.

- `irc.look.smart_filter on`
- `irc.look.smart_filter_account on`
- `irc.look.smart_filter_chghost on`
- `irc.look.smart_filter_join on`
- `irc.look.smart_filter_nick on`
- `irc.look.smart_filter_quit on`
- `irc.look.smart_filter_setname on`

**Comment by flashcode** [comment]
You must add a filter to enable the smart filter, in addition to these options, see the doc here: https://weechat.org/files/doc/weechat/stable/weechat_user.en.html#irc_smart_filter_join_part_quit

**Comment by L3RN3W** [comment]
Oh you mean `/filter add irc_smart * irc_smart_filter *` ? Will try ;-) Thank you flashcode!
