### ISSUE TITLE
How to make a trigger to filter some lines based on regex given?

### ISSUE THREAD

**Issue by L3RN3W** [weechat/weechat#1961]
## Question

I've seen examples in wiki but kind of confused on how to use it. Can you please give me an example on how to create a basic trigger or filter to hide specific lines in the buffer. For example.

```
(PRE) (XXX) SomeTextHere - regex should target any (XXX) part and hide it.
(PRE) (MP3) SomeTextHere - regex should target any (XXX) part and hide it.
```

I would like to hide any lines based on regex group like `(XXX|MP3)` in specific channel #pre on specific server like irc.someserver.com Thank you!

---

- WeeChat version: 3.8
- OS, distribution and version: Linux

**Comment by flashcode** [comment]
Issues are not a forum, please join #weechat on irc.libera.chat to ask such questions, and be sure you have read all the docs and wiki before asking.

Thanks.

**Comment by L3RN3W** [comment]
I understand but I don't have time to hang in #weechat =( And I already read wiki but still confused =( Thanks anyway!

**Comment by L3RN3W** [comment]
Is it something like this? `/trigger addreplace hidewords *,irc_in2_PRIVMSG "${message_without_tags} =~ (XXX|MP3)" "" "`

**Comment by flashcode** [comment]
No you don't understand.
I lock this issue, and this is the last warning. Next time you are banned.
