### ISSUE TITLE
Configuration autoupgrade: Clarify unknown key message

### ISSUE THREAD

**Issue by hseg** [weechat/weechat#1967]
## Feature description
The current message emitted when an option gets deprecated is unclear to me:
> =!= Warning: /home/user/.config/weechat/sec.conf, line 15: unknown option for section "crypt": passphrase_file = ""

sounds as if it's just warning about the option and will ignore it, instead of its actual behaviour of deleting it.
While this _is_ documented in the user's guide, a clearer message would also be nice, perhaps as simple as
> ...: deleting unknown option ...

A more ambitious ask might be to question this design choice (in general, I don't expect my tools to modify
my configuration) or to distinguish between deprecated options and actually unknown options, but I'll leave
that for someone else to propose.

**Comment by flashcode** [comment]
Hi,

To be accurate, the option is not really "deleted", it's just not loaded in memory and will be really deleted in file if you do `/save` (you could argue the result is the same, but small difference).

That means if you do `/reload` before doing `/save`, the warning will still appear, until it's actually written on disk (either `/save` or `/quit`).

So I'm not fan "deleting unknown option", I could maybe suggest:

    =!= Warning: /home/user/.config/weechat/sec.conf, line 15: discarding unknown option for section "crypt": passphrase_file = ""

**Comment by hseg** [comment]
Ah, OK. Checking my configs, it appears I set `save_config_on_exit`, which contributed to my confusion.

**Comment by flashcode** [comment]
So, what should I do, change the message displayed?

**Comment by hseg** [comment]
Not sure it's still worthwhile - modulo my misunderstanding, this is the sensible behaviour I would expected. Perhaps
`ignoring unknown option`?
