### ISSUE TITLE
Multi line messages in wee-slack don't display on WeeChat 4.0.0

### ISSUE THREAD

**Issue by superjamie** [weechat/weechat#1969]
## Bug summary

In earlier versions, multi-line messages in wee-slack would display correctly, eg:

```
line1
line2
```

Now, the 

## Steps to reproduce

1. Install WeeChat 4.0.0
2. Install wee-slack - https://github.com/wee-slack/wee-slack
3. Connect to a Slack team, you can connect to your own team for $0
4. Send a multi-line message to yourself with `line1<Alt+enter>line2`

## Current behavior

Only the first line of the message `line1` is displayed

## Expected behavior

Both lines of the message `line1` then `line2` are displayed

## Additional information

The multi-line message does arrive at the client properly. A notification plugin shows the message with multiple lines.

Not all messages from others break this, some multi-line messages work fine, but I haven't been able to figure out why.

---

- WeeChat version: 4.0.0
- OS, distribution and version:  Ubuntu 22.04
- Terminal: Terminator 2.1.1
- Terminal multiplexer (screen/tmux/…/none): none

**Comment by trygveaa** [comment]
Hm, I can't reproduce this. Which commit/version of wee-slack are you using?
Can you run `/buffer get input_multiline` in a buffer where you experience the problem and post the line that's printed in the core buffer?
Which scripts and triggers do you have? Run `/script list` and `/trigger listfull`.

**Comment by superjamie** [comment]
It turns this is caused by `colorize_lines.pl`. I had tested a new install, but I also made the mistake of assuming all my old plugins were fine.

It looks like I should report this at https://github.com/weechat/scripts/issues instead.

Thank you for the super-quick response, and sorry for the bother!

**Comment by trygveaa** [comment]
Ah, great, that makes more sense. I can reproduce it with `colorize_lines.pl` (on multiline irc as well).

**Comment by flashcode** [comment]
Just for your information, the script colorize_lines.pl has been fixed (v4.0.1).
