### ISSUE TITLE
local script will not autoload.

### ISSUE THREAD

**Issue by AntiHugoTremblay** [weechat/weechat#1980]
## Steps to reproduce

1.  create script and place in script directory
2.  open weechat
3.  run command "/script autoload <script.ext>

## Current behavior

autocompletion does not work
script will not load

## Expected behavior

autocompletion should work correctly
script should be moved into autoload directory

## Suggested solutions

probably some issue with the symlink

## Additional information

when trying to do the symlink manually the link is broken

wsl2

---

- WeeChat version:  4.1.0-dev
- debian 11
- Terminal: putty
- Terminal multiplexer (screen/tmux/…/none):  tmux

**Comment by flashcode** [comment]
Hi @AntiHugoTremblay,

Could you please paste output of `/debug dirs` in WeeChat?

And in which directory did you put our script (please provide the full path)?

Thanks.

**Comment by AntiHugoTremblay** [comment]
21:26 Directories:
21:26   home:
21:26     config: /home/user/.config/weechat
21:26     data: /home/user/.local/share/weechat
21:26     cache: /home/user/.cache/weechat
21:26     runtime: /mnt/wslg/runtime-dir/weechat
21:26   lib: /usr/lib/x86_64-linux-gnu/weechat
21:26   lib (extra): -
21:26   share: /usr/share/weechat
21:26   locale: /usr/share/locale

I tried placing a script I wrote myself in the "data" directory and it seems to load fine, however I can't get the "/script autoload <script.py> function to work, autocomplete also doesn't work for the command.

**Comment by flashcode** [comment]
Hi,

I can not reproduce the problem.

What I tested, under WSL:

- install a script from repository: `/script install go.py`: works, symlink created, script auto-loaded
- remove link, run command `/script autoload go.py`: works, symlink recreated, script auto-loaded

Note: command `/script autoload` works only for scripts known in repository, not custom script that you put in directory.

**Comment by trygveaa** [comment]
The issue is that you can only use `/script autoload` for scripts from the repo, not scripts manually copied to the data directory.

So after e.g. `cp my_script.py ~/.local/share/weechat/python` then `/script autoload my_script.py` is expected to work, but it says `script: script "my_script.py" not found`. `/script load my_script.py` works though.

**Comment by flashcode** [comment]
OK, I'm fixing this by allowing commands `/script autoload`, `/script noautoload` and `/script toggleautoload` to work with any script, even those not in scripts repository.
