### ISSUE TITLE
My ACTIONs lack boldness

### ISSUE THREAD

**Issue by ncfavier** [weechat/weechat#1981]
## Bug summary

Since upgrading to 4.0.2, `ACTION` messages sent by me are cut as soon as I use bold.

For example, here is the result of sending "/me test **test** test" to myself:

![screenshot-2023-07-17-221448](https://github.com/weechat/weechat/assets/4323933/f884b9f3-6890-4e34-8d74-23c75be6a973)

The first line is the one I sent, the second line is the echo from the server. This also happens in channel buffers, except that I don't see the echo.

## Steps to reproduce

See above

## Current behavior

See above

## Expected behavior

Not that

## Additional information

---

- WeeChat version: 4.0.2
- OS, distribution and version: NixOS unstable
- Terminal: alacritty
- Terminal multiplexer (screen/tmux/…/none): tmux

**Comment by flashcode** [comment]
Hi,

I confirm the bug and it's related to the echo-message capability, added in WeeChat 4.0.0.

As a workaround, you can disable it on-the-fly with `/cap req -echo-message` or with `/set irc.server_default.capabilities "*,!echo-message`.
