### ISSUE TITLE
/join doesn't switch any more

### ISSUE THREAD

**Issue by ncfavier** [weechat/weechat#1982]
## Bug summary

Since upgrading to 4.0.2, `/join #foo` does not switch to the `#foo` buffer automatically.

## Steps to reproduce

1. `/join #foo`

## Additional information

---

- WeeChat version: 4.0.2
- OS, distribution and version: NixOS unstable
- Terminal: alacritty
- Terminal multiplexer (screen/tmux/…/none): tmux

**Comment by flashcode** [comment]
Hi,
It works for me with default config.
Can you check that option `irc.look.buffer_switch_join` is `on` (this is the default value)?

**Comment by ncfavier** [comment]
It is, but `irc.look.buffer_switch_autojoin` was `off`. Turning it `on` solves the issue. This seems unexpected

**Comment by ncfavier** [comment]
Here's my entire config: https://github.com/ncfavier/config/tree/main/modules/server/weechat

**Comment by flashcode** [comment]
This is expected, there are 2 separate options: by default there is no switch for auto-joined channels (option .autojoin), and a switch for manually joined channels (with /join).

If you did manually /join with default config, the switch to buffer should be done.
If not, please give all steps with a default config to reproduce the issue.

**Comment by ncfavier** [comment]
This seems to be enough, from a default config:

1. `/set irc.look.buffer_switch_autojoin off`
2. `/set irc.server_default.autojoin_dynamic on`
3. `/server add libera irc.libera.chat/6697 -tls`
4. `/connect libera`
5. `/join #foo`

The new `#foo` buffer is not switched to.
