### ISSUE TITLE
Action messages, aka `/me`, aren't displayed properly on weechat on the remote instance when using IRC relay protocol (PM only)

### ISSUE THREAD

**Issue by PeGaSuS-Coder** [weechat/weechat#1986]
## Bug summary
Action messages, aka `/me`, sent on PM aren't displayed properly on the remote instance when using IRC relay protocol, but messages sent from the remote instance are properly displayed  on the instance connected via IRC relay protocol

## Steps to reproduce

1. Connect one weechat instance over IRC relay protocol to your remote instance
2. Send an `/me` to some PM
3. `me` messages aren't properly displayed on the remote when sent from the local instance instance but are properly displayed on the local instance when sent from the remote instance

## Current behavior
`me` messages aren't properly displayed on the remote when sent from the local instance instance but are properly displayed on the local instance when sent from the remote instance

## Expected behavior
`/me` messages should be displayed properly on remote instance when sending it from the local instance connected via IRC relay protocol

## Additional information
- Messages sent from local instance to a PM,  connected via IRC relay protocol:
![rss_bot_local](https://github.com/weechat/weechat/assets/25697531/c07c5743-62f5-408b-b863-8378fc215dbb)

- Messages seen in the remote instance
![rss_bot_remote](https://github.com/weechat/weechat/assets/25697531/1145a9ce-730b-4c80-ab30-2af20c8b34de)

---

- WeeChat version: WeeChat 4.1.0-dev (git: v4.0.0-66-g13241cdca)
- OS, distribution and version: Ubuntu 22.04.2 LTS
- Terminal: xfce4-terminal
- Terminal multiplexer (screen/tmux/none): tmux

**Comment by flashcode** [comment]
Thanks, fixed in master and 4.0 branches (it was a regression introduced in 4.0.0).
