### ISSUE TITLE
Outgoing PvNotice's echo-message interpreted as an incoming PvNotice

### ISSUE THREAD

**Issue by runxiyu** [weechat/weechat#1991]
## Bug summary

When an outgoing PvNotice (`/notice nick [#channel] something`) is sent, it is displayed as an incoming PvNotice from and to the WeeChat user.

## Steps to reproduce

1. Connect to a network with the `echo-message` IRCv3 capability
2. `/join #test`
3. `/notice RandomUser [#test] Hi`

## Current behavior

The WeeChat user `Harriet` sees the following on their WeeChat, in the `#test` buffer: `-- | PvNotice(Harriet): Hi`.

This is confusing, because `-- | PvNotice(Harriet): Hi` is supposed to mean "You, the WeeChat user, received a NOTICE from `Harriet`, with the contents `[#test] Hi`", but here we're actually sending an outgoing PvNotice to another user. The WeeChat user also has no way to see who they actually sent their PvNotice to.

Most commonly, this is triggered by ChanServ entry messages: `-- | PvNotice(ChanServ): Welcome to this channel, please check out our rules and such...`

## Expected behavior

Some method of displaying that lets the WeeChat user `Harriet` see that they sent a PvNotice to `RandomUser`. For example, `-- PvNoticeTo(RandomUser): Hi`.

## Suggested solutions

I have no idea how the internals of WeeChat works, but I strongly suspect that it's related to misinterpreting the IRCd's echoed message as an incoming PvNotice.

---

- WeeChat version: 4.0.2
- OS, distribution and version: Debian 12 bookworm with Linux 6.1.0-9
- Terminal: [foot](https://codeberg.org/dnkl/foot/)
- Terminal multiplexer: tmux

**Comment by flashcode** [comment]
Hi,
Thanks for reporting the issue.
The problem should be fixed, could you please test and confirm?
(either on master or 4.0 branch).

**Comment by runxiyu** [comment]
I can confirm that it's working, built master on Debian bookworm
