### ISSUE TITLE
automate the configuration

### ISSUE THREAD

**Issue by Xat59** [weechat/weechat#1993]
## Feature description

It would be nice to be able to ocnfigure weechat automatically. without user interaction.
In my case I am deploying weechat on several servers and I want to benefit of the automation to configure each weechat instance.

Several possibility to do this :
- be able to create a configuration file in plaintext
- be able to run 'weechat' binary with a mode that allows us to configure stuff, for instance: `weechat --cli '/server add libera irc.libera.chat'`

In both case, we need to have a better management of secrets (user password, server password, and so on...).

**Comment by weechatter** [comment]
- all weechat configuration files are in plaintext!
- see weechat -h
- see /help secure

**Comment by Xat59** [comment]
I need to execute several `weechat` commands with `-r` argument. But each command with `-r` enters into a weechat session while I just want to configure it, not using it at this stage.

It is possible to tell weechat to not go into interactive mode and opening the weechat app ?
