### ISSUE TITLE
TEST(IrcJoin, CompateJoinChannel) does not pass on aarc64

### ISSUE THREAD

**Issue by mtasaka** [weechat/weechat#1997]
## Bug summary
As of 41dbcb1a81a036548c20310612ef7a032e6e3a90 (as well as v4.0.3), `TEST(IrcJoin, CompateJoinChannel) `  does not pass on aarch64 such as:

```
1: TEST(IrcJoin, CompateJoinChannel)
1: /builddir/build/BUILD/weechat-4.0.3_git/tests/unit/plugins/irc/test-irc-join.cpp:145: error: Failure in TEST(IrcJoin, CompateJoinChannel)
1: 	LONGS_EQUAL(45, irc_join_compare_join_channel (NULL, &join_chan1, &join_chan2)) failed
1: 	expected <45 (0x2d)>
1: 	but was  <90 (0x5a)>
```

Looking at the code, so https://github.com/weechat/weechat/blob/41dbcb1a81a036548c20310612ef7a032e6e3a90/tests/unit/plugins/irc/test-irc-join.cpp#L145 , that is https://github.com/weechat/weechat/blob/41dbcb1a81a036548c20310612ef7a032e6e3a90/src/plugins/irc/irc-join.c#L58 is failing.

Actually the following code:

```
#include <string.h>
#include <stdio.h>

int main(void) {
	char str1[] = "key_abc";
	char str2[] = "key2_abc";

	int diff = strcmp(str1, str2);
	fprintf(stdout, "diff[%d]\n", diff);

	return 0;
}
```

actually shows `diff[90]` on "my" aarch64, which is allowed because `strcmp` assures the signedness of the return value.

## Suggested solutions

As there is `string_strcmp` available, for making test pass, the simplest fix would be:

```
diff --git a/src/plugins/irc/irc-join.c b/src/plugins/irc/irc-join.c
index 7f794701f..f362bb57d 100644
--- a/src/plugins/irc/irc-join.c
+++ b/src/plugins/irc/irc-join.c
@@ -25,6 +25,7 @@
 #include <string.h>
 
 #include "../weechat-plugin.h"
+#include "../../core/wee-string.h"
 #include "irc.h"
 #include "irc-join.h"
 #include "irc-channel.h"
@@ -55,7 +56,7 @@ irc_join_compare_join_channel (struct t_irc_server *server,
     if (!join_channel1->key && join_channel2->key)
         return 1;
 
-    return strcmp (join_channel1->key, join_channel2->key);
+    return string_strcmp (join_channel1->key, join_channel2->key);
 }
 
 /*
```

**Comment by flashcode** [comment]
Hi,

Could you please explain why the result of 90 is OK for you?
Codepoint for "_" is 95, "2" is 50, so the diff should be 45, and there is no signed numbers here (and the result should be -45 when comparing str2 to str1).

Did I miss something?

**Comment by mtasaka** [comment]
My word should be "which is allowed because strcmp assures **only** the signedness of the return value."

`man 3p strcmp` says (or https://pubs.opengroup.org/onlinepubs/9699919799/functions/strcmp.html says:)

```
Upon completion, strcmp() shall return an integer greater than, 
equal to, or less than 0,  if the string pointed to by s1 is greater than, 
equal to, or less than the string pointed to by s2, 
respectively.
```

specification says only this,  so specification guarantees the signedness of the return value (i.e. positive or 0 or negative), but not the "size" of the return value and it depends on the implementation.

So for this case that `strcmp("key_abc", "key2_abc")` must return _some_ positive value, but not required to be 45. Similarly, `strcmp("key2_abc", "key_abc")`  must return _some_ negative value, but not required to be -45.

**Comment by flashcode** [comment]
OK, understood.

In this case I'll fix the tests on this function that are too stricts, I'll just check if the result is negative, 0 or positive.
The code itself is used to sort channels, so the exact difference is not used anyway.

**Comment by mtasaka** [comment]
Confirmed fixed, thank you!
