### ISSUE TITLE
Future of supporting 32 bit arch?

### ISSUE THREAD

**Issue by mtasaka** [weechat/weechat#1998]
With weechat 4.0.3 as well as git head ( 2ad8a0d868b594204eb7199f6380b865ebf45c8b ), I see some test failures on i686 arch, and they really seems to be "32bit" issue.

If weechat is still going to support 32 bit (especially i686), then I am going to report such test failures one by one, however before filing (multiple) issue, first I want to ask if this is willing.

**Comment by flashcode** [comment]
Hi,
Yes 32-bit arch is supported and all tests must pass there.
Please report just one issue with all the fails and I'll fix them, thanks.

**Comment by mtasaka** [comment]
Okay, then l'll try.
