### ISSUE TITLE
Adding more hashing algorithms

### ISSUE THREAD

**Issue by c6c534e825f4a3d41ede3e67473187d1** [weechat/weechat#2008]
## Feature description
I'd like to see some more hashing algorithms in WeeChat. Here's a list of ones which I think would be good, and the reason why:

- SHA512/256: is a bit more resistant to length extension attacks (SHA384 with 128 bits vs SHA512/256 with 256 bits)
- SHA3-256: while slow, it might be a good idea to start implementing non-SHA2 hashing algorithms, INCASE it gets broken (you never know)
- BLAKE2b: SHA3 is slow, very slow, hence why something like BLAKE2b would be very nice to have. It's faster than SHA3, is length-extension attack immune (like SHA3) and is more secure than SHA2.

Another thing I'd like to request is another feature already requested [here](https://github.com/weechat/weechat/issues/1253), which is about adding a key derivation function (like Argon2id) for more secure data storage. Just putting it here incase it was forgotten about.

Cheers

**Comment by flashcode** [comment]
Hi,

Where do you want such hashing algorithms, you mean in option `sec.crypt.hash_algo`?

I ask because SHA3-256 is already available in the API function crypto_hash: https://weechat.org/files/doc/weechat/devel/weechat_plugin_api.en.html#_crypto_hash

**Comment by iloveyumyumshrimpnoodles** [comment]
yeah, as value for `sec.crypt.hash_algo`

**Comment by flashcode** [comment]
Implemented.
I keep the other issue open as it's not yet implemented.

**Comment by c6c534e825f4a3d41ede3e67473187d1** [comment]
cheers
