### ISSUE TITLE
/action command

### ISSUE THREAD

**Issue by 0xallie** [weechat/weechat#201]
It would be nice to have an `/action` command which is like `/msg` but for `/me`s.

Examples:

```
/action * tests
/action #test tests
/action -server testnet #test tests
```

**Comment by flashcode** [comment]
I already added an alias called `/action` for 4.0.0, but I just realize there's this issue and it's much better to have it as an IRC command, to be able to use `-server` and `*`, like the `/msg` command, so I'll remove the alias and add a new IRC command instead.
