### ISSUE TITLE
Automatically backup any config file with unsupported config version

### ISSUE THREAD

**Issue by flashcode** [weechat/weechat#2013]
## Feature description

When a configuration file with an unsupported config version is loaded, there's a simple error message, and all settings are reset to the defaults:

```
=!= | Error: /path/to/irc.conf, version read (4) is newer than supported version (3) => rest of file is IGNORED, default options are used
```

If you miss this error and do `/quit`, all IRC settings are lost (overwritten by default config, which has no servers).

To prevent this, WeeChat should do a backup version of the configuration file being read.
The backup filename is the same as the config file with suffix `.backup.<date>` where `<date>` is the current date/time (example: `20230912.145144`). If ever this filename already exists, a suffix is added to make it unique: `.2`, `.3`, etc.

The following messages should be displayed in case of unsupported version:

```
=!= | Error: /path/to/irc.conf, version read (4) is newer than supported version (3) => rest of file is IGNORED, default options are used
=!= | File /path/to/irc.conf has been backed up as /path/to/irc.conf.backup.20230912.145144
```

**Comment by weechatter** [comment]
Most important to me is, that user do not lose any data.
