### ISSUE TITLE
Error thrown in terminal: "pidof: can't read from ########/stat"

### ISSUE THREAD

**Issue by Scary-Guy** [weechat/weechat#2017]
## Bug summary:
While using Weechat the terminal will sometimes throw an error (probably caused by a script).

"pidof: can't read from #######/stat" 

## Steps to reproduce:
1. Run Weechat for a really long time.

## Current behavior:
Error thrown in terminal shifting the TUI up three lines.

## Expected behavior:
No error thrown in terminal

## Suggested solutions:
Either of these makes the error go away:
Restarting Weechat
Make window (if ran in a window) fullscreen then back, or vice versa.

## Additional information:
It's really more of a minor annoyance than anything.
This has been going on for YEARS across different versions of Debian and LMDE versions 4/5.

- WeeChat version: 3.8
- OS, distribution and version: Regolith Linux 2 (Ubuntu)
- Terminal: Terminator
- Terminal multiplexer (screen/tmux/…/none): None

## List of installed scripts (as it may be related to one of these):
autostart.py
grep.py
autojoin.py
colorize_nicks.py
autoauth.py
autosavekey.py
chancomp.py
commorkers.py
hl_here.py
i3lock_away.py
leet.py
listbuffer.py
prism.py
pv_info.pl
screen_away.py
tmux_env.py
topicdiff.py
undernet_totp.py
unset_unused.pl
unwanted_msg.py
whois_on_query.py

**Comment by flashcode** [comment]
Hi,

I think the error comes from i3lock_away.py, which is running the `pidof` command: https://github.com/weechat/scripts/blob/master/python/i3lock_away.py#L135

Either the call to `subprocess.Popen` should have `stderr=subprocess.DEVNULL`, or the script should better use the WeeChat API function `weechat.hook_process`, which is designed to run a forked process in WeeChat.

As it seems it's not a WeeChat issue, could you please report the issue to the author of script (by email, it seems there's no upstream repository), or in the https://github.com/weechat/scripts repository?

Thanks.

**Comment by Scary-Guy** [comment]
Okay, new thread created and conversation can be moved there.  Thanks for the assistance :)
