### ISSUE TITLE
`/script install` can delete local script even with `--temp-dir`

### ISSUE THREAD

**Issue by lacygoill** [weechat/weechat#2019]
## Bug summary

Installing a script might actually delete a script in `~/.local/share/weechat/` even if WeeChat was started with `--temp-dir`.

## Steps to reproduce

Run these shell commands:

    echo "# my forked script which I don't want to lose" >~/.local/share/weechat/python/autosort.py
    weechat --temp-dir --run-command='/set script.scripts.download_enabled on ; /script install autosort.py ; /wait 1s /quit'

## Current behavior

`~/.local/share/weechat/python/autosort.py` has been deleted.

## Expected behavior

`~/.local/share/weechat/python/autosort.py` has *not* been deleted, because WeeChat was started with `--temp-dir` under the assumption that it would leave the contents of our config and scripts unaltered.

## Suggested solutions

N/A

## Additional information

One could argue that when naming a local script, we should make sure not to choose a name which is already taken on the official scripts repository.  But what if we choose a name which is free now, and gets taken in the future?

Also, why is the script removed at all?  It might make sense *without* `--temp-dir`, because WeeChat is going to install a script at that location on the filesystem.  But it does not make sense *with* `--temp-dir`, because in that case, the script is not installed under `~/.local/share/weechat/python/`; instead, it's installed under something like `/tmp/weechat_temp_8sHRlw/`.

I'm working on a re-write of `autosort.py` (for personal use only).  If Vim hadn't kept a backup, I would have lost valuable code.  If this is not considered as a bug, maybe we could document this pitfall somewhere?  For now, I'll name all my local scripts with a leading underscore (I don't think there is any script starting with a leading underscore on the official scripts repository).

---

   - WeeChat version: WeeChat 4.1.0-dev (git: v4.0.0-257-g12106ae7b) [compiled on Sep 20 2023 20:13:45]
   - OS, distribution and version: Ubuntu 20.04.6 LTS
   - Terminal: XTerm(353)
   - Terminal multiplexer (screen/tmux/…/none): none

**Comment by trygveaa** [comment]
This does not reproduce for me. The file is still there after running the commands you provided. I tried with the same commit as you're running, 12106ae7b.

**Comment by flashcode** [comment]
@lacygoill: are you really sure you're running WeeChat with a temporary directory?

While running, you can check directories with `/debug dirs`, and you should see that home config/data/cache/runtime directories are all set to the same directory, for example: `/tmp/weechat_temp_awAUCM`.

And only sub-directories of this one are used by WeeChat and all plugins, including script plugin that stores and removes downloaded scripts there.

**Comment by trygveaa** [comment]
How did you compile weechat? (Specifically the thing I'm wondering is what you set `CMAKE_INSTALL_PREFIX` to)

**Comment by flashcode** [comment]
> However, notice that `lib`, `share` and `locale` are not. Is that expected?

Yes it's expected, these directories are used for read-only (plugins to load, translations, docs, etc.). WeeChat must never write or delete any file in these directories.

**Comment by flashcode** [comment]
By the way, I can not reproduce the problem (I tried many times, the script in home is never deleted for me).

If I set a longer time before quitting (eg: 20 seconds), I get this output:

```
Option changed: script.scripts.download_enabled = on  (default: off)
script: downloading list of scripts...
script: 310 scripts for WeeChat 4.1.0-dev
python: loading script "/tmp/weechat_temp_IhOKLF/python/autosort.py"
python: registered script "autosort", version 3.9 (Flexible automatic (or manual) buffer sorting based on eval expressions.)
```

Do you also see the "loading script" with such temporary path?

**Comment by flashcode** [comment]
Try this command instead, add of `/debug dirs`, and double check the temporary directory is really used:

```
weechat --temp-dir --run-command='/debug dirs;/set script.scripts.download_enabled on ; /script install autosort.py ; /wait 10s /quit'
```

**Comment by flashcode** [comment]
Reopening the issue, I can reproduce (I had to compile with install prefix `$HOME/.local`).
