### ISSUE TITLE
Hex color messages are not displayed properly

### ISSUE THREAD

**Issue by AnInternetTroll** [weechat/weechat#2025]
## Bug summary
Messages that use hex color codes do not display properly

## Steps to reproduce and Current behavior

The message "\*\*\*Does this look fancy\*\*\*?" (using gitter.py) sent gets sent back as
```
FF00FF,FFFFFFDFF0000,FFFFFFoFFFF00,FFFFFFe00FC00,FFFFFFs00FFFF,FFFFFF0080FF,FFFFFFtFF00FF,FFFFFFhFF0000,FFFFFFiFFFF00,FFFFFFs00FC00,FFFFFF00FFFF,FFFFFFl0080FF,FFFFFFoFF00FF,FFFFFFoFF0000,FFFFFFkFFFF00,FFFFFF00FC00,FFFFFFf00FFFF,FFFFFFa0080FF,FFFFFFnFF00FF,FFFFFFcFF0000,FFFFFFy?
```
when using [matrix2051](https://github.com/progval/matrix2051), which decodes the following message
```html
<font data-mx-color=\"#FF00FF\">D</font><font data-mx-color=\"#FF0000\">o</font><font data-mx-color=\"#FFFF00\">e</font><font data-mx-color=\"#00FC00\">s</font><font data-mx-color=\"#00FFFF\"> </font><font data-mx-color=\"#0080FF\">t</font><font data-mx-color=\"#FF00FF\">h</font><font data-mx-color=\"#FF0000\">i</font><font data-mx-color=\"#FFFF00\">s</font><font data-mx-color=\"#00FC00\"> </font><font data-mx-color=\"#00FFFF\">l</font><font data-mx-color=\"#0080FF\">o</font><font data-mx-color=\"#FF00FF\">o</font><font data-mx-color=\"#FF0000\">k</font><font data-mx-color=\"#FFFF00\"> </font><font data-mx-color=\"#00FC00\">f</font><font data-mx-color=\"#00FFFF\">a</font><font data-mx-color=\"#0080FF\">n</font><font data-mx-color=\"#FF00FF\">c</font><font data-mx-color=\"#FF0000\">y</font>?
```
## Expected behavior

Colorful text

## Additional information

I was told to link this
https://modern.ircdocs.horse/formatting#hex-color

---

- WeeChat version: 4.0.5
- OS, distribution and version: Void Linux
- Terminal: foot 1.15.3
- Terminal multiplexer (screen/tmux/…/none): none

**Comment by flashcode** [comment]
Hi,

Hex color codes (code 0x04 in messages) is not supported, so for me it's not a bug, but a feature request. Or maybe you mean WeeChat should just ignore these codes and display properly without colors, as it's not supported?

If it's OK for you, I'll update the label accordingly and check how it can be implemented: it shouldn't be that hard, WeeChat has already functions to map hex color codes to internal colors.

**Comment by AnInternetTroll** [comment]
That would be great, thanks!

**Comment by flashcode** [comment]
It's now implemented, your feedback is welcome, whether it works well or not!

**Comment by progval** [comment]
works for me!

**Comment by AnInternetTroll** [comment]
Hi, thanks for taking the time to fix this!
>It's now implemented, your feedback is welcome, whether it works well or not!
Kinda works for me.
I use glitter.py, so I tested this by typing the following messages
```
***testy test***
***second test***
***a test with many words***
```
The output I got was
```
testytest
secondtest
atestwithmanymanywords
```
With the spaces missing, though the text is coloured correctly.
There is also a light background color, which for my dark-mode themed
terminal is kind of ugly, though I'm not sure if this is a feature for
light themed terminals and I didn't enable a setting.

**Comment by AnInternetTroll** [comment]
Here is a screenshot
![20231101-181808](https://github.com/weechat/weechat/assets/40470127/cb2d379b-6bc7-4aed-becb-cc70a9635292)

Pressing the up arrow also gives me 
```
C13sC4eC8cC9oC11nC12dC13 C4tC8eC9sC11tC
C13aC4 C8tC9eC11sC12tC13 C4wC8iC9tC11hC12 C13mC4aC8nC9yC11 C12mC13aC4nC8yC9 C11wC12oC13rC4dC8sC
```
Which when send output the same colorful text that was originally sent. Though that might just be glitter.py

**Comment by flashcode** [comment]
If there is a light background in messages, that means the background color was forced.
It's weird because I just tested this script glitter.py and I have no white background.
Maybe another script is conflicting there?

Can you try with a default config and just the script glitter.py?

Anyway I think this problem is not related to the RGB color feature just added.

**Comment by flashcode** [comment]
Also check your value of option `/set irc.color.mirc_remap`.

**Comment by AnInternetTroll** [comment]
I moved the .config/weechat folder somewhere else and installed
glitter.py and I still get the light background and missing spaces.

Here is my irc.color.mirc_remap
>irc.color.mirc_remap  string  "1,-1:darkgray"

To clarify in case it matters, I built from source from this archive
with the voidlinux template
https://github.com/weechat/weechat/archive/f16857fc3db2d83e7c355c16016f79e534d381ad.tar.gz

**Comment by flashcode** [comment]
Just moving .config/weechat is not enough (for example scripts are in another directory, so they'll be still loaded).

It's not even needed to move directories to test another config, you can run `weechat -t` (to use a temporary "home" directory, that is deleted on exit) or `weechat -d /tmp/weechat` to use another directory (not deleted on exit).

**Comment by AnInternetTroll** [comment]
Opsy, didn't know that.
I've ran weechat -t and I am still experiencing the same issue.

Here are the scripts and plugins I have loaded right now.

Scripts loaded:
    ia   glitter.py 0.1 (Replaces ***text*** you write with rainbow text)

Plugins loaded:
   typing: Typing status of users
   fifo: FIFO pipe for remote control
   perl: Support of perl scripts
   exec: Execution of external commands in WeeChat
   irc: IRC (Internet Relay Chat) protocol
   python: Support of python scripts
   relay: Relay WeeChat data to remote application (irc/weechat protocols)
   trigger: Text replacement and command execution on events triggered by WeeChat/plugins
   fset: Fast set of WeeChat and plugins options
   script: Script manager
   xfer: DCC file transfer and direct chat
   lua: Support of lua scripts
   charset: Charset conversions
   buflist: Buffers list
   alias: Alias commands
   logger: Log buffers to files

**Comment by flashcode** [comment]
I'm not able to reproduce, here's what I did, using my own IRC test server, running locally:

```
weechat -t
/set script.scripts.download_enabled on
/script install glitter.py
/server add local 127.0.0.1 -notls -autojoin=#test
/connect local
```

Then I send this text:

```
***a test with many words***
```

The result is:

![image](https://github.com/weechat/weechat/assets/1776783/bea9aaa1-631a-4930-8f57-58040925215b)

**Comment by progval** [comment]
Actually, I have a complaint: in Foot with `TERM=xterm`, in this message: `:foo\x04FF0000bar\x0399,99\x047F0000baz\x0399,99`, "bar" and "baz" are both shown the same red, even though `\x04FF0000` and `\x047F0000` should map exactly to `\x0304` and `\x0305` according to the values used in the CSS, which is the best authority I'm aware of

**Comment by flashcode** [comment]
Actually, the color `FF0000` is converted to terminal `9` (bright red) and `7F0000` is converted to terminal color `1` (dark red).

And if I try IRC colors 04 and 05 I have same result:



In my terminal I see a color difference:


Note that RGB colors are directly mapped to terminal colors (0-255) and not IRC colors, so more colors can be used.

**Comment by flashcode** [comment]
Actually, the color `FF0000` is converted to terminal `9` (bright red) and `7F0000` is converted to terminal color `1` (dark red).

And if I try IRC colors 04 and 05 I have same result:

![image](https://github.com/weechat/weechat/assets/1776783/d9974a73-8ea9-442e-ba45-20eb701afdb9)

Note that RGB colors are directly mapped to terminal colors (0-255) and not IRC colors, so more colors can be used.

**Comment by progval** [comment]
Ack, it must be my terminal then
