### ISSUE TITLE
Allow /ignore to tag messages instead of removing them

### ISSUE THREAD

**Issue by Earnestly** [weechat/weechat#2028]
## Feature description
Instead of removing messages `/ignore` could gain a new option to tag the messages such as `irc_ignored`, possibly as `/ignore tag [re:]<nick> [<server> [<channel>]]`. This tag can then be filter the messages.

My particular usecase is to allow such messages to be toggled so that conversations don't appear as monologues.
I would use such a feature with something like `/filter add ignored * irc_ignored *` and then bind a key to execute `/filter toggle ignored` to temporarily toggle display of ignored messages.

**Comment by flashcode** [comment]
Duplicate of #989.
