### ISSUE TITLE
Ask for confirmation when sending a command preceded by one or more spaces

### ISSUE THREAD

**Issue by TehPeGaSuS** [weechat/weechat#2035]
## Feature description
It would be nice to have a way to be warned and ask for confirmation when sending a command preceded by a space (and possibly double slashes?).

This would help people that type something like `" /ns identify <password>"` (note the space between the quote and the slash) into channels, exposing sensitive data.

I've seen this being implemented on a web client and it hit me because I was recently kickbanned from a channel after typing `" /join #help"` without double-checking, by a bot which is configured to kickban inviters.

We could have a warning like **`[You're about to send a command as a message, which may contain sensitive data. Continue? [ctrl-y] Yes [ctrl-n] No]`**, when hitting Enter (I don't know if we can halt it).

Cheers

**Comment by weechatter** [comment]
there is a trigger and also an script to prevent sending commands as messages:

https://github.com/weechat/weechat/wiki/Triggers#prevent-sending-commands-as-messages-when-preceded-by-space

or

https://weechat.org/scripts/source/unwanted_msg.py.html/

also have a look at:

https://weechat.org/scripts/source/anti_password.py.html/

also remember, weechat is single threaded. this warning may block weechat

**Comment by TehPeGaSuS** [comment]
No need to keep this lingering around
