### ISSUE TITLE
syntax highlighting for eval

### ISSUE THREAD

**Issue by pascalpoitras** [weechat/weechat#2042]
## Feature description

It would be useful to have syntax highlighting for eval. It would be available in two ways

1. using /eval -h
2. using ${highlighting:...}

the highlighting variable would have the second [top priority](https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#eval_variables) (so just after raw). Nothing would be evaluated inside highlighting (exactly like raw does).

So if the cut variable is green and the rev variable is red, both

`/eval -h ${cut:1,,${rev:hello}}`

and

`/eval -n ${highlighting:${cut:1,,${rev:hello}}}`

will print

![WeeChat Screenshot](https://user-images.githubusercontent.com/3608314/282574281-4616c4aa-5b5e-4d3c-959d-618eac2c1927.png)

We could also have an option similar to weechat.color.chat_nick_colors which contains a list of colors and an option similar to weechat.look.nick_color_hash taking an algorithm so the color will be choosed automatically

All ${info:...} would be colored the same way no matter the info name, same for ${modifier:...} OR different color not sure what is the best here

the ${define:...} is interesting since it priority allow it to redefine variable so for example what the color the following ${info:version} should be

`/eval -h ${define:info:version,hello}${info:version}`

the color for info or the color for custom variables ?

This feature is useful in many scenario, for example

1. sending an eval string on IRC with syntax highlighting

`/eval ${modifier:irc_color_decode_ansi,1,${modifier:color_encode_ansi,,${highlighting:${cut:1,,${rev:hello}}}}}`

2. using it in a input_text_display modifier so you have syntax highlighting when writting a code snippet in the input bar

**Comment by pascalpoitras** [comment]
Ok so, FlashCode accepted this feature so here it was it look like in the input bar

![byzanz-record-2023-11-20-154503](https://user-images.githubusercontent.com/3608314/284387626-157c6a8a-1b59-4e61-9d25-dd9e4a017287.gif)

**Comment by flashcode** [comment]
Done with `${raw_hl:...}` (raw string with syntax highlighting) and `${hl:...}` (evaluated string with syntax highlighting).
