### ISSUE TITLE
Infinite loop when displaying emojis in excessively small terminal

### ISSUE THREAD

**Issue by progval** [weechat/weechat#2053]
### Describe the bug

Weechat freezes and uses a full CPU when trying to render emojis in a terminal too small to render them

### Steps to reproduce

1. `weechat -t -r '/server add ergotestnet testnet.oragono.io/6697 -ssl; /set irc.server.ergotestnet.autoconnect on; /set irc.server.ergotestnet.autojoin #whatever'`
2. type `👉👉👉`
3. Resize the terminal so that there are only four columns of actual text, like this: 
![screenshot-2023-12-14_21-32-28](https://github.com/weechat/weechat/assets/406946/5fd396d1-03c8-45c2-8908-b99ae4a98aeb)
4. Then make it one column smaller, like this:
![screenshot-2023-12-14_21-32-48](https://github.com/weechat/weechat/assets/406946/db0df0f7-ccb5-4e91-ae73-323eef4c3bdd)
5. Then one column smaller: 
![screenshot-2023-12-14_21-32-55](https://github.com/weechat/weechat/assets/406946/fc381750-4d0f-434a-b6f3-1bc6990c93b3)
6. then one more

### Current behavior

shows this and crashes:
![screenshot-2023-12-14_21-37-45](https://github.com/weechat/weechat/assets/406946/ff8fcc36-dbed-4c8f-becb-d453cbb0b951)

### Expected behavior

should not crash

### WeeChat version

from <3.0 to latest master (ffa933bcf89b1d470cf816551b515eddd2a10426)

### What OS are you using?

Debian 12

### On which terminal are you running WeeChat?

Foot, gnome-terminal

### Which terminal multiplexer are you using?

none, tmux, dtach

**Comment by pascalpoitras** [comment]
Here no crash but the screen become blank and I can't do anything

![Weechat Screenshot](https://gist.github.com/assets/3608314/8e75d8ef-7b3a-4292-85a3-749bab7d41c2)

**Comment by progval** [comment]
Backtrace:

```
0x0000557a7b45c8c0 in utf8_char_size_screen (string=0x557a7cdf3f70 "👉👉👉") at /home/dev-weechat/weechat/src/core/wee-utf8.c:514
514	   if (!string || !string[0])
(gdb) bt
#0  0x0000557a7b45c8c0 in utf8_char_size_screen (string=0x557a7cdf3f70 "👉👉👉") at /home/dev-weechat/weechat/src/core/wee-utf8.c:514
#1  0x0000557a7b4887c7 in gui_chat_string_real_pos (string=0x557a7cdf3f70 "👉👉👉", pos=1, use_screen_size=1) at /home/dev-weechat/weechat/src/gui/gui-chat.c:261
#2  0x0000557a7b4b1d89 in gui_chat_display_word (window=0x557a7cddc880, line=0x557a7ce32540, word=0x557a7cf22990 "👉👉👉", word_end=0x0, prefix=0, num_lines=0, count=0, pre_lines_displayed=0, lines_displayed=0x7ffea82a861c, simulate=1, apply_style_inactive=1, 
    nick_offline=0) at /home/dev-weechat/weechat/src/gui/curses/gui-curses-chat.c:625
#3  0x0000557a7b4b4296 in gui_chat_display_line (window=0x557a7cddc880, line=0x557a7ce32540, count=0, simulate=1) at /home/dev-weechat/weechat/src/gui/curses/gui-curses-chat.c:1587
#4  0x0000557a7b4b4a50 in gui_chat_calculate_line_diff (window=0x557a7cddc880, line=0x7ffea82a8718, line_pos=0x7ffea82a870c, difference=-26) at /home/dev-weechat/weechat/src/gui/curses/gui-curses-chat.c:1826
#5  0x0000557a7b4b4dcc in gui_chat_draw_formatted_buffer (window=0x557a7cddc880) at /home/dev-weechat/weechat/src/gui/curses/gui-curses-chat.c:1959
#6  0x0000557a7b4b5b78 in gui_chat_draw (buffer=0x557a7cf212f0, clear_chat=1) at /home/dev-weechat/weechat/src/gui/curses/gui-curses-chat.c:2359
#7  0x0000557a7b4bb56f in gui_main_refreshes () at /home/dev-weechat/weechat/src/gui/curses/gui-curses-main.c:350
#8  0x0000557a7b4bb741 in gui_main_loop () at /home/dev-weechat/weechat/src/gui/curses/gui-curses-main.c:436
#9  0x0000557a7b3fe134 in main (argc=4, argv=0x7ffea82a8928) at /home/dev-weechat/weechat/src/gui/curses/normal/main.c:44
```
