### ISSUE TITLE
Configurable permissions for irc.conf and other files (such as group ownership)

### ISSUE THREAD

**Issue by zwimer** [weechat/weechat#2057]
### Feature description

When starting weechat (I use the official alpine docker container version) it chmod's some files as 600; that is only the user has read/write permissions; even if umask is 2. It'd be nice if we could configure this; or at least allow group ownership (i.e. chmod 660). That way we could allow members of the 'weechat' user-group to edit these files rather than just the 'weechat'.

**Comment by flashcode** [comment]
Done, new option: `weechat.look.config_permissions`, for example:

```
/set weechat.look.config_permissions "660"
```
