### ISSUE TITLE
"irc_is_message_ignored" is calling the wrong callback

### ISSUE THREAD

**Issue by necauqua** [weechat/weechat#2059]
### Describe the bug

Looks like I'm the first person to actually call it :upside_down_face: 

[here](https://github.com/weechat/weechat/blob/71fee810c9578ec249b2766ffa400684ee1c7f26/src/plugins/irc/irc-info.c#L1261-L1265)

### Steps to reproduce

Write a script intercepting some IRC commands and manually printing them into a buffer with some bells and whistles
Try to add support for ignores by checking weechat_info_get('irc_is_message_ignored', 'server,raw')

### Current behavior

It does not work

### Expected behavior

I should work

### Suggested solutions

Hopefully an obvious oneline fix, I didn't make a PR myself because I'm currently not up to setting up a C dev env on nix to properly test it, sorry

### WeeChat version

4.1.2

### What OS are you using?

NixOS 24.05.20240102.63143ac

**Comment by flashcode** [comment]
Hi, indeed it's wrong, I'll fix ASAP.

By the way instead of catching IRC signals and using this info (which is specific to IRC plugin), I would recommend to use a function like hook_line, which is called when a line is displayed (by WeeChat or any plugin). If a line is displayed, that means it's not ignored by irc plugin (except if option irc.look.ignore_tag_messages is enabled, it's new in 4.2.0).

**Comment by flashcode** [comment]
And I'll also add unit tests on IRC infos to prevent such bugs.

**Comment by necauqua** [comment]
Thanks :)

I've considered hook_line, but between all the things I wanted to achieve, it seems most straightforward to intercept those messages and print them to buffer completely on my own, as I've described there

(I'm almost done making my own version of twitch.py, which does not call the http apis, but extracts and shows significantly more information from ircv3 tags and presents it better, including adding a lot of it to tags for versatile filtering and even post-tagging moderated messages to be (potentially) filtered out as well

The irc_filter thing is literally me reading about the shortcomings of twitch.py from it's desc and trying my best to work around those)

**Comment by flashcode** [comment]
Fixed in 4.0.8, 4.1.3, 4.2.0.
