### ISSUE TITLE
New relay "api": HTTP REST API

### ISSUE THREAD

**Issue by flashcode** [weechat/weechat#2066]
### Feature description

Add a new relay protocol called "api", with the following goals:

- easy client implementation: HTTP REST API, JSON input/output
- data synchronization: real-time sync with websocket or polling with HTTP requests
- no internal structures exposed: ANSI color codes, no use of pointers & complex structures like hdata
- WeeChat itself can connect to another WeeChat using this protocol (also known as relay "remote")

Specification: https://specs.weechat.org/specs/2023-005-relay-http-rest-api.html

**Comment by nilscc** [comment]
Would be nice if the API would support CORS, such that you can use it with OpenAPI directly.

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#preflighted_requests

**Comment by bqv** [comment]
Old protocols will remain, right?

**Comment by flashcode** [comment]
@bqv: short answer: yes, for now.

Long answer:

IRC protocol will remain as it allows any IRC client to connect, like a bouncer does.

The goal with API protocol is to deprecate and replace the "weechat" protocol.
The API protocol has major benefits: standard HTTP API using JSON, safe to use (no pointer or internal structures exposed), colors converted, and connection to another WeeChat is possible.
For these reasons, at some point, the "weechat" protocol could be completely removed.
But this will take time (I mean years) as some major external clients are using it today.
For the future, all efforts will be focused on the API protocol, the weechat protocol should not evolve much further.

**Comment by bqv** [comment]
Can I register my request that the "weechat" protocol remain indefinitely?

I'm not keen on the new api relay, for my own reasons, but I've no right to complain, it's your prerogative as developer. I'd just like the other option to stick around in the same way, even if it doesn't get any explicit development from you (and if I'm not alone, maybe contributors may help with that)

**Comment by flashcode** [comment]
@bqv: I can understand it requires time to convert any existing client of "weechat" to "api" relay, but on the other side, I see no reason to keep "weechat" relay indefinitely, because purpose of the "api" relay is to correct all design flaws of the "weechat" protocol: with a modern design (standard HTTP+JSON instead of custom binary protocol), that is much easier to implement in a client.

For now, the "api" is not mature enough and doesn't provide all features of "weechat" protocol, so don't worry, the "weechat" protocol is not going to be removed any time soon, and of course such removal will be announced well in advance.
