### ISSUE TITLE
\x11 (monospace) formatting code is stripped from incoming traffic

### ISSUE THREAD

**Issue by ToxicFrog** [weechat/weechat#2073]
### Describe the bug

Weechat's colour processing code [here](https://github.com/weechat/weechat/blob/8b6452eb918abfe3b3e886e7f6515394052db464/src/plugins/irc/irc-color.c#L261) silently strips `\x11` (used by irccloud and some other clients for "monospaced text") from incoming messages. This means that there is no way to see that someone tried to send you this formatting other than looking at `irc_raw`, and no way to use a script or trigger to reformat it in a way that distinguishes it from the surrounding text.

### Steps to reproduce

1. Get someone to send you a message with `\x11` character codes in it (say, from irccloud or another service that supports this formatting, or just doing it by hand)
2. Observe that the codes show up in `irc_raw` but not in the message as displayed

### Current behavior

All `\x11` characters are silently removed.

### Expected behavior

`\x11` should be handled the same way as `\x1E` (strikethrough), and other formatting characters weechat doesn't support, i.e., passed through to the buffer and rendered using inverse video (as inverse `Q`, in this case, since `\x11` is `^Q`).

### Suggested solutions

This is probably just a matter of deleting the three lines in `irc_color_decode()` that handle `IRC_COLOR_FIXED_CHAR`.

### WeeChat version

4.1.1

### What OS are you using?

NixOS

**Comment by trygveaa** [comment]
> no way to use a script or trigger to reformat it in a way that distinguishes it from the surrounding text.

It's possible to handle this in a script/trigger by using the `irc_in2_privmsg` modifier to change `\x11` to something else. 

I do agree with you that WeeChat should probably not just strip it though. but not sure if just treating it as unhandled (like strikethrough) is the best way. After all, all text in WeeChat is monospace, so it's in a sense handled. But I do see that it would be useful to be able to distinguish between normal text and text marked as monospace. Maybe WeeChat should add an internal code for monospace text and have an option to determine how it should be represented?

**Comment by ToxicFrog** [comment]
That would be even better! The project that engendered this bug was writing a script to bracket monospace text with ` and colour it light blue, since I chat with a lot of people using clients that *do* support monospace and it's often used in load-bearing ways in these conversations, but if becomes a weechat builtin the need for that script goes away.

**Comment by GoldsteinE** [comment]
Is it possible to enable stripping `^Q` somehow? I don’t find it useful (all the text is already monospace) and random inverted `Q`s in the text are distracting.
