### ISSUE TITLE
highlight the timestamp instead of nick 

### ISSUE THREAD

**Issue by satmd** [weechat/weechat#2079]
### Feature description

I'd like to apply formatting to my chat's timestamp for highlights events instead of formatting the sender's nick.

This is especially useful for me since the timestamps have a fixed column on the left while I have nick + text alignment to the right (nick >| text).

We currently cannot do this and FlashCode asked me to put this idea up as a feature request.

**Comment by flashcode** [comment]
Implemented!

Now the option weechat.look.buffer_time_format allows a new variable `${highlight}` which can be used in a condition to have a specific format in case of highlight, for example:

    /set weechat.look.buffer_time_format "${if:${highlight}?${color:yellow,124}%H${color:187}%M${color:181}%S:${color:252}%H${color:243}%M${color:237}%S}"

In addition, a new boolean option weechat.look.highlight_prefix (`on` by default) is added to turn off highlight in the prefix (nick):

    /set weechat.look.highlight_prefix off

Result with these settings:

![image](https://github.com/weechat/weechat/assets/1776783/3d620586-1076-42db-9c04-7b6b99c36710)
