### ISSUE TITLE
Provide stable IDs for relay objects

### ISSUE THREAD

**Issue by oakkitten** [weechat/weechat#2081]
### Feature description

In relay clients, we receive from WeeChat various objects such as buffers, lines, nicks, etc. Currently none of them have stable IDs, and it is impossible to reliably tell whether or not two objects represent the same thing. There are pointers, but they may become reused when old objects such as lines are removed. This does happen in practice. Also, upgrading WeeChat invalidates all pointers. For buffers, there are full names, but these can also change.

This is a big problem when reconnecting, which is a rather common occurrence in Weechat-Android, and in some other cases. When reconnecting, we already have a list of buffers, and some lines for some buffers. If we don't have stable IDs, we cannot tell which old buffers or lines correspond to the new ones, and thus cannot properly animate the changes.

Another issue is that we have problems saving local state. For instance, Weechat-Android maintains a local read line marker, and after reconnection its position may become invalid.

And, generally speaking, having stable IDs makes the development so much easier. Android APIs often ask to provide IDs for things and then it all just works out of the box.

So I propose having stable IDs for relay objects. I imagine that these would be as unique as possible within their domain, e.g. two buffers are allowed to have lines with the same IDs, and the ID is just a number that gets increased until it overflows. I'm not quite sure about C, I imagine that you'd use 64 bits for these on a 64-bit machine, which should give us 18 quintillion IDs, which should be enough even for cases when there's a plugin or script that overwrites the lines a lot.

**Comment by flashcode** [comment]
Actually the buffer lines have an id since WeeChat 3.8 (see issue #901), but I just realized it's not sent to weechat relay clients, so I'll add this.

I'll add identifiers in the other objects, starting with the buffers.

For nicks, is it really needed as well?

**Comment by oakkitten** [comment]
That's great, thanks!

> For nicks, is it really needed as well (as a nickname is unique in the nicklist)?

Well, we are in fact detecting item movements when diffing the nicklist. So if you change your nick from `foo` to `bar`, you would see your name visually move upwards. Without IDs, you'd see one name disappear and another name appear. On the other hand, we should not delude ourselves into thinking that in reality anyone cares about nicklist animations...

**Comment by flashcode** [comment]
I added unique identifier (called `id`) in buffers, that persists across `/upgrade`.

For nicks, this is a bit more complicated to add as-is, it can be added later, I plan to remove list of nicks in IRC plugin and use only buffer nicklist.

I keep issue open until it's implemented.

**Comment by weechatter** [comment]
I would still prefer to have the nicklist as a plugin, in that context

**Comment by flashcode** [comment]
If IRC plugin stores data on the core nicklist, it must be in core.
As all plugins are independent, IRC must not depend on another plugin to be able to run fine.

Maybe you could detail your idea @weechatter, and explain why for you it could be better to have a nicklist as plugin?

**Comment by flashcode** [comment]
I finally added the id in nicklist groups and nicks, so I close this issue.

This id is returned in the new API relay (see the spec: https://specs.weechat.org/specs/2023-005-relay-http-rest-api.html).

Protocol "weechat" is unchanged, as it should be progressively replaced by the "api" protocol, and may even be removed in a future version (when no more clients are using it).
