### ISSUE TITLE
memory leak after using a huge argument list to a command

### ISSUE THREAD

**Issue by pascalpoitras** [weechat/weechat#2084]
### Describe the bug

When running any command with a huge argument list, the memory is not freed

### Steps to reproduce

1. /eval /print -core ${repeat:4000,hello hello hello}

consume huge memory, however, no problem if there is no space (just one big argument)

1. /eval /print -core ${repeat:4000,hellohellohello}
 
no problem here

### Current behavior

consume a huge amount of memory and never give it back

### WeeChat version

4.3.0

### What OS are you using?

Debian 12

### On which terminal are you running WeeChat?

kitty

### Which terminal multiplexer are you using?

tmux

**Comment by flashcode** [comment]
After some tests, I think this is not a memory leak in WeeChat (and Valgrind doesn't report any problem).

When doing a lot of `malloc()` and `free()`, the memory is not always shown as released by the process, but can be reused later for new calls to `malloc()`.

I wrote a simple program `test-malloc.c` that highlights this behavior:

```C
#include <stdlib.h>
#include <unistd.h>
#include <stdio.h>

int main (int argc, char *argv[])
{   
    char *test[50000];
    int i;

    for (i = 0; i < 50000; i++)
    {   
        test[i] = malloc (100000);
    }
    printf ("mallocs done\n");
    usleep (10 * 1000000);

    for (i = 0; i < 50000; i++)
    {   
        free (test[i]);
    }
    printf ("free done\n");
    usleep (10 * 1000000);

    return 0;
}
```

To test:

```
gcc -o test-malloc test-malloc.c && ./test-malloc
```

The memory increases, then is freed (there is no memory leak in this program).
After the free is done, the memory is still shown as used by the process (RSS = 201340 in this example of `ps aux` output):

```
user     3832288  0.4  0.3 4886328 201340 pts/4  S+   13:52   0:00 ./test-malloc
```

Valgrind also shows there's no issue with this program:

```
$ valgrind --leak-check=full --show-reachable=yes ./test-malloc
==3829375== Memcheck, a memory error detector
==3829375== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==3829375== Using Valgrind-3.20.0 and LibVEX; rerun with -h for copyright info
==3829375== Command: ./test-malloc
==3829375== 
mallocs done
free done
==3829375== 
==3829375== HEAP SUMMARY:
==3829375==     in use at exit: 0 bytes in 0 blocks
==3829375==   total heap usage: 50,001 allocs, 50,001 frees, 5,000,001,024 bytes allocated
==3829375== 
==3829375== All heap blocks were freed -- no leaks are possible
==3829375== 
==3829375== For lists of detected and suppressed errors, rerun with: -s
==3829375== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

**Comment by trygveaa** [comment]
>  When doing a lot of malloc() and free(), the memory is not always shown as released by the process, but can be reused later for new calls to malloc().

Right. An easy way to verify this is to just run the command multiple times, right? If there was a memory leak, the memory usage should continue to increase, but the memory usage almost doesn't increase on subsequent runs for me.

**Comment by flashcode** [comment]
> Right. An easy way to verify this is to just run the command multiple times, right? If there was a memory leak, the memory usage should continue to increase, but the memory usage almost doesn't increase on subsequent runs for me.

The memory is completely released anyway when the process exits.

I made another test: I do two times all the `malloc()` and `free()` by duplicating the code, and the second time the memory doesn't increase (or very little increase).
That confirms the fact the memory is reused on the subsequent `malloc()` calls.

**Comment by trygveaa** [comment]
> The memory is completely released anyway when the process exits.

I meant running `/eval ...` inside WeeChat multiple times, without exiting WeeChat.

**Comment by topcat001** [comment]
@flashcode A periodic `malloc_trim` might help to reduce the resident size. This is often seen with the gnu runtime (apparently for performance reasons).

**Comment by flashcode** [comment]
@topcat001: thanks, I didn't know this function!

I just tested, and it releases memory instantly, so I'll try to call it periodically in WeeChat.

@pascalpoitras: even if the memory is now shown as released, that does not mean there's a memory leak.

**Comment by flashcode** [comment]
I'm closing this issue as "Invalid" as there's no memory leak.

And I just added option `malloc_trim` in command `/sys` to release free memory from the heap (commit: a1bee89ecc6b88dab954269c5820f97cf5d30405).
