### ISSUE TITLE
/amsg and /ame also send in parted channels

### ISSUE THREAD

**Issue by crazycatdevs** [weechat/weechat#2085]
### Describe the bug

/amsg and /ame also send in parted channels if the buffer is not closed

### Steps to reproduce

1. do a /part in a channel without /close its buffer
2. do /amsg hello

### Current behavior

If channel is +n, you got a _No external channel messages_ response.
If channel allows external messages, the /amsg is well saw in the channel

### Expected behavior

/amsg and /ame sent only in channels the user is

### WeeChat version

4.0.2

### What OS are you using?

Debian 12

### Which terminal multiplexer are you using?

Screen

**Comment by flashcode** [comment]
Now the command `/allchan` (as well as aliases `/amsg` and `/ame`) is executed on all channels except parted channels.

A new paramter `-all` has been added to execute command on all channels.

And the parameter `-parted` is still there to execute command only on parted channels.
