### ISSUE TITLE
removing a line in a hook_line differ between free and formatted buffer

### ISSUE THREAD

**Issue by pascalpoitras** [weechat/weechat#2090]
### Describe the bug

as answered by @flashcode in the issue [#2087]([https://github.com/weechat/weechat/issues/2087), to remove a line in a weechat_print modifier, a simple /.*// is enough, in a hook_line you must remove the buffer from buffer_name.

but when you use hook_line on a free buffer it doesn't behave this way, I mean, all you have to do is a /.*// to remove the line, you don't have to remove the buffer from buffer name. 

not sure if this is a bug, I would like to know before pursuing what I'm doing since it change the way I have to implement it

### Steps to reproduce

1. `/trigger add test line "*;core.my_buffer_*" "" "/.*test.*//"`
2. `/print -switch -newbuffer my_buffer_formatted test`
3. a blank line is there as expected since we didn't touch buffer_name
4. `/print -switch -newbuffer my_buffer_free -free test`
5. no line is printed at all but we didn't touch buffer_name...
6. proof, print a non test line it will be the first line of the buffer
7. `/print -switch -newbuffer my_buffer_free -free hello`

### Current behavior

the behavior is not the one defined by FlashCode in the following issue [#2087]([https://github.com/weechat/weechat/issues/2087). So it's either a bug or he forgot to mention that it behave differently in a free buffer

### Expected behavior

should print a blank line according to issue [#2087]([https://github.com/weechat/weechat/issues/2087)

### WeeChat version

4.3.0

### What OS are you using?

Debian 12

**Comment by flashcode** [comment]
In fact this is normal because of a specificity of free buffers: when you print a line with an empty message, this deletes the line.

If the hook_line is modified to do that, that means deleting a line on free buffer must be done with another way, and this have impact on scripts doing this.

I'm going to document this in the hook_line API function.

**Comment by pascalpoitras** [comment]
all good, as long as it is documented!
