### ISSUE TITLE
For many IRC signals, ${nick} is the server domain instead of the nick

### ISSUE THREAD

**Issue by trygveaa** [weechat/weechat#2091]
### Describe the bug

In the `xxx,irc_in2_yyy` signal `${nick}` is supposed to be set to the nick, but for many of the IRC commands it's set to the server domain instead.

### Steps to reproduce

```
weechat -t -r '/trigger add print_irc_in2 signal *,irc_in2_* "" "" "/print nick: \${nick} - signal: \${tg_signal}"; /server add libera irc.libera.chat -autoconnect -autojoin=#test123'
```

### Current behavior

For many IRC commands `${nick}` is set to the server domain. If I try connecting to libera and joining a channel, only `MODE` and `JOIN` has it set to the nick, all the other commands has it set to the domain.

### Expected behavior

`${nick}` is set to the nick. It looks like many of the commands include the nick so this is possible, but for the commands that doesn't include the nick (e.g. before the nick is set), `${nick}` should be empty.

### WeeChat version

4.2.1

### What OS are you using?

Arch Linux

**Comment by flashcode** [comment]
Hi,

The variable `${nick}` is the sender of the message, not your own nick (which can be read in `${irc_server.nick}`.

I added a note in the doc: https://weechat.org/files/doc/weechat/devel/weechat_user.en.html#trigger_data_signal

**Comment by trygveaa** [comment]
Ahh, thanks!
