### ISSUE TITLE
Behaviors search_text and search_text_here the same? 

### ISSUE THREAD

**Issue by rieje** [weechat/weechat#2100]
### Question

I'm having trouble finding any differences in behavior between `search_text` and `search_text_here`, can someone describe a scenario where they differ? E.g. when I'm scrolled down to the bottom of the buffer, type `com` and as I type each character they show the same results (both show results from the full buffer).

I think `search_text_here` means restrict results to the viewable buffer, right? `/help input`:

    search_text_here: search text in buffer at current position
    search_text: search text in buffer

P.S. Wouldn't Github Discussions be more appropriate for people to ask simple questions like these and discuss ideas in general?

**Comment by trygveaa** [comment]
Both search in the current buffer, but `search_text_here` searches from the scrolled position, while `search_text` searches from the bottom of the buffer. I.e. it scrolls to the bottom and then searches. So if you're already at the bottom, they're the same.
