### ISSUE TITLE
Expose setting custom FIFO path as CLI argument for convenience

### ISSUE THREAD

**Issue by rieje** [weechat/weechat#2101]
### Feature description

Expose setting custom FIFO path as CLI argument. FIFO is a common way pass to Weechat commands to configure the client since editing the dotfiles is not recommended and a fixed path is convenient.

This is particularly convenient when setting up Weechat from scratch with a weechat-init script. There's `weechat -r` but trying to escape this in quotes to pass to `weechat -r '/exec ...` is a nightmare: `awk '{sub(/^#.*| * #.*/, ""); { if ( $0 != "" ) { print "*"$0 }}}' "weechat-init.conf"` (remove comments from my weechat-init.conf, prepend lines containing e.g. `/set` with `*/set`. I could have weechat-init script expose an argument that does the above parsing but I feel a custom FIFO path as a CLI argument makes more sense. 

Currently what I have as a workaround:

    # Kill existing weechat instances if any and remove potential remnants of
    # FIFO...
    
    # ...

    # Begin checking for weechat process to start. When weechat is started
    # later, configure it. Do this check in the background before weechat starts
    # since this script should be self-contained, i.e. when weechat starts it
    # should be ready to use)
    while ! pidof weechat /dev/null 2>&1; do 
      sleep 1
    done
    fifo=$(fd weechat_fifo /run/user/1000/weechat)
    awk '{sub(/^#.*| * #.*/, ""); { if ( $0 != "" ) { print "*"$0 }}}' "weechat-init.conf" > "$fifo"
    } &

    weechat

**Comment by trygveaa** [comment]
You can set a custom fifo with `-r`, e.g.:

```
weechat -r '/set fifo.file.path ~/.weechat_fifo'
```
