### ISSUE TITLE
Why does my custom buflist.format.buffer not respect color changes by weechat?

### ISSUE THREAD

**Issue by rieje** [weechat/weechat#2104]
### Question

What is causing buffer to always be white even when there are unread messages in other channels? To be clear, it should be gray on non-channel buffers, white on channel buffers (but respect color changes by weechat for e.g. unread messages), light gray for nick count: 

/set buflist.format.buffer "${format_number}${indent}${format_nick_prefix}${color_hotlist}${if:${type}==channel?${color:254,}:${color:250,}}${format_name}${if:${irc_channel.name}!=? ${color:gray,}${buffer.nicklist_nicks_count}:}"

Unrelated question: how come /color shows a color for 016 listed as "weechat color pairs pre-allocated" but when i Alt-c to show 256 colors, 016 is a different color? 

Much appreciated.

**Comment by flashcode** [comment]
Hi @rieje,

In your buflist format you use `${color_hotlist}` which sets the buffer color according to the hotlist, but after that you force the color by for example `${color:254,}`, which forces the color to white for any channel, discarding the hotlist color sets before.
So if you use hotlist color, you must not use any other color after.

For the colors buffer, WeeChat automatically allocates colors dynamically, this is displayed by default: so the number and the color is not related to "terminal colors" that you can display with alt+c. Only terminal colors are relevant and used. For example, if you use `${color:11}`, this is always yellow (what you can see on the buffer with alt+c or with `weechat -c` on command line).
