### ISSUE TITLE
ruby: (some) builtin functions not available with ruby 3.3

### ISSUE THREAD

**Issue by u3shit** [weechat/weechat#2109]
### Describe the bug

Upgrading my ruby from 3.1 to 3.3.1, my very simple script stopped working because it couldn't find `Kernel.loop`. (But it's also easily reproducible from `/ruby eval`).

### Steps to reproduce

1. `/ruby eval [].shuffle` or `/ruby eval loop { break }` or call any other function defined in `.rbinc` files.

### Current behavior

```
21:51:28 =!= | ruby: error: (eval at (eval at eval:34):7):1:in `script_ruby_eval': undefined method `shuffle' for an instance of Array (#<Class:#<NoMethodError:0x00007f4b6cdd6d78>>)
21:51:28 =!= | ruby: error:      from (eval at eval:34):7:in `module_eval'
21:51:28 =!= | ruby: error:      from (eval at eval:34):7:in `script_ruby_eval'
```

### Expected behavior

Built-in ruby functions work...

### WeeChat version

4.2.2

### What OS are you using?

Gentoo

**Comment by flashcode** [comment]
Hi,

Where can I find documentation on the function `ruby_process_options` ?
I just found the header `ruby/internal/interpreter.h` but the information is not detailed there.

**Comment by flashcode** [comment]
By the way, the problem is not specific to Ruby 3.3 because I have Ruby 3.1.2 and the same issue.
