### ISSUE TITLE
unban with range as parameter

### ISSUE THREAD

**Issue by fedxyz** [weechat/weechat#2113]
### Feature description

Hi,

right now it is possible to use for example  `/unban 1 2 3 4` , it would be nice imho to be able to use `/unban` with range, like `/unban 1-4`.
This will simplify if you have to remove a lot of bans in a channel.

Thanks

**Comment by flashcode** [comment]
The command `/unquiet` has a similar behavior, so it should be modified as well and work like `/unban`.
