### ISSUE TITLE
"Raw" logging

### ISSUE THREAD

**Issue by knghtbrd** [weechat/weechat#2114]
### Feature description

I would like to be able to have the option of logs that have IRC formatting left intact … The use of ANSI codes is helpful for colorizing logs I suppose, but for development I'm not dealing with ANSI codes, I'm dealing with ctrl-c, ctrl-b, ctrl-v, etc codes. Currently I'm debugging with printf (or at least with weechat.prnt) where I'm having to frobnicate these things to into basically duplicated log lines with formatting "intact" (encoded at least).

**Comment by flashcode** [comment]
Hi,
This is not so easy to do, as the IRC "raw codes" are first converted to WeeChat internal colors to be displayed.
And the logger plugin logs the messages displayed in buffers (not the IRC messages), this way it can log any message displayed, not only IRC protocol.
That's why you can either strip WeeChat colors (default) or convert them to ANSI colors optionnally.

**Comment by knghtbrd** [comment]
I wondered if it might be a case of "not the right way to do that" and "you should do this instead" when raising the question, I'm just not sure what the best "do this instead" would be in this case. It isn't the first time I've run into some frustration dealing with color/formatting codes. They're not too hard to strip out, but parsing them and generating weechat colors for them is kind of a pain (especially since I use a couple of mappings to prevent black on black and to actually approximate mIRC's orange for color 7)

But the major issue is needing to interact with bots that use colors and random unicode I need to write regexes for. Suggestions for the best way to do that are definitely welcome!

**Comment by flashcode** [comment]
I would say the solution to your problem depends on your needs, what do you want to do exactly?
With this input, I can suggest solutions.

If you need to deal with raw IRC messages, maybe the default logger is not the best one to do this.
Instead you could use signals in a trigger or in a script.

For example the following short Python script writes all messages received from the server in data directory called `irc_logs` (all server and channels messages are mixed in the same file):

```python
import weechat

LOG_DIR = None


def signal_irc_msg(data, signal, signal_data):
    """Raw log of IRC message."""
    server = signal.split(",")[0]
    with open(f"{LOG_DIR}/{server}.log", "a") as log_file:
        log_file.write(f"{signal_data}\n")
    return weechat.WEECHAT_RC_OK


weechat.register("irc_logger", "FlashCode", "0.1", "GPL3", "IRC logger", "", "")
LOG_DIR = weechat.string_eval_expression("${weechat_data_dir}/irc_logs", "", "", "")
weechat.mkdir_parents(LOG_DIR, 0o0755)
weechat.hook_signal("*,irc_raw_in_*", "signal_irc_msg", "")
```

**Comment by knghtbrd** [comment]
I think just logging myself with python is probably the right way to do it—basically I'm parsing output from bots and trying to keep my regexes specific. That means they break if the output changes (it just did), but it also means that that my script responds to only what it's supposed to. But there's noprintables (color and formatting) in the bot output, so I want to make sure the regexes account for that. When I'm working on that kind of thing, the easiest way would be to log everything raw as it comes from the server (at least the part in msg[4:]), interact with the bots manually, then use that log to write the hooks.

That's such a simple script and it'd be easy to extend with e.g. a toggle … I'd say it solves the problem, so I'll go ahead and close this issue.
