### ISSUE TITLE
Regex /list searches do not create or populate a dedicated list buffer

### ISSUE THREAD

**Issue by meldra** [weechat/weechat#2124]
### Describe the bug

The current `/help list` does not make obvious that `/list -re pattern`, unlike the previous two examples, will not create or populate a dedicated buffer.

```
      20:56 Examples:
      20:56   list all channels on server and display them in a dedicated buffer (can be slow on large networks):
[1]   20:56     /list
      20:56   list channel #weechat:
[2]   20:56     /list #weechat
      20:56   list all channels beginning with "#weechat" (can be very slow on large networks):
[3]   20:56     /list -re #weechat.*
      20:56   on /list buffer:
      20:56     channels with "weechat" in name:
      20:56       n:weechat
      20:56     channels with at least 100 users:
      20:56       u:100
      20:56     channels with "freebsd" (case insensitive) in topic and more than 10 users:
      20:56       c:${topic} =- freebsd && ${users} > 10
      20:56     sort channels by users (big channels first), then name2 (name without prefix):
      20:56       s:-users,name2
```

[1] creates a list buffer and mentions dedicated buffer
[2] creates a list buffer and *does not* mention dedicated buffer
[3] *does not* create a list buffer and *does not* mention dedicated buffer

If it is supposed to, it does not. If it's not supposed to, this should be made clear to prevent suckers like me staring at the list buffer waiting for it to populate.

### Steps to reproduce

1. Read `/help list` and do `/list #weechat.*`
2. Have results appear in network buffer
3. Wait for it to appear in the dedicated /list buffer
4. Wait some more
5. Notice unread lines in the network buffer, curse out loud, and swap to that

### Current behavior

Outputs the results in the network buffer

### Expected behavior

Output appears in the dedicated list buffer, creating it if necessary.

### Suggested solutions

Ideally it should go where it's expected, the dedicated list buffer.

If there are Reasons why it cannot then the helptext needs to be more clear.

### WeeChat version

4.3.1  and  WeeChat 4.4.0-dev (git: v4.3.0-40-g9264803bc) [compiled on Jun  1 2024 13:24:43]

### What OS are you using?

Debian Bookworm

**Comment by flashcode** [comment]
Hi,

I agree `-re` should ideally open a new buffer, I think it was not so easy to implement, but I'll look again.

By the way it's clearly mentioned in the help that a buffer is not opened with this option, extract:

```
list channels and their topics

 server: send to this server (internal name)
  regex: POSIX extended regular expression used to filter results (case insensitive, can start by "(?-i)" to become case sensitive); when a regular expression is used, the result is displayed on server buffer instead of a dedicated buffer
(...)
```

It could be also mentioned in the example though.

Anyway my preferred solution would be to always open the buffer, even with `-re`.\
If needed I could introduce a specific new option `-raw` to force the results to be displayed on the server buffer (and then not opening the /list buffer), eg:

```
/list -raw -re #weechat.*
```

**Comment by flashcode** [comment]
Or maybe `-re` could just be renamed to `-raw`, and mention that the following parameter is a regex?

Or do we need to be able to filter with regex even before the buffer is opened?

**Comment by meldra** [comment]
> I think it was not so easy to implement, but I'll look again.

If you can remember why and explain it perhaps a solution can be crowd-sourced

> Anyway my preferred solution would be to always open the buffer, even with -re.

same, its way easier to read. Also it would be nice to be able to easily revise the pattern in the same context -- without a bunch of similar outputs that aren't well separated from the previous attempt.

> By the way it's clearly mentioned in the help that a buffer is not opened with this option, extract:

ooh i missed that!

> I could introduce a specific new option -raw to force the results to be displayed on the server buffer 

might be worthwhile regardless, i can think of use-cases where people might want to do that so they can grab the output from the log.

**Comment by flashcode** [comment]
> might be worthwhile regardless, i can think of use-cases where people might want to do that so they can grab the output from the log.

By the way, in the meanwhile I added `/list -export <filename>` so you can now export the results displayed in list buffer to a file (with new option `irc.look.list_buffer_format_export` to customize the format of lines written in the file).

So as a solution to the issue, I propose to just rename `-re` to `-raw`, with one mandatory parameter after, which could be either `*` (no filtering) or a regex, to filter by channel name.

And also mention clearly in `/help list` that `-raw` doesn't open the list buffer.

Would that be OK?

**Comment by meldra** [comment]
Yeah I think that's all good!
