### ISSUE TITLE
Input prompt is not displayed in IRC private buffers

### ISSUE THREAD

**Issue by flashcode** [weechat/weechat#2128]
### Describe the bug

When opening an IRC private buffer with `/query <nick>`, the input prompt is not displayed.

### Steps to reproduce

1. Connect to any server.
2. Issue command: `/query <nick>` (any nick)

### Current behavior

Nothing is displayed in input prompt.

### Expected behavior

Nick and modes are displayed in input prompt, like: `[nick(i)]`.

### WeeChat version

4.3.1

### What OS are you using?

Debian Sid

### On which terminal are you running WeeChat?

Terminator

### Which terminal multiplexer are you using?

screen

**Comment by meldra** [comment]
WeeChat 4.3.2-dev [compiled on Jun  6 2024 12:56:06] confirmed fixed with opening a /query <nick> and a /dcc chat <nick>
