### ISSUE TITLE
Adding word to spell personal dictionary

### ISSUE THREAD

**Issue by klapvogn** [weechat/weechat#2144]
### Describe the bug

When I do IE: `/spell addword en rj45` I get :  spell: failed to add word to personal dictionary

### Steps to reproduce

1. Try and add a word to spell personal dictionary

### Current behavior

spell: failed to add word to personal dictionary

### Expected behavior

It should add a givin word to the personal dictionary

### Suggested solutions

No clue

### Additional information

Have none

### WeeChat version

4.4.0-dev

### What OS/distribution are you using?

Ubuntu 22.04

### On which terminal are you running WeeChat?

Kitty

### Which terminal multiplexer are you using?

tmux

**Comment by flashcode** [comment]
Hi,

You mean command `/spell addword en rj45`?

Can you check if aspell or enchant is used in output of `/debug libs` in WeeChat?

If aspell is used, you should have a file `~/.aspell.en.pws` writable by your used, is this the case? (this is your personal dictionary)

**Comment by flashcode** [comment]
It could be an error of aspell, but WeeChat might not display the aspell error, just a generic message. I'll look it I get the aspell error in this case.

If you do this in shell:

    echo -e "*rj45\n#" | aspell -a

What's the result?

**Comment by flashcode** [comment]
OK so this means the word "rj45" is not valid for aspell (weird by the way).
I have the same error as you with this word in weechat.
Then I think it's not a WeeChat issue, but I'll try to display a clean error in WeeChat anyway.

**Comment by flashcode** [comment]
Done, the error displayed for command `/spell addword en rj45` is now:

    =!= | spell: failed to add word to personal dictionary: The word "rj45" is invalid. The character '4' (U+34) may not appear in the middle of a word.

**Comment by flashcode** [comment]
Once the new version is compiled & installed (at same location), you can do `/upgrade`.
