### ISSUE TITLE
api relay: nicklist is not getting refreshed unless you re-open the clientside buffer

### ISSUE THREAD

**Issue by NetSysFire** [weechat/weechat#2161]
### Describe the bug

This results in the nick list being essentially frozen.

Edit: This was the result of a state that was broken somehow. I can not reproduce this anymore and instead search for how the state got broken. I suspect `/upgrade`.

### Steps to reproduce

1. Connect to a remote.
2. Join any channel.
3. Wait until someone in there leaves.

### Current behavior

The nicklist still shows the nick that left. This also affects the completion because a newly joined nick can not be tab completed.

The only way to force an update of the nicklist is to /remote disconnect, *manually* close all the buffers on the client and then connect again.

### Expected behavior

The nicklist updates with each join/leave event.

### WeeChat version

4.3.4

### What OS/distribution are you using?

Arch Linux, Ubuntu 24.04

**Comment by flashcode** [comment]
Yes it seems to be related to `/upgrade` issues on client side, the remote is disconnected and not automatically reconnected after upgrade.

I keep the issue opened to fix this issue, but this is not a nicklist refresh issue, nothing is updated any more in the buffer.

**Comment by NetSysFire** [comment]
It was most certainly being updated, just not the nicklist.

**Comment by NetSysFire** [comment]
An update:

This is happening again. As I said, only the nicklist does not refresh. Per `#weechat`, I looked in `/relay raw` and the nicklist_nick_removing, nicklist_nick_added and buffer_line_added lines show up just fine. I can see people joining or leaving but just the nicklist is essentially frozen in a state where it does not get updated.

Right now I do not believe that /upgrade is at fault because the last /upgrade happened two days ago or so and the nicklist started acting up yesterday. I can not reliably say that /upgrade has no part in it however.

```
17:35 <@FlashCode> if /remote reconnect doesn't work, that's probably because the id of nicks or groups are wrong
17:35 <@FlashCode> in the buffer
```
