### ISSUE TITLE
Add support for numeric 569

### ISSUE THREAD

**Issue by TehPeGaSuS** [weechat/weechat#2162]
### Feature description

UnrealIRCd recently added ASN support for WHOIS.
The numeric they chose was `569`, which seems to be used by UnrealIRCd and InspIRCd (only opers can see ASN related info).
The relevant UnrealIRCd commit is [this one](https://github.com/unrealircd/unrealircd/commit/1b4f987ab772cdb9994738c9d99dd76a2c69b6ac).
Currently when we do an WHOIS to someone we get something like `-- James 8772 is connecting from AS8772 [NetAssist LLC]` which seems to be a generic reply.
Some more context [here](https://github.com/unrealircd/unrealircd/blob/unreal60_dev/doc/RELEASE-NOTES.md#developers-and-protocol-1).

**Comment by flashcode** [comment]
Done, the following message:

    :server 569 alice bob 12345 :is connecting from AS12345 [Hoster]

is displayed as:

    -- | [bob] is connecting from AS12345 [Hoster] (12345)
