### ISSUE TITLE
Add an option to force ipv6

### ISSUE THREAD

**Issue by NetSysFire** [weechat/weechat#2164]
### Feature description

There is `irc.server.<server>.ipv6` but no equivalent for ipv4. For several reasons you may want to force using ipv6. Apparently setting `irc.server.<server>.local_hostname` to `::` or systemd service unit shenanigans (`RestrictAddressFamilies=AF_UNIX AF_INET6` or the like) may work, but this is a bit hacky.

Related: #1197

**Comment by flashcode** [comment]
Proposal: transform the boolean server option `.ipv6` to an enum, with 3 possible values:

1. `auto` (default): use IPv6, fallback on IPv4
1. `force`: use ipv6 only
1. `disabled`: use IPv4 only

By the way the proxy boolean option `.ipv6` could be changed with the same behavior.

What do you think?

**Comment by NetSysFire** [comment]
I assume you mean `.ipv4` at the last part there.

I am unsure because that enables you to set both `.ipv6` and `.ipv4` to `force` and feels thus a bit clunky. But the only other solution I have in mind is e.g having `.ip_prefer` and setting that to either `ipv4` or `ipv6`. Which also partially has that issue and does not make that any better.

**Comment by trygveaa** [comment]
No, he means only having an `.ipv6` option which is set to one of those three values. So you won't be able to set any conflicting values.

**Comment by flashcode** [comment]
Done, proxy and IRC server options `ipv6` have been converted to enum (`disable` / `auto` / `force`), with new version and automatic upgrade for config files weechat.conf and irc.conf.
