### ISSUE TITLE
add a signal when we switch to a different layout

### ISSUE THREAD

**Issue by pascalpoitras** [weechat/weechat#2167]
### Feature description

It would be useful to have a signal when we switch to a different layout. It would also fix a problem with autosort.py, if you save your layout, switch to a different one, open additionals buffers, and came back to the previous layout, the news buffers are not sorted you must issue a /autosort sort. With that we could add the signal to autosort.sorting.signals or ask @de-vri-es to change the default value of that option

**Comment by de-vri-es** [comment]
Sure, if such a signal exists it sounds like a good idea to add it to the defaults. Although it does sound odd to mix layouts with autosort.py :o
