### ISSUE TITLE
IRC channels with ISO-8859-15 characters do not work.

### ISSUE THREAD

**Issue by Nredor** [weechat/weechat#218]
There's one channel named #esitelmä with one ISO-8859-15 character. I can join typing /eval /join #esitelm${\0344} but when I try to write something there weechat says "no such channel".  My system is UTF-8.

**Comment by OzQu** [comment]
I'm also suffering from this bug. I would love to start using weechat instead of irssi, but this is quite important for me. 

Just wanted to make some noise about this bug, so maybe one day someone will have time to do something about it..

**Comment by ISO-B** [comment]
Having same issue as well.

**Comment by flashcode** [comment]
Hi,
The problem should be fixed.
I made some tests (which were OK), but I'm not sure if ISO-8859-15 chars in channel names could cause some bugs in display or commands.
If you find other bugs, please open a new ticket (or reopen this one if you think the problem is not fixed).

**Comment by Mikaela** [comment]
**offtopic**

> (or reopen this one if you think the problem is not fixed)

unless you close the issue by yourself, only organization members with appropiate permissions can reopen issues.

**Comment by flashcode** [comment]
Ah, then just add a comment instead of reopening the issue if that's not possible.

**Comment by flashcode** [comment]
I changed the behavior in version 2.7-dev, to fix the issue #832, so now the default is to decode/encode the whole IRC message. See the commit and the release notes for more info: 39b6fb61370de2591146460bd5414955a234801e and https://weechat.org/files/releasenotes/ReleaseNotes-devel.html#v2.7_irc_message_decoding.
