### ISSUE TITLE
Add possibility to set headers in hook_process_hashtable

### ISSUE THREAD

**Issue by Ulrar** [weechat/weechat#219]
Hi,

It would be useful to be able to set custom headers in hook_process_hashtable, like the Content-Type as discussed on irc. guile-curl takes an alist for example, with a key and a value for each.

**Comment by flashcode** [comment]
Done via PR #826.

To send custom HTTP headers in the request, see the second example in function hook_process_hashtable: https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hook_process_hashtable
