### ISSUE TITLE
Log status changes of users/members in bitlbee

### ISSUE THREAD

**Issue by ManuGraiph** [weechat/weechat#2196]
### Question

Hi,

I'm using weechat with the bitlbee plugin in order to gateway into slack, discord, etc. Is there a way to log (either into bitlbee or weechat) when a user goes offline/online/away in one of the said bitlbee gateway plugins?

Thanks in advance!

**Comment by flashcode** [comment]
Hi,

Which plugin or script are you using?

There is maybe a bitlbee option to do that, I'm not sure this is a WeeChat issue: WeeChat displays all messages received from the server.

**Comment by ManuGraiph** [comment]
Hi,

Yeah, it's for sure a bitlbee thing, because the status change doesn't trigger a chat message, but i thought maybe it was a common feature that already was solved/scripted in some weechat plugin or similar.

I'm using the `slack 02` plugin for bitlbee (the standard libpurple one).

Any idea how to achieve it?

Thanks in advance.

**Comment by flashcode** [comment]
I'm not using this and I don't know.
I keep the issue open just in case anyone can help.

**Comment by ManuGraiph** [comment]
Yep, that's precisely why i posted it, so if somebody knows how to do it and wanna share, he is more than welcome :).
