### ISSUE TITLE
Remove formatting codes in script parsed incoming messages

### ISSUE THREAD

**Issue by edy1234** [weechat/weechat#2200]
### Question

Hi,

I am using a python script to try and parse incoming messages.

I use hook_signal 

weechat.hook_signal("*,irc_in2_privmsg", "parse_messages", "")

and then in that function 

message_string = weechat.info_get_hashtable("irc_message_parse", {"message": signal_data})

If I output the parsed messages with weechat.prnt() in an extra buffer and if they contain color or boldness formatting, extra letters for the formatting show up in the output. Like e.g.

C14This is my dark grey text.C BOh, and here it is bold.B

I've tried to clean it up with regex expressions, but since there isn't that universal pattern I see, I wondered if there is a weechat way to get rid of the formatting codes in the strings output. I've found settings that disable the colour in the chat buffers of channels I am in, but the parsed messages I output with weechat.prnt() still contain the codes.

**Comment by flashcode** [comment]
Hi,

You can call the modifier "irc_color_decode" to strip IRC color codes in message before printing it:

```python
result = weechat.hook_modifier_exec("irc_color_decode", "0", message)
```

And if you replace "0" by "1", this replaces IRC color codes by WeeChat color codes, so the color are properly displayed.

**Comment by edy1234** [comment]
Got it to work. Thank you very much for the help and explanation! Much appreciated.
