### ISSUE TITLE
.tls and .tls_verify options are not found

### ISSUE THREAD

**Issue by Charlie-Bell** [weechat/weechat#2203]
### Describe the bug

I just installed the most recent stable version of WeeChat on my Ubuntu 22.04 via the instructions https://weechat.org/download/debian/

I have a server called `irchighway` which I added via:
```
/server add irchighway irc.irchighway.net/7000
```

When I run `/connect irchighway` I get message `irc: connection refused`.

I've checked my settings via:
```/fset irc.server.irchighway.*```
and can see that `irc.server.irchighway.tls` and `irc.server.irchighway.tls_verify` are `on`.

The real issue is when I try to set them to `off` with for example
```/set irc.server.irchighway.tls off```
I get the message `Option "irc.server.irchighway.tsl" not found`

This is of course unexpected behaviour since this should not happen.

### Steps to reproduce

Create a server and try to set tls to off exactly as written in the docs.

### Current behavior

Option for tls is not found.

### Expected behavior

Option for tls should be set to off.

### WeeChat version

4.4.2

### What OS/distribution are you using?

Ubuntu 22.04

### On which terminal are you running WeeChat?

Terminal (default)

### Which terminal multiplexer are you using?

None

**Comment by flashcode** [comment]
Hi,

> I get the message `Option "irc.server.irchighway.tsl" not found`

Your message mentions `.tsl` option, while the real option is `.tls`, are you sure you didn't make a typo in your command?

The option `irc.server.xxx.tls` should always exist, if the server `xxx` exists.

**Comment by Charlie-Bell** [comment]
Just tried it on a fresh install and all worked as expected. It could have been a typo before whenever I was running the `/set irc.server.irchighway.tls off`.

**Comment by flashcode** [comment]
OK, so I close this issue.
