### ISSUE TITLE
Script window crashes when a search term is found and highlight bar is on the last line

### ISSUE THREAD

**Issue by paulw2u** [weechat/weechat#2215]
### Describe the bug

1. When using the script window to find scripts I experience a crash when moving to end of the list and enter a search term which **is** part of a script name, i.e. the search is successful.

### Steps to reproduce

1. Start WeeChat
2. Open a script window with /script
3. Move to the end of the list
4. Enter a search term such as "mon" or "py"

### Current behavior

WeeChat crashes every time a search is successful, i.e. _mon_, _py_ or _wtt_ but it won't crash if you search for something like _uuuu_, _ooo_ or _iii_.

### Expected behavior

The display should change to include every script that includes the filter term.

### Additional information

======= WeeChat backtrace =======
(written by WeeChat 4.5.0-dev (git: v4.4.0-200-gea1162379), compiled on Nov 25 2024 20:30:29)
001  ??:? [function weechat_backtrace]
002  ??:? [function debug_sigsegv_cb]
addr2line: '0xaec23': No such file
addr2line: '0x1d7156': No such file
005  ??:? [function __sigaction]
addr2line: '0xbe78': No such file
addr2line: '0xea52': No such file
addr2line: '0xefaa': No such file
009  ??:? [function hook_signal_send]
010  ??:? [function gui_line_free_all]
011  ??:? [function gui_buffer_clear]
addr2line: '0xe7ff': No such file
addr2line: '0x16879': No such file
addr2line: '0xf335': No such file
015  ??:? [function input_exec_data]
016  ??:? [function input_data]
017  ??:? [function gui_input_send_data_to_buffer]
018  ??:? [function gui_input_return]
019  ??:? [function command_input]
020  ??:? [function hook_command_exec]
021  ??:? [function input_exec_command]
022  ??:? [function input_data]
023  ??:? [function gui_key_pressed]
024  ??:? [function gui_key_flush]
025  ??:? [function gui_key_read_cb]
026  ??:? [function hook_fd_exec]
027  ??:? [function gui_main_loop]
028  ??:? [function main]
029  ??:? [function __libc_init_first]
030  ??:? [function __libc_start_main]
031  ??:? [function _start]
======= End of  backtrace =======

### WeeChat version

4.5.0-dev (git: v4.4.0-200-gea1162379)

### What OS/distribution are you using?

Kubuntu 24.04

### On which terminal are you running WeeChat?

Konsole

### Which terminal multiplexer are you using?

tmux

**Comment by trygveaa** [comment]
I just opened a PR to fix this: #2214
