### ISSUE TITLE
Command line option to set UI language

### ISSUE THREAD

**Issue by umikali222** [weechat/weechat#2217]
### Feature description

There should be a command line option to open weechat with a specific UI language.

**Comment by flashcode** [comment]
Hi,

As most commands, WeeChat is based on your current locale, so the language depends on environment variables (either global on your system or specific to your user), and this is the standard way to change the languages for commands you execute.

For example if you want to force the English (US) language, just for WeeChat, you can do:

```
LANG=en_US.UTF-8 weechat
```

You can also define such variable in your shell init file (eg `~/.bashrc`) or make an alias:

```
alias weechat="LANG=en_US.UTF-8 weechat"
```

I'm curious why you would need extra command line argument to force the language, what's the use case?

**Comment by umikali222** [comment]
I thought this option might be useful, because I didn't think of just changing the environment variable.
