### ISSUE TITLE
Add support for SASL ECDSA-NIST256P-CHALLENGE

### ISSUE THREAD

**Issue by maxteufel** [weechat/weechat#251]
Please add support for the SASL ECDSA-NIST256P-CHALLENGE mechanism.
Documentation is here: <https://github.com/atheme/ecdsatool>

**Comment by flashcode** [comment]
Quick instructions (I'll add that soon in user's guide):
1. `openssl ecparam -genkey -name prime256v1 >~/.weechat/ecdsa.pem`
2. `openssl ec -noout -text -conv_form compressed -in ecdsa.pem | grep '^pub:' -A 3 | tail -n 3 | tr -d ' \n:' | xxd -r -p | base64` (this is your pubkey as base64)
3. `/connect freenode`
4. `/msg nickserv set property pubkey <pubkey here>`
5. `/set irc.server.freenode.sasl_mechanism ecdsa-nist256p-challenge`
6. `/set irc.server.freenode.sasl_username <account>`
7. `/set irc.server.freenode.sasl_key %h/ecdsa.pem`
8. `/reconnect freenode`

**Comment by maxteufel** [comment]
> 4 `/msg nickserv set property pubkey <pubkey here>`

`/msg NickServ set pubkey <pubkey here>` is preferred in Atheme 7.2.3+ (freenode is running 7.2.4 with nickserv/set_pubkey.so loaded at the moment).

**Comment by Mikaela** [comment]
And because of that issue you found, no one should run Atheme that desn't have the `/ns set pubkey`.

**Comment by un1versal** [comment]
> Deleted, sorry

@ctrlaltca so this is where you spend your time ;)
