### ISSUE TITLE
Scripts seem to be downloaded insecurely

### ISSUE THREAD

**Issue by 8573** [weechat/weechat#253]
The `/script` command appeared to download the scripts and the index of
scripts via unsecured HTTP, which would seem to be a security risk, unless
there is some subsequent cryptographic verification of the downloaded data.

Three potential solutions I see are:
- Downloading from https://github.com/weechat/scripts rather than from
  http://weechat.org.
  
  I suppose the script index would need to be uploaded to GitHub, perhaps
  with GitHub’s “releases” feature.
- Upgrading `weechat.org` to HTTPS, perhaps with a free certificate from
  GlobalSign: https://www.globalsign.com/ssl/ssl-open-source/.
  
  This would also cover the packages that are offered for download from
  http://weechat.org.
- Having the scripts and the script index be cryptographically signed with
  (e.g.) an OpenPGP implementation, and verifying the signatures.

**Comment by flashcode** [comment]
The option script.scripts.url_force_https has been removed because now weechat.org is HTTPS only (there's an automatic redirection from HTTP to HTTPS).
The default value for option script.scripts.url is now using HTTPS.
