### ISSUE TITLE
Renumber windows

### ISSUE THREAD

**Issue by Ram-Z** [weechat/weechat#257]
Add an option to change the number of the current window.

**Comment by SethMilliken** [comment]
I have multiple sessions in each of which I monitor about a dozen weechat windows in roughly the same layout. Being able to renumber windows would make it much easier to have the window numbers match up with the corresponding physical locations of the windows in each session.

**Comment by flashcode** [comment]
Duplicated by #605, I close this one (the other issue has more info).
