### ISSUE TITLE
nicklist sorting is case sensitive when nicknames are not in latin

### ISSUE THREAD

**Issue by oakkitten** [weechat/weechat#258]
e.g. it can go like

```
Груша
Яблоко
груша
яблоко
```

**Comment by flashcode** [comment]
I made some tests with function `towlower_l` but that does not work with accents.
And I don't know any function in glibc to compare two UTF-8 in a case insensitive way, if someone knows a function for that, any help is appreciated.

**Comment by Earnestly** [comment]
Perhaps try using [libunistring](http://www.gnu.org/software/libunistring/manual/libunistring.html).  It's not a trivial requirement to sort arbitrary locale dependent strings. I would consider using a library designed for these tricky details such as this or [icu](http://site.icu-project.org/).

ICU demonstration for sorting: http://demo.icu-project.org/icu-bin/locexp?_=en_US&d_=en&x=col

**Comment by Hello71** [comment]
I think you may want to try `strcoll` function.

**Comment by flashcode** [comment]
Thanks, this function seems interesting, it works fine with French accents.
I'll play a bit with it.

**Comment by flashcode** [comment]
So after some tests, I can say the function `strcoll` seems relevant to sort things for display, like the nicklist.

But the downside it that it is very slow compared to `strcmp` or the weechat case-insensitive comparison `string_strcasecmp`, so it should probably not be used everywhere in the code for case insensitive comparisons.

**Comment by Hello71** [comment]
if you are sorting large data then you are supposed to first call strxfrm to normalize the data before sorting with strcmp.

**Comment by flashcode** [comment]
Finally I noticed that functions `towlower` and `towupper` works well with the locale properly set, so I used them and made some optimizations to skip them in case of ASCII chars (< 128).

Example:

    /eval -n ${upper:àáâãäåæçèéêëìíîïðñòóôõöøœšùúûüýÿ}
    == [ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØŒŠÙÚÛÜÝŸ]

Nicklist should now be properly sorted, like everything that is sorted in a case insensitive way in WeeChat as well (as low-level functions were updated).
