### ISSUE TITLE
Add a speed limit for received files

### ISSUE THREAD

**Issue by notfoss** [weechat/weechat#269]
While downloading files using dcc, the speed limit is not being enforced. The xfer plugin _is_ being loaded. I have the following in my `xfer.conf`. 

```
speed_limit = 60
```

Using:
1. Version: WeeChat 1.0.1 (also tried with 0.4.2) 
2. OS: Linux Mint 17

**Comment by faulesocke** [comment]
Any progress on this since 2014? I could maybe invest some time and implement it, when someone could point me to the relevant places in the code? Actually, this would just require limiting the amount of recv-calls, right?

**Comment by flashcode** [comment]
No progress yet, but it should not be so hard to implement, so I'll make some tests.
I'll rename the current option to from `xfer.network.speed_limit` to `xfer.network.speed_limit_send` and introduce a new one: `xfer.network.speed_limit_recv`.

**Comment by flashcode** [comment]
Done!

**Comment by mdnghtman** [comment]
Right now, the speedlimit is only limiting the speed of single files.
I think it would be better to limit the speed globally for all received files, or at least give an option to do so. Receiving multiple files now leads to having the full bandwith unintendedly taken by weechat.

**Comment by flashcode** [comment]
@mdnghtman: good point, please add a new issue for this feature.
I'll think about the way to configure that (new option or not), and it should also adjust the speed of transfers in progress (not so easy because transfers are made in forked process).
