### ISSUE TITLE
weechat error while starting in Mac

### ISSUE THREAD

**Issue by ghost** [weechat/weechat#277]
```
weechat --version
1.0.1

MAC OSX : 10.8.5

weechat
Error: unable to create/append to log file (weechat.log)
If another WeeChat process is using this file, try to run WeeChat
with another home using "--dir" command line option.
```

This is a clean installation from homebrew. I would be great if someone know about this problem. Thanks

**Comment by georgeportillo** [comment]
How could I re-connect to my weechat instance?

**Comment by flashcode** [comment]
@georgeportillo: if you mean keep weechat running and disconnect, you can run WeeChat under screen or tmux, and detach from it, then reattach later.
