### ISSUE TITLE
backlog missing when irc.look.buffer_open_before_autojoin is true

### ISSUE THREAD

**Issue by holomorph** [weechat/weechat#279]
i'm not seeing backlog in autojoined channels. I still see backlog in `&bitlbee`, but I guess that's different.

Toggling `irc.look.buffer_open_before_autojoin` to `false` restores backlogs in autojoin channels.

**Comment by flashcode** [comment]
Some news about the problem?
The next release (1.1) is scheduled tomorrow, so if there's really a problem with this new option, it would be nice to fix before the release.

**Comment by holomorph** [comment]
Hm, changing my logger settings from
```
[file] (logger.conf)
  logger.file.mask = "$server/$channel.log"  (default: "$plugin.$name.weechatlog")
  logger.file.path = "~/.cache/weechat/logs"  (default: "%h/logs/")
```
back to the defaults, I find the directory `$server` in `logs`, with the file `$channel.log` containing
```
2015-01-03 08:58:36		Option changed: logger.file.mask = "$server/$channel.log"  (default: "$plugin.$name.weechatlog")
2015-01-03 09:19:26		Option changed: logger.file.path = "%h/logs/"
```

**Comment by holomorph** [comment]
Here's my current `/set diff` from a fresh config in weechat `6d12514`
```
[server_default] (irc.conf)
  irc.server_default.nicks = "holomorph"  (default: "")
  irc.server_default.sasl_username = "holomorph"  (default: "")
  irc.server_default.ssl = on  (default: off)
  irc.server_default.ssl_cert = "~/.config/ssl/certs/holomorph.pem"  (default: "")
  irc.server_default.username = "holomorph"  (default: "")

[server] (irc.conf)
  irc.server.freenode.addresses = "chat.freenode.net/7000"  (default: (undefined))
  irc.server.freenode.autoconnect = on  (default: (undefined))
  irc.server.freenode.autojoin = "#weechat"  (default: (undefined))
  irc.server.freenode.sasl_password = "${sec.data.freenode}"  (default: (undefined))
  irc.server.freenode.ssl_dhkey_size = 1024  (default: (undefined))
```
Also copying the relevant `sec.conf` setting. I still get the issue. No backlog.

Beyond this, if I toggle `irc.look.buffer_open_before_autojoin` to `off` I get backlog again.

**Comment by flashcode** [comment]
You should use $server only in the option `logger.mask.irc` because $server is defined only on irc buffers (not core buffer for example).
See: https://weechat.org/files/doc/devel/weechat_user.en.html#logger_irc_files_by_server_channel

But for your logging problem, I still don't understand why you don't have the backlog with the new option...

**Comment by flashcode** [comment]
Ah, I have an idea!
Can you check the case of channel name in your autojoin, vs the real channel joined? Are they different?
For example you have `#WeeChat` in autojoin, while the real channel name is `#weechat` (or reverse)?
Buffer names are case sensitive, so if WeeChat opens `irc.freenode.#WeeChat` instead of `irc.freenode.#weechat`, the backlog can not be read.

**Comment by flashcode** [comment]
Hmm.. if `logger.file.name_lower_case` is `on` (default), this problem should not happen.

**Comment by holomorph** [comment]
Ok, so far confirmed that only setting `irc.server.freenode.autojoin = "#somechannel"  (default: (undefined))` doesn't cause the issue. Time to bisect settings.

**Comment by flashcode** [comment]
It looks like the problem happen when `autoconnect` is `on`, sometimes the irc plugin is loaded before logger plugin, and then the backlog can not be displayed when the buffers are opened on server connection.

**Comment by flashcode** [comment]
Please tell me if the fix is OK for you.

**Comment by holomorph** [comment]
Appears to be fixed. Thanks! \o/
