### ISSUE TITLE
Add support of SHA256 for SSL fingerprint (SHA1 is deprecated)

### ISSUE THREAD

**Issue by Mikaela** [weechat/weechat#281]
I mean the option `irc.server.<network>.ssl_fingerprint`. ZNC 1.5 wants in SHA256 fingerprints .

**Comment by maxteufel** [comment]
May I ask why specifically SHA-2-256? I'd actually propose SHA-2-512 as GnuTLS already supports that (or everything from SHA-2-224 to SHA-2-512 if it will be possible to use different hash algorithms).

**Comment by Mikaela** [comment]
Probably because everyone else is also moving to SHA256, but some stronger would probably be better.

**Comment by maxteufel** [comment]
Everyone doing that doesn't mean it's a good idea.
