### ISSUE TITLE
irc: not enough memory

### ISSUE THREAD

**Issue by wowaname** [weechat/weechat#288]
This happens when (re)connecting to a server after having an uptime of over a month, so it suggests a memory leak. Everything else seems to work fine except for connecting to a server. It looks like the error comes from src/plugins/irc/irc-server.c and I may investigate further when I have more time on my hands, but the issue is here for anyone else to look at if they want. Running WeeChat 1.0-rc3 (git: v1.0-rc3-5-g3d63ed0) on Debian.

**Comment by wowaname** [comment]
```
01:18 Scripts loaded:
01:18  * ia N buffers.pl 4.7 (Sidebar with list of buffers)
01:18    ia   kickban.pl 0.3 (A new, customizable kickban command)
01:18    ia   query_blocker.pl 0.9 (Simple blocker for private message (i.e. spam))
01:18    ia   topicsed.pl 0.1 (Edit channel topics by perl regular expressions or in input-line)
01:18    ia   autojoin.py 0.2.5 (Configure autojoin for all servers according to currently joined channels)
01:18    ia   chanstat.py 0.1 (Channel statistics)
01:18    ia N fish.py 0.8 (FiSH for weechat)
01:18         otr.py 1.4.0 (Off-the-Record messaging for IRC)
01:18    ia N prism.py 0.2.7 (Taste the rainbow.)
01:18    ia N screen_away.py 0.12 (Set away status on screen detach)
01:18    ia   translate.py 0.7 (Translate string using Google translate API)
01:18    ia   weestats.py 0.2 (Useless statistics about your open buffers and windows)

01:20 Plugins loaded:
01:20   trigger: Text replacement and command execution on events triggered by WeeChat/plugins
01:20   relay: Relay WeeChat data to remote application (irc/weechat protocols)
01:20   alias: Alias commands
01:20   script: Scripts manager
01:20   fifo: FIFO pipe for remote control
01:20   exec: Execution of external commands in WeeChat
01:20   perl: Support of perl scripts
01:20   xfer: DCC file transfer and direct chat
01:20   logger: Log buffers to files
01:20   irc: IRC (Internet Relay Chat) protocol
01:20   charset: Charset conversions
01:20   python: Support of python scripts
```
I suppose I can get rid of a few things like xfer and query_blocker.pl since I never use those... Not that it would fix the memory leak. I'll try updating to 1.0.1 next time I restart WeeChat.

@flashcode I specified my distro in the OP. And isn't /upgrade useless with a git compile?

**Comment by flashcode** [comment]
Scripts like fixh.py or otr.py (which are called on each message displayed) may be the cause of memory used.
The `/upgrade` command is even more useful with git version, to keep your version up-to-date, so you can use the command almost every day. With a stable version you need `/upgrade` only one time every 3-4 months.

**Comment by flashcode** [comment]
It sounds like a memory leak in a script, so I close the bug.
If you have more info or think it's still a bug in WeeChat feel free to add new info.
