### ISSUE TITLE
Complete quoting for parameters of some CMake commands

### ISSUE THREAD

**Issue by elfring** [weechat/weechat#29]
Some parameters (like "[${SHAREDIR}/man](https://github.com/weechat/weechat/blob/97254780d655dd29b4093e52c6930aecaecca2eb/CMakeLists.txt#L53)" and "[${CMAKE_COMMAND}](https://github.com/weechat/weechat/blob/bd06f0f60f8c3f5ab883df9cb876fe29715055b3/doc/en/CMakeLists.txt#L24)") are passed to CMake commands in your build scripts without enclosing them by quotation marks. I see that these places will result in build difficulties if the contents of the used variables will contain special characters like spaces.

I would recommend to apply [advices from a Wiki article](http://cmake.org/Wiki/CMake/Language_Syntax#CMake_splits_arguments_unless_you_use_quotation_marks_or_escapes.).

**Comment by flashcode** [comment]
Closing this old issue, if there are still problems please comment or send a pull request, thanks.

**Comment by elfring** [comment]
How do you think about to [recheck data processing for CMake lists](https://cmake.org/cmake/help/v3.17/manual/cmake-language.7.html#lists "Description for CMake lists")?

**Comment by flashcode** [comment]
If there are still issues for you, please show me exactly the location in files or provide a pull request, thanks.

**Comment by elfring** [comment]
Another example:
https://github.com/weechat/weechat/blob/e130ee7358564cfd5572ca0cf1ac6871425548ed/CMakeLists.txt#L62

**Comment by flashcode** [comment]
OK I see, I reopen the issue and will escape properly the variables/parameters in CMake files.

**Comment by flashcode** [comment]
Finally fixed!

**Comment by elfring** [comment]
Thanks for [your script adjustment](https://github.com/weechat/weechat/commit/6415c09a077e2564fe5e6548e09caa1dade0a3fc "add quotes around paths in CMake files").
