### ISSUE TITLE
Password censoring when identifying via nickserv is broken

### ISSUE THREAD

**Issue by The-Compiler** [weechat/weechat#296]
On `v1.1-rc1-15-g235cc3f`, when typing `/msg nickserv identify `, my prompt suddenly changes to `$1$.*+` instead of being able to type the (censored) password like it used to work earlier.

**Comment by flashcode** [comment]
You have to restore the default triggers, because the format has changed. See the release notes of devel version (file ReleaseNotes.asciidoc in git).
