### ISSUE TITLE
Channels open in reverse order

### ISSUE THREAD

**Issue by Shawn-Smith** [weechat/weechat#303]
If `irc.look.buffer_open_before_autojoin` is being used when first starting weechat any server that is autoconnected to will open channels set in `irc.server.<server>.autojoin` in reverse order.

This is somewhat annoying since I use this to order the channels instead of using /layout, and have to order them backwards.

**Comment by flashcode** [comment]
Are you sure you don't have a layout applied (try `/layout leave`) or a script that reorders your buffers (try to uninstall/unload it if you have one)?
If needed try with a new config: `weechat --dir /tmp/weechat`.

**Comment by Shawn-Smith** [comment]
I managed to reproduce it with the following steps:

````
weechat --dir /tmp/weechat
/set irc.look.server_buffer independent
/set irc.look.new_channel_position near_server
/set irc.look.new_pv_position near_server
/set irc.server.freenode.autojoin "#test,#test1,#test2,#test3"
/set irc.server.freenode.autoconnect on
/quit
weechat --dir /tmp/weechat
````
````

**Comment by flashcode** [comment]
OK, I managed to reproduce the problem, it's with the option `irc.look.new_channel_position` when the channels are opened before the join.
