### ISSUE TITLE
The default server freenode isn't using SSL.

### ISSUE THREAD

**Issue by Mikaela** [weechat/weechat#309]
WeeChat supports SSL and it should work with freenode by default. freenode also has valid certificate.

**Comment by Shawn-Smith** [comment]
I don't think it should default to ssl, not everyone compiles weechat with ssl support and it makes it harder for it to work out-of-the-box if you have to edit the default server in order to connect.

**Comment by Mikaela** [comment]
It's not very good idea to compile without SSL and SSL should be included in all instructions (`apt-get build-dep weechat`, `yum-builddep weechat` etc.) that you hear at \#weechat.

**Comment by sckasturi** [comment]
But there is the possibility that for some unseen reason why compiled
without ssl. For that reason, I vote no to defaulting to SSL.


–Srijay Kasturi
http://techfilmer.com

**Comment by stfnm** [comment]
Maybe the default setting should depend on whether WeeChat was compiled with or without SSL support.

**Comment by Mikaela** [comment]
Or maybe WeeChat shouldn't have default servers at all?
