### ISSUE TITLE
Cygwin connection issues

### ISSUE THREAD

**Issue by Shawn-Smith** [weechat/weechat#311]
I've noticed that since upgrading from 1.0 to 1.1 in cygwin weechat will randomly stop allowing me to connect to new servers.

On SSL-enabled servers I get this error:

```
[17:29:46]  -- | irc: connecting to server <server> (SSL)...
[17:30:06] =!= | irc: TLS handshake failed
[17:30:06] =!= | irc: error: Error in the push function.
[17:30:06]  -- | irc: reconnecting to server in 20 seconds
```

On plaintext servers I get this error:

```
[17:32:39]  -- | irc: connecting to server <server>...
[17:32:39]  -- | irc: connected to <server> (<ip>)
[17:32:39] =!= | irc: sending data to server: error 128 Transport endpoint is not connected
[17:32:39] =!= | irc: sending data to server: error 128 Transport endpoint is not connected
[17:32:42]  -- | irc: disconnected from server
```

I have no idea what could be causing this.

Sometimes it happens just minutes after starting weechat, other times it will take hours before I get this. The only way to fix it is to restart weechat.

**Comment by flashcode** [comment]
I tried with both 32 and 64-bit versions of Cygwin, version 1.1, and I have no connection problems on new servers (SSL or not).
Maybe some network problem on your side?
Can you give me an example of server you added, for which you can't connect to?

**Comment by Shawn-Smith** [comment]
I can normally connect to any server I have added fine, but when this bug starts it'll prevent me connecting to any server. The existing connections will work fine and outside of weechat I can ping the servers I'm trying to connect to, but weechat wont connect and will display the errors in the original post.

Is there any way I can get a debug log of what's happening when this bug starts? I tried looking at the raw log with Alt-j, Alt-r, but that doesn't display anything when trying to connect during this.

**Comment by flashcode** [comment]
Can you try to reinstall version 1.0.1 with setup.exe (it should be available if you click many times on version), and check if you have problems with this one?
The problem you have is maybe caused by something external to WeeChat. I see no reason why connections to servers would suddenly stop working.

**Comment by Shawn-Smith** [comment]
I can't reproduce this with 1.0.1, I'll re-open this issue if I get more information to go on.

**Comment by flashcode** [comment]
You mean you can not reproduce with 1.1.1 ?

**Comment by Shawn-Smith** [comment]
Whoops I'm sorry, I only tried 1.0.1, I didn't realize a 1.1.1 was released. I'll reinstall with that now and see if it happens again.

**Comment by Shawn-Smith** [comment]
@flashcode I reproduced it on 1.1.1..

Currently I'm on 9 servers, but I cannot connect to any more without getting the same errors as posted in the original post.

It happened after my internet went out twice and that caused a lot of disconnects/reconnects, I've found that if I disconnect from one server I'm connected to I can connect to another server just fine, but then I cannot reconnect to the one I disconnected from again without first disconnecting from another one.

I'm thinking that maybe cygwin has a limit on the number of active connections any one program can have, and that WeeChat wasn't properly closing the connections when I was disconnected due to the internet going out.

**Comment by KindOne-** [comment]
cygwin does not care about max connections, I've had 50+ connections from znc in cygwin.

**Comment by Shawn-Smith** [comment]
Then I've got no idea what causes this bug.

**Comment by Shawn-Smith** [comment]
I got this bug again today, still not sure what's causing it.

If #302 was implemented that would indirectly fix this issue, being able to use /upgrade without losing current SSL connections whenever this bug happens would be fine.

**Comment by Shawn-Smith** [comment]
I haven't had this bug happen in quite some time now, so I'm going to close the issue.

I'm not sure what was causing it, and I'm not sure what fixed it. It's quite possible that pull #801 fixed it but I can't say for certain.

I'll re-open this in the future if I come across it again and have more information.
