### ISSUE TITLE
Option to gzip log files.

### ISSUE THREAD

**Issue by ddan39** [weechat/weechat#314]
Just noticed my weechat logs are getting quite big, and figured I should gzip them to save space, but then thought maybe we can have weechat write to the files gzipped?

But is this even possible? By the nature of compression, I have a feeling it would not be, unless output is buffered and written in chunks... but I have no idea how gzip actually works :(

and on that note, maybe there is a better lib/algorithm for compressing a text stream?

Please & Thanks :)

**Comment by Shawn-Smith** [comment]
If it isn't possible to gzip current logs, maybe just gzipping old ones would be fine. If you have logs set to rotate by day, week or month. When a new log file is made it can gzip the old ones.

**Comment by nyuszika7h** [comment]
It should keep more than one ungzipped log file per buffer though, especially if logs are rotated by day. Maybe it could be a configuration option.

**Comment by highflyer77** [comment]
Maybe have weechat read the compressed log files using:  zcat like other applications do.

**Comment by NoSuck** [comment]
With ~500 MB of log data, I am interested in this possibility but would be concerned about losing the convenience of readily-available, universally viewable logs.

**Comment by nyuszika7h** [comment]
Well, there is zcat and zgrep, and it could probably automatically (un-)gzip on next start if you change the option.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jeaye** [comment]
I have 2.0 GB worth of logs that're causing me some space issues right now, but I can't sacrifice the ability to easily search through them with `/grep` or similar plugins. Having weechat automatically compress these in a way that can be read via weechat would be superb, so this gets my 👍.

In the meantime, a fork of the `grep` plugin could likely be made to consider rotated, compressed files in its searching. That requires not only a custom plugin, but also a cron/systemd job for logrotating.

**Comment by flashcode** [comment]
Implemented with 3 new options:

- logger.file.rotation_size_max: if set to something higher than 0, enables rotation with this file size is reached
- logger.file.rotation_compression_type: compression of log files (none / gzip / zstd)
- logger.file.rotation_compression_level: compression level (if compression is enabled)

For now the rotation is only based on log size, and we can still use filename masks to split logs by date, see: https://weechat.org/files/doc/devel/weechat_user.en.html#logger_filenames_masks

**Comment by flashcode** [comment]
For the option `logger.look.backlog`, WeeChat only reads the latest (current) log file, which is not compressed.

Scripts that search in log files, like grep, must be adapted to take care of compressed files.
