### ISSUE TITLE
Make irc.server_default.capabilities like weechat.plugin.autoload & make * safe capabilities that break nothing

### ISSUE THREAD

**Issue by Mikaela** [weechat/weechat#320]
Currently WeeChat requires all capabilities enabled manually in `irc.server_default.capabilities`. WeeChat should automatically request safe capabilities where safe means that it shouldn't break anything (possibly external to WeeChat like pisg).

Combining comments there could be `*` as special capability that requests the safe ones and it could be configured like `weechat.plugin.autoload`.

> `comma separated list of plugins to load automatically at startup, "*" means all plugins found, a name beginning with "!" is a negative value to prevent a plugin from being loaded, wildcard "*" is allowed in names (examples: "*" or "*,!lua,!tcl")`

The default value would be `*`.

The safe capabilities could be:
- account-notify
- away-notify
- cap-notify
- multi-prefix
- server-time & znc.in/server-time-iso (1.7.0+ support server-time (https://github.com/znc/znc/commit/d7a6a136dbdd04af2c9f403a362f63d010fb00af), but people and distributions are SLOW to upgrade.)
- znc.in/self-message (https://github.com/weechat/weechat/commit/b860043646755773a2d6173d411f80e2c3b89182)

_This issue was originally on requesting all capabilities, but it has been decided to be possibly a very bad idea™ and I rewrote this on 2015-03-30. I also removed all my comments as they were used to derail from this issue._

**Comment by stfnm** [comment]
Maybe allowing a wildcard value like "*" for this option meaning "all supported capabilities" would solve this nicely.

**Comment by Mikaela** [comment]
```
2015-01-24 16:27:38+0200 < grawity> the .capabilities setting could maybe allow cap1,cap2,!cap3 syntax in case someone wants to forcefully disable a known capability
2015-01-24 16:27:51+0200 <@FlashCode> yes like plugins
2015-01-24 16:27:57+0200 <@FlashCode> something like "*" for automatic
2015-01-24 16:28:18+0200 <@FlashCode> or empty string (or "-") for nothing by default
```

**Comment by Shawn-Smith** [comment]
I wouldn't mind seeing `*` for "all capabilities", but I don't think they should all be enabled by default.

**Comment by Mikaela** [comment]
>  I don't think they should all be enabled by default.

and why is this?

**Comment by Shawn-Smith** [comment]
Because some capabilities people don't need, like `away-notify` is only useful if you use the `away_check` setting. And the list of capabilities that aren't needed will only grow as more time passes.

**Comment by Mikaela** [comment]
> Because some capabilities people don't need

They don't hurt existing and many scripts can also take use of them when they exist.

> like away-notify is only useful if you use the away_check setting.

Or if you use `/notify` - https://github.com/weechat/weechat/issues/270

> And the list of capabilities that aren't needed will only grow as more time passes.

Could you give me example of some entirely unneeded capability? The user is always able to disable capabilities they don't need. It's also worth noting that all plugins are loaded by default too and some of those plugins are useless to many people (and some users are even encouraging not loading some).

For example, I have `/set weechat.plugin.autoload alias,exec,irc,perl,python,script,trigger,logger` and to me `aspell, charset, fifo, lua, relay, ruby, tcl, xfer` are entirely useless.

Charset is also useless to most of ZNC users as it includes charset module and in 1.6.0 that has moved to core. So we could probably argue that all plugins shouldn't be loaded automatically either.

**Comment by Shawn-Smith** [comment]
>In computing, hardening is usually the process of securing a system by reducing its surface of vulnerability.

http://en.wikipedia.org/wiki/Hardening_%28computing%29

>For example, I have /set weechat.plugin.autoload alias,exec,irc,perl,python,script,trigger,logger and to me aspell, charset, fifo, lua, relay, ruby, tcl, xfer are entirely useless.

If you're not using them it's wasteful to continue loading them.

**Comment by nyuszika7h** [comment]
`extended-join` might break pisg. Sure, you might say it's a bug in pisg that should be fixed, but it hasn't been maintained for a while.

**Comment by Mikaela** [comment]
I don't think pisg is directly releated to WeeChat and as you say, it's bug in pisg and pisg is dead. There are alternatives though.

**Comment by kaniini** [comment]
I think instead of "all or nothing" a reasonable set of capabilities should be enabled by default, and enabling additional features which require a capability should either enable it or tell you that it needs to be enabled.  This solves the usability problem while still managing risk.

**Comment by Mikaela** [comment]
What would you consider as reasonable check of capabilities? And do you think `*` should expand to those?

My list would probably be (from capabilities supported by 1.2-dev):

* *away-notify* to stop that who-polling and it would also help with https://github.com/weechat/weechat/issues/270
* *multi-prefix* which shouldn't cause any harm and would fix https://github.com/weechat/weechat/issues/368
* *server-time* and *znc.in/server-time-iso* as it makes using ZNC a lot more nicer (until https://github.com/znc/znc/issues/181#issuecomment-87368224)

I am not sure on *account-notify*, *extended-join* has that pisg issue and possibly other parsers, *userhost-in-names* I am also unsure about.

**Comment by kaniini** [comment]
`account-notify` would be useful if the default client uses it.  You could also have scripts register their interest in capabilities somehow so that everything "just works".

**Comment by Mikaela** [comment]
Account-notify was just added in 1.2 and I am not sure if it affects logging some way, but probably not thinking about away-notify. As far as I am aware, account-notify is not used for anything yet, but it should probably be part of my list.

On script side, this is wished with at least chanop.py (https://github.com/weechat/scripts/issues/52) which was opened on the same day as account-notify support was added if I recall correctly.

**Comment by Mikaela** [comment]
I zs>chaged</s> typoed the title and rewrote the original issue based on comments, opinions?

**Comment by nyuszika7h** [comment]
`extended-join` probably shouldn't be requested by default, as all log parsers would have to be rewritten to support it (they should be, anyway, but we shouldn't suddenly break things).

**Comment by GLolol** [comment]
I spent a bit trying to figure out why multi-prefix didn't work, and it turns out it wasn't even enabled by default. :+1: for making at least `multi-prefix,server-time` a default.

**Comment by JacobHenner** [comment]
Any updates? This would be excellent.

**Comment by daenney** [comment]
I'd appreciate a set of safe defaults too.

**Comment by qguv** [comment]
Is this addition still being considered? I'm all for it.

**Comment by jesopo** [comment]
Any movement on this?

**Comment by weechatter** [comment]
no. simply /set irc.server_default.capabilities to the default capabilities you like.

**Comment by jesopo** [comment]
I've done that but I'm curious to know if this issue is still being considered

**Comment by flashcode** [comment]
Yes, issue is still open.
We need to build a list of capabilities that are considered "safe", and then enable them by default.

**Comment by RyanSquared** [comment]
What would be the proper definition of safe for this? Things that by default just improve the IRC experience? Some things I'm thinking of:

- SASL 3.1 and 3.2
- account-notify
- account-tag possibly?
- server-time
- away-notify

These serve to reduce the "polling" aspect of IRC, which makes it more convenient to use on larger channels as you don't have as many messages coming in.

So, would "safe" be defined as things that improve the protocol? Or things that might modify messages as well, such as server-time?

**Comment by jesopo** [comment]
having used this configuration for a fair few months now, I will propose these CAPs as "safe" and general improvements to UX.

- `account-notify`
- `away-notify`
- `cap-notify`
- `chghost`
- `extended-join`
- `invite-notify`
- `multi-prefix`
- `server-time`
- `userhost-in-names`

SASL is already covered by being enabled when it is configured.

**Comment by Mikaela** [comment]
I wonder if this moving to LiberaChat would be a good time to think of this as it implements several more than freenode did?

**Comment by RyanSquared** [comment]
> I wonder if this moving to LiberaChat would be a good time to think of this as it implements several more than freenode did?

Additionally, at about 20 channels, no matter what I set my away check interval to, I still had issues with weechat flooding the server. I think this is the result of another issue -- weechat not spreading out the WHO checks -- but it would also be helped if weechat can just disable the away checks if away-notify is supported and negotiated.

**Comment by flashcode** [comment]
After discussion with @jwheare, all the currently supported capability could be enabled by default, with prior changes (see below):

- `account-notify` (changes required, see below)
- `away-notify`
- `cap-notify`
- `chghost`
- `extended-join` (changes required, see below)
- `invite-notify`
- `multi-prefix`
- `server-time`
- `setname` (new in WeeChat 3.3)
- `userhost-in-names`

SASL is always enabled if SASL options are set.

Some changes required before capabilities are all enabled by default:

- `account-notify`: an option should be added to NOT display ACCOUNT messages received (like: `user has identified as xxx`). By default such messages are displayed if account-notify is enabled.
- `extended-join`: an option should be added to keep display of JOIN message unchanged (no account / real name displayed). By default the account and real name are displayed if received in the JOIN.

Other ideas for further improvements (not part of this issue):

- add a way to display nick info (without doing a WHOIS), displaying some internal states like the account and real names (that could be fetched thanks to capabilities which are enabled by default).
