### ISSUE TITLE
ZNC *playback support

### ISSUE THREAD

**Issue by Mikaela** [weechat/weechat#323]
- Homepage: http://wiki.znc.in/Playback
- HexChat issue: https://github.com/hexchat/hexchat/issues/1109
- HoloIRC issue: https://github.com/tilal6991/HoloIRC/issues/92

HexChat and HoloIRC issues are written by @jpnurmi and are probably more detailed than I can give.

**Comment by shish** [comment]
Weechat is both a client and a bouncer - is this requesting support for playback when weechat connects to znc, or support for playback when a client connects to weechat? (I'm currently trying to set up the second, nobody discussing playback support seems to mention if they're working on making weechat a playback client or playback server >_<)

**Comment by Mikaela** [comment]
This issue is for third party ZNC module called \*playback which prevents repeating lines when you get disconnected from ZNC.

WeeChat has no issues connecting to ZNC other than having to manually add `znc.in/server-time-iso` to `irc.server_default.capabilities`

* For connecting WeeChat to ZNC you might be interested in http://wiki.znc.in/Weechat
* For automatically requesting supported capabilities from server, please see https://github.com/weechat/weechat/issues/320

**Comment by emilyst** [comment]
Anyone working on this one?

**Comment by flashcode** [comment]
@emilyst : I think nobody is currently working on that, the current developments (by versions) are displayed here: https://weechat.org/dev/

**Comment by sickill** [comment]
I'd love to see a support for this too.

**Comment by chrislovessushi** [comment]
Would also like to see support for this

**Comment by medik** [comment]
https://github.com/ircv3/ircv3-specifications/pull/292

This is on the roadmap for the IRCv3 specifications. Isn't this the capability you search for? If it is I suggest that this issue should be paused until it is included in the specifications

**Comment by aliceinwire** [comment]
https://github.com/ircv3/ircv3-specifications/pull/292
as been solved, we can close this bug ?

**Comment by aliceinwire** [comment]
with the znc playback plugin I have playback support.

**Comment by Mikaela** [comment]
In addition to ZNC this would help with getting playback from Oragono IRCd

**Comment by Ristovski** [comment]
PSA: In the mean time, there is a plugin that implements this functionality: https://weechat.org/scripts/source/zncplayback.py.html/

**Comment by weechatter** [comment]
@Ristovski :  Its a "script", not a "plugin" ;-) 

So, this issue can be closed?

**Comment by Mikaela** [comment]
I agree that the script is currently a better solution for those requiring ZNC specific playback as the wider IRC ecosystem to my knowledge is using CHATHISTORY, so I am closing this in favour of https://github.com/weechat/weechat/issues/1661.
