### ISSUE TITLE
Passwords with ; in it won't work with /secure

### ISSUE THREAD

**Issue by HptmHavoc** [weechat/weechat#324]
Passwords with ; in it wont work with /secure. If you want to paste your password you only get the part till ; . For Example if you make a password like 123;546 and you want to paste it, you only get 123. If you create an password with a generator with special chars it isn't impossible that it contain this char.

**Comment by stfnm** [comment]
What do you mean by pasting?
```
/secure set test 123;456
/eval -n ${sec.data.test}
```

This example works just fine for me and displays the expected result.
```
>> ${sec.data.test}
== [123;456]
```

**Comment by HptmHavoc** [comment]
This works, correct, but if you want to show the password, only for example, to a chan or want it to sent it to someone or want to identify your nick this won't work. The char ; works as a seperator, you get 2 lines. 
Try /eval /msg #channame ${sec.data.test}

**Comment by flashcode** [comment]
The problem is not secured data, but /eval which automatically splits the commands on ";".
I'll remove that from /eval (and add another way to split commands, if needed, but not done by default).

**Comment by Shawn-Smith** [comment]
Maybe just add a `-nosplit` option to eval instead of removing it all together?

**Comment by flashcode** [comment]
I'll probably enable the split with a new option, but not do it by default (I think in most cases, you don't want to split the content after /eval).
