### ISSUE TITLE
Requiring 'json' module crashes Weechat

### ISSUE THREAD

**Issue by ifonefox** [weechat/weechat#326]
If you load any ruby file that tries to require the json module, WeeChat crashes. You can test this by loading a ruby file with just "require 'json'". Requiring other modules does not crash WeeChat. I am testing this with  "WeeChat 1.2-dev [compiled on Jan 31 2015 15:26:47]" on OS X 10.10.2.

**Comment by flashcode** [comment]
I am not able to reproduce this crash under Debian.
Can you please report the backtrace with gdb? See info in user's guide: https://weechat.org/files/doc/devel/weechat_user.en.html#report_crashes
