### ISSUE TITLE
Buffer name changes case

### ISSUE THREAD

**Issue by wowaname** [weechat/weechat#336]
If I have a channel #test (so the buffer name is irc.network.#test) and someone joins #Test or #TEST then my buffer name will become irc.network.#Test or irc.network.#TEST to reflect that person's join message.

**Comment by flashcode** [comment]
I tried on freenode with latest devel version, I'm not able to reproduce the problem.
If that's not happening on freenode, could you please tell me on which server you have the problem?
The best would be exact steps to reproduce the problem.
Thanks.

**Comment by flashcode** [comment]
I was able to reproduce by simulating a fake JOIN on a channel (with different case), and I identified the wrong code, I'm fixing that.

**Comment by wowaname** [comment]
Okay, thanks. Affected IRCd was ngIRCd (irc.barton.de)

**Comment by flashcode** [comment]
Can you please confirm me if the fix is OK?

**Comment by wowaname** [comment]
@flashcode Will do.

``Receiving objects:  38% (34961/90060), 65.54 MiB | 74.00 KiB/s``

**Comment by wowaname** [comment]
Looks fixed.

**Comment by flashcode** [comment]
Nice, thanks for testing.
