### ISSUE TITLE
When connecting, always try preferred nicks in order

### ISSUE THREAD

**Issue by BlacklightShining** [weechat/weechat#337]
If the first preferred nickname for a server is in use when weechat connects, the second one will be used, but if weechat is subsequently disconnected and automatically attempts to reconnect, it will skip the first nickname and try the third if the second is in use.

**Comment by flashcode** [comment]
This behavior seems normal to me, WeeChat will start from the current nick in list to search another available nick.
In a normal case, if you are identified with the second nick, you should revert manually to the first one (when it is available), which fixes your problem. It seems not normal to me to continue using the second nick forever, it should be temporary.

**Comment by BlacklightShining** [comment]
I personally have a couple of alternate nicks that I actively use sometimes (I'm sure I'm not the only one). Could you add an option to try the current nick first, then try each nick in order beginning with the first one in the list, then?

**Comment by flashcode** [comment]
OK, then I'll look at which level I can add an option for that.
And then I turn this issue into an enhancement.

**Comment by arza-zara** [comment]
Possibly you haven't noticed that your nick has changed. This is also inconsistent as manual /reconnect resets the nick. My solution: #965.
