### ISSUE TITLE
Separate backlog settings for private vs channel

### ISSUE THREAD

**Issue by grawity** [weechat/weechat#350]
In PM/query windows, the backlog will usually have something relevant – parts of the conversation with the same person.

In channels, however, it'll merely have random chatter. You left yesterday while some people were discussing thing X; you rejoin when other people are discussing thing Y.

So I'd like to somehow set `logger.look.backlog` to 15–25 for queries and 0 for channels.

**Comment by flashcode** [comment]
This is possible since WeeChat 2.1 with the option `logger.look.backlog_conditions` (see #1132).

Closing this one as duplicate.
