### ISSUE TITLE
Allow more variables with custom CTCP replies

### ISSUE THREAD

**Issue by Mikaela** [weechat/weechat#353]
I would like to tell people attempting to whois me instead and the command to do this seems to be:

```
/set irc.ctcp.userinfo `/whois ̣$nick $nick`?
```

but WeeChat doesn't support `$nick`.

Some other things would be nice too, for example ZNC supports the ones documented at http://wiki.znc.in/ExpandString .

**Comment by flashcode** [comment]
In version 4.1.0-dev, CTCP replies are now evaluated, so you have access to far more variables.
I close this issue, if ever you need even more variables, let me know here.
