### ISSUE TITLE
zlib not found when using PREFIX and installing weechat from source locally to user directory

### ISSUE THREAD

**Issue by randomessence** [weechat/weechat#354]
Installing weechat 1.1.1 from source code on Debian Stable or Ubuntu current LTS as a non root user and installing weechat to their home directory using cmake 3.1.3 x64. 

If I set a `-DPREFIX=$HOME` zlib is not found even though the dependencies are all installed using Debian Wheezy apt-get.

~~~
CMake Error at cmake/FindPackageHandleStandardArgs.cmake:91 (MESSAGE):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.7")
Call Stack (most recent call first):
  cmake/FindPackageHandleStandardArgs.cmake:252 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindZLIB.cmake:71 (find_package_handle_standard_args)
  CMakeLists.txt:175 (find_package)
~~~

I can only overcome this by 

1: not using a prefix and then zlib is detected.

2: Install zlib 1.2.8 locally using `./configure --prefix=$HOME` and then I can use `cmake . -DPREFIX=$HOME`

The second is not an ideal solution as I do did not imagine this to be the desired functionality. Is this a bug or is it intended, meaning i must specify the zlib location with arguments?

**Comment by Mikaela** [comment]
Are you sure that the depedencies are installed? I have never experienced this and `apt-get build-dep weechat` has always worked for me.

I think that it wants `zlib1g-dev`

On Ubuntu 14.10 the requirements for the package are the following:

```
#  apt-rdepends --build-depends --follow=DEPENDS weechat
Reading package lists... Done
Building dependency tree       
Reading state information... Done
weechat
  Build-Depends: asciidoc (>= 8.5)
  Build-Depends: cmake
  Build-Depends: debhelper (>= 9)
  Build-Depends: docbook-xml
  Build-Depends: docbook-xsl
  Build-Depends: gem2deb
  Build-Depends: guile-2.0-dev
  Build-Depends: libaspell-dev
  Build-Depends: libcurl4-gnutls-dev
  Build-Depends: libgcrypt20-dev
  Build-Depends: libgnutls28-dev
  Build-Depends: liblua5.1-0-dev
  Build-Depends: libncursesw5-dev
  Build-Depends: libperl-dev
  Build-Depends: pkg-config
  Build-Depends: python-dev
  Build-Depends: source-highlight
  Build-Depends: tcl8.5-dev
  Build-Depends: xsltproc
  Build-Depends: zlib1g-dev
```

Note that the git version also wants `libv8-dev` for Javascript support.

**Comment by randomessence** [comment]
This is not a dependency issue since all required dependencies are installed. This is a cmake 3 + weechat issue when installing locally to a non root profile from source.

This seems to be a problem with cmake version `3.1.3` (the version I used). This does not happen with cmake version `2.8.12.2`

Everything works fine with `2.8.12.2` but with version 3 as soon as I add the prefix it seems to not be able to find the dependencies even though they are all installed properly

**Comment by flashcode** [comment]
My cmake was upgraded from 3.0.2 (working fine) to version 3.2.2, and now I have the same problem.
I'm investigating.

**Comment by flashcode** [comment]
The WeeChat doc is wrong for cmake: `-DCMAKE_INSTALL_PREFIX=...` should be used instead of `-DPREFIX=...` (it looks like now PREFIX is used for other things that make cmake fail).
I'll fix the doc and then close this issue.
