### ISSUE TITLE
Don't use chat.{eu,us}.freenode.net in examples

### ISSUE THREAD

**Issue by nyuszika7h** [weechat/weechat#365]
They have been discouraged by staff for a long time and they are now just redirects to `chat.freenode.net`. `chat.au.freenode.net` is still maintained, though.

**Comment by Mikaela** [comment]
Which examples do you see these in?

**Comment by flashcode** [comment]
It's in `/help server`.

**Comment by Mikaela** [comment]
Oh, I have somehow missed those and I have only seen chat.freenode.net everywhere lately.
