### ISSUE TITLE
Add ability to connect to remote weechat relays

### ISSUE THREAD

**Issue by moopie** [weechat/weechat#369]
Would be nice to be able to use weechat relays through the client itself.

**Comment by flashcode** [comment]
For now this feature is not planned.
You could run WeeChat under screen or tmux, and it's even better than using an extra network layer, with limited features (the protocol will not let you do exactly same things than in WeeChat itself).

**Comment by fuzzy76** [comment]
But it does not let you interact with the local terminal.

**Comment by x89** [comment]
Not sure what you mean @fuzzy76? You can add a `/relay weechat` and then connect (for example via the Android app) and it has all your buffers on it.

It would be nice if you could do this from another linux machine. The alternative at the moment is adding `/relay add freenode bla bla bla` and on the client adding `/server add freenode <serverip>`.

Am I missing something?

**Comment by fuzzy76** [comment]
The original issue explained it nicely. :) This issue is about connecting to a weechat relay WITH a weechat client.

**Comment by robcross** [comment]
I would also like this feature. I like that the weechat protocol supports full buffer syncing, and I also like the weechat curses interface.

**Comment by foxxx0** [comment]
+1 for this request

**Comment by carnager** [comment]
This seems a rather strange limitation. A program implements a completely new protocol and is not able to interpret it. 

Definitely would like to see this.

**Comment by bastelfreak** [comment]
+1 for this, would be a really helpfull feature.

**Comment by gitdings** [comment]
+1 for this. It would indeed be a great and wonderful feature that'd make the (weechat-) world even better.

**Comment by HarHar** [comment]
+1 for this, it would bring over world peace and let me turn off ZNC

**Comment by hrnz** [comment]
+1

**Comment by jreinert** [comment]
+1 makes no sense to me why this hasn't been implemented

**Comment by bastelfreak** [comment]
Hi @flashcode, do you have any update for us?

**Comment by Nokogiri** [comment]
+1

**Comment by flashcode** [comment]
Issue is still open and not marked as "won't fix", so this could be implemented in far future.

"Far future" because it's not quick and easy task to add that, following features must be added:

1. decoding of WeeChat protocol (not so easy, even if the reverse (encode data) for clients is already implemented), especially because as far as I know, no C client currently implements that
2. add a new network layer in relay plugin to act as a "client": connect to a remote host, like it's done in irc plugin, and manage network problems (reconnection, resynchronization with remote relay, ...)
3. manage "relay servers", like irc servers, ie being able to define multiple WeeChat relays with different addresses/properties and auto-connect to them on startup (this feature is not mandatory in a first step though)
4. create new relay buffers matching the remote WeeChat instance ; and as I said previously, this could work but in a limited way because these buffers will not be exactly the same as real irc buffers (completion will not be as smart as irc buffer, scripts will not interact properly with these buffers, etc...).

**Comment by fuzzy76** [comment]
That sounds like a whole lot of plumbing for a client that already is supposed to have multi-protocol architecture according to the featurelist.

**Comment by anarcat** [comment]
for me the key feature here is the ability to connect to N servers without having to configure N relays, N ssh port forwards/firewall holes, N passwords and so on. it's a big annoyance in the current irssi proxy code as well, and I was hoping that weechat's protocol would mean that this would be solved.

i am also surprised that weechat doesn't fully implement its own protocol, in other words. :)

and yes, tmux/screen/dvtm kind of do what we want here, but they have their own set of issues, mostly with latency and non-local environments that make desktop notifications and similar needlessly difficult to implement. mosh resolves the latency issues, but not the others (and has its own terminal compatibility issues).

so it would be great to see this implemented!

**Comment by sixtyfive** [comment]
Wow, I was surprised to find this issue. I'm a user of the standard `ssh` > `tmux` > `weechat` chain, which keeps me happy at home or in other places having a reliable internet connection. I'd always thought that there would be a way to connect through my existing Weechat buffers running on the server through SSH plus a Weechat client running on my laptop. Not sure if the devs can see this as a valid use case (call me Alice or Bob if you'd like :) ). In any case, big, fat, +1!

**Comment by weechatter** [comment]
try mosh with tmux.

**Comment by Phyks** [comment]
Mosh with tmux is not a valid solution in my opinion. When you have a laggy internet connection, you really want to type locally and send complete messages, and not only use mosh prediction. Typically, when I have a laggy connection, I want to type consecutive messages, and rely on my client to try to send them indefinitely, till it succeeds, while I am still typing next messages. Plus mosh adds an extra layer and you might be unable to have it on your remote server (contrary to weechat relay which is basically just a port to bind).

@flashcode (about https://github.com/weechat/weechat/issues/369#issuecomment-169220363) I am not at all familiar with Weechat internals and management of protocols, but why would it have to be written in C, and be in Weechat core? Wouldn't it be possible to write it as a Weechat module in Python, similarly to what is done for [jabber](https://weechat.org/scripts/source/jabber.py.html/) or [slack](https://weechat.org/scripts/source/slack.py.html/)?

**Comment by craftyguy** [comment]
Mosh is also not an option for those of us that have to connect
through proxies, since Mosh screws with ProxyCommand.

**Comment by flashcode** [comment]
@Phyks : it's easier to integrate code in the relay plugin, where there's already the code to send data to the client (get data from WeeChat, compress, and send). So some parts of code could be reused for the decoding part on the other side.

**Comment by regnarg** [comment]
Seconded. Another problem with the ssh/tmux/whatever solution is when you want to use weechat from two computers with different screen sizes (so a shared tmux session is not viable because the terminals have different sizes).

**Comment by anarcat** [comment]
note that since 1.0.0, irssi can multiplex multiple proxy connexions over a single port.

**Comment by x89** [comment]
But who uses irssi in 2017?

**Comment by anarcat** [comment]
me, for one, because of this and #928 - just to name a few things.

**Comment by ashyon** [comment]
This feature would be great to have

**Comment by yvan-sraka** [comment]
:+1:

**Comment by acgissues** [comment]
Let me up-vote this too. +1

**Comment by Wh1t3Fox** [comment]
+1

**Comment by gviscardi** [comment]
Let me add yet another useless +1

**Comment by bendem** [comment]
You should totally use the thumbs up (👍) feature on the first post instead of sending notifications to every single person watching this repository. It's less noise and easier to [filter by](https://github.com/weechat/weechat/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement+sort%3Areactions-%2B1-desc).

**Comment by sixtyfive** [comment]
And perhaps one of the contributors could delete the +1s thus far (mine included) :-)

**Comment by flashcode** [comment]
I'm starting the development of an external C library to decode weechat protocol, with a CLI test client.

Once done, I'll add the feature in relay plugin to connect to another running WeeChat using weechat protocol.

This can take some weeks/months, according to my free time, no planned date/version for now.
Stay tuned!

**Comment by sixtyfive** [comment]
Release early, release often ;-) @flashcode

**Comment by flashcode** [comment]
@sixtyfive: sure, I agree with that. But I never release partial features, or broken things.
But as usual, the development version of relay lib and WeeChat will be available for tests before the final release.

**Comment by iKarith** [comment]
Color me interested as well.  Currently I use znc whose setup is non-trivial and does not lend itself to adding a random network you may or may not use long-term, etc.  The znc lives on a machine I can reach out and touch (more easily than I can the machine I'm typing this from actually--it's just out of reach), but the machine I'm typing from is my primary workstation and it always needs to be rebooted to fiddle with kernels or video drivers, so I keep the bouncer running.

I doubt znc is ever going to feel like I'm just using my irc client, because I'm not.  Using a relay does, only the relay client isn't just sitting as window 1 inside my primary tmux session like I'd prefer.

**Comment by SakiiR** [comment]
+1 a very good feature to make it better than ZNC :)

**Comment by yeled** [comment]
@flashcode will a donation help in finding spare time in your schedule?

**Comment by flashcode** [comment]
@yeled: donations help to keep me motivated for features, but unfortunately, they don't add hours to days (if only they could!).
So it will give higher priority, but for now I'm busy on personal things and have currently no time for WeeChat related developments. I should have some free time again in early 2018.

**Comment by shibumi** [comment]
@yeled I guess that Pull-Requests are always welcome ;)

**Comment by vvug** [comment]
Any chance to see this in the [roadmap](https://weechat.org/dev/roadmap/) for 2.2?

Thank you!

**Comment by flashcode** [comment]
@vvug: no changes for 2.2. I'm working on the separate lib to communicate with a weechat relay, which should take some time (I made about 20%), and once ready I have to implement the client side for relay in WeeChat itself, using the lib.
So I don't expect all that stuff to be ready before some months, and this mostly depend on my free time (which is low).

Note: I'll publish the very first version of the lib soon, so people can contribute.

**Comment by Kreijstal** [comment]
why invent a totally new protocol if you can't read it yourself lmao

**Comment by aep** [comment]
could a bounty revive interest here maybe?

**Comment by kevinelliott** [comment]
I think this feature is very important.

**Comment by jesse-osiecki** [comment]
I think if we don't fix this, we should at least make it clear in the docs about /relay that the weechat protocol will not work with weechat itself
It's very confusing as a newcomer

**Comment by khronosschoty** [comment]
Please add this!

**Comment by KristianLyng** [comment]
I'm hoping to see some movement here. A ...hypothetical use case I see is where you need to connect to an IRC server behind several layers of security, where the client has to run behind similar layers and will not be able to receive incoming connections for, e.g., hooking up a phone. Since most IRC activity would not be bound by such security measures, one could run a second client on the public internet with a regular relay. The more secure client could then make an outgoing connection to the relay so the user would not have to have two clients open at the same time, but instead only has to chose which client to connect to. Which, presumably, would be dictated by whether or not said user is at work or not.

As a bonus, the user would not be reminded of their dark past of having to juggle multiple BitchX-clients to connect to multiple IRC networks. 

If,hypothetically, there's anything I can do to speed up this development or make it more motivating, let me know... I'd offer code, but I suspect that would just increase the amount of work needed since I'm not familiar with the code base, but if not...

**Comment by shibumi** [comment]
Still waiting for this feature and since version 2.4 hopefully with working TOTP.

**Comment by weechatter** [comment]
it does not get faster, even if this issue is pushed ever month.. Please be patience

**Comment by flashcode** [comment]
Hey, some news about the development of this feature.

I've just setup and pushed a new repository with the WeeChat Relay library: https://github.com/weechat/weechat-relay

So the next steps are:

1. use this library in relay plugin, to send messages from WeeChat to clients; so some code will be moved from the relay plugin to the library (target version: **2.5**)
2. add decoding of WeeChat binary messages in the lib (target version: **2.6**, but it's in the lib, not WeeChat)
3. connect to a remote WeeChat in the relay plugin (target version: **2.7 or 2.8**)

Note: the target versions are just estimations.
The WeeChat roadmap will be updated according to the work in progress: https://weechat.org/dev/roadmap

**Comment by sparr** [comment]
@flashcode Could we get a status update over here, more concise than the weechat-relay changelog?

**Comment by flashcode** [comment]
I recently implemented the `weechat-relay-cli` command line tool to connect to WeeChat.
It's working partially: you can send commands to WeeChat and receive bytes, but the messages from WeeChat are not decoded (this is missing in the lib and requires some work, this is the bigger part in lib).

I have no estimate in term of version or date, the progress is slow, depending on my free time.

**Comment by shibumi** [comment]
@sparr according to the weechat roadmap it will be possible to connect to a weechat relay with weechat in January 2021: https://weechat.org/dev/roadmap/

**Comment by leogcurvelo** [comment]
I'd just like to say that the frowny face reaction in the last comment is uncalled for, and we appreciate your work!

To whomever is unsatisfied with the roadmap, please consider donating: https://liberapay.com/weechat

**Comment by craftyguy** [comment]
Uh, the *confused* face was because one developer says "best effort, whenever I have time to do it" and someone else says "roadmap says X" (when obviously the developer's comment would supercede any potentially outdated roadmap....) I mean, why even reply with a link to any roadmap when the developer literally gave a response to the question.

**Comment by flashcode** [comment]
Yes, the roadmap was just a goal, but there is a good chance features planned will move again to later versions.

The priority for me is to fix bugs and review pending pull requests, and I'm almost alone for this work. There are currently 393 issues and 61 PR, this is a huge work. I'm sad to see that some bugs were opened 6 years ago and still not fixed, and that does not even include the old Savannah bug tracker were some bugs were opened 14 years ago…

WeeChat as a relay client is not on top of priorities, so the progress is slow, sorry about that.

Note about donations: it's good for motivation, but unfortunately I miss more time than money.

Help on WeeChat to fix reported bugs, translate docs, review scripts pending (new and updates) would be appreciated. The less time I spend on this, the more time I have for WeeChat as a relay client.

**Comment by flashcode** [comment]
Some news: as you can see in weechat-relay repository (https://github.com/weechat/weechat-relay), the development is active.

I'm currently working on the binary message parser, to decode messages sent from WeeChat to client. This is the most important part of the library.

The other parts of library are already OK: build of binary messages, send of commands to WeeChat, and a CLI tool to test with a running WeeChat (it still has to be improved with the binary message parser, and some completion can be added as well).

Stay tuned for next news... :smiley:

**Comment by diegombeltran** [comment]
> Some news: as you can see in weechat-relay repository (https://github.com/weechat/weechat-relay), the development is active.
> 
> I'm currently working on the binary message parser, to decode messages sent from WeeChat to client. This is the most important part of the library.
> 
> The other parts of library are already OK: build of binary messages, send of commands to WeeChat, and a CLI tool to test with a running WeeChat (it still has to be improved with the binary message parser, and some completion can be added as well).
> 
> Stay tuned for next news... smiley

Great job flashcode!

**Comment by weechatter** [comment]
I guess a donation is welcome :-)

**Comment by flashcode** [comment]
The message parser is implemented: https://github.com/weechat/weechat-relay/commit/9c78acf26e32bb89a237b47ab7dec26acda79c6f :smiley:

**Comment by iot-resister** [comment]
Can I specifically sponsor/donate for this feature?

**Comment by flashcode** [comment]
@iot-resister: a donation is always welcome, it's important for the motivation!
But it will unfortunately not speed up a lot the development of this specific feature, which is still active, but the progress is slow as I don't have a lot of free time.

The next steps are:

1. Use the weechat-relay library to send messages from WeeChat to the client. That means the library must be first packaged in Debian and become a required dependency.
2. Now that the parser is ready in weechat-relay, WeeChat has to use this parser to connect to another WeeChat as a client. This is the biggest part and requires a lot of changes in the WeeChat relay plugin.

**Comment by iot-resister** [comment]
any updates on this?

**Comment by shibumi** [comment]
@iot-resister pro tip: Good devs look at the development roadmap: https://weechat.org/dev/roadmap/

**Comment by empus** [comment]
Just checking in to see if this one is still on target for 3.8 🤞

**Comment by flashcode** [comment]
The progress is still very slow, for sure it will not land in 3.8.

First step is to use weechat-relay library in WeeChat, I'll try to do that in 3.9.
The second step (connect to another WeeChat) is far more complex and will be addressed later (I can not give any date for now).

I just updated the roadmap consequently.

**Comment by JohnXLivingston** [comment]
> I just updated the roadmap consequently.

Thanks for the update!
And many thanks for your work!

**Comment by d3xt3r01** [comment]
+1 ... maybe in 4.1!

**Comment by KebabLord** [comment]
Seems like this feature will never be completed.
I also been using tmux+weechat for many years, recently started to use znc+weechat and i'm really angry at myself that i didn't use that earlier.

- no need to ssh, tmux, weechat-relay 
- no need to create complex workarounds just to get a notification!
- logs and files downloaded with xfer goes to your own computer, not to the server
- you can connect not just from weechat but from any client
- you can distribute your znc instance to a friend that doesn't want to mess with setting up his own server

useful links:
https://flusp.ime.usp.br/others/chatting-on-irc-with-weechat-and-znc/
https://wiki.znc.in/Weechat
https://weechat.org/scripts/source/zncplayback.py.html/  (for playback messages to work)

i'm Junicchi @ libera, feel free to reach if you have any questions about it.

**Comment by flashcode** [comment]
You're right, this one will probably not be implemented, but… I'm working on the same feature with relay API protocol (a REST API provided by relay plugin, new in devel version). See: #2066.

I'll push a development branch soon for tests, stay tuned!

**Comment by flashcode** [comment]
Hi,

Good news, the first alpha version of relay "remote" is there, I pushed the development branch: https://github.com/weechat/weechat/tree/relay-remote

Note that it's work in progress, with following limitations and known bugs:

- no TLS support
- no proxy support
- no nicklist support
- same buffer is sometimes opened multiple times

If you want to test, I strongly recommend a test instance of WeeChat with a separate config.

You can quickly test with the following command:

    weechat -t -r "/set relay.network.password secret; /relay add api 9000; /remote add test http://localhost:9000 -password=secret; /remote connect test"

I close this issue as "won't fix", please share your feedback on the relay API issue: https://github.com/weechat/weechat/issues/2066

**Comment by flashcode** [comment]
The development branch has been removed: merged to master.
