### ISSUE TITLE
Very bad, WeeChat is crashing (SIGSEGV received).

### ISSUE THREAD

**Issue by wxg4net** [weechat/weechat#372]
======= WeeChat backtrace =======
(written by WeeChat 1.2-dev (git: v1.1-172-gfa389d3), compiled on Mar 26 2015 09:40:56)
001  ??:? [function weechat_backtrace]
002  ??:? [function debug_sigsegv]
004  ??:? [function hook_process_send_buffers]
005  ??:? [function hook_process_add_to_buffer]
006  ??:? [function hook_process_child_read]
007  ??:? [function hook_process_child_read_stdout_cb]
008  ??:? [function hook_fd_exec]
009  ??:? [function gui_main_loop]
010  ??:? [function main]
011  ??:? [function __libc_start_main]
012  ??:? [function _start]
======= End of  backtrace =======

full ver: http://perhome-file.stor.sinaapp.com/weechat_crash_20150326_20376.log

**Comment by Mikaela** [comment]
@wxg4net You might want to get core file and **read your full ver**.

```
      [option (addr:0xa4adb08)]
        config_file. . . . . : 0xa49fae8
        section. . . . . . . : 0xa4abcd0
        name . . . . . . . . : 'freenode.command'
        type . . . . . . . . : 2
        description. . . . . : 'command(s) to run after connection to server and
 before auto-join of channels (many commands can be separated by ";", use "\;" f
or a semicolon, special variables $nick, $channel and $server are replaced by th
eir value) (note: content is evaluated, see /help eval)'
        string_values. . . . : 0x0
        min. . . . . . . . . : 0
        max. . . . . . . . . : 0
        default value. . . . : null
        value (string) . . . : '/msg nickserv identify <VERY WEAK PASSWORD THAT WAS ALREADY WEAK>'
        null_value_allowed . : 1
        callback_change. . . : 0xb653329a
        loaded . . . . . . . : 1
        prev_option. . . . . : 0xa4acc28
        next_option. . . . . : 0xa4adc88
```

To change your password, `/msg nickserv set password swordfish` where swordfish is your new password.

You might also be interested in using SASL which is better way to identify.

```
/set irc.server_default.sasl_mechanism PLAIN
/set irc.server.freenode.sasl_username NICK
/set irc.server.freenode.sasl_password PASSWORD
```

Your current config also sends the password directly to NickServ which is bad as unlike `/nickserv`, `/msg nickserv` doesn't check that the services server is U-lined and has  risk of sending the password to malicious user in case of server misconfiguration and real services being down. Has happened at freenode many times.

**Comment by flashcode** [comment]
@wxg4net : please report the full trace using gdb, you have some help in user's guide here: https://weechat.org/files/doc/devel/weechat_user.en.html#report_crashes

**Comment by wxg4net** [comment]
@Mikaela thx. @flashcode   i learned "report_crashes". i will report it  if crash again.

**Comment by flashcode** [comment]
OK, so I close the issue.
