### ISSUE TITLE
Register callback to be triggered at end of file download

### ISSUE THREAD

**Issue by hashken** [weechat/weechat#375]
I want to write a script that will do some post-processing for the files that are downloaded. I'm looking for a way to register a callback that will be triggered at the end of file download. Is this possible with the current code?

**Comment by flashcode** [comment]
You can use the signal "xfer_ended", see the plugin API reference, function hook_signal(): https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hook_signal
