### ISSUE TITLE
Weechat does not support WHOX, leading to warnings when parsing numeric 354.

### ISSUE THREAD

**Issue by Zarthus** [weechat/weechat#376]
Some IRC servers support a custom extended-WHO. This can be read in /VERSION as 'WHOX'.
(/quote help who: https://gist.github.com/Zarthus/3910bb555acebd45e95d).

Freenode is an example network who supports this format.

However, when using this command, Weechat does not properly handle it:

```
16:22:57    esper =!= │ :insanity.esper.net 354 Weethus 2001:41d0:2:e787::1:1
16:22:57    esper =!= │ irc: too few arguments received from IRC server for command "354" (received: 4 arguments, expected: at least 5)
16:22:57    esper =!= │ irc: failed to parse command "354" (please report to developers):
16:22:58    esper  -- │ [#zarthus] End of /WHO list.
```

This is during `/WHO #zarthus %i` (it is not specific to this command. `/WHO Zarthus %i` also generates this, and `/WHO Zarthus %a` does as well). 

Everyone in the weechat channel (that responded) can reproduce the issue, and will not get any output on WHO's with two or more parameters using the percent symbol, with one weechat will error.

To be exact, with two or more characters after the symbol, the following is the only thing returned:
```
01:39:31 freenode  -- │ [Zarthus] End of /WHO list.
```

Debian 7.8, Weechat 1.2-dev (just before javascript support), as well as the latest master
I tested with an old client (Weechat 0.4.2), and that did not seem to have this issue.
It's not a plugin either, I tested with all of them unloaded.

(ps: whilst not significant at all, it seems like the colon on '(please report to developers):' is out of place. Maybe it should be removed?)

**Comment by Mikaela** [comment]
Did you enable account-notify? I think it's required for whox.

**Comment by Shawn-Smith** [comment]
account-notify is not a requirement for whox. or at least it shouldn't be, whox has uses outside of account notification.

**Comment by Zarthus** [comment]
@Mikaela - I don't know what account-notify is or how to check if it is enabled.  So I'd imagine it's set at the default option.

**Comment by Mikaela** [comment]
> or at least it shouldn't be

and here there is the bug.

> I don't know what account-notify is or how to check if it is enabled. So I'd imagine it's set at the default option.

`/help irc.server_default.capabilities` and after setting that, reconnect.

**Comment by Zarthus** [comment]
@Mikaela 

```
│19:33:34    esper  -- │ irc: client capability, server supports: account-notify away-notify extended-join multi-prefix sasl tls
│19:33:34    esper  -- │ irc: client capability, requesting: account-notify sasl
│19:33:34    esper  -- │ irc: client capability, enabled: account-notify sasl
│19:33:36    esper  -- │ You are now logged in as Zarthus. (Weethus!Zarthus@zarth.us)```
```
```
 │19:34:07    esper =!= │ irc: too few arguments received from IRC server for command "354" (received: 4 arguments, expected: at least 5)
 │19:34:07    esper =!= │ irc: failed to parse command "354" (please report to developers):
 │19:34:07    esper =!= │ :availo.esper.net 354 Weethus 2001:41d0:52:400::651
 │19:34:07    esper  -- │ [Weethus] End of /WHO list.
```

Nope, that didn't fix it.

**Comment by Shawn-Smith** [comment]
I can't seem to reproduce this on that network, even without account-notify enabled.

Joined two channels, `#zarthus` and `#diablo`, and did `/who #chan %i` on them both with no issues. I even found the same IP you did on one of the channels.

`[17:29:16]* -- | 2001:41d0:52:400::651`

`[17:29:16]*esperirc -+| :anarchy.esper.net 354 testnick 2001:41d0:52:400::651`

**Comment by Zarthus** [comment]
I don't use a bouncer with weechat, no.

**Comment by Mikaela** [comment]
I have no idea what causes this, but I can use some whox without any issues, but I am able to reproduce this at freenode with ` /WHO #weechat %i`

**Comment by Zarthus** [comment]
It seems like `%ai` works, but just `%a` or `%i` doesn't.  `%ai` however does not genereate any output aside from 'END OF WHO'

**Comment by Mikaela** [comment]
> It seems like %ai "works", but just %a or %i doesn't. %ai however does not genereate any output aside from 'END OF WHO'.

This is another bug in WeeChat as the server does respond. Performing the WHO request with \*raw ZNC module loaded that shows all raw messages passing ZNC:

```
2015-03-28 02:40:06+0200 < *raw> YOU -> [WHO Zarthus %airn]
2015-03-28 02:40:06+0200 < *raw> IRC -> [:rajaniemi.freenode.net 354 Mikaela 255.255.255.255 Zarthus Zarthus :Zarthus]
2015-03-28 02:40:06+0200 < *raw> IRC -> [:rajaniemi.freenode.net 315 Mikaela Zarthus :End of /WHO list.]
```

And as said before, WeeChat only shows

```
2015-03-28 02:40:06+0200 -- [Zarthus] End of /WHO list.
```

**Comment by maxteufel** [comment]
The `too few arguments` warning was caused by IRC_PROTOCOL_MIN_ARGS being set to a wrong value (5 instead of 4). `End of who` being the only line when using more than two options is intended because we can't (without catching/storing WHOX messages sent to the server) know the content of the result. See #419.
