### ISSUE TITLE
Add irc.server.xxx.umodes

### ISSUE THREAD

**Issue by nyuszika7h** [weechat/weechat#377]
I know you can do this with `irc.server.xxx.command` already, but I think adding a more explicit option could be nice.

**Comment by Mikaela** [comment]
I am not sure if it's obvious (probably yes), but I think it should accept it in format `<+|-><umodes>` like `Rw` or `+Rwg-i` or `the other way.

**Comment by nyuszika7h** [comment]
Yeah, probably any of the following should work:

```
Rw
Rw-i
+Rw
+Rw-i
-i+Rw
```

**Comment by Shawn-Smith** [comment]
I think the `+` or `-` should be required to avoid confusion.

**Comment by flashcode** [comment]
Done with a new server option "usermode" (thanks @sim642 for the PR).
The content is just modes sent in the command `/mode $nick <modes>`.

**Comment by nyuszika7h** [comment]
It seems `+` is implied if not specified on all ircds I tested on.
