### ISSUE TITLE
Prefix color option and read marker color option

### ISSUE THREAD

**Issue by AlissaSquared** [weechat/weechat#383]
I've been customizing WeeChat to my liking and - unlike how everyone says - there are two components that I have found that I believe are missing an option to their color. The chat prefix-suffix marker (the one separating nick from chat), and the read marker (displaying last read line). Is there any planned setting for these?

**Comment by weechatter** [comment]
You don't mean:
weechat.color.chat_prefix_suffix
weechat.color.chat_read_marker
weechat.color.chat_read_marker_bg
