### ISSUE TITLE
Run /who before /ban to know the $host variable

### ISSUE THREAD

**Issue by freijon** [weechat/weechat#384]
When running /ban \<nick\> for a user that has been in the channel before you, the $host variable in the setting irc.network.ban_mask_default is unknown to weechat which results in a fallback banmask $nick!\*@\*.
Weechat should run /who \<nick\> before /ban \<nick\> automatically.

**Comment by Shawn-Smith** [comment]
For networks that support the `userhost-in-names` cap this information is sent on join and shouldn't need an additional /who.

**Comment by Mikaela** [comment]
> For networks that support the userhost-in-names cap this information is sent on join and shouldn't need an additional /who.

Issue: WeeChat doesn't request userhost-in-names by default and it's not considered as safe capability in https://github.com/weechat/weechat/issues/320.

**Comment by Shawn-Smith** [comment]
It doesn't need to be requested automatically, but if it is requested the extra who isn't needed.

**Comment by flashcode** [comment]
Duplicated by #578 which has more info, closing this one.
