### ISSUE TITLE
How to make highlight case sensitive?

### ISSUE THREAD

**Issue by OnkelTem** [weechat/weechat#386]
I couldn't find documentation on RegEx weechat implementation details. Specifically, was looking for a way to make ```weechat.look.highlight_regex``` case sensitive.
I'm creating this issue to allow Google for indexing and let people find this info faster.

The answer turned to be "already there" which means it is literally contains in the built-in help:
```
/help weechat.look.highlight_regex
```
prints this nice how-to:
```
Option "weechat.look.highlight_regex":                                                                                                                         
description: POSIX extended regular expression used to check if a message 
has highlight or not, at least one match in string must be surrounded by delimiters 
(chars different from: alphanumeric, "-", "_" and "|"), regular expression is case 
insensitive (use "(?-i)" at beginning to make it case sensitive), examples: 
"flashcode|flashy", "(?-i)FlashCode|flashy"
```
Thus to make your regex case sensitive, just add (?-i) to the beginning. 
My example:
```
/set weechat.look.highlight_regex "(?-i)\b(Onkel Tem|Onkel|Tem)"
```

**Comment by flashcode** [comment]
All options (core and plugins) are described in user's guide, available with other docs here: https://weechat.org/doc/

**Comment by OnkelTem** [comment]
@flashcode  
> All options (core and plugins) are described in user's guide, available with other docs here:
> https://weechat.org/doc/

It is too vague as it's hard to find the requested info by that link. Specifically FAQ - doesn't help, Quick start - doesn't help. So [Users's guide] (https://weechat.org/files/doc/stable/weechat_user.en.html) would be more appropriate link in this case.

**Comment by flashcode** [comment]
Yes that's what I said: my link points to ALL WeeChat docs, not only FAQ or quickstart.
