### ISSUE TITLE
Auto complete the active (channel) buffer first (and optionally group by network)

### ISSUE THREAD

**Issue by koobs** [weechat/weechat#392]
Currently, it appears that weechat (as of 1.1.1) auto-completes channel names as a single alphabetically sorted list, even when on multiple networks.

This is an enhancement request to:

- [ ] Auto-complete the *active* (channel) buffer *first* when completing `#<matchtext>`. An option could / should be created such as `weechat.completion.channel_active_first=on|off`.

- [ ] An option to group channel completion list by network, such that if on network1 and network2, completion will cycle through all network1 channel buffers *first*, then cycle through network2 channel buffers. Suggested option name `weechat.completion.channel_group_by_network=on|off`.

Note: Existing Savannah task [#12923: Channel completion](https://savannah.nongnu.org/task/?12923)

**Comment by koobs** [comment]
Thank you! Just to confirm, the suggestions options to globally enable/disable this, and/or group networks has not been added correct?

**Comment by flashcode** [comment]
Yes, I think options are not even needed, so this is the new default behavior.
You can still complete as usual with #something [+TAB], all matching completions will be used (even if not sorted alphabetically).

**Comment by bendem** [comment]
Would be neat if that worked with prefixed channels as well like `/msg @#<channel> <msg>`
