### ISSUE TITLE
Autocomplete wrong case

### ISSUE THREAD

**Issue by HelixSpiral** [weechat/weechat#398]
With `weechat.completion.partial_completion_other` set to `on` the case of the nick you're completing can sometimes be wrong (all lowercase)

To reproduce
- Have two nicks on a channel, I used {Andrew} and {Andrew}|Mobile because they were available on a channel I'm in
- Set weechat.completion.partial_completion_other on
- Type {A and tab-complete
- You will get {andrew} instead of {Andrew}

Now if you add a | to the end of {andrew} and tab-complete you'll get {Andrew}|Mobile with the correct casing.

**Comment by Mikaela** [comment]
I don't have `weechat.completion.partial_completion_other` as on, but I had similar issue which might or might not be related.

I had query buffer with `nickname` where the nick is spelled as `NickName` and tab for some reason decided to autocomplete it wih all small letters.

**Comment by flashcode** [comment]
This seems to be the same bug as: https://savannah.nongnu.org/bugs/?32213

**Comment by flashcode** [comment]
Fixed by #1872, commit f0415c8ec3c6def45e5e61756e9a521f25e5f8a3.
