### ISSUE TITLE
Add a `weechat.desktop` file to the repository/distribution

### ISSUE THREAD

**Issue by lucc** [weechat/weechat#408]
I suggest to add a [desktop file](http://standards.freedesktop.org/desktop-entry-spec/latest/). This should allow weechat to appear in menus for desktop environments like Gnome or KDE and should enable users to open irc:// links with `xdg-open`.

I think the file should look something like this:

``` desktop
[Desktop Entry]
Name=Weechat
Categories=Application
GenericName=IRC Client
Exec=/usr/bin/weechat %u
Terminal=true
Type=Application
MimeType=x-scheme-handler/irc
```

**Comment by Mikaela** [comment]
ircs:// links should also be handled.
