### ISSUE TITLE
segfault when /list /list -re **

### ISSUE THREAD

**Issue by StatelessCat** [weechat/weechat#412]
Hey,
Version : Weechat 1.1.1 on debian stable and Archlinux, and Weechat 1.2-rc1 on Archlinux
Weechat crash on any big irc server when 
```
/connect freenode
```
```
/list 
```
And few secs after the flood has began
```
/list -re **
```
(or any faulty regex)

It happens everytime.
If you want any more information, i'll be glad to help you :)

**Comment by flashcode** [comment]
Nice crash! Thanks for reporting, it is fixed :)

**Comment by StatelessCat** [comment]
Thanks to you :)
