### ISSUE TITLE
SASL 3.2 REAUTH

### ISSUE THREAD

**Issue by Mikaela** [weechat/weechat#413]
- http://ircv3.net/specs/extensions/sasl-3.2.html
- Depends on https://github.com/weechat/weechat/issues/182

SASL REAUTH allows users to identify using SASL if services were down during the initial connection. Currently this is only possible with CertFP.

**Comment by Mikaela** [comment]
It has also been talked about that there should be command such as `/authenticate username password` for manually invoking SASL REAUTH for identifying as another account (such as bot, or placeholder (freenode-staff, ubuntuirccouncil...)) and without parameters it could probably send the configured credentials.

**Comment by voidzero** [comment]
Good idea
