### ISSUE TITLE
unicode emojis?

### ISSUE THREAD

**Issue by fuzzy76** [weechat/weechat#428]
unicode emojis are filtered out. They display as blank spaces. The terminal handles them fine.

```
charset: terminal: UTF-8, internal: UTF-8
```

**Comment by Mikaela** [comment]
Glib issue, duplicate of https://github.com/weechat/weechat/issues/79

**Comment by flashcode** [comment]
Here's a post that could help you: https://blog.nytsoi.net/2015/05/04/emoji-support-for-weechat
