### ISSUE TITLE
"Server notice mask" misparsed

### ISSUE THREAD

**Issue by grawity** [weechat/weechat#429]
Weechat seems to have troubles parsing the snomask on Unreal 3.2 servers:

    --> :virgule.cluenet.org 008 grawity :Server notice mask (+kcfFvGqSso)

This gets displayed as:

    -i- Server notice mask for grawity is [Server]

Yeah, okay, the numeric as sent by Unreal is a bit annoying to parse in the first place. But still, the "Server notice mask (+kcfFvGqSso)" is supposed to be a single token, so it's weird that the first word got split off.

**Comment by flashcode** [comment]
On which server can I test that, and which command to run?

**Comment by grawity** [comment]
Most Unreal-based servers should work, such as `irc.gimp.org`. Use `/umode +s` to test. (Usually snomasks +ks are available to non-opers, `/umode +s +sk` can enable them.)

**Comment by wowaname** [comment]
(unhelpful to the issue but let the record state these issues are the reasons Unreal sucks)
