### ISSUE TITLE
[cygwin] Ruby not loading in 1.2

### ISSUE THREAD

**Issue by Shawn-Smith** [weechat/weechat#432]
Ever since updating to WeeChat 1.2 the ruby plugin no longer loads properly.

````
=!= | Error: unable to load plugin "/usr/lib/weechat/plugins/ruby.dll": No such file or directory
=!= | If you're trying to load a script and not a C plugin, try command to load scripts (/perl, /python, ...)
````
````
$ file /usr/lib/weechat/plugins/ruby.dll
/usr/lib/weechat/plugins/ruby.dll: PE32+ executable (DLL) (console) x86-64, for MS Windows
````

So I'm not sure what's happening here.

Edit :: Ruby is installed, and I can use it just fine, just not in WeeChat

**Comment by flashcode** [comment]
It looks like Ruby has been upgraded from version 2.0 to 2.2 in cygwin.
So I'll rebuild WeeChat cygwin packages (version "-2") and upload them soon.

**Comment by flashcode** [comment]
I just uploaded weechat-1.2-2 packages in Cygwin, they should be available in the next hours on cygwin mirrors.
Please confirm if it's not OK for you, and then I'll close this issue.

**Comment by Shawn-Smith** [comment]
This fixes the issue. Thank you.
