### ISSUE TITLE
bare_display_time_format can no longer be used independently of buffer_time_format

### ISSUE THREAD

**Issue by quasarj** [weechat/weechat#441]
Commit 2498ff63dba0ad3880fc3dadcac6b36f047ac0e2 changed the independent behavior of weechat.look.bare_display_time_format, such that it now is only respected if weechat.look.buffer_time_format is set (not an empty string). I don't really understand the purpose of this change - if you didn't want the time displayed in either mode, you could easily unset them both. 

I prefer to have a timestamp in bare mode (for copy/paste) but no timestamp in my normal display. As a workaround, I can set weechat.look.buffer_time_format to a single space, though that is not quite optimal.

**Comment by flashcode** [comment]
Hmm you're right, I'm looking at my own commit and I don't remember the exact reason why the time in bare display should be displayed only if `weechat.look.buffer_time_format` is set to non-empty string.
