### ISSUE TITLE
Data from hook_process is corrupted after repeated usage in (relatively) long time

### ISSUE THREAD

**Issue by tomoe-mami** [weechat/weechat#442]
When using hook_process/hook_process_hashtable to fetch content of URL, the returned data is prepended with one or more `\x07` character after about 1 to 2 days of repeated usage.

I have put [demo triggers for testing this in gist][1]. The trigger will check [this other gist][2] (contains only `AAAAAAAAAA` so it's easier for checking) every 5 minutes. If it detect corruption it will print an error message in core buffer and run `xxd` to dump the hex output. When you're testing the trigger, **do not upgrade/quit weechat**. It looks like doing that reset the state/curl/whatever it is handling hook_process/etc and you'll have to wait another 1-2 days to get the corrupted data.

I'm using WeeChat 1.3-dev (git: v1.2-24-g799b0ca) [compiled on Jun  9 2015 09:22:20] but this issue has existed at least since v0.4.4-dev/v1.0 so I doubt the version matters.

[1]: https://gist.github.com/tomoe-mami/e70213c5d1d159df7309
[2]: https://gist.githubusercontent.com/anonymous/516b08a56c6b8c1c8ff5/raw

**Comment by torhve** [comment]
I have seen similar things using matrix.lua script. My script error reporting says the following:
   
    Expected value but found invalid token at character 1 during json load: ^G^G{"chunk":[{"content":{"avatar_url":"mxc://matrix.org/diZJubyWZftcUfebmAiZbGOA","displayname":"Mike","last_active_ago":358952,"presence":"unavailable","user_id":"@mpicher:matrix.org"},"type":"m.presence"}],"end":"s220152_12024_4561","start":"s220152_12021_4561"}

**Comment by flashcode** [comment]
So the problem was caused by some printf on stdout or stderr without a flush after, like the "\a" sent when you search text in buffer (ctrl-R) and that this text is not found (by the way the alert sent in this case was not working properly: all the alerts were sent only on flush of stdout, so most of times on `/quit` only).
