### ISSUE TITLE
weechat.look.color_nick_offline doesn't apply to /me's.

### ISSUE THREAD

**Issue by Mikaela** [weechat/weechat#446]
![screenshot](http://i.imgur.com/fWLrqHm.png)

(In case the screenshot doesn't appear: http://i.imgur.com/fWLrqHm.png)

I hope join/quit messages still stay the normal colour, but /me's are written by the user so I think their colour should also be changed.

_Noticed by @sim642 at #weechat on 1.2 and I reproduced with 1.3-dev (git: v1.2-24-g799b0ca) [compiled on Jun  9 2015 20:56:17]._

**Comment by sim642** [comment]
I've identified that the problem is due to the lack of `prefix_nick_*` tag on ACTION lines because that tag is used when checking offline status of nicks on lines.

**Comment by flashcode** [comment]
The problem is not the lack of tag, but the way to check if the nick in an action is offline or not.
The tag prefix_nick_xxx is used only on lines with a nick in prefix (ie NOT for /me actions).

**Comment by wowaname** [comment]
Off-topic: how did you get op prefixes in actions?

**Comment by stfnm** [comment]
@wowaname See `/help irc.look.nick_mode`.

**Comment by wowaname** [comment]
@stfnm Neat, overlooked that.

**Comment by flashcode** [comment]
Clsing, as it was implemented in 4.3.0, commit: b0b733a8f0af0adcd268ddb161f0c5b9269dcfad.
