### ISSUE TITLE
Make signal trigger more useful by making pointer data an actual pointer instead of just extra var

### ISSUE THREAD

**Issue by unzan** [weechat/weechat#450]
Apologize if the title isn't clear enough. Currently inside a signal trigger there are only these:

```
tg_signal: <name-of-the-signal>
tg_signal_data: <any-string>
```
According to the doc, `${tg_signal_data}` can contain "pointer" like in `irc_pv_opened` signal, but it's useless because unlike modifier trigger (eg, `weechat_print` modifier) where you get an actual `${buffer}` pointer, this one is  just a hex string. I can't use `${tg_signal_data}` to get property of the new pv buffer that is just opened.There is `${buffer}` variable inside signal trigger but it's pointing to current buffer which means for `irc_pv_opened` signal it's useless.

Can we please improve the signal trigger so that instead of just random useless hex string we get an actual buffer/window/filter/etc pointer?

**Comment by flashcode** [comment]
The `${tg_signal_data}` in signal `irc_pv_opened` should be a pointer to the buffer opened, so it's not a random string.

**Comment by unzan** [comment]
But it's not. In `/trigger monitor` it is listed under extra_vars unlike in modifier trigger where it is listed under pointer ([screenshot][1]).

I've also tried `${tg_signal_data.full_name}`, `${${tg_signal_data}.full_name}` and `${tg_signal_data}.full_name`. The first two are evaluated to empty string and the third one is evaluated to something like `0x966f870.full_name`. So it's definitely not a pointer.

[1]: https://i.imgur.com/KAAyYRf.png

**Comment by flashcode** [comment]
It's a buffer pointer, but you can not use it like that, because when adding .full_name, weechat does not know that the pointer is a pointer to a buffer (the pointers sent as data with signals have no "type").
So some things must be changed in the API to allow you to use the pointer (or in trigger plugin for some signals, but it would be better to have something generic for all signals).

**Comment by flashcode** [comment]
This is already possible with a specific syntax to force the type "buffer": `${buffer[${tg_signal_data}].full_name}`

**Comment by unzan** [comment]
That one is still evaluated to current buffer in here instead of the newly opened buffer. I'm using WeeChat 1.3-dev (git: v1.2-44-g7c1b7df) [compiled on Jun 17 2015 01:41:05] and here's the test trigger I use:

```
/trigger add pv_opened signal "irc_pv_opened" "" "" "/print -core ${buffer[${tg_signal_data}].full_name}" "ok"
```

When I'm in #weechat channel and there's a new pv opened, the trigger prints `irc.freenode.#weechat` instead of `irc.freenode.nickname`.

**Comment by flashcode** [comment]
OK, you're right, it doesn't work.
I'll fix evaluation of string to allow a pointer (`0x...`).
