### ISSUE TITLE
ISO-8859-15 encoded message to UTF-8 channel with ä in the name is shown only in irc raw

### ISSUE THREAD

**Issue by OzQu** [weechat/weechat#451]
Channel is created with UTF-8 ä letter in it. User who sends the message has irssi and has recode_out_default_charset = ISO-8859-15 which means that his irssi recodes every message out. I guess irssi still sends message to UTF-8 channel, instead of recoding the name also.

I can see in irc raw that message is received (letter ä in messsage body is replaced with ?). Message is not printed to any channel at all. Decode is set to recognize ISO-8859-15. Doesn't help even if decode is empty. 

Weechat propably decodes whole irc message including the channel name instead of just the message.

**Comment by Mikaela** [comment]
Possibly related https://github.com/weechat/weechat/issues/218 ?

**Comment by flashcode** [comment]
Yes, related to #218, I think one fix can be applied for both problems.

**Comment by flashcode** [comment]
The problem is that WeeChat decodes whole message (charset conversion), including headers and channel name, instead of just the body of user message.
