### ISSUE TITLE
glyphs/unicode won't show, but will show in the terminal

### ISSUE THREAD

**Issue by esn89** [weechat/weechat#455]
i'm using termite right now and i've tried using other terminals as well such as rxvt-unicode. 
on my terminal and vim, I am able to view the special unicode characters such as the lightning bolt and the triangle as seen here:

http://i.imgur.com/SzMa8KK.png

when it gets to weechat, nothing but a bunch of the letter "M"s take the place:

http://i.imgur.com/xEh5rG7.png

the white "M" in the second picture is where I did:  "/me " and the lightning bolt is supposed to be there.  

I've also tried the suggestions of setting: export LANG=en_US.UTF-8 LC_CTYPE="en_US.UTF-8"
but that doesn't seem to be working out.

**Comment by flashcode** [comment]
Hi,

First, what's your WeeChat version?

Can you try with a new config (`weechat -d /tmp/weechat`), check the charset used (`/charset`) and the other things related to charset in this question of FAQ: https://weechat.org/doc/faq#charset

Another thing to try: display this char in a message, and then do alt-l (alt-L) to display bare display. Is it properly displayed in this mode?

And do you know the code of the char not properly displaed by WeeChat? So that I can try.

**Comment by Mikaela** [comment]
I have strange feeling of https://github.com/weechat/weechat/issues/79.

**Comment by esn89** [comment]
My weechat version is 1.2.  Here is a screenshot of what I get when I do /charset:

http://i.imgur.com/aEMaWnz.png

A copy of my /tmp/weechat/charset.conf:   http://ix.io/jnm/#n-LINENO

When I go into a channel, pressing alt-L does not help.

Here is a snippet of my weechat.conf with the glyphs in case you wish to try:

http://ix.io/jnn/#n-LINENO

**Comment by Mikaela** [comment]
Do you see characters such as ÄÖÅ or others like that used in some languages? If you do, I would say this is #79.

**Comment by esn89** [comment]
nah, I actually don't see those characters.

**Comment by flashcode** [comment]
Then if you don't see chars like äöë, please double check the charset question in FAQ (https://weechat.org/doc/faq#charset), this should solve your problem.

**Comment by esn89** [comment]
Thanks.  I checked most of the requirements, and I've met all the ones except the linking to libncursesw.  How can I link it that library?

**Comment by flashcode** [comment]
If you compiled yourself, you have to install libncursesw5-dev (this is the Debian name and may be different on other distributions).
See dependencies in user's guide: https://weechat.org/doc/user#dependencies

**Comment by esn89** [comment]
Sweet.  Thanks.  So just to reiterate, all I need to do is install that dependency?  No need to add in any params during the ./configure phase?

**Comment by esn89** [comment]
Ah nevermind. It was a simple case of reconfiguring like you said. Thanks
