### ISSUE TITLE
Merged buffers: allow different prefix than buffer name

### ISSUE THREAD

**Issue by azrdev** [weechat/weechat#456]
I have joined two channels with the same name on different networks/servers, and merged their buffers. weechat uses the buffer name as prefix for each line, which defeats the purpose of identifying them.
Proposed solution: Allow for the server name to be used as prefix instead.
#416 (proposal to hide the prefix) is also related.

**Comment by flashcode** [comment]
WeeChat uses the "short_name" to display name of merged buffers. You can customize it as you want with `/buffer set short_name xxx`.
This is not saved in config file, so you can use script buffer_autoset.py to save it.

**Comment by azrdev** [comment]
Okay, works for me. Thank you, I consider this now fixed
