### ISSUE TITLE
It should not be possible to /query a #channel name

### ISSUE THREAD

**Issue by flashcode** [weechat/weechat#459]
When doing `/query #test` then `/join #test`, the query buffer becomes a channel, but without nicklist (maybe others bugs can appear as well on the buffer).
WeeChat should refuse to `/query #test` and display an error.
And if ever a private buffer `#something` exists, WeeChat should not reuse this buffer on `/join`.

**Comment by Mikaela** [comment]
I believe it should be possible to `/query #channel` as there is channel mode `-n` which allows messages to be sent even if you aren't on the channel.

I don't know what the original logic behind this was, but I would imagine it to be what I just said.

**Comment by flashcode** [comment]
@Mikaela: `/query` in WeeChat is *only* to open a private buffer with someone. If you want to send a message to a channel, you can use `/msg #channel message`.

**Comment by Mikaela** [comment]
I see. `/query` would make sending more messages to channel mor easy, but that is probably very special use-case and if it's only or opening private buffer with someone no changes needed.
