### ISSUE TITLE
Suggestion, /list order by user count

### ISSUE THREAD

**Issue by softgot** [weechat/weechat#461]
Sometimes it's interesting to get an overview of the most popular channels on a server. Sorting the output from /list by the number of users on the channels would make this possible. I can't see this feature implemented in Weechat, are there any plans to implement it in the future?

Thank you for a great program and keep up the good work!

**Comment by Mikaela** [comment]
You might be interested in `/script install listbuffer.py` and then trying `/list` again.

**Comment by softgot** [comment]
Oh I totally missed that script. Thanks!
