### ISSUE TITLE
Cygwin: Perl plugin not loading in 1.2

### ISSUE THREAD

**Issue by Wobblit** [weechat/weechat#474]
The Perl plugin is not loading for WeeChat 1.2 under Cygwin using the latest Perl package (5.22).
It works if reverting back to the alternate Cygwin package for perl (5.14).

> Error: unable to load plugin "/usr/lib/weechat/plugins/perl.dll": No such file or directory

**Comment by flashcode** [comment]
I uploaded new packages for Cygwin, which should fix the problem (new version: 1.2-3).
They should be available soon on mirrors (for both x86 and x86_64).
