### ISSUE TITLE
Option to support supressing "Options saved to X.conf" messages

### ISSUE THREAD

**Issue by evaryont** [weechat/weechat#483]
I use an autosave plugin (specifically, [confversion](https://weechat.org/scripts/source/confversion.py.html/)) to automatically save & commit to git any settings I make. However, that can get real noisy when looking at the `weechat` buffer.

Alternatively, I could filter those but I'm not sure how; the following doesn't seem to work for me:

    /filter add supress_saved core.weechat * '^Options saved to'

**Comment by flashcode** [comment]
The script can do `/mute /save` instead of just `/save`.
I close this issue, since it's a script issue, not WeeChat.
So please open an issue in scripts repository, or send a patch to its author for this change, then he'll update the script.

**Comment by ksu-0** [comment]
#1694 could help with this, as `/save` would be able to only overwrite config files that have changed.
