### ISSUE TITLE
Cygwin: Perl plugin still not loading 1.2-3

### ISSUE THREAD

**Issue by FerusGrim** [weechat/weechat#485]
This bug was raised a week-and-a-half ago with Issue #474.

The solution that was suggested seems to have been a soon-to-be update to perl.dll in 1.2-3. However, now that this update is out, I'm having the same issue. The plugin is available where the other plugins (which are being loaded currently) are located, but will not be loaded by weechat.

Additionally, the error that I'm getting is that weechat can't even _locate_ the file, though I'm not sure if this is the standard response when the file isn't compatible/corrupted.

**Comment by flashcode** [comment]
Is your perl version up-to-date?
WeeChat now requires the latest perl in cygwin to work fine.
Please show me your versions of perl and weechat.

**Comment by FerusGrim** [comment]
Perl: perl-5.22.0-1
Weechat: weechat-1.2-3

That's what I'm using currently.

**Comment by FerusGrim** [comment]
After deleting my installation dir (D:\cygwin) and the downloads (C:\Users\Ferus\Downloads), and running the setup again, this seems to have resolved itself.

They were both clean installs (I reformatted, this morning), so I'm not sure what the winning trick was. xD

Sorry for the false report.

**Comment by flashcode** [comment]
Ok :-)
