### ISSUE TITLE
/debug tags doesn't show tags of message if there's zero-width space character at the end of it

### ISSUE THREAD

**Issue by tomoe-mami** [weechat/weechat#502]
If I send a message that has U+200B at the end of it and then run `/debug tags`, there won't be any tags displayed for it. Other people who run `/debug tags` won't be able to  view the tags for that message too.

**Comment by flashcode** [comment]
I think this is not specific to `/debug tags` but a bug caused by the zero width space, see the original bug report on savannah: https://savannah.nongnu.org/bugs/?40985

**Comment by flashcode** [comment]
It can be reproduced with this command: `/print -escape test \u200b message`
The word "message" is not displayed.

**Comment by tomoe-mami** [comment]
Oh, sorry. Forgot to check savannah. 

If I use `/print -escape one\u200btwo`, all of it is displayed. I select the text and dump the codepoint just to make sure all characters are there: https://i.imgur.com/mZkiDfy.png

So it's not displayed if there's space after \u200b ?

**Comment by flashcode** [comment]
Yes, I found the problem in code. It happens only if a whole "word" (delimited by spaces) has a length of zero on screen, so for example a word with one or more U+200B chars will cause the display problem.
When WeeChat finds a word with length of zero (on screen), it considers the line has ended and displays a new line, which is wrong in this case.
