### ISSUE TITLE
does not display astral characters

### ISSUE THREAD

**Issue by daxim** [weechat/weechat#506]
To reproduce:

* Copy 😮 to clipboard.
* Run weechat.
* Paste.

Expected:

😮 is displayed in the input line.

Actual:

A space character is displayed in the input line.

Perhaps bug #379 is related.

    $ echo $TERM
    xterm-256color

    $ konsole --version
    Qt: 4.8.6
    KDE: 4.14.9
    Konsole: 2.14.2

    $ zypper info weechat
    Repository: server:irc
    Name: weechat
    Version: 1.3-1.1
    Arch: x86_64
    Vendor: obs://build.opensuse.org/server:irc
    Installed: Yes
    Status: up-to-date
    Installed Size: 2.1 MiB
    Summary: Portable, Fast, Light and Extensible Chat Client
    Description:
      WeeChat (Wee Enhanced Environment for Chat) is a fast and light cross-platform
      chat environment. It can be entirely controlled with the keyboard, has a
      plugin-based architecture and is customizable and extensible with scripts in
      several scripting languages.

    $ cat /etc/os-release
    NAME=openSUSE
    VERSION="13.2 (Harlequin)"
    VERSION_ID="13.2"
    PRETTY_NAME="openSUSE 13.2 (Harlequin) (x86_64)"
    ID=opensuse
    ANSI_COLOR="0;32"
    CPE_NAME="cpe:/o:opensuse:opensuse:13.2"
    BUG_REPORT_URL="https://bugs.opensuse.org"
    HOME_URL="https://opensuse.org/"
    ID_LIKE="suse"

**Comment by Mikaela** [comment]
Duplicate of many issues and ultimately https://github.com/weechat/weechat/issues/79.

**Comment by Mikaela** [comment]
By the way in order to make GitHub to not make the smiley graphical, put it into two backticks \`☺\` = `☺`.

**Comment by daxim** [comment]
I'm having no graphical smiley. It's all text.

Confirming the work-around <https://blog.nytsoi.net/2015/05/04/emoji-support-for-weechat> works. This will hold me over until glibc 2.22 lands.
