### ISSUE TITLE
raw irc data printed in buffer/channel if null byte in privmsg

### ISSUE THREAD

**Issue by spaceone** [weechat/weechat#507]
If a server writes e.g. a message like this `:spacetwo!spacetwo@::ffff:12.34.56.78 PRIVMSG #test :test blah blah\x00foo bar\r\n`
The message is not printed directly, weechat waits until the server sends the next (non-privmsg?) message which is in my case e.g. a PONG or KICK etc. `:example.server.net PONG LAG1440663235546\r\n`.
The IRC buffer now contains this:
`spacetwo | test blah blah:example.server.net PONG example.server.net`
Seems everything after the null byte is dropped and everything until the next CRLF of a non privmsg is appended to the message which is printed into the channel-buffer.

**Comment by flashcode** [comment]
Maybe something that could be improved, but the RFC 2812 explicitely says that NUL chars are **NOT** allowed in IRC messages:

    2) The NUL (%x00) character is not special in message framing, and
        basically could end up inside a parameter, but it would cause
        extra complexities in normal C string handling. Therefore, NUL
        is not allowed within messages.

Ref: https://tools.ietf.org/html/rfc2812

**Comment by spaceone** [comment]
Well, the handling of broken servers and evil clients have to be improoved in weechat nevertheless.

**Comment by flashcode** [comment]
After a quick test in 2.7-dev, it seems this problem is not there any more.
If I'm wrong, please give me the steps to reproduce, I'll reopen the issue.
