### ISSUE TITLE
Please treat umode +g notices as highlights or something more noticable

### ISSUE THREAD

**Issue by Mikaela** [weechat/weechat#515]
I think it's numeric 718. `nick ident@host:is messaging you, and you have umode +g.`

Currently it takes me sometime to return to server buffer and notice that I have PM attept without the person pinging me on the channel.

More about umode +g:

* https://mikaela.info/english/2015/04/02/umode+g.html
<br><br>
* WeeChat 1.4-dev (git: v1.3-31-g4b2abd9) [compiled on Aug 31 2015 18:10:21]
* Debian GNU/Linux 7.8 (wheezy)

**Comment by Shawn-Smith** [comment]
@Mikaela Could you link to a specification for usermode +g? The link you provided doesn't seem to have numerics, or any specifications about it at all.

**Comment by wowaname** [comment]
The point of umode +g is to make things *less* annoying, though...

**Comment by Mikaela** [comment]
> Could you link to a specification for usermode +g? The link you provided doesn't seem to have numerics, or any specifications about it at all.

I would be happy to if I had any ideas where I would find those. I think umode +g is one of those things IRCds just decided to do.

> The point of umode +g is to make things less annoying, though...

The point of umode +g is to block unwanted private messages which it would still do while it's more noticable. I get far more unwanted /invites which are treated as highlight than unwanted umode +g notices (which are rarely annoying as they only contain the nick) and I prefer to know when I am contacted.

Of course how to treat them could be an option.

**Comment by Mikaela** [comment]
I asked on \#ircv3 and dx gave me https://github.com/grawity/irc-docs/blob/master/misc/irc-documentation-jilles/reference/modeg.txt

**Comment by wowaname** [comment]
On 15 09 05 04 52, Mikaela Suomalainen wrote:
>> Could you link to a specification for usermode +g? The link you provided doesn't seem to have numerics, or any specifications about it at all.
> 
> I would be happy to if I had any ideas where I would find those. I think umode +g is one of those things IRCds just decided to do.
> 
>> The point of umode +g is to make things less annoying, though...
> 
> The point of umode +g is to block unwanted private messages which it would still do while it's more noticable. I get far more unwanted /invites which are treated as highlight than unwanted umode +g notices (which are rarely annoying as they only contain the nick) and I prefer to know when I am contacted.
> 
> Of course how to treat them could be an option.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/weechat/weechat/issues/515#issuecomment-137910742
> 
I'd say hook a script to the numeric and print ^G that way.

**Comment by Mikaela** [comment]
I tested [IRCCLoud Notifier](https://chrome.google.com/webstore/detail/irccloud-notifier/hjjkpkihllldiogoboajdddgkfpjdigh) & IRCCloud for fun and it appears that it gives pop-up telling "Caller-ID: NICK is messaging you, and you have umode +g" which was a nice surprise.

> I'd say hook a script to the numeric and print ^G that way. That *is* what scripting is for.

I think highlight in WeeChat is more than only printing ^G.

**Comment by wowaname** [comment]
> I tested [IRCCLoud Notifier](https://chrome.google.com/webstore/detail/irccloud-notifier/hjjkpkihllldiogoboajdddgkfpjdigh) & IRCCloud for fun and it appears that it gives pop-up telling "Caller-ID: NICK is messaging you, and you have umode +g" which was a nice surprise.
As someone who doesn't like IRCCloud, that doesn't hold much weight to me.
> I think highlight in WeeChat is more than only printing ^G.
True, it also calls the buffer's highlight event and adds it to the hotlist.

**Comment by Mikaela** [comment]
Closing in favour of https://github.com/weechat/weechat/issues/664.
