### ISSUE TITLE
hdata last_read_line pointer is not present for current weechat buffer if the buffer has no read marker (all messages read)

### ISSUE THREAD

**Issue by oakkitten** [weechat/weechat#517]
using relay. it you navigate away from the buffer, last_read_line returns correct pointer
WeeChat 1.4-dev compiled on Sep  5

**Comment by flashcode** [comment]
This is not a bug: this pointer is NULL if everything is read in a buffer (ie if the read marker is NOT displayed in buffer).
So if it's NULL, the relay client can just consider everything is read, and no read marker has to be displayed.

**Comment by oakkitten** [comment]
last_read_line should point to the last read line. if all lines are read, it should be pointing to the last read line. and in this case it *is* pointing to the last line, *unless the buffer is active*.

**Comment by oakkitten** [comment]
apparently `last_read_line` does is not meant to represent the last read line.

**Comment by flashcode** [comment]
The variable `last_read_line` can have 2 values:
* **pointer to a line**: WeeChat will display read marker (dashed line) **after** this line
* **NULL**: that means everything is read in the buffer, and that the read marker must **NOT** be displayed at all.

So having `last_read_line` on last line or NULL is different: in both cases everything is read in buffer, but in the first case, the read marker is displayed after the last line of buffer.

**Comment by oakkitten** [comment]
according to what i see, this is incorrect. currently,

* **NULL** means that either:
   * no lines are read in the buffer, or
   * all lines are read in the buffer and the buffer is displayed (no marker)
* **pointer means that** either
   * there are unread lines in current buffer as compared to last time (marker is showing)
   * buffer is not displayed and it has read lines. this *includes buffers in which all lines are read*.

**Comment by MBuchaus** [comment]
What I was looking for when I came across this thread was  weechat.look.read_marker
