### ISSUE TITLE
Alias should show with "list" if it was created using "addcompletion"

### ISSUE THREAD

**Issue by highflyer77** [weechat/weechat#518]
When you make a new alias using addcompletion, there is no way to tell that you used "addcompletion" when using "/alias list" (or any other alias option).
"/alias list" should show you something to reflect the fact, that the alias was created using "addcompletion".
The only way I know how to do this now, is to look into the alias.conf file.
Should be a better way or maybe this is a bug?

For example: when you use the addcompletion option to make an alias and then use /alias list,
it doesn't show the addcompletion option in the output, and the completion part is completely missing.

I also feel that "/alias" should have an "edit" option. 
That would allow the output to be viewed exactly like it was created, so that it could be easily edited ready for command input.
That would make it a lot easier for tweeking an alias, at a later time.

Thanks to all the authors.
"WeeChat Rocks"

**Comment by flashcode** [comment]
I added the completion in `/alias list` (or just `/alias`).
For the edition of aliases, please open a separate issue.
