### ISSUE TITLE
Decoding charset on private chats is broken with irc.network.channel_encode = off

### ISSUE THREAD

**Issue by lamperi** [weechat/weechat#520]
Weechat fails to decode private messages in 1.3. This was still working on 1.2. This behaviours seems to be unaffected by any configuration with /charset. The other person's nickname is full ASCII in my case.

With option irc.network.channel_encode = on the messages are correctly decoded.

With option irc.network.channel_encode = off any non-utf-8 compactible characters seem to be displayed as questions marks (?).

**Comment by flashcode** [comment]
FYI, this bug was introduced by commit 0ff8d7b5439ee543fae8eb4c4080ec4ccf905b1d (so the problem was in version 1.3 only).
