### ISSUE TITLE
autojoin +keyed channels on invite

### ISSUE THREAD

**Issue by motharussia** [weechat/weechat#526]
make weechat use the irc.server.*.autojoin key when invited to a +keyed channel. currently weechat will not use it and therefor not autojoin a channel that has key protection.

**Comment by flashcode** [comment]
Hi,
WeeChat itself (without script) has no automatic way to join a channel where you are invited.
So if you mean adding this feature in script autojoin_on_invite.py, please open an issue in the scripts repository, instead of weechat: https://github.com/weechat/scripts

**Comment by motharussia** [comment]
https://github.com/weechat/scripts/issues/99
