### ISSUE TITLE
Support logging of IRC colours

### ISSUE THREAD

**Issue by Zarthus** [weechat/weechat#528]
It would be nice to have a setting that ensures colours do not get removed in the logging.

Some usecases:
- Paste messages exactly as they were received
- Ban a specific annoying realname that has a weird and/or annoying colour combination that is no longer available in WHOWAS.
- Easier grepping when you know a message you're looking for has used colours.

**Comment by BlacklightShining** [comment]
Would this just cover colors? I'd like my logs to include all formatting—really the message as it was received, like @Zarthus said.

**Comment by Zarthus** [comment]
A good point - yes, the intention is to "log the message as it is", just in a weechat-readable logging method. (i.e. no raw irc message logging, but without weechat stripping things from the message either)

**Comment by flashcode** [comment]
I'll add an option to write log files with ANSI color codes, and then display of backlog will be in color by default if this option is enabled (#621).
If ANSI color codes are written, the log file can be read with `less -R filename`, and it will probably break scripts reading log files like grep.py. So they'll need an update to support ANSI color codes.
I'll add functions in API to convert colors from WeeChat to ANSI and from ANSI to WeeChat
