### ISSUE TITLE
Add an option to disable newline added to multiline paste

### ISSUE THREAD

**Issue by arza-zara** [weechat/weechat#543]
Paste a string like:

	"/print abc
	/print incompl"

with no newline in the end - and weechat runs also the incomplete command.

- This happens only after paste confirmation.
- This isn't related to bracketed paste mode.

**Comment by flashcode** [comment]
This is in fact a feature (see commit a539dcbff8ba6989b0625d773fc0260a41c35eb8).

In most cases, it's better to automatically add a new line at the end: it's weird when you paste 10 lines to send 9 and keep the last one in the input buffer.

But then I'll add an option to disable that if you prefer to send exactly what is pasted.
