### ISSUE TITLE
weechat.bar.size_max semantics

### ISSUE THREAD

**Issue by wlhlm** [weechat/weechat#544]
`weechat.bar.*.size_max` [is documented as](https://weechat.org/files/doc/devel/weechat_user.en.html#bars):

> The maximum size for a bar, 0 = no limit **(this option is used only if size = 0)**.

Unfortuantely, the code tells a different story:

``` c
if ((CONFIG_INTEGER(ptr_bar->options[GUI_BAR_OPTION_SIZE_MAX]) > 0)
    && (CONFIG_INTEGER(ptr_bar->options[GUI_BAR_OPTION_SIZE]) >
        CONFIG_INTEGER(ptr_bar->options[GUI_BAR_OPTION_SIZE_MAX])))
{
    snprintf (value, sizeof (value), "%d",
              CONFIG_INTEGER(ptr_bar->options[GUI_BAR_OPTION_SIZE_MAX]));
    config_file_option_set (ptr_bar->options[GUI_BAR_OPTION_SIZE], value, 1);
}
```

This is from [`gui_bar_config_change_size_max()`](https://github.com/weechat/weechat/blob/master/src/gui/gui-bar.c#L1108-L1131) which is run when `size_max` is changed.

Here `size` gets "clipped" to `size_max` in case `size` is bigger than `size_max`. But shouldn't `size_max` be ignored?

What is correct here &mdash; the documentation, or the code?

**Comment by flashcode** [comment]
Hi,
The code you're pointing is not to change the size of the bar (for display), but to change the `.size` option of the bar (like `/set weechat.bar.xxx.size N`) in case you set a size > size_max (which does not make sense). So WeeChat ensures the size is never greater than size_max in the bar options.

**Comment by flashcode** [comment]
Closing old issue/question.
