### ISSUE TITLE
Highlights and unbreakable spaces

### ISSUE THREAD

**Issue by ProgVal** [weechat/weechat#55]
When receiving a message containing `mynick\xa0?` (`\xa0` is the unbreakable space), weechat does not detect it as a highlight.

Some informations, as ask in `Contributing.asciidoc`:
* Version: `WeeChat 0.4.4-dev (git: v0.4.3-336-gb09fbea) [compilé le Mar 19 2014 18:54:24]`
* OS: Debian Sid
* How to reproduce: ask someone (or a bot) to write your name followed by an unbreakable space (some keyboard layouts map unbreakable spaces to AltGr+Space). For instance, with a Supybot you could do: `@echo "test $nick\xa0?"`

**Comment by flashcode** [comment]
This issue is related to this old task on savannah: https://savannah.nongnu.org/task/?9459
I think both could be fixed at same time.
