### ISSUE TITLE
Add an option to prefix the completer char

### ISSUE THREAD

**Issue by mkaito** [weechat/weechat#551]
I've had the need to complete nick mentions to `@username` instead of `username:`.

Ideally, this would be accomplished by setting `weechat.completion.nick_completer = "@"` and something like `weechat.completion.nick_completer_prefix = true`.

In my particular case, it would be great if this was a per-network setting.

**Comment by flashcode** [comment]
This is not exactly same thing, but related to #187 and #345 (which requires some changes before being merged).

**Comment by mkaito** [comment]
No, not quite. I mean to complete a nick 'nickname' to '@nickname'.

My particular use-case is the gitter/irc bridge.

**Comment by mkaito** [comment]
Add the slack IRC gateway to the use case.

**Comment by mkaito** [comment]
Actually, can a weechat plugin hook into tab completion to change this on a per-server basis?

**Comment by flashcode** [comment]
I think it's possible to write a script that does that:
1. add a default completion with all prefixed nicks (ie a list like "@nick1", "@nick2", ...)
2. hook the Tab key (command `/input complete_next`), detect if you are trying to complete a nick (by analyzing input), if yes, and if no prefix like "@" is detected, add the prefix before the nick, and run the completion again, which will use the default completion list (defined above in first point). This could be done only on some buffers if needed.
I'll try to write a very basic script doing that, and let you improve it by adding config and such things.

**Comment by mkaito** [comment]
That would be greatly appreciated. I have no experience working with weechat plugins, but if you give me a basic framework to work with, I'll polish it.

**Comment by Mikaela** [comment]
:+1: ­— I also have to use some Slacks and their IRC gateways and as we are bridging some channels to IRC, we have set Slack to require the `@` so people won't highlight themselves over bridges. However on the channels that aren't bridged being able to `@a<tab>` would make using the gateway easier.

*My WeeChat is behind ZNC which has set to detach channels that are bridged (which means not showing the client it's on those channels or anything related to them while still keeping ZNC on them).*

**Comment by tomoe-mami** [comment]
I decided to [write a script][1] for it but using different method than the one described in @flashcode's comment. Instead of creating new completion, this one just modifies the result of the completion.

The script uses buffer's localvar instead of per server settings like in your original request because this way it would be easier for server like Bitlbee where there could be more than one way of mentioning someone within the same server. The readme has examples on how to set it up. If you need prefix to be set per server, you can use:

    /autosetbuffer add irc.servername.* localvar_set_ncw_prefix @

[1]: https://github.com/tomoe-mami/weechat-scripts/tree/master/nick_complete_wrapper

**Comment by flashcode** [comment]
Done, with the script https://github.com/weechat/scripts/blob/master/lua/nick_complete_wrapper.lua from @tomoe-mami.
