### ISSUE TITLE
add new "sticky" command to move the read marker

### ISSUE THREAD

**Issue by highflyer77** [weechat/weechat#552]
Have a command to move the read marker to somewhere else in the chat area and make it sticky, 
so that it doesn't reset when switching buffers.  That would make it easier to catch up on reading,
while still being able to switch buffers.

**Comment by Petzku** [comment]
This could be very useful, for instance when reading backlogs (say, something over 100 lines) and someone messages you, so you don't have to remember exactly where you were, or just quickly read a highlight in the same buffer, then scroll back up to where you were.

**Comment by mkoskar** [comment]
I would suggest to change `/input set_unread_current_buffer` such that it would place read marker after last visible line at the bottom of the current window and scroll one line to make marker visible. Or better yet:

* `/input set_unread_current_buffer` - scroll to end of buffer (this **doesn't** happen now) and place read marker at the end
* `/input set_unread_current_buffer_here` - place read marker at current scrollback position (as described above)

Above naming and behavior is more or less consistent with `search_text` / `search_text_here` or `search_stop` / `search_stop_here`.

Furthermore configuration option e.g., `weechat.look.read_marker_auto {on|off}` could designate whether automatic placing of read marker at the end of buffer should take place when buffer is no longer displayed in any window.

**Comment by dstensnes** [comment]
Yes please, i have been trying to figure out if there is a way of preventing it from automatically moving the read marker. +1 from me

**Comment by ksu-0** [comment]
I think a good solution could look like this:
* after switch to buffer, if it is not scrolled and the read marker is not in view, scroll up until it is at the top of the view
* before switch from buffer, if it is scrolled and the read marker is located before the view, move the read marker to the top of the view
* on switch from buffer, if it is scrolled, do not update the read marker

**Comment by flashcode** [comment]
Implemented in 4.0.0 via #1895: `/buffer set unread [+/-]N`.
