### ISSUE TITLE
Trigger cmd_pass.regex breaks relay.network.password input

### ISSUE THREAD

**Issue by rbgarga** [weechat/weechat#554]
I'm using weechat 1.3 and tried to set relay.network.password. When I press space after password word to be able to start typing the desired password line changes to the value of trigger.trigger.cmd_pass.regex, that is "$1$.*+".

If I type the password, it saves it without problem, but I still only see $1$.*+ on the prompt

If I set trigger.trigger.cmd_pass.regex to "" the issue disappears

**Comment by flashcode** [comment]
Hi,

If you have upgraded from version 1.0 of WeeChat, the format of trigger has changed.
You must reset your triggers, see the release notes here (in version 1.1): https://weechat.org/files/releasenotes/ReleaseNotes-devel.html
