### ISSUE TITLE
"file_in" option in hook_process_hashtable with "url:" command

### ISSUE THREAD

**Issue by sim642** [weechat/weechat#557]
The API documentation is extremely brief on [hook_process_hashtable](https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hook_process_hashtable)'s use as URL handler with the `file_in` argument. The existence of the option is mentioned but there's no information about how to use the inputted file in the query, or even if it can be used in a specific way or not.

Namely the problem in question was putting an input file into a POST request's POST-able field. libcurl's information about `CURLOPT_READDATA` doesn't give much about where the data can go either.

Surely it's possible to directly append the file contents after some `key=` in `postfields` option but that's not very safe as the contents could easily contain "&" or "=" characters themselves, messing with the fields.

This feels relatively libcurl problem rather than weechat's but curl has different ways of POST-ing files which don't really apply here. Either way it'd be nice to have more detailed information in the documentation as `file_in` isn't a libcurl option directly.

_Motivated by UnDeRsOuL's failed attempts to use `file_in` in #weechat._

**Comment by batalooppak** [comment]
According to Singalaut in #weechat
>curl_easy_setopt doc says to use CURLOPT_HTTPPOST if I want to make multipart/form-data
>request (the correct way to upload via POST) but that option is disabled in wee-url.c

It’s not possible to do multipart/form-data. Either upload via PUT using file_in or urlencode the whole file and put it in post fields."

but according to http://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.2
>The content type "application/x-www-form-urlencoded" is inefficient for
>sending large quantities of binary data or text containing non-ASCII characters.
>The content type "multipart/form-data" should be used for submitting forms that
>contain files, non-ASCII data, and binary data."

**Comment by flashcode** [comment]
Duplicate of #344, which I just scheduled for version 2.2.
