### ISSUE TITLE
IPv6 not being preferred for IRC connections

### ISSUE THREAD

**Issue by akerl** [weechat/weechat#558]
I have ipv6 set to "on" in my default server config in irc.conf, and the server I'm connecting to ("irc.oftc.net") has AAAA records as well as A records and responds on IPv6. Here's the snippet from my config:

https://gist.github.com/akerl/894a809ac124a9a01664

I've confirmed that if I use iptables to drop IPv4 traffic outbound on 6697, weechat tries to connect on IPv4, fails, then falls back to IPv6 and succeeds. Per the docs, I'd expect it to try IPv6 first: https://weechat.org/files/doc/stable/weechat_user.en.html#irc_options

Am I missing some facet of the network configuration for weechat?

**Comment by flashcode** [comment]
Hi,
Yes I confirm, IPv6 should be tried first by WeeChat if the option `ipv6` is `on`.
Are you sure your IPv6 configuration is OK on your machine?
And what's your OS (and its version) and WeeChat version?

**Comment by Mikaela** [comment]
I think that in other words this issue is *WeeChat doesn't have Happy Eyeballs biasing towards IPv6*.

**Comment by akerl** [comment]
I'm running Arch and on Weechat 1.3. I've confirmed my IPv6 is working properly, and I've been testing Weechat's behavior by doing the following:

* Start weechat and connect to irc.oftc.net (using the config pasted above)
* Watch it connect on IPv4
* /disconnect oftc
* Block outbound IPv4 on port 6697 using iptables
* /connect oftc
* Watch it try to connect on IPv4, fail due to firewall, and then successfully connect over IPv6

Given that it successfully uses IPv6 once I block IPv4, it definitely looks like it's not trying in the correct order, vs there being a v6 issue.

I was also looking for where in the code it prefers IPv6 over IPv4, and couldn't find it. I'd be happy to poke around at that and see if I can isolate what's going on, if you could give me a pointer on where it's doing the lookup (searching the codebase for "ipv6" proved less-than-effective)

**Comment by brainpower** [comment]
I've got weechat 1.3 on arch, too,
and it connects without any issue to freenode via IPv6.
But I've explicitly set irc.server.freenode.ipv6 to on, instead of just irc.server_default.ipv6.
Maybe it's not using the server_default option correctly?

@akerl: what if you try to set irc.oftc.ipv6 to on? Does it still try IPv4 first?

**Comment by akerl** [comment]
Yes, it still tries IPv4 first with IPv6 explicitly set to "on" for OFTC

**Comment by brainpower** [comment]
well, it was worth a try...
It's weird, though, I don't remember setting anything special for IPv6, just all the server.xxx.ipv6's to on
Maybe it's because I'm using SSL?
I see no other config value that could influence how connections are made...

And weechat is definitely using v6 to connect on my machine:

    $ host leguin.freenode.net
    leguin.freenode.net has address 130.239.18.119
    leguin.freenode.net has IPv6 address 2001:6b0:e:2a18:5054:ff:fe01:8119
    $ lsof -nP -p 748 | grep 2001:6b0:e:2a18:5054:ff:fe01:8119
    weechat-c 748   bp   44u  IPv6 416608      0t0      TCP [2001:XXXX]:32874->[2001:6b0:e:2a18:5054:ff:fe01:8119]:7000 (ESTABLISHED)

For reference, my irc.conf:
https://gist.github.com/brainpower/0666c14468231aa47ab5

**Comment by akerl** [comment]
@flashcode any idea what's up here? I'm happy to try more debugging, just not sure where to start looking

**Comment by Mikaela** [comment]
How does WeeChat currently handle selecting the internet protocol? I am hoping IRCv3.3 to start encouraging Happy Eyeballs (RFC 6555) (https://github.com/ircv3/ircv3-specifications/issues/189)  and if you dare to throw idiotic comments (like https://github.com/kvirc/KVIrc/issues/1760#issuecomment-163951304)  I am switching to irssi!

*(The part about irssi is not serious as they lack IRCv3 support entirely.)*

**Comment by flashcode** [comment]
@akerl: I tried again with oftc and SSL, it connects in IPv6 by default (using WeeChat devel, but it should be the same with 1.3).
Maybe some DNS problem on your side?
Can you try command `host` on irc.oftc.net, you should have something like:

    $ host -t AAAA irc.oftc.net
    irc.oftc.net is an alias for irc6.geo.oftc.net.
    irc6.geo.oftc.net has IPv6 address 2001:1b40:5000:fe0::6667
    irc6.geo.oftc.net has IPv6 address 2a02:2458:1:11::3
    irc6.geo.oftc.net has IPv6 address 2001:6b0:e:2a18::116

When I connect in WeeChat, I have following output:

    oftc  -- │ irc: connecting to server irc.oftc.net/6697 (SSL)...
    oftc  -- │ gnutls: connected using 2048-bit Diffie-Hellman shared secret exchange
    oftc  -- │ gnutls: receiving 4 certificates
    (...)
    oftc  -- │ irc: connected to irc.oftc.net/6697 (2a02:2458:1:11::3)

**Comment by akerl** [comment]
So, I've narrowed this down:

The kernel specifically doesn't treat IPv6 addresses in fd00:: as "better than v4" for purposes of getaddrinfo. So it was preferring v4 despite gai.conf claiming to prefer v6.
