### ISSUE TITLE
Autojoin channels are rejoined after reconnection if all channels were closed

### ISSUE THREAD

**Issue by flashcode** [weechat/weechat#560]
When all channels of a server are closed (/buffer close), a reconnection to the server (with /reconnect or after a network disconnection) will rejoin all channels in `.autojoin` option.
But if at least one channel was still opened, the reconnection will not rejoin other channels in `.autojoin` option.
Expected behavior: never rejoin new channels on reconnection but only currently opened channels.

Reported by Boobuigi_ on #weechat.

Bug on Savannah: https://savannah.nongnu.org/bugs/?21529

**Comment by mkoskar** [comment]
I would suggest to:

* keep `/connect` and `/reconnect` behaviour as is; it processes `.autojoin` (if set) by default + rejoins all channels in opened buffers; if `-nojoin` is passed no channels are autojoined or rejoined
*  create configuration option `irc.(server_default|<server>).autoreconnect_autojoin` (**on** / **off**); **on** - when auto-reconnecting process (or don't in **off** case) autojoins (if set)
