### ISSUE TITLE
autojoin of channels doesn't wait for authentication after reconnecting to the server

### ISSUE THREAD

**Issue by spaceone** [weechat/weechat#571]
Every X-month some servers like freenode are restarting their services. Weechat automatically reconnects and joins into every channel. It is very annoying that weechat doesn't wait for being authenticated until joining the channel. This causes that the server redirects me to e.g. #channel-unregistered. I think also no automatic nickserv identify is done. It's not nice because due to this I am loosing information what happens in the original channels.

**Comment by flashcode** [comment]
There is already an option `.commnd_delay` in servers to delay the autojoin after the command.
But I would recommend to use SASL authentication instead of nickserv, with that you are always identified before joining channels.

**Comment by Mikaela** [comment]
I tried to comment by email, but apparently the comment never came through. What I tried to say was that if you want to be identified before even being visible to the network you should use SASL or not being identified before joining channels can only be blamed on you. 

* [Very simple instructions for using SASL](https://mikaela.info/english/2015/03/26/weechat-sasl-simply.html)

> some servers like freenode are restarting their services.

You mean *networks* like freenode restart their *servers*. Services would be NickServ & co and you won't get  reconnected or logged out if they restart.

In case the network doesn't support SASL, contact them about it or use certfp or if they don't support it either, something is seriously wrong with your network.

**Comment by spaceone** [comment]
I already have SASL activated. It still sucks very much:
```
freenode   -- | irc: Der Nickname "spaceone" wird bereits verwendet. Es wird nun versucht den Nicknamen "space" zu nutzen
freenode   -- | irc: Clientfähigkeit, aktiviert: sasl
freenode   -- | You are now logged in as spaceone.
freenode   -- | NickServ (NickServ@services.): This nickname is registered. Please choose a different nickname, or identify via /msg NickServ identify <password>.
freenode   -- | NickServ (NickServ@services.): You have 30 seconds to identify to your nickname before it is changed.
freenode   -- | NickServ (NickServ@services.): You failed to identify in time for the nickname space
```

**Comment by flashcode** [comment]
Check that your nick is OK, you should not see the message saying the "nickname is registered".

**Comment by spaceone** [comment]
I have got fallback nicknames which aren't registered by me/nickserv.
But the problem here is that weechat changes the nickname because freenode says that someone is still connected with that nickname (which is the same weechat instance but one side reconnected so there is no ping timeout yet). Then SASL authentication works (!) for the correct username but the nickname was still changed and nickserv renames me.

**Comment by flashcode** [comment]
Then you could link many nicks to your main nick (with nickserv) and use these nicks as alternate nicks.
So that using these nicks will be considered OK (registered).

**Comment by Mikaela** [comment]
Your nick being changed due to using a nick you don't own is not a WeeChat issue.

Either do as @flashcode said and take a unregistered nick and `/msg nickserv group` it and set it as your alternative nick or `/set irc.server.fr.command /msg nickserv regain primarynickhere`. *Do note to change fr into whatever your freenode is named as.*

**Comment by spaceone** [comment]
But isn't it a weechat issue to handle this case correctly? It seems to be a race condition as the SASL authentication succeeds but weechat shouldn't change the nick during a SASL authentication attempt.

**Comment by Mikaela** [comment]
SASL authentication happens before registration and is indepent of your nick. Your nick is sent to server only after SASL authentication is finished and if your primary nick is unavailable for one reason or another, WeeChat attempts to use other configured nicks and if you don't own the secondary nick, NickServ requests you to identify to account owning it and in case the account has ENFORCE set, it changes your nick.

**Comment by spaceone** [comment]
If that is the case (And I of course believe you) why is weechat then first printing that the nickname is unavailable and then printing that it tries to make SASL authentication (as can be seen in comment 4, sorry that it is partly german)?

**Comment by spaceone** [comment]
Also what I don't understand is that freenode says "You are now logged in as spaceone." and if I manually change the nickname back to "spaceone" it tells me that I need to authenticate at nickserv (again).

Can I implement a workaround somehow that if my nickname is not the primary nickname weechat tries to change the nickname back to the primary one every X seconds (until freenode detects the ping-timeout or what is happening over there)?
