### ISSUE TITLE
/quiet and /unquiet ignore irc.network.ban_mask_default

### ISSUE THREAD

**Issue by Mikaela** [weechat/weechat#577]
I noticed this while reading the logs of testing https://github.com/weechat/weechat/issues/576.

```
/quiet Euforia
2015-11-05 15:01:00+0200 -- Mode ##Mikaela [+q Euforia!*@*] by Mikaela
/unquiet Euforia
2015-11-05 15:01:04+0200 -- Mode ##Mikaela [-q Euforia!*@*] by Mikaela
```

Based on my `irc.network.ban_mask_default` `*!*@*$host` I believe that the mask for quiet should have been `*!*@*unaffiliated/mikaela/bot/dysforia` instead of `Euforia!*@*`.

Quiet is just lesser form of ban (only prevent talking and nick changes while ban also prevents joining the channel) and as it works the exact same way, I don't see why it would be immune to that option or any reason why there should be different option for it.
- Debian GNU/Linux 7.9 (wheezy)
- WeeChat 1.4-dev (git: v1.3-103-g99ebcca) Copyright (C) 2003-2015, compiled on Nov  5 2015 09:33:55

**Comment by sim642** [comment]
We could also have a different variable for quiet, e.g. `irc.network.quiet_mask_default` because options.

**Comment by sim642** [comment]
Also the [source code](https://github.com/weechat/weechat/blob/master/src/plugins/irc/irc-command.c#L4022) for `/quiet` suggests that it directly sends the given arguments, so if only nicks are specified, only nicks are sent, leaving it to the IRCd to make sense of it.

**Comment by Mikaela** [comment]
>> or any reason why there should be different option for it.

> We could also have a different variable for quiet, e.g. `irc.network.quiet_mask_default` because options.

Do you see any reason why it should be different option? How does it differ from ban or do anything to deserve separate option?

Without any use case the only case where I accept separate option is if it defaults to whatever is configured as banmask and changes when I change the banmask.

**Comment by Mikaela** [comment]
> Also the source code for /quiet suggests that it directly sends the given arguments, so if only nicks are specified, only nicks are sent, leaving it to the IRCd to make sense of it.

This seems like a bug to me as it's incosistent with ban which does more than just sends everything to `/mode +b `.
