### ISSUE TITLE
Contact notes

### ISSUE THREAD

**Issue by devcline** [weechat/weechat#581]
Hello 

While talking to "everyone" that not always your friend or talking to a guys who change nicks everydays i woud love to remeber them or just write a information like date, , links numbers and else into a note for a user with mask

IS there is a feature or a plugin that exists ?

/note foo thenote

 thanks!

**Comment by flashcode** [comment]
Hi,
You can search a script with `/script search` in WeeChat (see `/help script` for help on command), or on WeeChat site: https://weechat.org/scripts/
If such script does not exist, please open an issue in scripts repository: https://github.com/weechat/scripts/

**Comment by Mikaela** [comment]
Is https://github.com/weechat/weechat/wiki/Triggers#append-label-to-message-from-certain-users at all related?

**Comment by highflyer77** [comment]
There is a notes.pl script at:  http://weechat.arza.us/notes.pl
also, there is a feature request for a bookmark feature at:
https://github.com/weechat/scripts/issues/96

**Comment by devcline** [comment]
@highflyer77 its almost this, its missing the console command adding /notes text
@Mikaela how do i intall or activate trigger plugin? As i undestood the label will be showed near a nick?

**Comment by Mikaela** [comment]
@devcline `/plugin load Trigger` and preferably add it to `weechat.plugin.autoload`. If you don't have it, you are on ancient unsupported version of WeeChat.

**Comment by devcline** [comment]
I dont have it installed , no such file or directory.. hmm and weechatis already the latest version

btw i found this solutions ofr my notes use: 

   /buffer set title My best friend !
   /script install buffer_autoset.py
   /autosetbuffer add irc.freenode.r3m title My best friend !
   /cycle
   /script install customize_bar.py
