### ISSUE TITLE
iset plugin

### ISSUE THREAD

**Issue by Mikaela** [weechat/weechat#584]
Iset is very useful and everyone always assumes that it's installed by everyone, but there are always people who don't have it and don't want to install scripts they don't consider as needed or don't even compile plugins for languages they don't consider useful to them.
- Debian GNU/Linux 7.9 (wheezy)
- WeeChat 1.4-dev (git: v1.3-103-g99ebcca) Copyright (C) 2003-2015, compiled on Nov  5 2015 09:33:55

**Comment by wlhlm** [comment]
What exactly is your issue here?

**Comment by Mikaela** [comment]
This issue is that there is no iset plugin that ships with WeeChat, but instead there is iset perl script which everyone at #weechat assumes to be installed.

To use iset.pl, you must have the perl plugin compiled and install the script.

**Comment by flashcode** [comment]
I started development of iset-like feature in core, with the same /set command and a dedicated buffer.
I made some commits 1.5 year ago, but did not have enough time to finish that yet.
Adding it in core could be better than a plugin because it would use less memory (no need to build a separate list of all options, like iset.pl does).

**Comment by Mikaela** [comment]
Core sounds even better, but I thought that would be too much to wish for.

**Comment by dcunited001** [comment]
i concur, i would rather not run any plugins at all, if possible.  but i would like some of the functionality.  perhaps if the functionality is basic enough, some plugins should be made core.

**Comment by flashcode** [comment]
You mean not run any "script"? And some "scripts" should be "plugins" or in core?
(script = a scripting language, plugin = a C plugin, like irc).

**Comment by flashcode** [comment]
The "fset" plugin has been added in version 2.0, it replaces iset.pl with many new features (see the devel blog: https://weechat.org/blog/post/2017/06/26/Fset-plugin).
So I close this issue.
