### ISSUE TITLE
The size of this repo is very large

### ISSUE THREAD

**Issue by Earnestly** [weechat/weechat#601]
I recently re-cloned this repo and found it had swelled to 104.42M while the source code alone only consumes 19M.

There many be blobs hidden in the history which have been inadvertently carried forward.  Searching for these and removing them might be a wise choice because right now the size is becoming pretty ridiculous in my opinion as a user on a not-so-great internet service.

Please consider investigating into the reason for this 5x increase in history size.
Thanksl

**Comment by flashcode** [comment]
Hi,

As far as I know there's no big and unused files or objects in this repository.

My .git local repository is only ~25MB.
When I clone the github repository, .git directory is 109MB, and after a `git gc --aggressive`, it's 24MB.
But I think there is no way to run that on github side (they're responsible of doing `git gc` periodically, and I'm not even sure running it with `--aggressive` is a good thing).

So I have no idea what I can do on my side.

Please add comments if you know some ways to shrink github repositories.

**Comment by bendem** [comment]
I generally clone big repos with --depth 50 to avoid these issues. Doesn't fix the problem, but works everywhere.

**Comment by Earnestly** [comment]
Ack, it looks like yet another github failing (the list is getting pretty long).

Perhaps you're right and github simply hasn't gc'd this repo for a long time.  On the other hand I still find it difficult to accept; consider a repo like mpv with almost 42,500 commits (at the time of writing).  A clone of this is "only"  71M (and 64M after a aggressive gc).

However I do hope that it's the case github simply hasn't gc'd this repo yet, it'd be really nice to get back to a size similar to the size of the source (obviously plus some for the overhead of git).

Thanks for the replies

**Comment by Earnestly** [comment]
Heh, more like "can't fix".

**Comment by wlhlm** [comment]
Hmm, maybe they can manually initiate a gc when you mail them...

**Comment by flashcode** [comment]
So I set "invalid" as I can't do anything in WeeChat itself for that.
