### ISSUE TITLE
Server passwords doesn't start with colon with spaced password

### ISSUE THREAD

**Issue by kyrias** [weechat/weechat#602]
If the server password sent contains spaces the argument has to have a colon prepended to it so that the whole password is recognized as a single argument by the server. WeeChat currently just sends `PASS <password>`.

**Comment by kyrias** [comment]
(For reference: znc/znc#1188)

**Comment by Mikaela** [comment]
@flashcode I fear your fix breaks many IRCds when password without space is used. See https://github.com/hexchat/hexchat/issues/1550 and the easiest fix would probably be https://github.com/irssi/irssi/issues/362#issuecomment-159064710.

**Comment by flashcode** [comment]
OK, I'll update accordingly.

**Comment by flashcode** [comment]
@Mikaela: it should be better with the second commit.
