### ISSUE TITLE
/key's command <key> argument can't be quoted for spaces

### ISSUE THREAD

**Issue by mkoskar** [weechat/weechat#603]
It seems it's impossible to use `/key` command with a `<key>` argument which contains a space character (ASCII 040 / 32 / 0x20).

As an example consider `Meta + <Space>` sequence:
- `alt-k` (`/input grab_key_command`) shows `meta-`
- doing `/key bind meta- /print x` results in `Error: unable to bind key "meta-"`
- any usual quoting I've used doesn't work (e.g., `'...'`, `"..."`, `\.`)
- but utilizing Python API **works**: `weechat.key_bind('default', {'meta- ': '/print x'})`

**Comment by flashcode** [comment]
Old savannah issue: https://savannah.nongnu.org/bugs/?32133

**Comment by flashcode** [comment]
Closing this issue as this has been fixed in version 1.9, released on 2017-06-25.

ChangeLog has been updated accordingly (commit: 2cfecc2).
