### ISSUE TITLE
Closing a server buffer doesn't always close channels

### ISSUE THREAD

**Issue by mumixam** [weechat/weechat#606]
If a server connection failed or a certain channel has never been joined, the channel does not get properly associated with that server and the channel buffer stays open until it is manually closed. Reproduce by creating a network with an invalid hostname, and fill in the autojoin with some random channels. The channels and server buffers will all be created, but if you close the server buffer, channels will remain.

**Comment by Mikaela** [comment]
I think the proper procedure is:

1. `/disconnect` so the reconnection attempts are stopped.
2. `/close` and all the buffers attached to that network get also closed.

However this probably isn't the optimal behaviour and this has been labeled as a bug.

**Comment by flashcode** [comment]
I just tested with 2.7-dev and for me it works fine, the channel buffers, even if not joined, are always closed when I close the server buffer.
If you can reproduce the problem, please give me the steps to reproduce and I'll reopen the issue.

**Comment by mumixam** [comment]
I am unable to reproduce this issue now too.
Must of been fixed somewhere along the way
