### ISSUE TITLE
gui: key_pressed double signaling

### ISSUE THREAD

**Issue by sim642** [weechat/weechat#609]
_I used the following trigger to test the signaling:
`/trigger addreplace key_pressed signal key_pressed "" "/\x01\[/meta-/ /\x01/ctrl-/" "/print -core key_pressed\t${tg_signal_data}"`_

`key_pressed` signal seems to send some keys twice in certain scenarios:
1. **Key combos where first key is not decisive:** this affects combos like `meta-jnn` where pressing `meta-j` isn't enough to decide on the key combo made. For example pressing `meta-jq` causes the signal to fire five times: `meta-`, `j`, `meta-`, `j` and `q`. The separation of `meta-j` put aside, it is signaled twice even though pressed only once.
2. **Key combos where first key is not bound.** For example pressing `ctrl-Sctrl-U` causes the signal to fire three times: `ctrl-S`, `ctrl-S` and `ctrl-U`. Again, the first key is signaled twice even though pressed only once.

From these cases it seems to me like the buffer which stores keys for current combo being pressed is sent to `key_pressed`, not just the key that most recently got pressed. Regarding the earlier cases:
1. `meta-j` stays in the buffer because it's not complete, but is signaled regardless. Completing the combo with `j` causes the signal again but sends the entire combo, not the key pressed additionally.
2. `ctrl-S` stays in the buffer unknown reason and gets signaled twice as described in the first case.

Changing the behavior of `key_pressed` does not pose any compatibility issues in my opinion as no plugin and only three scripts (vimode.py, url_hinter.rb, multiline.pl) use such hook. The latter two seem to completely ignore the key being pressed and the first being the script which would benefit from this being fixed.

_Issue brought to my attention by GermainZ in #weechat._

**Comment by flashcode** [comment]
Hi,
This has been fixed in version 4.0.2 via #1976.
