### ISSUE TITLE
Add support of SNI for IRC SSL connection

### ISSUE THREAD

**Issue by Mikaela** [weechat/weechat#620]
Currently it looks like SNI will be required by IRCv3.3 (https://github.com/ircv3/ircv3-specifications/pull/185) and it's already supported by multiple clients such as:

* HexChat - https://github.com/hexchat/hexchat/commit/dbad9285b8a4267cc7e7e3c3fd84699ed406a13a
* Yaaic - https://github.com/pocmo/Yaaic/commit/c49c476cd04e80c0831c5c07f7f21a2ff886e20b
* ZNC (bouncer) - https://github.com/znc/znc/commit/47f887ce435c0c6559cf5aea34dd3697d0e2c015
* irssi - https://github.com/irssi/irssi/commit/28aaa653cf681b7bf8500b073f74a255a6fb15eb

[GnuTLS Server name indication](http://gnutls.org/manual/html_node/Server-name-indication.html)

**Comment by Mikaela** [comment]
And there it is https://github.com/ircv3/ircv3-specifications/blob/master/core/sni-3.3.md (required by IRCv3.3 in it's current form).

**Comment by KindOne-** [comment]
Forgot mIRC. 

```
28/02/2015 - mIRC v7.41
...
9.Extended SSL support to allow connecting to SNI servers.
```
http://www.mirc.com/versions.txt
