### ISSUE TITLE
logger: option to show backlog with colors

### ISSUE THREAD

**Issue by sim642** [weechat/weechat#621]
There should be an option to show backlogs like the lines used to show up, this includes not overriding the line color with gray and using nick colors.

**Comment by Zarthus** [comment]
Might be related to https://github.com/weechat/weechat/issues/528 - while your issue describes the backlog, I'd reckon my issue is a prerequisite for this to happen.

**Comment by flashcode** [comment]
Colors will be automatic with implementation of #528.
