### ISSUE TITLE
Remove support for RC4 and 3DES ciphers in the default list

### ISSUE THREAD

**Issue by r4v5** [weechat/weechat#628]
Same argument as #248: `NORMAL:-VERS-SSL3.0` still supports some dud ciphers.
https://wiki.mozilla.org/Security/Server_Side_TLS#GnuTLS_ciphersuite has a recommendation for a modern list, with the caveat that gnutls will choke if you list a cipher that isn't implemented.
For server connections, I can see erring on the side of compatibility. For relays, this is far more important, because of /exec.
We could either specify that list as-is and hint that it might not work on every implementation of gnutls, or detect what ciphers in that list the user's gnutls doesn't support and error. I _think_ the latter is already implemented in https://github.com/weechat/weechat/blob/master/src/plugins/relay/relay-config.c#L219 but I'm not familiar enough with gnutls to confirm that.

**Comment by flashcode** [comment]
Hi,

These ciphers have been removed from `NORMAL` priority: `RC4` has been removed in GnuTLS 3.4.0 (released on 2015-04-08) and `3DES-CBC` has been removed in GnuTLS 3.6.0 (released on 2017-08-21).

Thus I close this issue (by the way I'll remove `-VERS-SSL3.0`, which is not needed any more).
