### ISSUE TITLE
Display default values for unchanged server options too

### ISSUE THREAD

**Issue by fourzerofour** [weechat/weechat#629]
Normally to see some server options for a particular server I have to also check values from server_default for unchanged options

	/set irc.server_default.sasl*
	08:22:37     | [server_default] (irc.conf)
	08:22:37     |   irc.server_default.sasl_fail = disconnect  (default: continue)
	08:22:37     |   irc.server_default.sasl_key = ""
	08:22:37     |   irc.server_default.sasl_mechanism = plain
	08:22:37     |   irc.server_default.sasl_password = ""
	08:22:37     |   irc.server_default.sasl_timeout = 15
	08:22:37     |   irc.server_default.sasl_username = ""
	08:22:37     | 
	08:22:37     | 6 options (matching with "irc.server_default.sasl*")
	08:22:42     |

	/set irc.server.freenode.sasl*
	08:22:42     | [server] (irc.conf)
	08:22:42     |   irc.server.freenode.sasl_fail
	08:22:42     |   irc.server.freenode.sasl_key
	08:22:42     |   irc.server.freenode.sasl_mechanism
	08:22:42     |   irc.server.freenode.sasl_password = "${sec.data.freenode}"  (default: (undefined))
	08:22:42     |   irc.server.freenode.sasl_timeout
	08:22:42     |   irc.server.freenode.sasl_username = "${irc.server.freenode.nicks}"  (default: (undefined))
	08:22:42     | 6 options (matching with "irc.server.freenode.sasl*")

It would make things much easier if unchanged options also have their default values from server_default shown

	/set irc.server.freenode.sasl*
	08:22:42     | [server] (irc.conf)
	08:22:42     |   irc.server.freenode.sasl_fail (default: disconnect)
	08:22:42     |   irc.server.freenode.sasl_key (default: (undefined))
	08:22:42     |   irc.server.freenode.sasl_mechanism (default: plain)
	08:22:42     |   irc.server.freenode.sasl_password = "${sec.data.freenode}"  (default: (undefined))
	08:22:42     |   irc.server.freenode.sasl_timeout (default: 15)
	08:22:42     |   irc.server.freenode.sasl_username = "${irc.server.freenode.nicks}"  (default: (undefined))
	08:22:42     | 6 options (matching with "irc.server.freenode.sasl*")

**Comment by flashcode** [comment]
You can see inherited values from "server_default" options with command `/server listfull freenode`.

But I agree this would be nice to see that in `/set` as well (and `/iset` with script iset.pl).
I'll make changes to create link between options and get/display the inherited values when needed (in `/set` and the API, so that other plugins than irc can use such mechanism).
