### ISSUE TITLE
tests: make tests locale independent

### ISSUE THREAD

**Issue by sim642** [weechat/weechat#631]
Currently when I run the tests on my computer I get the following two failures:
```
>>>>>>>>>> TESTS >>>>>>>>>>
......
/home/simmo/weechat/tests/unit/core/test-util.cpp:93: error: Failure in TEST(Util, GetTimeString)
	expected <Sat, 01 Jan 2000 00:00:00>
	but was  <L, 01 jaan  2000 00:00:00>
	difference starts at position 0 at: <          L, 01 jaan>
	                                               ^

...............
/home/simmo/weechat/tests/unit/core/test-string.cpp:1021: error: Failure in TEST(String, FormatSize)
	expected <10.0 KB>
	but was  <10,0 KB>
	difference starts at position 2 at: <        10,0 KB     >
	                                               ^

.............................
.............................
Errors (2 failures, 79 tests, 79 ran, 1922 checks, 0 ignored, 0 filtered out, 3 ms)

<<<<<<<<<< TESTS <<<<<<<<<<
```

Both of these appear to be caused by the locale I use in my system but tests shouldn't depend on the locale.

**Comment by flashcode** [comment]
The tests are supposed to be locale independent, see this code: https://github.com/weechat/weechat/blob/master/tests/tests.cpp#L126

How are you running tests?

**Comment by sim642** [comment]
I saw that code but something about it isn't working I think.

In the build directory I just run `./tests/tests`.

**Comment by sim642** [comment]
Closed by https://github.com/weechat/weechat/commit/415dea5c7483f6b77b1abc69f97043391f77ffec.
