### ISSUE TITLE
Redirected-to channels are opened in a new buffer with buffer_open_before_autojoin on

### ISSUE THREAD

**Issue by ManDay** [weechat/weechat#643]
Version 1.1.1, channels with redirect (e.g. #opengl on Freenode) will leave an empty buffer and open the target channel in a new buffer if irc.look.buffer_open_before_autojoin is ON.

**Comment by wlhlm** [comment]
Does this still happen with version 1.3?

**Comment by flashcode** [comment]
I can confirm this still happens on latest devel version.
