### ISSUE TITLE
Alias on "/" no longer works in 1.4-rc1

### ISSUE THREAD

**Issue by xnrand** [weechat/weechat#646]
After updating to weechat 1.4-rc1 (running on debian jessie, package weechat-devel from debian.weechat.org), aliases on "/" (empty name) no longer work.
Previously, I had aliased just "/" to "/buffer" (which used the config variable `alias.cmd./`). After the update, this alias no longer works and trying to re-add an alias for "/" fails as follows:
```
Output of command: /alias add / buffer:
=!= alias: error creating alias "" => "buffer"
```

**Comment by flashcode** [comment]
Adding such alias with the command `/alias` has never work (I suppose you edited the file by hand or you used `/set`).
Moreover, in 1.4, I fixed a bug with empty command name, now just `/` (without command name) is NOT considered as a command any more: for me it was a bug to run a command which doesn't have a name (so your working alias was the result of a bug!).
Consequently, an alias with just `/` does not work any more (for more info, see commit 57b6e320d3c9d2d9473090eb3881de206c81e52c).

If you really need to run `/buffer` with just `/ somehing`, you could write a trigger that replaces leading `/ ` by `/buffer ` (so for example `/ 5` becomes `/buffer 5`) when the input is sent to the buffer, using the modifier "input_text_for_buffer" (see `/help trigger` and function hook_modifier in plugin API reference for more info).

**Comment by xnrand** [comment]
Oh, right. Sorry, I misremembered that. The command I used to add the alias was `/alias // buffer`.
Doing `/alias // buffer` in 1.4-rc1 still yields `Alias "/" => "/buffer" created` and thus creates an unusable alias.

**Comment by flashcode** [comment]
Then it's probably a bug in alias plugin, such alias name should not be allowed.
