### ISSUE TITLE
Milliseconds in buffer_time_format

### ISSUE THREAD

**Issue by bqv** [weechat/weechat#649]
When I try and use %f in weechat.look.buffer_time_format, it inserts a literal %f. Please implement!

**Comment by flashcode** [comment]
Hi,

Here are my remarks about your suggestion:

1. The option `weechat.look.buffer_time_format` uses `strftime` to format time, and `%f` conversion specifier character seems not supported in strftime (see `man strftime`).

2. The milliseconds are not stored in buffer lines internally, for two reasons:

    * I think such precision is not needed when you have chats on many days/weeks/months (or please give me serious reasons to add milliseconds!).

    * It would use more memory to store that. For example a single integer with milliseconds added to each line, if you have 100 buffers with 4096 lines (the default max lines in buffers), this will use **~6.5MB** extra memory (the int uses 8 bytes on 64-bit processor, and there are two times stored in each line: `100*4096*8*2`).

**Comment by flashcode** [comment]
Finally the support of microseconds in buffer lines has been implemented.

This is done with WeeChat specific modifiers added to those one supported by `strftime`:

- `%.1` to `%.6`: zero-padded microseconds on N digits
- `%f`: alias of `%.6`

The support of microseconds is supported almost everywhere in WeeChat (for example in hooks, or in logger, where you can write microseconds in log files).
