### ISSUE TITLE
Relay-related crash on /upgrade

### ISSUE THREAD

**Issue by scajanus** [weechat/weechat#652]
The crash happened even when running /upgrade on version v1.4-rc2-5-g8e280f8, without touching the binary in-between. It didn't happen every time, but roughly every 3rd/4th time, even when using a new configuration directory (just setting up the relay). The relay client used was WeechatAndroid v0.11-45g7432c3c.

Backtrace:
[gdb3.txt](https://github.com/weechat/weechat/files/84071/gdb3.txt)

/version
12:35 WeeChat 1.4-rc2 (git: v1.4-rc2-5-g8e280f8) [compiled on Jan 10 2016 12:07:32]
/relay list
12:36 Connected clients for relay:
12:36   1/weechat/85.76.17.52 (connected), started on: Sun, 10 Jan 2016 12:33:05

Description:    Ubuntu 14.04.1 LTS

**Comment by flashcode** [comment]
Closing old issue, if ever you still have the problem, please explain the way to reproduce or provide a backtrace with the latest stable version.
