### ISSUE TITLE
cmake fails to generate configuration for perl plugin

### ISSUE THREAD

**Issue by dcunited001** [weechat/weechat#654]
I'm running Linux Min 17 (Ubuntu 14.04) and building from source.  

`./weechat/build $ cmake ..` seems to work fine, but never mentions the perl plugin.  `find \.so | grep perl` on the build folder returns nothing.  I've checked that I have the perl source in the repo and that cmake is getting the default value, `ENABLE_PERL=ON` and it does.  

I've tried blowing away my build folder and reinstalling, as mentioned in #469, but no dice.  I'm just going to install from apt-get, then grab the .so and then move it in manually.

**Comment by dcunited001** [comment]
i'm looking at `FindPerl.cmake` and `cmake` seems to be able to find the `PERL_INCLUDE_PATH`, but not `PERL_LIBRARY`, so maybe there's something messed up with my perl install

**Comment by Mikaela** [comment]
Did you try `sudo apt-get build-dep weechat?` 

Also Linux Mint is not Ubuntu and vice versa.

**Comment by flashcode** [comment]
Did you install Perl with your package manager, in a standard way?

**Comment by flashcode** [comment]
Works for me, so I close the issue.
