### ISSUE TITLE
Allow for flexible filtering/redirecting messages to a buffer

### ISSUE THREAD

**Issue by satmd** [weechat/weechat#66]
I'm trying to collect messages from different sources (several irc bots over different networks) into a single buffer, maybe like this:

<botA> banned user badspammer for ... on ... 
<botB> banned user someidiot for ... on ...

This could be also nice to redirect all services' messages to a single buffer, like server.services collecting all messaged from *@services.server - NickServ, ChanServ, OperServ, ... 

Responding to these messages will probably be easy, because there's no way to address the target.

It'd also be nice if filtering/redirecting messages can be chosen to either duplicate the messages to that buffer or redirect it alltogether.

in bash syntax: "cat sometext > buffer" VS "cat sometext | tee -a buffer"

**Comment by flashcode** [comment]
This is possible with the hook "line" introduced in WeeChat 2.3, and you can create a trigger that can redirect any message (not only IRC) to any buffer.

Documentation:
* API function `hook_line`: https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hook_line
* Trigger of type "line": https://weechat.org/files/doc/devel/weechat_user.en.html#trigger_data_line
