### ISSUE TITLE
Buffer names with unicode characters are cropped at the wrong position when displayed on hotlist

### ISSUE THREAD

**Issue by tomoe-mami** [weechat/weechat#668]
If I set `weechat.look.hotlist_names_length` to non zero value, the name displayed on hotlist for buffers with unicode characters aren't cropped properly.

Screenshot:

![](http://i.imgur.com/xg0IalI.png)

**Comment by flashcode** [comment]
Nice bug, I think it's very old, and nobody noticed it before :)
It needs some refactoring in build of hotlist content, I'll do that very soon.
