### ISSUE TITLE
new alias "edit" and "rename" options

### ISSUE THREAD

**Issue by highflyer77** [weechat/weechat#671]
@FlashCode , as per your instruction of your request #518

> "For the edition of aliases, please open a separate issue."

`/alias` should have an `edit` option. 
That would allow the output to be viewed exactly like it was created and sending it to the input bar, 
so that it could be more easily edited and ready for re-input (trigger has a similar feature), 
but `edit` is a much better more sane option name (much easier for users to remember).

Additionally,  `/alias` could also use a  `rename` option (like `/filter` and `/trigger` has).

**Comment by flashcode** [comment]
If an option `addreplace` is added (see #657), then the `edit` option is not needed.

By the way you can already edit alias, with two ways:

1. `/alias add <name> [TAB]`  (this will complete with the content of the alias)
2. `/set alias.cmd.<name> [TAB]`  (see `/set alias.*`)

And OK for a rename option.

**Comment by highflyer77** [comment]
For me,
\# 1.  does not work, it just dumps the commands into the status bar. It might be the way I have my completion setup, probably, but I don't know?
So, not a solution for everybody.


\# 2.  works but seems "kludgy", I always just used `/iset` to do it, but still "kludgy", compared to just running:
` /alias edit foo`

**Comment by flashcode** [comment]
Hi,
It's possible to edit aliases with `/fset` and the `rename` option as been added in 4.0.0.
So I close this issue.
