### ISSUE TITLE
DCC transfer failed when resizing a terminal emulator window

### ISSUE THREAD

**Issue by hasB4K** [weechat/weechat#677]
Hello,

I have detected a weird issue, it seems that when you resize a terminal emulator window like xterm or urxvt with weechat in it, all DCC transfer that was active, will now be in 'failed' status.

I have reproduced this issues on:

* Linux (Archlinux)
* i3-wm as Windows Manager
* xterm and rxvt-unicode as terminal emulators

Weechat versions concerned:

* WeeChat 1.4 [compiled on Feb  2 2016 09:40:40]
* WeeChat 1.5-dev (git: v1.4-32-g02bcee0) [compiled on Feb  3 2016 17:13:51]

Step to reproduce:

* Launch a DCC transfer to you weechat client
* Change the dimension of your terminal emulator (with or without being in the 'xfer.list' buffer, it seems that it's not related!)

Thank you for your time,
hasB4K

**Comment by flashcode** [comment]
I will make some tests, but I'm surprised that a resize of the terminal can have any impact on a DCC!
Just to be sure, you're using DCC file, not chat?

**Comment by hasB4K** [comment]
Yes I know it's a weird bug, and it took me a while to figuring out...

And yes I'm using DCC file, but it seems that this bug only occur when you receive a file, not when you send one.

* DCC Chat: no issue
* DCC File (send): no apparent issue
* DCC File (receive): Failed when resizing

**Comment by sim642** [comment]
Confirmed receiving bug on 438f2dee3ed16f4f972ca682ffa05e345f35987a.

**Comment by sim642** [comment]
I've narrowed down the exact call which doesn't properly handle the suspected `EINTR` and put in additional checks. My fixes are in PR #680.

**Comment by flashcode** [comment]
Just for info, I found an old commit fixing similar bug with DCC: edd70d463656426d32a40c07cd3ec2f7bf3264dd
