### ISSUE TITLE
Automatically restore default triggers on upgrade

### ISSUE THREAD

**Issue by sim642** [weechat/weechat#679]
#### Problem

Default triggers getting changed has been a problem multiple times now:
1. WeeChat 1.1 - regex format being changed
2. WeeChat 1.5 - addition of NickServ commands to hide

Both of these require manual intervention of the user. Very few users actually read the release notes, thus most end up coming to #weechat with the same issues even a year after 1.1 was released.
#### Proposed solution

To solve this problem, default triggers should automatically be restored when WeeChat is upgraded to minimize user action. The restoration should only happen when the triggers were default before because otherwise we'd end up overwriting users' own customized triggers. There should be no inherent downside to restoring default triggers which the user has not modified, it only saves them trouble.

There is, however, a difficulty in implementing this solution: the upgraded version with its potentially modified default triggers can't anymore know which were the defaults for the previous version. Thus it isn't easily possible to determine, which the user has modified and which not.

**Comment by stfnm** [comment]
I guess this could be related to #19.

**Comment by flashcode** [comment]
I'm not sure this is a good idea to automatically restore triggers on upgrade (and there is same problem with other things in config, like keys).
The default trigger changes are described in release notes, so users can easily restore them by following instructions there.
I prefer manual actions for things that could be destroyed by automatic upgrades.

**Comment by flashcode** [comment]
And for the regex format, there's no upgrade procedure, because it would be complex (it's intentional, and like mentioned aboved, it's described in release notes).

**Comment by sim642** [comment]
> I prefer manual actions for things that could be destroyed by automatic upgrades.

Which is exactly why I said that this should only apply to not-modified default triggers. Nothing gets destroyed as the result (unless for some reason default triggers are made worse than they were, which makes no sense).

**Comment by Mikaela** [comment]
:+1: for automatic updating of default triggers, I have forgotten the 1.5 trigger update entirely when I thought I would remember it.

Alternatively there should at least be warning in the core buffer about default triggers having been changed and how to fix them.

**Comment by sim642** [comment]
> Alternatively there should at least be warning in the core buffer about default triggers having been changed and how to fix them.

I'm not sure how such warning would work though, it might not be possible to know from which version we're upgrading from to know if they changed between the two versions.

**Comment by flashcode** [comment]
Automatic upgrades or even messages on upgrade are not implemented because it would introduce complicated code, for a very minor result (it's not a problem if the user doesn't update the trigger).
I add all manual changes the users must to in release notes, they *must* read them on upgrade.

**Comment by flashcode** [comment]
Hi,

This is not planned to restore default triggers on upgrade (as discussed in this issue).

With WeeChat 4.0.0, there's now a configuration version in config files and automatic upgrade of the file content if ever the new format is incompatible (this is for example the case with new key bindings format in 4.0.0).

So if ever triggers change format in future, the file trigger.conf would be automatically updated (if that's possible).
