### ISSUE TITLE
DCC and ipv6 vs ipv4 (and debugging thereof)

### ISSUE THREAD

**Issue by satmd** [weechat/weechat#68]
The original problem is independent of weechat, but needs consideration within the implementations.

The syntax of DCC CHAT is "DCC CHAT <ip>< port>", with ip and port being chosen by the local client.

DCC CHAT may fail when the IRC server is dual-stack and the local client and the remote target don't use the same IP protocol.

Example: I'm connecting to the IRC server with IPv6, trying to DCC to an IPv4-only target.

The target won't be able to connect to me as it doesn't have a valid IPv6 route.

Unfortunately the local client cannot safely figure out which IP to use in DCC CHAT.

Suggested workaround: Allow the user to specify -4/-6 for /DCC, maybe have a config setting irc.default_server.dcc.protocol with "undefined", "ipv4", "ipv6" - with undefined resembling current behaviour.

PS: It'd probably make sense to also show the LOCALly chosen ip in xfer.list for better debugging.

**Comment by Mikaela** [comment]
Isn't this `xfer.network.own_ip`? It says to accept DNS address and that DNS address is most likely allowed to have both A and AAAA records.
