### ISSUE TITLE
support ncurses 6

### ISSUE THREAD

**Issue by axaith** [weechat/weechat#682]
With ncurses 6 weechat gives me a mostly blank screen

**Comment by flashcode** [comment]
Hi,
Can you please tell me more?
Which version of WeeChat, ncurses (the exact number), your operating system and its version?
And if possible a screenshot of the problem.

**Comment by axaith** [comment]
I compile latest weechat from git.  ncurses 6.0.  gentoo, and recompiled almost everything (i think) after installing ncurses 6.  ncurses 6 caused way more of a headache than i bargained for, i wish i wouldnt have screwed around with it.

my transparent term:

![term](https://cloud.githubusercontent.com/assets/8694499/12865304/31455c08-cc5d-11e5-81e9-b74f1e465d4c.png)

weechat with mostly black screen:

![weechat](https://cloud.githubusercontent.com/assets/8694499/12865308/3b418cae-cc5d-11e5-92c0-a57713e0ba32.png)

**Comment by flashcode** [comment]
Your $TERM is OK (according to your terminal or any multiplexer like screen/tmux)?
A bad value can cause severe display bugs.

**Comment by axaith** [comment]
well, i wonder about the terminfo stuff but i dont know what could be wrong or what one might do to fix it.  i use tmux-256color or screen-256color for TERM usually.  if i try a more basic one like TERM=xterm, weechat displays a little more but still mostly black:

![xterm](https://cloud.githubusercontent.com/assets/8694499/12909790/7189a2ca-ceb9-11e5-8e31-2ee34b98c382.png)

with TERM=xterm-256color there is some transparency but still black where text should be:

![xterm-256color](https://cloud.githubusercontent.com/assets/8694499/12909878/22ded23e-ceba-11e5-8c19-d2f389465cd1.png)

**Comment by flashcode** [comment]
OK, then I'll try myself soon to compile with ncurses 6.

**Comment by cedra** [comment]
Same issue, random letters and characters show up in query windows and input box bugging out sometimes, using ncurses version: 6.0.20150808

![asw](https://cloud.githubusercontent.com/assets/17232623/13033476/f266ec06-d317-11e5-9c47-17d3705983a4.png)

**Comment by flashcode** [comment]
Ncurses 6 is now in Debian unstable (6.0+20160319-1) I tested and everything works fine for me.
Maybe you could check on your gentoo how is compiled ncurses (which options)? It could be different from Debian.

**Comment by lucy** [comment]
Works fine with ncurses 6.0-r1 on gentoo here. Built with `cxx threads unicode -ada -debug -doc -gpm -minimal -profile -static-libs -test -tinfo -trace`.

**Comment by namarrgon** [comment]
I can reproduce it in an msys2 environment with weechat-git 1.4.154.g948d7b3-1.
$TERM doesn't seem to have much effect at all unless e.g. vt400 is used in which case all color is gone.
![weechat](https://cloud.githubusercontent.com/assets/3209906/14470549/6e5d4cd8-00ea-11e6-8f0b-bb2f7500fb5d.png)

**Comment by flashcode** [comment]
Old problem, not reproduced, so I close the issue.
