### ISSUE TITLE
Add an option for changing kick message color

### ISSUE THREAD

**Issue by kiririn** [weechat/weechat#683]
Similar to irc.color.reason_quit

**Comment by sim642** [comment]
Adding a new `irc.color.reason_kick` option would be simple but I think this has to be thought through at a broader scale if more fine-grained coloring is to be added for such things.

Currently all quit related messages use `message_quit` color but only PART and QUIT use `reason_quit` color, others use default color. If `reason_kick` color is to be added, shouldn't there maybe also be `message_kick` color to go with unwillful quiting, e.g. KICK and KILL, messages, not just reasons?

**Comment by sim642** [comment]
I have opened a PR with the changes I described which could be suitable: #684.
