### ISSUE TITLE
Example scripts from documentation giving register error with WeeChat 1.4

### ISSUE THREAD

**Issue by predatorian3** [weechat/weechat#686]
I was trying to write a script for WeeChat to load, so I copied and pased the ones from the [WeeChat Scripting](https://weechat.org/files/doc/stable/weechat_scripting.en.html#register_function), and when I attempt to call the fuction such as 
```
/ruby test_ruby
```
I get the following error without much information
```
=!= | Error with command "/ruby test_ruby" (help on command: /help ruby)
```
Then when I issue the command
```
/ruby load test_ruby.rb
```
I get the following errors with a bit more detail, but not much in order to troubleshoot. 
```
    | ruby: loading script "/home/predatorian/.weechat/ruby/autoload/test_ruby.rb"
=!= | ruby: unable to register script "test_ruby" (another script already exists with this name)
    | Hello, from ruby script!
=!= | ruby: function "register" not found (or failed) in file "/home/predatorian/.weechat/ruby/autoload/test_ruby.rb"
```
The script being tested contains the following code.
```
def weechat_init
  Weechat.register("test_ruby", "FlashCode", "1.0", "GPL3", "Test script", "", "")
  Weechat.print("", "Hello, from ruby script!")
  return Weechat::WEECHAT_RC_OK
end
```
I'm using MRI 2.2.3 on ArchLinux using rbenv. This same error also happens for Python as far as I've tested using the scripts provided, being copied and pasted. I also made sure to land the script in `~./weechat/ruby/` then `ln -s` the script to the autoload directory.

**Comment by flashcode** [comment]
It's better to use `/script` command, which is generic for all languages.
The first error is caused by an invalid syntax (`/ruby name` is not valid, but `/ruby load name.rb` is valid).
The second error means the script is already loaded: if you have put it in autoload directory (which is not mandatory), it will be automatically loaded on startup (so no need of `/ruby load ...` or `/script load ...`).
So for me there's no problem here.

**Comment by predatorian3** [comment]
Why would I get the `ruby: function "register" not found (or failed) in file` error when I use both `/script` or `/ruby`, and I'm copying the example directly from the docs?

**Comment by flashcode** [comment]
The error `ruby: unable to register script "test_ruby" (another script already exists with this name)` means you are trying to load the same script twice, which is not allowed (you must unload/load it, or reload it).
And I don't see any `/ruby test_ruby` in the scripting guide, there's only this example: `/ruby load script.rb`, which is working fine.
If there is something wrong in the scripting guide, please give me the exact line in the source file (in `/doc/en/weechat_scripting.en.asciidoc`).

**Comment by predatorian3** [comment]
I was copying out of the https://weechat.org/files/doc/stable/weechat_scripting.en.html#register_function examples. I'll try not having them autoloaded, and then loading the plugins. Thanks for your help @flashcode !

**Comment by predatorian3** [comment]
I unloaded the script, removed it from the `~/.weechat/ruby/autoload/` directory. However, This is what I get when I issue the `load` command.
```
[user01 (Zi)] /ruby load test_ruby.rb
11:02:06   weechat     | ruby: loading script "/home/predatorian/.weechat/ruby/autoload/test_ruby.rb"
11:02:06   weechat     | ruby: registered script "test_ruby", version 1.0 (Test script)
11:02:06   weechat     | Hello, from ruby script!
[user01 (Zi)] /ruby test_ruby
11:02:16   weechat =!= | Error with command "/ruby test_ruby" (help on command: /help ruby)
[user01 (Zi)] /script test_ruby
11:02:24   weechat =!= | Error with command "/script test_ruby" (help on command: /help script)
```

**Comment by flashcode** [comment]
The commands `/ruby test_ruby` or `/script test_ruby` are **NOT** valid commands (and I have no idea where you found such commands).
You can check `/help ruby` and `/help script` for help and examples.

**Comment by predatorian3** [comment]
I understand now what is going on. Since these scripts being loaded don't have an action actually attached to them like listening for a certain command, or phrase in a chat room, then its just loading nothing, and printing the hello world on load. Thus why none of that worked. My apologies, I'll go back to working on making my own scripts for it now. Thank you @flashcode !
