### ISSUE TITLE
Multi-line input bar problem with OFTC

### ISSUE THREAD

**Issue by verdurin** [weechat/weechat#695]
I'm trying to run a nickserv command on OFTC, as I would do on Freenode. However, as soon as the text in the input bar needs to wrap, a strange string appears:

```
$1$.*+
```

and sending the command fails.

This is with version 1.3 on Fedora 22.

**Comment by flashcode** [comment]
This is probably caused by an old trigger format (used in version 1.0 only, format has changed in 1.1+).
See the release notes (version 1.1) for more info: https://weechat.org/files/releasenotes/ReleaseNotes-devel.html

**Comment by verdurin** [comment]
Yes, I found upgrading to 1.4 fixed this, in any case. Thanks for the explanation.
