### ISSUE TITLE
escaping commands does not work.. for example: //nick test

### ISSUE THREAD

**Issue by shibumi** [weechat/weechat#699]
Hello Guys,
In the past when I did `//nick test` the sentence `/nick test` was printed to the current channel. This way was perfect for showing IRC beginners some commands.. 

I am running weechat in version 1.4 now and this is not working anymore.
When I try `//nick test` now my nickname will be changed **and** i will paste the sentence `/nick test` to the channel.. 

I think it has something todo with the weechat relay. I am connected to an IRC relay (running on a weechat same version) with my client (also a weechat version 1.4). 

Seems like the weechat IRC relay is executing the escaped command because the client is sending the escaped command to the relay and the relay thinks the command is valid..

I am not sure if this is a a bug or a feature.

**Comment by flashcode** [comment]
Hmm you're right, the commands from irc relay client are executed on server, which is not good :/
The problem is new in 1.4?

**Comment by shibumi** [comment]
@flashcode 
I haven't tested this behaviour in version <1.4. I also tried to execute other commands like changing settings of the relay via the client but this is not working. It seems like only IRC commands are effected.

**Comment by flashcode** [comment]
According to my tests this is not a new problem, it was at least in 1.3 and I think older releases.
I'll fix that very soon.
