### ISSUE TITLE
Use info:term_width instead of window.win_width in bar conditions help text

### ISSUE THREAD

**Issue by Petzku** [weechat/weechat#703]
The help for option `weechat.bar.*.conditions` gives the following example for hiding nicklist on smaller terminals: `${nicklist} && ${window.win_width} > 100`

While this works most of the time, as the `window.win_width` property doesn't account for bars like the nicklist, certain term widths (in this case, between 101 and 110-ish) will result in a feedback loop of sorts, where the nicklist shows and hides (because win_width goes above and below 100).

The "correct" solution is to use `info:term_width` instead, as it only depends on the size of the full terminal window WeeChat is running in. Example: `weechat.bar.nicklist.conditions = "${nicklist} && ${info:term_width} > 100"`

**Comment by flashcode** [comment]
Thanks for reporting the problem, it is fixed.
