### ISSUE TITLE
gui: mouse scrolling outside of mouse mode should be equivalent to up/down arrow key

### ISSUE THREAD

**Issue by sim642** [weechat/weechat#711]
When using mouse scrolling outside of mouse mode, weechat scrolls the equivalent of 7 (at least for me) respective arrow key presses. This is somewhat unintuitive because other command line programs such as bash can detect such scrolling behavior for scrolling between input history without having to take control of mouse handling in the terminal. Similar detection of quickly sent arrow key presses could be also in weechat to have special handling not to equate to multiple presses for a single scroll tick.

**Comment by flashcode** [comment]
When mouse is disabled, WeeChat does not receive anything as key code (or mouse code).
So the 7 lines are not handled at all by WeeChat, and I have no idea how to customize that inside WeeChat.
It's maybe a terminal or X setting.

**Comment by sim642** [comment]
They aren't received as a different key code but as a sequence of some. For example when I do `alt+k` and then scroll up by one tick it prints `meta2-Ameta2-Ameta2-Ameta2-Ameta2-Ameta2-Ameta2-A`. Weechat even detects them all as one sequence so it should be possible to have special handling for it as well.

**Comment by flashcode** [comment]
So I suppose this is with mouse enabled in WeeChat. When mouse is not enabled, I can't see any code received in WeeChat (which is normal).
If that's the case, I suppose it's because your terminal or something is setup to send keys to apps. Could you please tell me how to configure so I can test?

**Comment by sim642** [comment]
I run WeeChat in `screen` and use it with `xfce4-terminal`.

After some more testing it seems that the behavior is somewhat unpredictable. I'm not sure when it changes from attempting to scroll the terminal to sending the scroll as arrow keys but under some condition it seems to.
