### ISSUE TITLE
Repo uses weak digest algorithm (SHA1)

### ISSUE THREAD

**Issue by hinderaker** [weechat/weechat#721]
With the new Ubuntu 16.04 Xenial I am getting the follow warning with every  "apt-get update".

W: https://weechat.org/ubuntu/dists/xenial/InRelease: Signature by key 11E9DE8848F2B65222AA75B8D1820DB22A11534E uses weak digest algorithm (SHA1)

**Comment by flashcode** [comment]
Hmm yes I saw this problem too, I'm going to fix that.
By the way, this is not a WeeChat bug, but a problem on weechat.org (which has its own repository on github).

**Comment by flashcode** [comment]
It should be fixed (I used gpg instead of gpg2 to sign the Release file).
