### ISSUE TITLE
Does not reconnect on timeout after detach of screen

### ISSUE THREAD

**Issue by Zarthus** [weechat/weechat#723]
When weechat times out it only reconnects as I re-enter the screen session, it seems like it doesn't properly recognize a disconnect until the screen session is restored with `screen -r`

```
(17:45:08) * Elysia (Zarthus@trivialand/guesser/zarthus) Quit (Ping timeout: 276 seconds)
(18:08:39) * Elysia (Zarthus@trivialand/guesser/zarthus) has joined #weechat
```

```
irc: reading data on socket: error -54 Error in the pull function.
```

The reconnection is when I reattached to screen. CTRL+A+D to detach, `screen -r` to reattach, `screen -dmS weechat weechat` to start. Not specific to a version (currently running 1.5RC1, but it's been happening for longer), debian 8 jessie 

Perhaps https://savannah.nongnu.org/bugs/?36851 is related.

**Comment by flashcode** [comment]
Hi,
Can you try to connect to the server without SSL? To check if it's a bug with gnutls lib, or something else.
And what's your version of screen and gnutls?
You can also try with tmux instead of screen (but anyway weechat with SSL in screen should just work fine).

**Comment by Zarthus** [comment]
Screen version 4.02.01 (GNU) 28-Apr-14
OpenSSL 1.0.1k 8 Jan 2015

I connect without SSL to QuakeNet but my logs there seem to be OK when grepping except for this one occasion (which means the issue may be inconsistent, I can't quite grep if those were times I reattached to screen - it's a bit of a goose chase and not reliable information; but it might help):

```
 % grep 'disconnect' irc.server.quakenet.weechatlog -A 5                                             .weechat/logs lunar
2016-01-01 21:15:52     --      irc: disconnecting from server...
2016-01-01 21:15:52     --      irc: disconnected from server
2016-01-01 21:15:52     --      irc: reconnecting to server in 10 seconds
2016-01-01 21:27:05     --      irc: connecting to server irc.quakenet.org/6667...
2016-01-01 21:27:05     --      irc: connected to irc.quakenet.org/6667 (91.217.189.21)
2016-01-01 21:27:05     --      *** Looking up your hostname
2016-01-01 21:27:05     --      *** Checking Ident
--
```

I'm currently trying a tmux session, but if anything else comes up I'll let you know.

**Comment by flashcode** [comment]
And your GnuTLS version? (WeeChat does not use OpenSSL at all)

Your log is weird, it says reconnection in 10 seconds, but the reconnection really  happened 12 minutes after!

**Comment by Zarthus** [comment]
```
 Libs:
   core:
     ncurses: 5.9 (patch 20140913)
     gcrypt: 1.6.3
     gnutls: 3.3.8
     curl: 7.38.0
     zlib: 1.2.8
   aspell: aspell 0.60.7-20110707
   guile: 2.0.11
   python: 2.7.9
   tcl: 8.6
   ruby: 2.1.5
   perl: 5.20.2
   lua: Lua 5.1
```

**Comment by flashcode** [comment]
I did not reproduce the problem, closing the issue.
