### ISSUE TITLE
A comma (,) can't be used in the weechat relay password

### ISSUE THREAD

**Issue by irth** [weechat/weechat#730]
Syntax for the init command used at the beginning of the relay connection is using a comma as an option separator, and there is no way to escape it so that it could be used in a password.

If I set my password to `foo,bar` and start the connection, clients send the command 
```init password=foo,bar,compression=zlib```
I suspect that weechat sees those options as `password=foo`, `bar`, and `compression=zlib` 
and thinks that the password is `foo`, which then it compares to the `relay.network.password` setting (which is equal to `foo,bar`) and rejects the password.

**Version:** `WeeChat 1.4 [compiled on Jan 10 2016 10:45:47]`
**OS:** `Linux Debian Jessie`
**Steps to reproduce:**
* Set relay password to one containing a comma (,)
* Try to connect from a Weechat Relay client, it fails with "Wrong password"

I tested it with Weechat Android and Glowing Bear.
**Logs:** (from `/relay raw`)
**Weechat Android:**
```
09:53 --> [1] weechat init password=foo,bar,compression=zlib
09:53 --> [1] weechat (checklogin) info version
(After that it disconnects and shows "Wrong password")
```

**Glowing Bear:**
```
(HTTP headers etc...)
10:19 --> [1] weechat (1) init compression=zlib,password=foo,test
10:19 --> [1] weechat (2) info version
(Error: wrong password)
```

**Comment by flashcode** [comment]
Yes since the comma is used as a separator, this can not be used in password; this is not a major issue in my opinion.
I could introduce a more complex syntax to support commas in passwords, but I'm not sure this is really needed.

**Comment by sim642** [comment]
@irth's original idea was to use `string_split_command` which allows escaping delimiters, It differs from `string_split` in numerous ways though and also lead to the discovery of #731.
