### ISSUE TITLE
Support relay listening on AF_LOCAL (AF_UNIX) sockets

### ISSUE THREAD

**Issue by nomis** [weechat/weechat#733]
Local sockets exist as files with normal permissions, so it would be possible to listen on a socket that only the user has access to. There'd be no need for multiple users to agree on listening ports or for a relay password.

SSH now has support for Unix socket forwarding, so it would be possible to have a client connect to weechat via SSH with no additional passwords.

**Comment by ilmaisin** [comment]
Could this feature also be documented?

**Comment by flashcode** [comment]
@ilmaisin: it is documented: https://weechat.org/files/doc/stable/weechat_user.en.html#relay_unix_socket.
