### ISSUE TITLE
Relay plugin password is empty by default

### ISSUE THREAD

**Issue by codedust** [weechat/weechat#735]
When `relay.network.password` is set to `""` (empty) it should not be possible to connect.

**Comment by flashcode** [comment]
Currently allowing an empty password (ie no password on connection) is a feature, not a bug. It could be used for example locally on a computer, or for tests. On the other hand, no connection on the relay is possible until you manually add a relay (type weechat or irc).

The user's guide mentions that the password is "highly recommended", but not mandatory: https://weechat.org/files/doc/devel/weechat_user.en.html#relay_password

I'm not against making it mandatory, if everybody is OK with that.

**Comment by Mikaela** [comment]
Not OK with making it mandatory. In addition to local testing, someone could have VPS or another host only on their use and WeeChat relay being only accessible from localhost or SSH tunnel in which case password would be just unnecressary complexion.

**Comment by Mikaela** [comment]
Maybe separate option for requiring password defaulting to yes?

**Comment by bendem** [comment]
I only use relay at home to access my laptop from my tablet so I don't use a password. I don't mind adding one if it becomes mandatory though.

**Comment by talisein** [comment]
If relay.network.bind_address is 127.0.0.1 then no password is fine. But otherwise there really should be a password IMHO.

**Comment by codedust** [comment]
I really like @Mikaela's idea to provide an option to allow empty passwords. Maybe something like `relay.network.allow_empty_password` which defaults to `off`. When setting up a relay, atm there is no authentication at all which can be a huge security/privacy issue.

**Comment by codedust** [comment]
:+1: Thanks! :tada:
