### ISSUE TITLE
st compatibility and del key

### ISSUE THREAD

**Issue by raedah** [weechat/weechat#736]
The purpose of this issue is to determine what is implementing the behavior that causes the DEL key not to work, and to find out if there is a proper way to implement a fix. The "problem" does not seem to be in st, but it does not seem to be in weechat either. It maybe in ncurses, terminfo, infocmp, or?

DEL key doesnt work in weechat when using 'st', the simple terminal from the suckless project. Weechat is probably not the only project effected. Could be other ncurses apps as well that use keypad mode. Suckless devs are not going to fix it because it seems to be a bad legacy behavior in xterm/urxvt.

http://st.suckless.org/patches/delkey
http://st.suckless.org/patches/st-0.6-delkey.diff
http://git.suckless.org/st/tree/FAQ

Here are some command line tests in zsh which show the behavior.
---st---
% echo "$terminfo[dch1]" | cat -v
^[[P
% echo "$terminfo[kdch1]" | cat -v
^[[3~
% cat <(printf "$terminfo[smkx]"; cat -v)
^[[3~
% cat <(printf "$terminfo[rmkx]"; cat -v)
^[[P

---urxvt---
% echo "$terminfo[dch1]" | cat -v
^[[P
% echo "$terminfo[kdch1]" | cat -v
^[[3~
% cat <(printf "$terminfo[smkx]"; cat -v)
^[[3~
% cat <(printf "$terminfo[rmkx]"; cat -v)
^[[3~

**Comment by flashcode** [comment]
Hi,

I'm not sure if it could easily be fixed in WeeChat.

With WeeChat ≥ 4.0.0, you can see the raw codes with `/debug key`:

```
# press Del
debug: "^[[P" -> meta-[P -> f1 -> "/bar scroll buflist * -100%"

# press F1
debug: "^[OP" -> meta-OP -> f1 -> "/bar scroll buflist * -100%"
```

Then you can see pressing Del and F1 results in the same action (scroll of buflist one page up).

So if you bind the raw code `meta-[P`, it works:

```
/key bind meta-[P /input delete_next_char
```
