### ISSUE TITLE
Reporting crash, per WeeChat request (happened at /quit)

### ISSUE THREAD

**Issue by sandebert** [weechat/weechat#744]
This happened immediately after me doing a `/quit`. The reason to why I was doing that was because I found WeeChat wasn't really communicating with the outside servers anymore and I wanted to restart it. (The UI was still responsive though.) And the reason to why it stopped communicating was most likely to me putting my computer to sleep, changing networks, waking up, and doing that two or three times. 

Let me know if the crash dump is needed.

    *** Very bad! WeeChat is crashing (SIGSEGV received)
    *** Full crash dump was saved to /home/ricksanchez/.weechat/weechat_crash_20160603_3852.log file.
    ***
    *** Please help WeeChat developers to fix this bug:
    ***   1. If you have a core file, please run:  gdb /path/to/weechat core
    ***      then issue command: "bt full" and send result to developers
    ***      (see user's guide for more info about report of crashes).
    ***   2. Otherwise send backtrace (below), only if it is a complete trace.
    ***      Keep the crash log file, just in case developers ask you some info
    ***      (be careful, private info like passwords may be in this file).

    ======= WeeChat backtrace =======
    (written by WeeChat 1.0.1, compiled on Sep 28 2014 15:54:55)
    001  ??:? [function weechat_backtrace]
    002  ??:? [function debug_sigsegv]
    003  ??:? [function __restore_rt]
    addr2line: '0x1a58db': No such file
    addr2line: '0x1a591c': No such file
    addr2line: '0x9341': No such file
    addr2line: '0xb0a6': No such file
    008  ??:? [function gui_buffer_close]
    addr2line: '0x2775b': No such file
    addr2line: '0x1da87': No such file
    addr2line: '0x176e6c': No such file
    addr2line: '0x17727d': No such file
    addr2line: '0x17727d': No such file
    addr2line: '0x1ea190': No such file
    addr2line: '0x177171': No such file
    addr2line: '0x1ea190': No such file
    addr2line: '0x13932c': No such file
    addr2line: '0x141be3': No such file
    addr2line: '0x142be1': No such file
    addr2line: '0x96ac': No such file
    addr2line: '0x990f': No such file
    addr2line: '0x9975': No such file
    addr2line: '0x257ce': No such file
    addr2line: '0xa0d4': No such file
    025  ??:? [function plugin_unload]
    026  ??:? [function plugin_unload_all]
    027  ??:? [function plugin_end]
    028  ??:? [function weechat_end]
    029  ??:? [function main]
    030  ??:? [function __libc_start_main]
    031  ??:? [function _start]
    ======= End of  backtrace =======
    Aborted

**Comment by flashcode** [comment]
If possible, first upgrade your WeeChat, version 1.0.1 is very old. You can find debian packages for debian/ubuntu on weechat.org if needed.
If you still have a crash on /quit with the latest version, please report the problem with this info: output of bt in gdb (requires a core file, see user's guide), the weechat version, your operating system (and its version).

Thank you.

**Comment by sandebert** [comment]
Ok, updated to latest stable. I'll post a new issue if it happens again. Thanks.
