### ISSUE TITLE
"/buffer set localvar_test abcd" doesn't seem to work

### ISSUE THREAD

**Issue by GLolol** [weechat/weechat#745]
I ran into this while trying to debug weechat/scripts#98. On the WeeChat buffer for example, when I do `/buffer set localvar_test abcd`, the results don't seem to save: `/buffer localvar` simply returns this:

```
00:08 Local variables for buffer "weechat":
00:08   plugin: "core"
00:08   name: "weechat"
```

Running WeeChat 1.5.

**Comment by sim642** [comment]
It doesn't seem to work because the usage is wrong. Correct names for the localvars which do work are described in the plugin API docs: https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_buffer_set.

The following would be the correct way of doing it:
```
/buffer set localvar_set_test abc
```

**Comment by GLolol** [comment]
So... https://github.com/weechat/scripts/blob/master/python/noirccolors.py#L7 is wrong then?

**Comment by GLolol** [comment]
Confirming that `/buffer set localvar_set_noirccolors true` works.
