### ISSUE TITLE
Suspend/resume on SIGTERM/SIGUSR1/...

### ISSUE THREAD

**Issue by lp0** [weechat/weechat#747]
To make it easier to handle a kernel reboot, I'd like to be able to send a signal to weechat to make it suspend its state to disk (like /upgrade but to a file) which will then automatically be used (and deleted) when it next starts to reload the state.

This is better than just showing the most recent log as the IRC smart filter still works. Connections would need to be explicitly closed ready for reconnection.

Suspends should write to a temporary file which is renamed, to avoid partial saved states. To avoid repeated failures if resuming causes weechat to crash or run out of memory, it should unlink the file after opening it but before reading it.

**Comment by flashcode** [comment]
You can save state for a reboot with: `/upgrade -quit`. And after reboot: `weechat --upgrade`.

If you want to do that automatically on a SIGTERM message, you can add a trigger:

    /trigger add sigterm signal "2000|signal_sigterm" "" "" "/upgrade -quit" "ok_eat"

And to restart WeeChat: `weechat --upgrade`.

**Comment by lp0** [comment]
What's the "2000" for?

I've amended it slightly by doing ```/save;/upgrade -yes -quit``` because the list of upgrade steps states that it will not save the config until after it has finished saving all the buffers, which could take a while.

**Comment by flashcode** [comment]
The 2000 is to give high priority to the signal callback, so it is executed before the WeeChat default callback (which quits without `/upgrade`). The "ok_eat" will "eat" the signal so that WeeChat will never receive it.
You don't need to `/save` before, because the `/upgrade` command does that.

**Comment by lp0** [comment]
According to ```/help upgrade``` it doesn't ```/save``` until after the upgrade process is complete. If there is a shutdown in progress (instead of a manual pre-shutdown SIGTERM) the server may power off before the upgrade completes and the config won't be saved.

Is there a list of priorities for the default callbacks?

**Comment by flashcode** [comment]
The save is done **before** upgrading (like if you /quit, before exiting). Look at the steps in /help upgrade: the save is done before either running new binary or before quitting. When you run /upgrade (with or without "-quit" argument), the config is **always** saved before exiting or running new binary.

The priority is just a number, default is 1000 and you can use any number lower (for lower priority) or higher (for higher priority, ie executed first).
See the API doc here: https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#hooks

**Comment by flashcode** [comment]
Oh I understood what you mean about /save in case of power off, then OK you can do it before the /upgrade.

**Comment by lp0** [comment]
It's also necessary to have a trigger on SIGHUP to handle the scenario where the terminal (screen/tmux) is killed.

**Comment by lp0** [comment]
The ```--upgrade``` option works really badly if there was nothing saved to resume.

It doesn't autoconnect and it saves a new layout with no buffers.

**Comment by flashcode** [comment]
Then please open another issue for this problem, I'm closing this one.
