### ISSUE TITLE
Starting with --upgrade when there is nothing to resume (or the resume fails) should start normally

### ISSUE THREAD

**Issue by nomis** [weechat/weechat#748]
If I start weechat with `--upgrade` and there is nothing to resume, it outputs the following error and does nothing else:
`irc: WARNING: some network connections may still be opened and not visible, you should restart WeeChat now (with /quit).`

This is inconvenient because I want to use `--upgrade` on boot and need it to autoconnect as normal if there is nothing to resume. It'll also overwrite the current (empty) layout on `/quit`.

**Comment by mumixam** [comment]
you can try this another user was wanting the same thing
https://gist.github.com/mumixam/752fb9928e56e21390f6eb5e339bc350

**Comment by flashcode** [comment]
Yes it's possible with a wrapper script, but I think it would be nice that weechat itself auto-detects that there are no upgrade files, and in this case performs a "normal startup" (ie like if `--upgrade` was not given on command line).
