### ISSUE TITLE
Setting WEECHAT_PASSPHRASE does not bypass secure prompt if incorrect passphrase is set

### ISSUE THREAD

**Issue by killerrabbit** [weechat/weechat#749]
According to /help secure, just setting WEECHAT_PASSPHRASE should bypass the prompt. Instead, it says the password is incorrect and sits at the prompt waiting for manual input.

Setting WEECHAT_PASSPHRASE to a space should make weechat skip the secure prompt and leave the data encrypted, just like entering a space in the prompt.

**Comment by mumixam** [comment]
you can try this out seems to work for me 3a340b096a951ad25cd177dff756a6cefe33be19

**Comment by flashcode** [comment]
Giving a wrong passphrase in WEECHAT_PASSPHRASE will ask you the passphrase again interactively, like if you typed a wrong passphrase, this is the expected and current behavior.
Currently there's no way to give a space like in the prompt, if you just need that, then I can add that.

**Comment by mumixam** [comment]
after talking to him a month ago on irc i believe he wants a way for weechat to be started by crontab and autoconnect to certain servers and not attempt to decrypt secure.conf until later on where he can manually connect to servers that have encrypted settings

**Comment by tpruzina** [comment]
@mumixam "why didn't he just say so" comes to mind, @flashcode probably doesn't have a crystal ball.
I second yours "nice to have".

**Comment by amerlyq** [comment]
I need passphrase non-interactive bypassing for setup/update, applying whole config through fifo.
```bash
WEECHAT_PASSPHRASE=' ' weechat -a -r '/exec -sh env-subs ./cfg/my.conf | ./run-pipe' -r /quit
```
It allows to keep whole user's configuration inside single file under VCS and update config after each git pull.
Keeping all weechat `*.conf` files under VCS and symlinking them into ~/.weechat isn't very constructive, as you need to diff those files with defaults on each weechat update to retrieve new config options.

**Comment by flashcode** [comment]
No answer since more than 3 years, closing the issue.
