### ISSUE TITLE
Support xorg urgency hint

### ISSUE THREAD

**Issue by manu09** [weechat/weechat#750]
Please support https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html#URGENCY so window managers like i3wm and others can make use of the urgency hint set.

**Comment by wlhlm** [comment]
Remember that weechat is an ncurses (terminal) application and thus there is no 'xorg urgency hint' available in that environment.

Though there is another way in which weechat can notify: by sending the 'bell' character ('\a'). When your terminal emulator receives this character it can choose to set the urgency hint, but that depends on the terminal settings, for example for urxvt you have to set `urxvt*urgentOnBell: true`

BTW, weechat already sends the bell when your nick gets mentioned. So there's not a lot to be done here. You can customize the behaviour with the trigger plugin (`/help trigger`). The weechat command for sending the bell character is `/print -beep`.
