### ISSUE TITLE
Failure to parse PRIVMSG

### ISSUE THREAD

**Issue by jtdaugherty** [weechat/weechat#751]
I'm using Weechat 1.5 with https://github.com/42wim/matterircd 0.7 and received these messages:
```
irc: too few arguments received from IRC server for command "privmsg" (received: 3 arguments, expected: at least 4)
irc: failed to parse command "PRIVMSG" (please report to developers):
:dwest!ysthswine3f8bgqqse38c1pg7c@https://mattermost.galois.com PRIVMSG #questions-and-feedback
```
CC @dwest-galois

**Comment by flashcode** [comment]
Are you sure such PRIVMSG without any message inside is conform to the RFC 2812? I am not sure.
What is supposed to be displayed with such PRIVMSG received? An empty message from user?

**Comment by jtdaugherty** [comment]
@flashcode I don't know the answers to your questions. I have only done what Weechat requested, which was to provide the report here. :) I don't know whether Weechat even printed the whole message, or what the behavior ought to be. It's possible that this is a bug in Matterircd, which is why I provided version info for that in case it's easy for someone here to spot what might be going wrong.

**Comment by flashcode** [comment]
Yes WeeChat displays the whole message, and the expected syntax is: `:nick!user@host PRIVMSG #target message` (where #target can also be a nick name). But the message is mandatory, that's why I'm asking if there's not a bug in the IRC server.

**Comment by jtdaugherty** [comment]
I see. I would not be surprised if the IRC server has a bug; it seems to be a very young project.

**Comment by jtdaugherty** [comment]
That sounds like the more likely problem so I'll close this and follow up with them. Thank you!
