### ISSUE TITLE
auto-rejoin of open buffer channels after auto-reconnect not configurable

### ISSUE THREAD

**Issue by PaulSalden** [weechat/weechat#753]
After an automatic reconnect, channels in open buffers are rejoined automatically. It would be nice to have an option to turn this behavior off. There is already an option _irc.server.xxx.autorejoin_, but that only affects kicks.

**Comment by jansol** [comment]
Some cases where this is useful:
- being on channels which require being identified
- when using a cloak

**Comment by mkoskar** [comment]
This is related to #560.

So we can have:

* `irc.(server_default|<server>).autoreconnect_autojoin` (**on** / **off**) - for #560 
* `irc.(server_default|<server>).autoreconnect_rejoin` (**on** / **off**) - for this issue; that is when auto-reconnecting do / or don't rejoin channels in opened buffers, defaulting to **on**

**Comment by flashcode** [comment]
Issue #560 has been implemented: without any new option, the behavior is now to NOT join channels on automatic reconnection.

I close this issue, if you think an option is still needed, please comment there.
