### ISSUE TITLE
Date is not translated properly when LC_TIME is in a different language

### ISSUE THREAD

**Issue by allan2** [weechat/weechat#754]
Using `%a, %d %b %Y %T` does not properly use the locale format of LC_TIME, resulting in a partial loss in translation.

Example:
`LC_TIME=en_CA.UTF-8 weechat`

> Channel created on Fri, 24 Jun 2016 13:33:08

`LC_TIME=zh_CN.UTF-8 weechat`

> Channel created on 五, 24 6月 2015 13:33:08

So the date is using something like `%a, %d %b %Y %T`

Note:

`LC_TIME=en_CA.UTF-8 weechat`

> Fri Jun 24 13:33:08 EDT 2016

The date elements are almost identical in English (there is no comma after `%a`).

`LC_TIME=zh_CN.UTF-8 weechat`

> 2016年 06月 24日 星期五 13:33:08 EDT

Although the 月 is hardcoded into `%b`, the other essential elements are lost in translation.

Using WeeChat 1.5 on Gentoo

**Comment by sim642** [comment]
That is how locales work: they specify the content of the specific date elements but don't modify the formatting string. The date elements are part of the locale, the formatting string is part of the code which formats the date, i.e. WeeChat.

**Comment by allan2** [comment]
I am aware.

The issue is in the current WeeChat formatting string, `%a, %d %b %Y %T`, works for English but not for other `LANG` or more specifically, `LC_TIME`.

It should take into account the locale by drawing from `locale date_fmt`, i.e. `date +%c`.

Using just `%c` would essentially solve the problem. It would introduce time zone to the date format, but that is trivial to remove.


Posted so you can see the format string differences:

`LC_TIME=zh_CN.UTF-8 locale date_fmt`

> %Y年 %m月 %d日 %A %H:%M:%S %Z

`LC_TIME=en_CA.UTF-8 locale date_fmt`

> %a %b %e %H:%M:%S %Z %Y

**Comment by sim642** [comment]
> It would introduce time zone to the date format, but that is trivial to remove.

Not really.

If you're thinking of removing the last space-separated token from the output with `%c` then we're bound to have another issue where someone comes along and says that in their locale date format string for `%c` does not contain the timezone as the last thing (your `en_CA` example). The whole reason why all the %-codes exist, to allow for fine-tuned control.

**Comment by allan2** [comment]
> If you're thinking of removing the last space-separated token from the output with %c then we're bound to have another issue where someone comes along and says that in their locale date format string for %c does not contain the timezone as the last thing (your en_CA example). The whole reason why all the %-codes exist, to allow for fine-tuned control.

Use a stream editor to remove `%Z`. Would that work?

**Comment by sim642** [comment]
When using `%c` the actual locale-specific date format string isn't exposed to the program but `strftime` itself fills it in and follows it. WeeChat isn't given the opportunity there to modify it prior to use.

**Comment by allan2** [comment]
Nobody said to modify `%c` before use. The issue is that the current date format does not work for translations.
You are the one who suggested `%c`. If you modified it after use, it could be translation-friendly.

**Comment by flashcode** [comment]
I'm not sure to understand exactly your problem.
Could you please tell me: your locale, the string used to format date, the result you have, and the expected result (what you think it should be).

**Comment by allan2** [comment]
Hi, I described the problem in my posts above. Here it is again:

The issue is that the current date string is not locale-sensitive. It works for English but not for some other languages (such as Chinese).

For English, `LC_TIME=en_CA.UTF-8`
Result I have: Channel created on Fri, 24 Jun 2016 13:33:08

For Chinese, `LC_TIME=zh_CN.UTF-8`
Result I have: Channel created on 五, 24 6月 2015 13:33:08
Result I should have: Channel created on 星期五, 2015年 6月 24日 13:33:08

The strings used by weechat presently are `%a, %d %b %Y %T` and `%a, %d %b %Y %T %z` .

**Suggested fix**
Use `%c`, which is locale-sensitive.

Result from `%c`:
English: Fri Jun 24 13:33:08 EDT 2016
Chinese: 2016年 06月 24日 星期五 12:19:34 EDT

If having the timezone everywhere is not an issue, just using `%c` instead of the current strings will be sufficient.
