### ISSUE TITLE
Search start position + stop search at point

### ISSUE THREAD

**Issue by Evropi** [weechat/weechat#76]
If I start a search with `Ctrl`+`r`, it scrolls me to the bottom of the buffer, from where I search. This is not necessarily desirable.

If I stop a search with `Enter` (equivalent to  or `Ctrl`+`m`) or `Ctrl`+`j`, it likewise scrolls me to the bottom of the window. There should be a way to stop a search on the point I was looking for.

Consider this redesign of the search interface:
* `Ctrl`+`r` starts a search from anywhere;
* `Enter` stops a search at a certain point (where the cursor is), like in GNU Emacs
* `Ctrl`+`j` returns to the point from where the search began
 * You could also make a new key to return to the bottom, for the convenience of users who like the current behaviour, but I don't see much of a use case for it given how easy it is to get to the bottom by conventional means.

**Comment by nishansubedi** [comment]
:+1:  i just switched to weechat and this seems highly desirable to me too

**Comment by wowaname** [comment]
Find function is indeed clumsy. +1
