### ISSUE TITLE
Icon for the trayer bar plugin

### ISSUE THREAD

**Issue by jrziviani** [weechat/weechat#763]
Hello,
I wrote a simple weechat plugin to put an icon on my desktop trayer, that icon will change when I get a message. If you guys think it's useful to have on weechat plugin list you can see/review the code at: https://github.com/jrziviani/weechat_trayer_blinkicon

thank you

**Comment by weechatter** [comment]
Its a script not a plugin!

You can upload a new script to https://weechat.org/scripts/add/ or you can use https://github.com/weechat/scripts.

I am going to close this issue
