### ISSUE TITLE
Weechat reports crash on exit

### ISSUE THREAD

**Issue by v4n** [weechat/weechat#769]
After exiting weechat I get `Very bad! WeeChat is crashing (SIGSEGV received)`.
Here is the crash dump: https://gist.github.com/v4n/e5a910808996310bf921b1497e31d5a2

Weechat 1.5 installed with `--with-aspell --with-curl --with-python --with-perl --with-ruby --with-lua --with-guile` on OS X 10.11.6 using default configs.

**Comment by v4n** [comment]
Did a quick test and installing with the flags in this exact order `brew install --with-python --with-perl  --with-lua --with-aspell --with-curl --with-ruby --with-gua` fixes the error.


Installing with only gua `brew install --with-gua` results in the following backtrace on exit:
```
======= WeeChat backtrace =======
(written by WeeChat 1.5, compiled on Aug  4 2016 14:12:18)
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
004  3   ???                                 0x0000000102c75e66 0x0 + 4341587558
005  4   ???                                 0x00007fff688efda8 0x0 + 140734947589544
006  5   ???                                 0x00007fff688f74ff 0x0 + 140734947620095
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
015  14  ???                                 0x0000000000000001 0x0 + 1
======= End of  backtrace =======
```

**Comment by flashcode** [comment]
Hi,
Did you try without guile plugin? There's a known problem with guile on OS X, which crashes on plugin unload (it's a guile issue, not WeeChat).
For more info, see issue #527 and there's a workaround: https://github.com/weechat/weechat/issues/527#issuecomment-184798686.

**Comment by flashcode** [comment]
Closing old issue.
