### ISSUE TITLE
Can't connect using the Windows subsystem for Linux

### ISSUE THREAD

**Issue by wodim** [weechat/weechat#770]
I compiled trunk and when I try to connect all I get is:

```
12:33:38       irc.efnet.org  -- | irc: connecting to server irc.efnet.org/6667...
12:33:38       irc.efnet.org =!= | irc: not enough memory (socketpair)
12:33:38       irc.efnet.org =!= | irc: error: socketpair
12:33:38       irc.efnet.org  -- | irc: reconnecting to server in 10 seconds
```

**Comment by wodim** [comment]
Could fix it by making sure `HOOK_CONNECT_MAX_SOCKETS` is defined, maybe support for `socketpair()` is limited on the Windows subsystem for Linux?

**Comment by flashcode** [comment]
Hi,
Are you testing under Cygwin?
WeeChat is not tested outside Cygwin on Windows, so I'm not sure it can run fine in another environment.

**Comment by wodim** [comment]
No, I am using the Windows subsystem for Linux, released with a recent Windows 10 update. It's sort of a native implementation of Linux inside the Windows kernel.

https://blogs.msdn.microsoft.com/wsl/2016/04/22/windows-subsystem-for-linux-overview/

**Comment by flashcode** [comment]
Ah OK.
I never tested that and I have no Windows 10 to try...

**Comment by Zarthus** [comment]
Can confirm Bash for Windows doesn't work.

**Comment by flashcode** [comment]
Windows 10 installed, I have the same problem, and I'm fixing it.

**Comment by flashcode** [comment]
Feedback is welcome, is connection OK now with this fix?

**Comment by Zarthus** [comment]
I can connect now as well!

**Comment by wodim** [comment]
It works.

**Comment by flashcode** [comment]
The problem is partially fixed, it's working only when the compilation is made on Windows/Ubuntu, because the check on socketpair() function is made at compilation time.
So if you install a binary for ubuntu compiled on Linux, the connection will not work.
Therefore I reopen the issue, another fix is needed.

**Comment by moro3ko** [comment]
please write how to install wechat in Windows subsystem for Linux

**Comment by wodim** [comment]
Compile it like you'd compile it on Linux... I don't remember any big
difference between the two.

**Comment by moro3ko** [comment]
I'm sorry but I can not. I used to use Cygwin. It was easy. According to the instructions, I can do

**Comment by moro3ko** [comment]
apt-get install cygwin installs an older version

**Comment by wodim** [comment]
So what's the error you get?

**Comment by wodim** [comment]
Don't compile as root.

You first need to clone the repository using git. There is also no need to use the -DCMAKE_INSTALL_PREFIX parameter.

**Comment by moro3ko** [comment]
I cloned using git. in the home/moroko/weechat folder

**Comment by wodim** [comment]
Log in as your user, not as root. Then `cd weechat`, then `mkdir build`, then `cd build`, then `cmake ..`

**Comment by moro3ko** [comment]
CMake Error at /usr/share/cmake-2.8/Modules/CMakeDetermineSystem.cmake:177 (file):
  file Internal CMake error when trying to open file:
  /home/moro3ko/weechat/build/CMakeFiles/CMakeOutput.log for writing.
Call Stack (most recent call first):
  CMakeLists.txt:24 (project)


CMake Error: Could not open file for write in copy operation /home/moro3ko/weechat/build/CMakeFiles/2.8.12.2/CMakeSystem.cmake.tmp
CMake Error: : System Error: No such file or directory
CMake Error at /usr/share/cmake-2.8/Modules/CMakeDetermineSystem.cmake:189 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:24 (project)


CMake Error at /usr/share/cmake-2.8/Modules/CMakeDetermineCompilerId.cmake:99 (file):
  file problem creating directory:
  /home/moro3ko/weechat/build/CMakeFiles/2.8.12.2/CompilerIdC
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/CMakeDetermineCompilerId.cmake:39 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/share/cmake-2.8/Modules/CMakeDetermineCCompiler.cmake:131 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:24 (project)


CMake Error at /usr/share/cmake-2.8/Modules/CMakeDetermineCompilerId.cmake:99 (file):
  file problem creating directory:
  /home/moro3ko/weechat/build/CMakeFiles/2.8.12.2/CompilerIdC
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/CMakeDetermineCompilerId.cmake:39 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/share/cmake-2.8/Modules/CMakeDetermineCCompiler.cmake:131 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:24 (project)


CMake Error at /usr/share/cmake-2.8/Modules/CMakeDetermineCompilerId.cmake:99 (file):
  file problem creating directory:
  /home/moro3ko/weechat/build/CMakeFiles/2.8.12.2/CompilerIdC
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/CMakeDetermineCompilerId.cmake:39 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/share/cmake-2.8/Modules/CMakeDetermineCCompiler.cmake:131 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:24 (project)


CMake Error at /usr/share/cmake-2.8/Modules/CMakeDetermineCompilerId.cmake:469 (file):
  file Internal CMake error when trying to open file:
  /home/moro3ko/weechat/build/CMakeFiles/CMakeError.log for writing.
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/CMakeDetermineCompilerId.cmake:48 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)
  /usr/share/cmake-2.8/Modules/CMakeDetermineCCompiler.cmake:131 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:24 (project)


-- The C compiler identification is unknown
CMake Error: Could not open file for write in copy operation /home/moro3ko/weechat/build/CMakeFiles/2.8.12.2/CMakeCCompiler.cmake.tmp
CMake Error: : System Error: No such file or directory
CMake Error at /usr/share/cmake-2.8/Modules/CMakeDetermineCCompiler.cmake:186 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:24 (project)


CMake Error: Could not find cmake module file: /home/moro3ko/weechat/build/CMakeFiles/2.8.12.2/CMakeCCompiler.cmake
-- Check for working C compiler: /usr/bin/cc
CMake Error at /usr/share/cmake-2.8/Modules/CMakeTestCCompiler.cmake:35 (file):
  file Internal CMake error when trying to open file:
  /home/moro3ko/weechat/build/CMakeFiles/CMakeTmp/testCCompiler.c for
  writing.
Call Stack (most recent call first):
  CMakeLists.txt:24 (project)


CMake Error at /usr/share/cmake-2.8/Modules/CMakeTestCCompiler.cmake:47 (try_compile):
  Unknown extension ".c" for file

    /home/moro3ko/weechat/build/CMakeFiles/CMakeTmp/testCCompiler.c

  try_compile() works only for enabled languages.  Currently these are:

    C

  See project() command to enable other languages.
Call Stack (most recent call first):
  CMakeLists.txt:24 (project)


-- Check for working C compiler: /usr/bin/cc -- broken
CMake Error at /usr/share/cmake-2.8/Modules/CMakeTestCCompiler.cmake:58 (file):
  file Internal CMake error when trying to open file:
  /home/moro3ko/weechat/build/CMakeFiles/CMakeError.log for writing.
Call Stack (most recent call first):
  CMakeLists.txt:24 (project)


CMake Error at /usr/share/cmake-2.8/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler "/usr/bin/cc" is not able to compile a simple test program.

  It fails with the following output:





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:24 (project)


-- Configuring incomplete, errors occurred!
CMake Error: Cannot open file for write: /home/moro3ko/weechat/build/CMakeCache.txt.tmp
CMake Error: : System Error: Permission denied
CMake Error: Unable to open cache file for save. /home/moro3ko/weechat/build/CMakeCache.txt
CMake Error: : System Error: Permission denied
moro3ko@DESKTOP:~/weechat/build$ sudo su
root@DESKTOP:/home/moro3ko/weechat/build# cmake ..
-- The C compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Looking for include file langinfo.h
-- Looking for include file langinfo.h - found
-- Looking for include file sys/resource.h
-- Looking for include file sys/resource.h - found
-- Looking for mallinfo
-- Looking for mallinfo - found
-- Looking for eat_newline_glitch
-- Looking for eat_newline_glitch - not found
-- Looking for include file libintl.h
-- Looking for include file libintl.h - found
-- Looking for dgettext
-- Looking for dgettext - found
CMake Error at cmake/FindPackageHandleStandardArgs.cmake:91 (MESSAGE):
  Could NOT find GCRYPT (missing: GCRYPT_LDFLAGS GCRYPT_CFLAGS)
Call Stack (most recent call first):
  cmake/FindPackageHandleStandardArgs.cmake:252 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindGCRYPT.cmake:49 (find_package_handle_standard_args)
  CMakeLists.txt:168 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/moro3ko/weechat/build/CMakeFiles/CMakeOutput.log".
See also "/home/moro3ko/weechat/build/CMakeFiles/CMakeError.log".

**Comment by flashcode** [comment]
You can install weechat 1.6 by adding weechat.org repository (for ubuntu trusty), see instructions on this page: https://weechat.org/download/debian/

**Comment by moro3ko** [comment]
I do not know what version of ubuntu. How to check it?

**Comment by flashcode** [comment]
By default on windows 10, the version is ubuntu trusty.

**Comment by wodim** [comment]
lsb_release -a

**Comment by moro3ko** [comment]
большое спасибо. я это сделал!
