### ISSUE TITLE
Get default realname from userinfo?

### ISSUE THREAD

**Issue by jansol** [weechat/weechat#774]
Some, especially education-related networks have a policy that requires a proper realname. Since weechat currently defaults to an empty string as the realname, new users are at risk of getting kicked out of their channels.

**Comment by flashcode** [comment]
Default option has empty value, but value of `.username` option is sent on connection if `.realname` is empty.

Example with this config (and the system username is "flashcode"):

    irc.server_default.sasl_username  string  ""
    irc.server_default.realname       string  "${username}"

The message sent on connection is:

    <-- server │ USER flashcode 0 * :flashcode

The second "flashcode" is the real name.
