### ISSUE TITLE
mouse support breaks copy/paste in screen

### ISSUE THREAD

**Issue by anarcat** [weechat/weechat#777]
Weechat seriously garbles basic mouse usage in screen. I can't copy-paste in screen windows reliably when weechat is running in a screen. As soon as I exit weechat, the problem goes away.

To reproduce, run: `xterm -e screen -c /dev/null weechat`, then type `control-a c` to open a new shell, then select a part of the prompt with the mouse, and paste it with the middle button. I expected the copy paste to work as usual, but instead, the copied data is pasted with a beep and surrounded by `0~` and `1~`.

Here's a video of the behavior, which should be available for the next week:

https://share.riseup.net/#h7a1kovsQXviDI1u6YVK7A

Note that it is the actual paste that is the problem, not the "copy". When I paste in a _different_ terminal (that is running screen or not), things are fine.

I can reproduce this with:

```
00:19:05 | WeeChat 1.0.1 [compilé le Sep 28 2014 15:54:55]
00:19:27 WeeChat 1.5 [compilé le May 30 2016 21:51:51]
00:24:05     | WeeChat 1.6-dev (git: v1.5-138-g3784cc5) [compiled on Aug 10 2016 00:21:04]
```

I am running Debian Jessie 8.5, which ships screen 4.2.1-3+deb8u1 and xterm 312-2. I can also reproduce with rxvt-unicode and gnome-terminal.

Within screen, the TERM variable is `screen`. Outside, it is whatever is set by the terminal, which varies in my tests: `rxvt-unicode` or `xterm` (and yes, gnome-terminal lies about being `xterm`).

Inside screen, setting TERM to `xterm`, `rxvt-unicode` or `dumb` fixes the problem but then severly garbles the weechat display.

tmux doesn't have the same problem (but has other issues that make me weary of switching).

Disabling mouse support (`/mouse disable` or `/set weechat.look.mouse off`) does not fix the problem.

This is somewhat problematic for me as I use copy-paste and screen quite a lot...

**Comment by anarcat** [comment]
so i was told on IRC this is the famous "bracketed paste mode" which I find quite interesting. i first read about this mode when i read [this disturbing article](http://thejh.net/misc/website-terminal-copy-paste) regarding the dangers of copy-pasting from an untrusted text source.

what is interesting is that even though this is partly designed to keep dangerous stuff from happening when you copy-paste, it doesn't actually work as expected. outside of screen, the above article can inject code in my shell freely.

so then the workaround for my issue is `/set weechat.look.paste_bracketed off`.

i am not sure what is going on here, or what braketed paste is defaulted to "on" on weechat. [this article](http://dev.weechat.org/post/2012/03/10/Bracketed-paste-mode) mentions the introduction of the feature, but doesn't clearly state why it has been implemented.

i am at loss as to where to go from here, to be honest. this confused the heck out of me...

**Comment by flashcode** [comment]
Hi,

This is a known problem of bracketed paste mode with screen (problem is in screen, not WeeChat).
So when running inside screen, I recommend to turn off bracketed paste mode.

I think this problem should be mentioned in docs/FAQ, or maybe bracketed paste mode could be off by default then, since a lot of people is still using screen.

**Comment by anarcat** [comment]
if this was in the FAQ, I wouldn't have opened that issue.

turning bracketed paste off by default also seems like a good idea.

unfortunately, we are kind of stuck with the screen bugs. i have just tried 2 other session managers (tmux and dvtm) and both have their own problems to deal with (tmux needs its own termcap file and dvtm can't deal with backspaces)...

one day, maybe, all this stuff will be cleaned up.

**Comment by d4goxn** [comment]
+1 for putting this in the FAQ, or expanding the section that mentions tmux. Why does no project ever mention "gotchas" upfront? It would save so many people so much troubleshooting...

**Comment by flashcode** [comment]
This has been added in FAQ on Aujust 2016 (commit a92e9608714aea0d135bb95f8c3b9f50800f29ee), so I close this issue.
