### ISSUE TITLE
crashes with '/dcc send <nick> ~/path/file'

### ISSUE THREAD

**Issue by anotheranne** [weechat/weechat#781]
weechat version 1.6-dev
Linux Mint 17.3 Rosa
Toshiba Satellite i5

Was running 1.3 while investigating failed transfers and attempting to make settings in line with Xchat (can transfer files with that). but no success. Then upgraded to version 1.5 stable but problem then worsened to a crash. upgraded to 1.6-dev to find problem of crash persisting.

![screenshot from 2016-08-20 10 19 35](https://cloud.githubusercontent.com/assets/595385/17830875/3d6d9424-66da-11e6-9185-bba0775e2135.png)

Ian

**Comment by flashcode** [comment]
Hi,
Please send a ful backtrace made with gdb, see how to do in the user's guide: https://weechat.org/files/doc/devel/weechat_user.en.html#report_crashes

**Comment by anotheranne** [comment]
here we go:


[trace.txt](https://github.com/weechat/weechat/files/428329/trace.txt)

**Comment by flashcode** [comment]
Can you please tell me the exact WeeChat version used to make this trace? (output of /v in WeeChat)

**Comment by flashcode** [comment]
OK I was able to reproduce the crash, I think it happens when you send a file and that the option xfer.file.auto_accept_nicks is set with your own nick. Is that the case?
Can you try to reset this option and confirm that no crash happens?
I'm fixing that.

**Comment by anotheranne** [comment]
1.6-dev

It was set, not with my nick but another nick on our channel. having reset this option to "" we do not get a crash. Then we are back where we were (no transfer, but a separate issue to this that I must sort).

thanks
Ian

**Comment by flashcode** [comment]
1.6-dev is not enough as version, I would like to know the exact commit you are using, on my WeeChat `/v` gives: `WeeChat 1.6-dev (git: v1.5-171-gc2ea70c)`

**Comment by anotheranne** [comment]
no luck. 

$ weechat -v gives only what I said. I downloaded and installed the dev version from weechat.org site today if that is any guide. 

ian

**Comment by flashcode** [comment]
Try `/v` inside WeeChat, the `-v` on command line does not give the full version (with git head).
If you downloaded today, then it's OK, I'm fixing the bug.

**Comment by anotheranne** [comment]
says compiled 20 Aug 2016 15:04:50
which I would guess is after I had downloaded - 11.32 SAST
