### ISSUE TITLE
/dcc send <file> command from Hexchat machine to Weechat machine fails

### ISSUE THREAD

**Issue by anotheranne** [weechat/weechat#784]
We have an issue with Weechat that is described as follows.

1.  We have our own network running inhouse for staff
2.  All machines use HexChat (easy GUI for them)
3.  One machine down, now replaced with my laptop
4.  /dcc send inksi <file> HexChat from Noza to me HexChat works fine
5.  /dcc send inksi <file> HexChat from Noza to me Weechat does not work

When files are sent from HexChat to HexChat there is a pop-up window for
the sender that shows amongs other things the IP address of the machine
that the files are going to (like 192.168.0.22:6667)

When files are sent from HexChat to Weechat this window then shows the
IP address as 0.0.0.0:0
At this stage this same window shows the file Status as 'waiting'.

Meanwhile at the WeeChat end the xfer window shows 'failed' and also the
0.0.0.0 address as shown here:

*** noza                     "rsync_anyte_199" (irc.fables) (0.0.0.0)                                                                         
*** -->> failed              [                    ]   0%   0 bytes / 93 bytes  (0 bytes/s)     

These are the relevant settings that we have on Weechat:

 [network] (xfer.conf) 
 xfer.network.blocksize = 65536 
 xfer.network.fast_send = on 
 xfer.network.own_ip = "192.168.0.22"  (default: "")
 xfer.network.port_range = "6660-6669"  (default: "")
 xfer.network.speed_limit = 0 
 xfer.network.timeout = 300    

 [file] (xfer.conf)
  xfer.file.auto_accept_files = off
  xfer.file.auto_accept_nicks = "noza"  (default: "")

Probably not relevant, but for the record:
HexChat at receiving end has the following settings:
"Get my address from the IRC server" is not selected
DCC IP address 192.168.0.22
1st DCC send port 6660
Last DCC send port 6669

Maybe relevant, and for the record:
HexChat at sending end has the following settings:
"Get my address from the IRC server" is not selected
DCC IP address 192.168.0.19
1st DCC send port 6660
Last DCC send port 6669

I assume that this cannot be server-related. The whole point of DCC
is in its name (Direct Client to Client ??), right?

I hope this is clear. Where-to now?

best
Ian

**Comment by talisein** [comment]
Are you sure the sending hexchat's dcc ip address is set to 192.168.0.19 ?
If so, in weechat you can use Alt-J Alt-R in the server buffer to see the raw irc message

It should be something like:
:apotter!~apotter@12.145.178.9 PRIVMSG tal__ :\x01DCC SEND blaz 178893342 60328 6\x01

If weechat is showing 0.0.0.0 for the ip address, then presumably hexchat is sending DCC SEND nova 0 60328 93, so lets confirm it

**Comment by anotheranne** [comment]
I confirm that the dcc ip address in Hexchat on the sending machine is set at 192.168.0.19 and also that I find this as the setting in the appropriate configuration file.

Using Alt-J Alt-R
This is what I find.

:noza!~noza@hypatia.fables.co.za PRIVMSG inksi :\x01DCC SEND rsync_anyte 199 0 63 206\x01    

Ian

**Comment by talisein** [comment]
This is a 'Passive DCC' request that Weechat does not yet support.

**Comment by anotheranne** [comment]
Thanks! That made me think. Why would Hexchat primarily support a non-standard protocol without supporting the standard protocol as well? Surely I should be able to initiate a standard protocol dcc send?

If I initiate /dcc send inksi <filename> from the Hexchat input text bar then we have success! I guess we missed that because Weechat is command line oriented and because Hexchat is a GUI environment and we were stuck in those respective grooves.

Next step is to find if the passive mode can be disabled as the default on Hexchat.

Still, filling feature request #487 would be cool.

Thanks for the time and effort.

Ian
