### ISSUE TITLE
Allow users to change the color of status bar time delimiters.

### ISSUE THREAD

**Issue by culb** [weechat/weechat#791]
The other time formats allow changing color of the delimiters but the time delimiters in the status bar can't be changed. This leaves an ununiform appearance.
![weechat_time_delimiter](https://cloud.githubusercontent.com/assets/7145650/18207072/8eebda96-70f7-11e6-98a9-4c6afca7aef7.png)

**Comment by flashcode** [comment]
You can with `/set weechat.look.item_time_format`.

**Comment by culb** [comment]
I've already tried that and it doesn't work. The string set, is what is
shown.

**Comment by flashcode** [comment]
Ah you meant changing the color, sorry, misread.

**Comment by culb** [comment]
Yes. I'd like the times to all have a uniform color. Thank you for
responding.

**Comment by flashcode** [comment]
You can now use colors inside the time format, for example:

    /set weechat.look.item_time_format "%H${color:blue}:${color:default}%M"

**Comment by culb** [comment]
@flashcode, Thank you for the change.
