### ISSUE TITLE
Config files apply instantly, but don't save - this combined behavior is deceptive and unintuitive

### ISSUE THREAD

**Issue by yrmvgh** [weechat/weechat#795]
I've been using weechat for months, so by now I know that I _should_ be saving. Sometimes I even randomly /save when I haven't changed anything, out of paranoia.

Unfortunately, I changed a ton of settings yesterday and lost them in a power outage. It was my "big 2016 revamp" as it were. And now I'm discouraged and likely to just leave weechat settings in a "good enough" state for awhile.

I think the fact that settings take effect immediately, makes it feel like they're already saved. The default behavior could be that whenever you /set something, it automatically /saves! I never have to save anything in my text editor unless I want to upload the file somewhere...

**Comment by weechatter** [comment]
A fast and simple solution is a trigger:

/trigger add save_config_on_set command_run "/set *" "" "" "/wait 1 /mute /save" "ok" "none"

**Comment by flashcode** [comment]
Automatically saving files on each option change is not planned, for 2 reasons:

1. it would make lot of writes on the disk, which is not very efficient
2. not saving allows you to `/reload` (one or more files) to undo the changes made with `/set`.

By the way, options are automatically saved when you quit.

As an alternate solution I could add an option to force saving on each change, but this should not be the default behavior for me.

**Comment by yrmvgh** [comment]
@weechatter If I set it to a long delay, can it "reset itself" and thus execute the /save only once in response to multiple /set actions in a short time?

**Comment by weechatter** [comment]
No. the trigger will be executed on every single /set. the "/wait" in trigger is necessary to wait until the /set command is finished.

**Comment by arza-zara** [comment]
You can save periodically: http://www.weechat.org/files/doc/devel/weechat_user.en.html#trigger_example_config_save
