### ISSUE TITLE
"[:End] of WHO list" in server buffer for Slack IRC bridge

### ISSUE THREAD

**Issue by The-Compiler** [weechat/weechat#796]
When using the IRC bridge of [Slack](https://slack.com/), I see this in my server buffer:

```
[...]
21:04 -- [:End] of WHO list
21:04 -- [:End] of WHO list
21:09 -- [:End] of WHO list
21:09 -- [:End] of WHO list
21:14 -- [:End] of WHO list
21:14 -- [:End] of WHO list
[...]
```

Looking at `/server raw`, it looks like this:

```
21:14 <-- sps WHO #association %cuhsnfdar
[...]
21:14 --> sps :irc.tinyspeck.com 352 the-compiler #association the-compiler localhost irc.tinyspeck.com the-compiler G :0 Florian
[...]
21:14 --> sps :irc.tinyspeck.com 315  #association :End of WHO list
```

I'm guessing the double space between `315` and `#` is the culprit? I'm not 100% sure yet whether it's valid according to the relevant RFCs, but I think it'd be nice if weechat would handle it correctly.

I'm on the current git master (1.6-rc1/20df8b8)

**Comment by The-Compiler** [comment]
Taking another look at [RFC 1459](https://tools.ietf.org/html/rfc1459#section-2.3) I think it's valid:

```
<message>  ::= [':' <prefix> <SPACE> ] <command> <params> <crlf>
<command>  ::= <letter> { <letter> } | <number> <number> <number>
<params>   ::= <SPACE> [ ':' <trailing> | <middle> <params> ]
<SPACE>    ::= ' ' { ' ' }
```

**Comment by flashcode** [comment]
The problem in the 315 message is that the nick "the-compiler" is missing before "#association" (I think that's why there are 2 spaces, but multiple spaces should not be a problem).
So WeeChat is not able to parse message properly, and then the message is displayed in buffer.
I think this 315 message is not valid, to be confirmed. It should be like the 352 where the nick is present.

**Comment by The-Compiler** [comment]
The RFC [says](https://tools.ietf.org/html/rfc1459#section-2.4):

>  The numeric reply must be sent as one message consisting of the sender prefix, the three digit numeric, **and the target of the reply**.

(emphasis mine)

So I guess you're right - should we close this then?

**Comment by The-Compiler** [comment]
Just in case someone else runs into this: `/filter add sps_who irc.server.sps irc_315 of WHO list` at least hides the messages.

**Comment by flashcode** [comment]
Yes I close since for me it's a server issue, not WeeChat.
