### ISSUE TITLE
if you just did a /list or /list -re command, /join could use the findings for tab completion. [enhancement]

### ISSUE THREAD

**Issue by yrmvgh** [weechat/weechat#799]
Convenience feature of low importance obviously, but I think it would be nice! :smile:

**Comment by weechatter** [comment]
i think it does not justify memory usage and effort. especially if you have more than one server.

**Comment by yrmvgh** [comment]
Fair enough. Should I close this or do you folks prefer to?

**Comment by yrmvgh** [comment]
Another, similar idea would be for /join # to be able to tab-complete any channel for which you currently have a weechatlog. For those places that you visit but forget to add to your autojoin, or you visit, leave, then decide you want to find that place again and you can't remember how it's spelled!
