### ISSUE TITLE
/PART: Support just supplying a message.

### ISSUE THREAD

**Issue by Zarthus** [weechat/weechat#803]
I wanted to part an active channel today with a message, but weechat only sends the message if you also send the channel(s), otherwise it just leaves the active channel with no message.

Something like "if argument 1 is not a channel/starts with a CHANTYPES prefix, interpret it as a part message." would be nice.

**Comment by flashcode** [comment]
Hi,

This should already work, I just try `/part something` on a #test channel, and the message is properly sent.
Maybe you were fooled by the server: some server like freenode don't display the part/quit message if you were not enough time in the channel/server (something like some minutes).

To be sure, check in raw messages sent to the server: `/server raw`, you should see that WeeChat sends the PART message.

**Comment by Zarthus** [comment]
Hey flashcode - now that you mention it, you're right.

The channel I tried to part was `+m`, and the ircd prevented my part message from coming through from that reason. I hadn't really considered that `+m` would also stop part reasons.

So you're right - this bug report is invalid and the ircd was preventing it from coming through.
