### ISSUE TITLE
Nick highlighting breaks if $nick2 is a substring of $nick1

### ISSUE THREAD

**Issue by tinyhippw** [weechat/weechat#805]
![screen shot 2016-09-23 at 09 18 50](https://cloud.githubusercontent.com/assets/1158289/18779093/58a90bba-816f-11e6-959e-db44da5f0bf3.png)

**Comment by flashcode** [comment]
I think this is a script issue, and not a WeeChat one.
Please open the issue in the weechat-scripts repository if that's the case (mentioning the script having the problem).
