### ISSUE TITLE
Merge text_item into core

### ISSUE THREAD

**Issue by silversquirl** [weechat/weechat#808]
The text_item.py script is invaluable for developing things such as triggers, aliases and bindings. Having this functionality built in to weechat shouldn't be too difficult to implement (I think) and would allow people to share their triggers, bindings and aliases, knowing that they will work whether or not text_item.py is installed.

**Comment by squigglezworth** [comment]
This would be great. I've found myself creating items like colored_bufname and such, where it would be much easier to be able to use things like {$color:red} inside an items setting

**Comment by weechatter** [comment]
its the concept of weechat, created years ago. lot of color options could be replaced by ${color}. But time is the one key factor.
