### ISSUE TITLE
string_match returns wrong value

### ISSUE THREAD

**Issue by arza-zara** [weechat/weechat#812]
string_match returns 0 incorrectly in the [end](https://github.com/weechat/weechat/blob/master/src/core/wee-string.c#L467) for masks beginning but not ending with an asterisk, for strings containing the mask multiple times.

	/perlexec weechat::print('', weechat::string_match('abaa','*aa',1));
	=> 1
	/perlexec weechat::print('', weechat::string_match('aabaa','*aa',1));
	=> 0

**Comment by flashcode** [comment]
Thanks for the bug report, just in time for release of 1.6!
