### ISSUE TITLE
get data in a trigger from a xfer_ended signal

### ISSUE THREAD

**Issue by michaelkebe** [weechat/weechat#815]
I would like to trigger some commands on xfer completion. Currently there is no way to get e.g. the filename or remote_nick. It is available programmatically via an infolist, but not in a trigger.

**Comment by flashcode** [comment]
I can look for that, but triggers don't aim to fully replace scripts. For some tasks, a script is better than a trigger.

**Comment by michaelkebe** [comment]
I created a script "xfer_run_command" doing exactly this.
So this issue can be closed.

https://weechat.org/files/scripts/pending/xfer_run_command.py
