### ISSUE TITLE
Allow multiple connections to one server

### ISSUE THREAD

**Issue by ItTakesTwo** [weechat/weechat#824]
I use ZNC with a bunch of different networks and with irssi I'm used to open as many connections as I need to the ZNC and login with username/network:(password on clients without my user cert). Weechat only allows **one** simultaneous connection to a saved server and therefore is not suitable for this usecase. Since I use IRC on my workingmachine I cannot simply add more server shortcuts with my login information in them because I don't want our inhouse IT to access them.

Could you please remove this limitation?

**Comment by flashcode** [comment]
Hi,

This is not planned to add multiple connections to one server. It's done like that by design, it's not a "bug".

You can very easily add other servers and share the same credentials using secured data (for example by using `${sec.data.freenode_password}` in options (command, password, ...).

I leeave this issue opened, but it's not planned in near future to change that behavior (this would introduce major changes in irc plugin, and plugins/scripts API).

**Comment by stfnm** [comment]
The `/server copy` command might be useful too.

**Comment by sim642** [comment]
If you exclusively use WeeChat to connect to a single ZNC instance you can configure its connection settings under `irc.server_default.*` options and add new servers without anything extra configured, except for the different `username` to connect to a different ZNC network for the ZNC user, for example. This way you can minimize the duplication required between servers in WeeChat.

**Comment by laymonk** [comment]
I am hitting this limitation too.  

@flashcode , @sim642, please, can you elaborate on your suggested solutions.  An example would help.

**Comment by flashcode** [comment]
@laymonk: in WeeChat you can create as many servers as you want, and they can use same address and username/password.
In WeeChat, there's are default options for all servers (irc.server_default.xxx) and server options which are null automatically inherits from the value in irc.server_default.xxx.

For example if you have:

    irc.server_default.address = "localhost/6667"
    irc.server_default.username = "xxx"
    irc.server.znc1.address = null
    irc.server.znc2.username = null
    irc.server.znc2.address = null
    irc.server.znc2.username = null

Then you can connect two times to znc (address: localhost/6667) with the same username "xxx".

**Comment by flashcode** [comment]
Not planned (by design).
