### ISSUE TITLE
long messages are getting split too vigorously

### ISSUE THREAD

**Issue by oakkitten** [weechat/weechat#828]
when i input `foo barbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarb`, the message gets split into 3 messages (`foo`, `barbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarb` and `ar`), while 2 messages would be more than enough

WeeChat 1.7-dev [compiled on Oct 17 2016, debian jessie

**Comment by flashcode** [comment]
WeeChat takes about "max length" of all fields in the IRC message, so for example the max length for a host (including nick/host and separators) is computed like that :

    max_length_host = 1 + /* ":"  */
        max_length_nick + /* nick */
        1 +               /* "!"  */
        63 +              /* host */
        1;                /* " "  */

So you have at least ~70-75 chars reserved for the host to subtract from the total size (512 bytes - 2 for the \r\n of the end).
This might explain why a long message is split into 2 or 3 messages.

You can check how it's done in source:  https://github.com/weechat/weechat/blob/master/src/plugins/irc/irc-message.c#L962

If you don't agree with some things or think there's a bug somewhere, please let me know.

**Comment by oakkitten** [comment]
i'm just saying that of 3 messages this input produces, one is "foo" and another is "ar". these two definitely can fit into 1 message.

**Comment by flashcode** [comment]
I see.
WeeChat tries to do a "smart" split, ie keep words not truncated (if possible). We can see it's properly done with your example, but your example gives a "non optimal" split.
I would say it's a specific case that would rarely happen (you have rarely one very small word followed by a huge word like that).

**Comment by ahmedelgabri** [comment]
Not sure if this is the same issue, but I have this issue with not too long messages at all

This happens when I try to type `/secure set foo <space>` 
![weechat](https://cloud.githubusercontent.com/assets/63876/20642714/ae27b6b6-b416-11e6-9402-22000162bb85.gif)

Maybe it's a setting or somethings that I'm not aware of, I tried to search a lot for a solution but I kind of failed. So excuse my ignorance.

**Comment by weechatter** [comment]
@ahmedelgabri: /trigger restore cmd_pass

see: https://weechat.org/files/releasenotes/ReleaseNotes-devel.html#v1.1

**Comment by ahmedelgabri** [comment]
Thanks @weechatter

**Comment by flashcode** [comment]
If you have ideas to improve the split, please let me know; for now I close the issue.
By the way in WeeChat 2.1-dev, there's a new server option "split_msg_max_length" to let you control the max length for split of outgoing messages. You could customize that (be careful, if you increase it, some server may don't like that and disconnect you).
