### ISSUE TITLE
Split window cursor tracking cuts off/wraps around early

### ISSUE THREAD

**Issue by miniCruzer** [weechat/weechat#830]
With mouse support obviously you can click which window you'd like to make the active window. On the bottom right window, if you try to click to the right of that vertical green line, it the mouse click actually goes to the opposite side of the screen in the buffers window. 

WeeChat 1.7-dev (git: v1.6-14-gd4a9c48) [compiled on Oct 26 2016 22:54:03]
Running Gentoo Hardened inside of screen.

Output of /window list:
`Windows list:
 [1] (23:49;147x28)
 [2] (23:0;295x19)
 [3] (171:20;147x57)
 [4] (23:20;147x28)
`

![WeeChat Screenshot](https://stole-my.bike/weechat.png)

**Comment by flashcode** [comment]
Some terminals don't support high mouse coordinates (because they don't send UTF-8 for mouse codes).
See this question in FAQ to check if that's your problem: https://weechat.org/files/doc/weechat_faq.en.html#mouse_coords
