### ISSUE TITLE
Nicks charset decode problem

### ISSUE THREAD

**Issue by factor-lg** [weechat/weechat#832]
In version 1.0.1 all OK.
Problem in 1.4 stable version gentoo, and also i compiled new 1.7 devel version from site.
When i am join channel all nicks are all right, but after cyrillic nick rejoin channel there are two nick in userlist, old and new "???????", while i am not rejoin. There are always "?????" in timestamp region.
The very text messages converted properly. Codepage CP1251 in irc and UTF-8 in my terminal.
Screenshot:
![weechat](https://cloud.githubusercontent.com/assets/23150253/19836781/2f0b1ac2-9ebc-11e6-9cea-12e62ace4d80.png)

P.S. Sorry for my English =)

**Comment by flashcode** [comment]
Hi,
Can you try with: `/set irc.network.channel_encode on` ?

**Comment by factor-lg** [comment]
Hi, I tried it already, and i tried to configure weechat from a client after clearing all config files. And i also try this option after clearing config. But nothing changes.

**Comment by flashcode** [comment]
What's your charset config, is it default one? (output of `/set charset.*`)
And your terminal charset? (output of `/charset`)

**Comment by factor-lg** [comment]
/set charset.*
```
| [default] (charset.conf)
|   charset.default.decode = "cp1251"  (default: "iso-8859-1")
|   charset.default.encode = "cp1251"  (default: "")
```
and /charset
```
| 2 options (matching with "charset.*")
| charset: terminal: UTF-8, internal: UTF-8

```

**Comment by flashcode** [comment]
Can you please try with version 1.1 (and higher if it works with this one)?
If I know the version introducing the problem, I'll check what was changed in this version about IRC message decoding.

**Comment by factor-lg** [comment]
OK, I try now.

**Comment by factor-lg** [comment]
Version to which the problem begins is 1.3.

**Comment by flashcode** [comment]
So I think this is related to the fix for issues #218 and #451.
Now the channels are optionally decoded/encoded but not the nicks.

**Comment by factor-lg** [comment]
No fix yet? Soon 3 years will pass =)

**Comment by flashcode** [comment]
@sandikata: thanks for the screenshots.
You told me the problem was in the nicklist (the bar on the right with list of nicks), but I see no problems there, is that right?
I see problems only in chat area, when a nick is joining a channel, is that the only problem?
Also I see you are using a script to colorize lines, could you please try without this script, to be sure the problem is present in a WeeChat instance without any script loaded?
Last question, do you please have a server and channel to join so I can see this problem myself?
Thanks.

**Comment by sandikata** [comment]
I meant nicks in chat area.
server irc,chatbg.info/6697 (ssl)

**Comment by sandikata** [comment]
As well, without any colorize scripts has no change.
After work, i could try another think, with empty weechat dir.

**Comment by weechatter** [comment]
iirc colorize_lines ignores join/part/quit messages

**Comment by factor-lg** [comment]
I can not compile the current version
`/usr/src/weechat/weechat/build/CMakeFiles/CMakeTmp/src.c: In function ‘main’:
/usr/src/weechat/weechat/build/CMakeFiles/CMakeTmp/src.c:9:17: error: passing argument 2 of ‘iconv’ from incompatible pointer type [-Werror=incompatible-pointer-types]
     iconv(conv, &in, &ilen, &out, &olen);
                 ^~~
In file included from /usr/src/weechat/weechat/build/CMakeFiles/CMakeTmp/src.c:2:
/usr/include/iconv.h:42:54: note: expected ‘char ** restrict’ but argument is of type ‘const char **’
 extern size_t iconv (iconv_t __cd, char **__restrict __inbuf,
                                    ~~~~~~~~~~~~~~~~~~^~~~~~~
cc1: all warnings being treated as errors
gmake[1]: *** [CMakeFiles/cmTC_17610.dir/build.make:66: CMakeFiles/cmTC_17610.dir/src.c.o] Error 1
gmake[1]: Leaving directory '/usr/src/weechat/weechat/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:121: cmTC_17610/fast] Error 2

Source file was:

  #include <iconv.h>
  int main(){
    iconv_t conv = 0;
    const char* in = 0;
    size_t ilen = 0;
    char* out = 0;
    size_t olen = 0;
    iconv(conv, &in, &ilen, &out, &olen);
    return 0;
  }
`

**Comment by flashcode** [comment]
@factor-lg: if you have a compilation issue (not related to this issue), please open a separate issue, mentioning the exact version causing problems, and the last one which worked for you.

**Comment by factor-lg** [comment]
Sorry, I got lost. Two days ago I setup it to check, but today I decided to update it.
And there were problems with the list of users, only screenshots I will not do now.
The problem shows itself when changing the nickname. I changed from latin to cyrillic, and then I could not change the nickname back, it seemed to change, but in the chat messages were still from cyrillic nick and from the list of users, he did not disappear. And the nickname "????????" appeared.

**Comment by factor-lg** [comment]
I was able to compile, and now I showing screenshots.
[https://ibb.co/album/d1EnFa](https://ibb.co/album/d1EnFa)
In userlist "С" and "?" - it's after my join to server with cyrillic nickname. And i can change nickname to latin (/nick), but nick "C" remains in the userlist ("?" disappeared), but only in weechat. For other users he's disappeared.
After that, when I change nickname to cyrillic with command  /nick, it is changed also in "С" (or other symbol). Then, i can't see other changes for my nick, but other users see normal if i change nick to latin.

**Comment by flashcode** [comment]
Please try the latest version and tell me if it's better. I tried on the #bulgaria channel, and the problem is fixed for me (with default config).

**Comment by sandikata** [comment]
I could test tomorrow. Thanks.

**Comment by sandikata** [comment]
It seems to work properly now. If there is issue,i will reopen this issue.
