### ISSUE TITLE
ipv6 socks proxy connectivity

### ISSUE THREAD

**Issue by mumixam** [weechat/weechat#836]
Reported by #weechat irc user 'theworst'
```
Hi, weechat doesn't seem to support IPv6 SOCKS5 proxies. I used the latest stable version (1.6). I configured tor to listen on ::1 and 9050 port by adding this line to the config:
"SocksPort [::1]:9050 NoIPv4Traffic IPv6Traffic"
Then added to weechat the following lines:
"/proxy add myproxy socks5 ::1 9050"
"/proxy set myproxy ipv6 on"
Of course my actual tor config doesn't allow any IPv4 traffic.
The proxy is listening on ::1 and 9050 port and works great e.g. with firefox.
It seems like weechat also doesn't resolve IPv6 hosts such as "localhost, ip6-localhost, ip6-loopback". Other programmes doesn't have any issues with it.
```

**Comment by mumixam** [comment]
I got around to testing this myself and it seems to work. I don't see any issues
http://i.imgur.com/o37HWEe.gifv

**Comment by flashcode** [comment]
For now the problem is not confirmed.
Please describe exactly how to reproduce the problem: which proxy is used, and its setup.

**Comment by flashcode** [comment]
I tried with this config, I can connect fine:

    List of proxies:
      tor-ipv6: socks5, ::1/9050 (IPv6), username: (none), password: (none)

    Server: freenode-tor-ipv6 [connected]
      addresses. . . . . . : 'chat.freenode.net/6697'
      proxy. . . . . . . . : 'tor-ipv6'
      ipv6 . . . . . . . . :   (on)
      ssl. . . . . . . . . : on
      ssl_cert . . . . . . :   ('')
      ssl_priorities . . . :   ('NORMAL:-VERS-SSL3.0')
      ssl_dhkey_size . . . :   (2048)
      ssl_fingerprint. . . :   ('')
      ssl_verify . . . . . :   (on)
      password . . . . . . :   (hidden)
      capabilities . . . . :   ('')
      sasl_mechanism . . . :   ('plain')
      sasl_username. . . . :   ('')
      sasl_password. . . . :   (hidden)
      sasl_key. .  . . . . :   ('')
      sasl_timeout . . . . :   (15 seconds)
      sasl_fail. . . . . . :   ('continue')
      autoconnect. . . . . :   (off)
      autoreconnect. . . . :   (on)
      autoreconnect_delay. :   (10 seconds)
      nicks. . . . . . . . :   ('FlashCode,flashy,flashy2,flashy3')
      nicks_alternate. . . :   (on)
      username . . . . . . :   ('FlashCode')
      realname . . . . . . :   ('FlashCode')
      local_hostname . . . :   ('')
      usermode . . . . . . :   ('')
      command. . . . . . . :   ('')
      command_delay. . . . :   (0 seconds)
      autojoin . . . . . . :   ('')
      autorejoin . . . . . :   (off)
      autorejoin_delay . . :   (3 seconds)
      connection_timeout . :   (60 seconds)
      anti_flood_prio_high :   (2 seconds)
      anti_flood_prio_low. :   (2 seconds)
      away_check . . . . . :   (1 minute)
      away_check_max_nicks :   (50)
      msg_kick . . . . . . :   ('')
      msg_part . . . . . . :   ('WeeChat ${info:version}')
      msg_quit . . . . . . :   ('WeeChat ${info:version}')
      notify . . . . . . . :   ('')

Connection:

    freenode-tor-ipv6  -- │ irc: connecting to server chat.freenode.net/6697 (SSL) via socks5 proxy ::1/9050 (IPv6)...
    freenode-tor-ipv6  -- │ gnutls: connected using 2048-bit Diffie-Hellman shared secret exchange
    freenode-tor-ipv6  -- │ gnutls: receiving 2 certificates
    freenode-tor-ipv6  -- │  - certificate[1] info:
    freenode-tor-ipv6  -- │    - subject `CN=adams.freenode.net', issuer `CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US', serial 0x03f2dd3f40dcaa397ac17f268d1814e15986, RSA key 4096 bits, signed using RSA-SHA256, activated `2017-01-12 16:59:00 UTC', expires
                          │ `2017-04-12 16:59:00 UTC', key-ID `sha256:597bbc5127e21d0b78447bd743916c11a9c7027b791931116776ea20e29e87d4'
    freenode-tor-ipv6  -- │  - certificate[2] info:
    freenode-tor-ipv6  -- │    - subject `CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US', issuer `CN=DST Root CA X3,O=Digital Signature Trust Co.', serial 0x0a0141420000015385736a0b85eca708, RSA key 2048 bits, signed using RSA-SHA256, activated `2016-03-17 16:40:46
                          │ UTC', expires `2021-03-17 16:40:46 UTC', key-ID `sha256:60b87575447dcba2a36b7d11ac09fb24a9db406fee12d2cc90180517616e8a18'
    freenode-tor-ipv6  -- │ gnutls: peer's certificate is trusted
    freenode-tor-ipv6  -- │ irc: connected to chat.freenode.net/6697 (::1)

**Comment by mumixam** [comment]
I'm just going to close this issue for now. The original reporter of this issue hasn't been seen on irc since late Nov 2016 and i am also unable to reproduce the issue.

**Comment by flashcode** [comment]
I discussed with the reporter of problem yesterday (on another channel), and with the same config I was not able to reproduce the problem.
