### ISSUE TITLE
[DOCS: WeeChat user’s guide] "irc private" → "irc private messages"

### ISSUE THREAD

**Issue by 01100001** [weechat/weechat#838]
In the **WeeChat user's guide**, under the section [**3.4. Buffers and windows**](https://github.com/weechat/weechat/blob/master/doc/en/weechat_user.en.adoc#34-buffers-and-windows), we have "irc private" under the list of *Examples of buffers*.

Would it be more correct to have "irc private messages"? Or is "irc private" the actual term?

I know this is not a major edit that I am suggesting (if at all it's right) but newbies like me instantly know that "private messages" are user-to-user conversations; less so (obvious) when we see "irc private". Just thought I should at least let you know considering how good the documentation is.

**Comment by flashcode** [comment]
Hi,
You're right, I'll fix that.
