### ISSUE TITLE
weechat.bar.* options seem to forget default value

### ISSUE THREAD

**Issue by 01100001** [weechat/weechat#846]
In WeeChat, I ran:

```
/iset color =default
```

And then, for all these options, I carefully set the color of the text (i.e. foreground-related options) to `223` and background of the text (i.e. background-related options) to `235`.

Now, after that, (I don't know if it matters or not) I `/quit` WeeChat, then started it again. I did this a couple of times for various reasons.

I didn't like the look of the custom theme that I was creating, so I issued `/iset color =default` and started resetting the values of all those options back to defaults by pressing <kbd>Alt</kbd> + <kbd>i</kbd>, <kbd>Alt</kbd> + <kbd>r</kbd>.

But then I noticed some of the options didn't change. They remained 223 or 235 depending on what I set them to earlier. They forgot their default value. Even the description for the options reflected the same, for e.g. `... [default: "235"]`.

The options that seem to have this problem are:

```
/iset weechat.bar*color
```

**Screenshot:**

![image](https://cloud.githubusercontent.com/assets/16049961/20395808/21d36966-ad0a-11e6-96a5-7e8fe1bc01a8.png)

Notice the options with 235 or 223 as values. But I think the same will happen to the other options shown in the screenshot (I haven't tested them). Also notice how the default value has changed in the description, e.g. `... [default: "235"]`.

NOTE: I have the scripts buffers.pl and iset.pl installed. I am **`fr3ya`** on freenode.

**Comment by 01100001** [comment]
@flashcode okay, dynamic options aside, can something be done about the note `... [default: XXX]` in the description? Can that be filled from the script instead of the config.?

I don't code (just getting started with a JS book), so I don't know if what I am asking above is feasible. :)

**Comment by flashcode** [comment]
Yes the script iset.pl could check if it's a dynamic option/section (not sure if it's really easy) and if yes do not display the default value if it's not relevant.

**Comment by flashcode** [comment]
But this will not fix the default value displayed with `/help weechat.bar.xxx.option`.

**Comment by evelikov** [comment]
Just had some fun with this issue, so some food for thought if I may:

Can we do something like below, until a proper solution is available
 - Detect dynamic options - how can we do that?
 - For dynamic options, omit the "default" value displayed with `/help weechat.bar.xxx.option`
 - Always list dynamic options under `/set diff` - since we don't know realistically if they vary from the default

I guess we can handle things properly for the `weechat.bar.foo.items == foo` use-case, and fallback to the "dynamic" detection as listed above?

**Comment by flashcode** [comment]
This should be fixed by this commit: e385eec1d6116b8c87889fc1d829aa1c5192156f.

If not, please add comments in this issue.
