### ISSUE TITLE
[DOCS: FAQ] Correct options for disabling IRC part and quit messages

### ISSUE THREAD

**Issue by 01100001** [weechat/weechat#847]
In *WeeChat FAQ* doc, under the question - [*8.3. I am paranoid about security, which settings could I change to be even more secure?*](https://weechat.org/files/doc/weechat_faq.en.html#security)...

This:

```
/set irc.server_default.default_msg_part ""
/set irc.server_default.default_msg_quit ""
```

Should be changed to:

```
/set irc.server_default.msg_part ""
/set irc.server_default.msg_quit ""
```

**Comment by flashcode** [comment]
Thanks for reporting, fixed.
