### ISSUE TITLE
[DOCS: FAQ] It's possible to reload the screenrc config. file

### ISSUE THREAD

**Issue by 01100001** [weechat/weechat#848]
In the FAQ, under [*3.15. How can I use 256 colors in WeeChat?*](https://weechat.org/files/doc/weechat_faq.en.html#use_256_colors), it's stated that:

> If you are using screen, you can add this line to your `~/.screenrc`:
> 
> ```
> term screen-256color
> ````

And then it's stated that:

> If your TERM variable has wrong value and that WeeChat is already running, you can change it with these two commands (with WeeChat ≥ 1.0):
> 
> ```
> /set env TERM screen-256color
> /upgrade
> ```

But the thing is, if your `$TERM` has wrong value and your WeeChat instance is already running **in screen**, you can simply create a `~/.screenrc` with `term screen-256color` and reload the .screenrc configuration file by pressing <kbd>ctrl</kbd> + <kbd>a</kbd> and then typing:

```
:source ~/.screenrc
```

or this: (sometimes `~` may not work, e.g. macOS)

```
:source $HOME/.screenrc
```

Amiright?

Sources:

- <https://wiki.archlinux.org/index.php/GNU_Screen#Command_Prompt_Commands>
- <http://serverfault.com/a/338902>

If that's correct, can this information be included in the docs too?

**Comment by Random832** [comment]
This won't tell the weechat process about the new value, it will only affect new windows created in screen.
