### ISSUE TITLE
add note to config file to not edit config file

### ISSUE THREAD

**Issue by weechatter** [weechat/weechat#851]
add note to config file to not edit config file

**Comment by ntwk** [comment]
I think a note at the top of all every configuration file indicating that it should not be edited directly would definitely be helpful.

Additionally, the [WeeChat quick start guide](https://weechat.org/files/doc/devel/weechat_quickstart.en.html) also contains the following text:

> You can edit configuration files (*.conf) by hand and reload them by /reload command if you don’t want to use /set command.

I think this section of the guide should also be ammended to warn the user than hand-editing is discouraged as weechat overwrites configuration files by default.

**Comment by Mikaela** [comment]
> I think a note at the top of all every configuration file indicating that it should not be edited directly would definitely be helpful.

:+1: ZNC config file starts:

```
% head .znc/znc.conf
// WARNING
//
// Do NOT edit this file while ZNC is running!
// Use webadmin or *controlpanel instead.
//
// Altering this file by hand will forfeit all support.
//
// But if you feel risky, you might want to read help on /znc saveconfig and /znc rehash.
// Also check http://en.znc.in/wiki/Configuration

```
