### ISSUE TITLE
need a /window close command to close only the current window

### ISSUE THREAD

**Issue by tenleftfingers** [weechat/weechat#853]
See the previous task at http://savannah.nongnu.org/task/?12401 for details, but basically there is no way to close a window and leave others open. I don't want to close the buffer, just the view.

**Comment by arza-zara** [comment]
You can make an alias to eg. /window up ; /window merge.

**Comment by tenleftfingers** [comment]
Thanks arza-zara. /window close would mean people wouldn't need to consult a manual - it's the first thing they'd try and it's consistent with /buffer close.

**Comment by KryDos** [comment]
Is there any pitfalls if we just make an alias to `/window merge`? It looks pretty the same to me.

**Comment by flashcode** [comment]
@KryDos: it's not the same action, `/window merge` merges the current window with the parent one. So you stay on the same window and the parent is closed.
