### ISSUE TITLE
Inaccurate documentation for irc.server_default.addresses

### ISSUE THREAD

**Issue by aaronmdjones** [weechat/weechat#856]
Hello. The documentation for `irc.server_default.addresses` states that the content is evaluated; but I am having difficulty using variables in it.

Specifically, I have done something along the lines of:

```
/secure set foo "192.0.2.83/6697"
/set irc.server.bar.addresses "${sec.data.foo}"
```

... and it is trying to look that up as a hostname rather than evaluate it.

I would prefer to store these addresses in encrypted form, as they are hidden hubs.

This is on version `1.7-dev (git: v1.6-37-g01f8443)`.

**Comment by flashcode** [comment]
Hi,
I just try with an empty config, it works fine for me.
I did:

    /secure set foo 127.0.0.1/6667
    /server add local ${sec.data.foo}
    /connect local

And it connects fine to address "127.0.0.1/6667".

Could you please give me the exact sequence of commands you typed?

**Comment by aaronmdjones** [comment]
I apologise. I accidentally entered square brackets `[]` instead of curly braces `{}`. It does indeed work as documented.
