### ISSUE TITLE
Confusing semantics for command_delay, and missing command pre-delay

### ISSUE THREAD

**Issue by haasn** [weechat/weechat#862]
`command_delay` (in `irc.server.X.`) describes itself as being a delay *after* executing a command and before auto-joining channels. I think it would make more sense to have that called `autojoin_delay`.

Furthermore, what I actually expected `command_delay` to do is to delay running a command after connecting, i.e. a command pre-delay. There seems to be no way of accomplishing that as of now. (I need to make sure I'm fully connected before running my command)

**Comment by arza-zara** [comment]
You can use /wait for pre-delay.

**Comment by flashcode** [comment]
Done!

New server option "autojoin_delay", on upgrade from any version to 4.3.0, the server option "command_delay" is copied to "autojoin_delay".

And the server option "command_delay" is now a delay **before** the execution of the command.
