### ISSUE TITLE
Nick in autojoin causes parsing errors on receiving messages from that nick

### ISSUE THREAD

**Issue by Neui** [weechat/weechat#869]
Steps to reproduce:

1. Get 2 Clients, A and B. A is using weechat (tested on 1.4 and 1.6), B can use any client.
2. A: Set `irc.server.<server>.autojoin` to include B's nickname (eg. `"#weechat,B"` or even just `"B"`)
3. A (and B) connects to the same server. A will get an message `"B: No such channel"`, but a buffer is created.
4. B sends an private message to A. (B: `/msg A What's up?`)
5. A's weechat reports "parsing" error.

```
-- End of /MOTD command.
-- User mode [+i] by A
-- B: No such channel
=!= Error: a buffer with same name (<server>.B) already exists
=!= irc: cannot create new private buffer "B"
=!= irc: failed to parse command "PRIVMSG" (please report to developers):
=!= :B!5e12647b@<server> PRIVMSG A :What's up?
```
Raw-log:
```
--> <server> :<server> 376 A :End of /MOTD command.
--> <server> :A MODE A :+i
--> <server> :<server> 403 A B :No such channel
--> <server> :B!5e12647b@<server> PRIVMSG A:What's up?
```
(Modified names and some other intentionally "private" stuff)

While this might be user error, it also means that the user might miss the messages because they're not written on the right buffer. Maybe a help-message (or not opening the buffer at all, or reuse the buffer) can help.

**Comment by JPTIZ** [comment]
(Sorry for the necrobump)

Reusing the buffer seems a very straight-forward solution and also sounds more intuitive for me. At least, I've set someone's nickname in autojoin thinking "I'm going to still have their chat opened when starting weechat, so we just go back chatting quicker".

(PS: If someone give me a little guide, maybe I can help with this issue - and if it is accepted, of course)

**Comment by flashcode** [comment]
I'll fix it by reusing the buffer: when a private message is received from "nick", if a buffer "irc.xxx.nick" exists and has type "channel" (opened by a manual `/join` or autojoin option), we reuse the buffer for the private chat.
