### ISSUE TITLE
/exec -o: Option to control command execution

### ISSUE THREAD

**Issue by xnrand** [weechat/weechat#877]
When running external programs with `/exec -o`, any output lines starting with a `/` will be run as weechat commands. A way to disable or control that behavior would be useful.

One approach would be to additional /exec flags similar to `-o`, for example:
- `-cmd` to run each line of output as a command
- `-otext` to output each line of output as text into the current buffer, not running any commands

**Comment by flashcode** [comment]
I changed the default behavior of option "-o" which is now to NOT execute commands in output (which is more secure).
I hope it's OK for everybody to have such default.
WIth the new option "-oc", commands are executed.

**Comment by weechatter** [comment]
perfect!
