### ISSUE TITLE
WebSockets broken because header fields treated case-sensitive

### ISSUE THREAD

**Issue by mholt** [weechat/weechat#888]
[RFC 2616 says](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2) that header fields are not case-sensitive. Unfortunately, [weechat is treating them case-sensitive](https://github.com/weechat/weechat/blob/7cd4a23cdcadba9ad6fbaef66a2d5ff80feee52c/src/plugins/relay/relay-websocket.c#L153). This is causing [web servers like Caddy to fail making WebSocket connections to weechat](https://github.com/mholt/caddy/issues/1332). Rather than [break spec/convention in Caddy](https://github.com/mholt/caddy/pull/1338) (and create more code and complexity to maintain), I'd rather like to see weechat treat header fields case-insensitively.

**Comment by mholt** [comment]
Thank you!!

**Comment by joelnb** [comment]
Thanks a lot for your quick work here @flashcode!

**Comment by flashcode** [comment]
You're welcome, I hope the fix is working fine (if not please ping me quickly so I can fix before the next release).

**Comment by joelnb** [comment]
@flashcode Had some issues getting it to build but that's all sorted now and I can confirm that the fix is working for me with a vanilla version of Caddy. Thanks a lot.
