### ISSUE TITLE
Multiline Input Issues

### ISSUE THREAD

**Issue by jdh313** [weechat/weechat#889]
I set multiline input based on the FAQ, but anytime the text enters the second line, the text of the first line, the title, and the buffer list all disappear and aren't fixed until the text is either deleted back to the first line or the tab is changed to a different buffer.

**Comment by flashcode** [comment]
Hi,

Could you please give us:

* your WeeChat version,
* your operating system with its version,
* the command used to set input as multiline,
* the terminal you are using,
* are you running WeeChat inside screen or tmux?
* a screenshot of the problem.

Thanks.

**Comment by jdh313** [comment]
No problem, they are:
- Weechat version 1.6-3
- Updated Arch Linux
- To enable multiline I used: 
`/set weechat.bar.input.size 0
/set weechat.bar.input.size_max 3`
- I use Termite, but the issue also exists in Terminator
- No tmux or screen.
- I'm attaching two screenshots, the top one is how everything looks before the issue, the bottom one is with the issue.  I've since noticed that by resizing the window, the problem fixes itself, so it seems as if the system isn't redrawing properly. [Screenshots](http://imgur.com/a/jVBVF)

**Comment by jdh313** [comment]
I've included a third image, this is what happens on Urxvt.  It can start a second line of text without issue, but when you delete back to the first line it duplicates as is shown.

**Comment by flashcode** [comment]
OK, then please check that:

* Option `weechat.look.eat_newline_glitch` is `off`; if you enable that you can have sever display problems, this is not recommended to enable it.
* Your `$TERM` is properly set, a bad $TERM can cause display bugs, like the background of status bar which stops before the end of the terminal, check the FAQ for more info: https://weechat.org/files/doc/weechat_faq.en.html#bars_background.

**Comment by jdh313** [comment]
Thank you, it was the former, weechat.look.eat_newline_glitch was on.
