### ISSUE TITLE
build against netbsd-curses broken with cmake

### ISSUE THREAD

**Issue by rofl0r** [weechat/weechat#891]
unfortunately i didn't remember that weechat doesn't ship the configure script in its release tarballs, so one has to build it with cmake anyway.
and there we face the same problem i tried to address in #814 and fixed in #870 for autoconf.
the cmake test for eat_newline_glitch is broken; it tests only for existence but not wether a value can be assigned to it (unlike the autoconf test).

```
-- Looking for eat_newline_glitch
-- Looking for eat_newline_glitch - found
...

weechat-1.7/src/gui/curses/gui-curses-term.c:49:5: error: assignment of read-only location '*(cur_term->flags + 9u)'

```

**Comment by coypoop** [comment]
this is probably ugly as hell:
http://coypu.sdf.org/patch-CMakeLists.txt

**Comment by rofl0r** [comment]
care to present this as a PR? that way it can be commented on, etc, using the normal github workflow

**Comment by flashcode** [comment]
Hi,
Yes if the problem is still present today, please submit a PR.
Otherwise we can close this issue.

**Comment by rofl0r** [comment]
just tried to build master, but it's blocked by getting the following build errors before getting there:

```
cc: error: unrecognized command line option '-Wformat-overflow=2'; did you mean '-Wstrict-overflow='?
cc: error: unrecognized command line option '-Wformat-truncation=2'; did you mean '-Wline-truncation'?
```
apparently the build system assumes that everybody uses GCC 10 or higher.
in my case it's gcc 6.5.0 which is a perfectly fine C11 compliant compiler. options like these should be checked for before adding them unconditionally to CFLAGS.

**Comment by flashcode** [comment]
Thanks for testing.

WeeChat supports some old compilers & libs, but the goal is not to support very old versions.
The oldest supported distro is currently Ubuntu Bionic 18.04, where gcc version is 7.5.0, so at least this version has the mentioned compiler options.

It's not planned to support oldest compilers, unless there's a serious reason to do it.
Over time, support of old compilers and libs is removed, to prevent having cumbersome code.

To test the netbsd-curses issue, you could just comment these 2 lines, compilation should be fine without them.

**Comment by rofl0r** [comment]
apart from the mentioned -Wformat... issue it builds. though i dont really understand why you prevent people from using the compiler they want just to not test whether a warning option is supported.
