### ISSUE TITLE
Add an "id" variable to the "line_data" structure.

### ISSUE THREAD

**Issue by rawdigits** [weechat/weechat#901]
Problem statement:

When writing scripts that work with printed lines in existing buffers, there is not currently a way to identify individual messages directly. The value `line_data.date` works most of the time, but the precision is only down to a full second. If two messages arrive during the same second, there is no way to tell them apart. Regardless, even down to the millisecond there could be conflicts, so time alone cannot solve this. When my script needs to modify an ambiguous line, it must do it by modifying the data outside of the buffer and then reprinting the entire buffer. This is inefficient for disk space (logs are written) and cpu.

Proposal:

When printing messages to a buffer, it would be helpful to allow an 'id' to be added (via something like a new method called `prnt_date_tags_id` or similar). This would allow a script to set an ID per message while it is being output. In my case, the ID would be used in concert with the timestamp to identify messages. Others may wish to use the ID differently.

**Comment by rawdigits** [comment]
Some additional context to demonstrate how I use the `line_data` structure currently:
https://github.com/wee-slack/wee-slack/blob/master/wee_slack.py#L1834-L1860

**Comment by Zarthus** [comment]
IRCv3 is working on a thing called "message ids", would supporting these solve your problem, or would you like something internal to weechat? (these require opt in from the user, and are set by the ircd. It's also a long way away from being wildely implemented)

https://github.com/ircv3/ircv3-specifications/blob/master/extensions/message-ids.md

**Comment by flashcode** [comment]
@Zarthus: thanks for the reminder on this future IRC "message id".
I think it could be complementary to an internal ID in WeeChat lines, which would be always there, even on non-irc buffers.
The IRC message id looks like a string (at least it's probable, nothing sure), while in WeeChat it would just be an integer to differenciate lines.

**Comment by flashcode** [comment]
Hi,

This is now implemented with a new field "id" (integer) in each buffer line.
Depending on the buffer type, the behavior is:

- with formatted content: the "id" starts to 0 on each buffer and is incremented on each new line displayed (it is reset to 0 if reaching INT_MAX; so two same identifiers in the same buffer is possible but extremely unlikely)
- with free content: the "id" is set to the same value as "y" (ie the line number, starting to 0).

**Comment by ksu-0** [comment]
> * with formatted content: the `id` starts to 0 on each buffer and is incremented on each new line displayed (it is reset to 0 if reaching INT_MAX; so two lines with the same `id` in the same buffer is possible but extremely unlikely)

Does `weechat.history.max_buffer_lines_number` need to be `0` for duplicate `id` to occur?

**Comment by flashcode** [comment]
@ksu-0: yes it must be set to 0, which is not recommended.
