### ISSUE TITLE
Slow redraw when terminal is resized

### ISSUE THREAD

**Issue by holomorph** [weechat/weechat#902]
I usually keep weechat in tmux. Here on Arch, weechat 1.7 (and as current as 0ef979a54) takes quite some time to redraw itself.  This appears to be a regression from 1.6. For instance, if a split a tmux window into left-right panes (`<prefix> %`), it will be roughly 0.5-1.0s before weechat refills its content.  I still had the 1.6 package in the pacman cache, and 1.6 does not exhibit this behavior.  The regression appears when invoking `weechat -a -p` in tmux, but does not appear in a plain terminal emulator (I use termite, a vte3 based TE).

**Comment by weechatter** [comment]
Please try with another terminal. termite is well known to make problems. i can not reproduce myself and i am running weechat for a long time in tmux.

**Comment by flashcode** [comment]
If running with `weechat -a -p`, no plugins/scripts are loaded.
As @weechatter said, it's important to compare times without any script loaded.

**Comment by holomorph** [comment]
Same behavior appears using instead st and invoking `weechat -a -p`.

**Comment by flashcode** [comment]
Could you please try to make a video of the problem? You can force refresh with ctrl-L in WeeChat, if needed.

**Comment by holomorph** [comment]
https://a.pomf.cat/lpbfya.mkv

**Comment by flashcode** [comment]
OK, thanks for the video, I am able to reproduce the problem.
I know where the problem is, it is caused by the commit 018b9693812eb58e6d15602366c61e937a9ea930 when I fixed a deadlock with signal handlers in WeeChat.
This affects the signal SIGWINCH which is received when the terminal is resized (and then in this case WeeChat redraws whole screen).
I have to move the signal handler just before the redraw of screen.

**Comment by flashcode** [comment]
@holomorph: could you please tell me if the refreshs are OK with the devel version now?

**Comment by holomorph** [comment]
@flashcode confirmed fixed. thanks.

**Comment by flashcode** [comment]
Great!

**Comment by bendem** [comment]
Awesome, this has always bothered me, but never enough to actually report it, I thought it was a limitation of console applications. Thanks both for reporting and fixing it 👍

**Comment by tomoe-mami** [comment]
@flashcode d6977490d0c91b3417a383dd3d1a844657c09f84 somehow made the info_get("term_height", "") return wrong result. [Demo video][1] and the [test script][2] that I use.

Weechat 1.8 sends sigwinch instantly but it looks like info_get returns the value of terminal height before it's resized. Weechat 1.5 has a bit delay but reports the correct height.

[1]: https://streamable.com/zmbhp
[2]: http://sprunge.us/MeAH

**Comment by flashcode** [comment]
@tomoe-mami: OK I see the problem, the send of signal "signal_sigwinch" must be delayed after the refreshs, so the terminal size will be OK.
I'll fix that, thanks for reporting.

**Comment by flashcode** [comment]
@tomoe-mami: the problem should be fixed, now the signal is sent after the refreshs.
Could you please confirm if it's OK for you with your script? Thanks.

**Comment by tomoe-mami** [comment]
Works great, flashcode. Thank You!

**Comment by flashcode** [comment]
Great! Closing the issue.
