### ISSUE TITLE
Include last-upgrade-restart-date in /uptime and/or /v

### ISSUE THREAD

**Issue by Zarthus** [weechat/weechat#903]
Include the date we /upgraded in version or uptime information, the "second start", so to speak. The compilation date isn't too useful if you use the weechat repos.

```
15:37:23     │ WeeChat uptime: 115 days 19:26:07, started on Mon, 10 Oct 2016 21:11:16
```

```
15:37:52     │ WeeChat 1.7 [compiled on Jan 15 2017 09:58:52]
15:37:52     │ Upgraded 1 time, first start: Mon, 10 Oct 2016 21:11:16
```

**Comment by flashcode** [comment]
Done, output of `/v`:

    WeeChat 1.8-dev (git: v1.7-26-g2437107e3) [compiled on Feb  3 2017 22:21:53]
    Upgraded 2 times, first start: Fri, 03 Feb 2017 22:22:11, last start: Fri, 03 Feb 2017 22:22:17
