### ISSUE TITLE
Documentation: Freenode via Tor

### ISSUE THREAD

**Issue by ohreally** [weechat/weechat#908]
Hi,

Small update for your documentation.

The Freenode .onion address is now **freenodeok2gncmy.onion**.
And the Freenode URL for more info on Freenode and Tor is now
**http://freenode.net/kb/answer/chat#accessing-freenode-via-tor**

Cheers,
  Rob

**Comment by flashcode** [comment]
Thanks for the info, the user's guide is updated.
