### ISSUE TITLE
Suggestion: Add warning about ssh -t setting unexpected LANG/LC_* variables to the FAQ

### ISSUE THREAD

**Issue by RGamma** [weechat/weechat#910]
When attaching to a screen/tmux session via `ssh -t` (for instance as in `ssh -t <host> screen -r <weechat-session>`) ssh may not set the LANG/LC_* environment variables as intended. One can check the variables in question via `ssh -t <host> locale` which may show 
```
LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```
leading to garbled umlauts for instance. In this case `/set env` may still show satisfactory LANG and LC_CTYPE variables. The issue stems from ssh not always sourcing environment variables from the host system as would be the case in an interactive shell. A solution is to have sshd (I only tested OpenSSH) accept setting certain environment variables through clients by adding the `AcceptEnv LANG LC_*` clause to the sshd configuration (default: `/etc/ssh/sshd_config`) while ssh clients have the `SendEnv LANG LC_*` clause in their configuration (default: `/etc/ssh/ssh_config`) and proper variables are sent. The sshd_config manual elaborates on this:
```
AcceptEnv
             Specifies what environment variables sent by the client will be copied into the
             session's environ(7).  See SendEnv in ssh_config(5) for how to configure the
             client.  The TERM environment variable is always sent whenever the client
             requests a pseudo-terminal as it is required by the protocol.  Variables are
             specified by name, which may contain the wildcard characters ‘*’ and ‘?’.  Mul‐
             tiple environment variables may be separated by whitespace or spread across mul‐
             tiple AcceptEnv directives.  Be warned that some environment variables could be
             used to bypass restricted user environments.  For this reason, care should be
             taken in the use of this directive.  The default is not to accept any environ‐
             ment variables.
```
It seems this should be also solvable by exporting these variables in files sourced by non-interactive shells like `/etc/profile`, but I didn't have luck with that. One might also call `ssh -t <host> "LANG=en_US.UTF-8 screen -r <weechat-session>"` or similar to achieve the desired effect (it merely is important that the screen session has a proper environment). Note that on Debian Sid the `AcceptEnv` clause is default in their sshd_config, so the above should be safe to suggest.

Here's my first draft of a suggestion to add to the FAQ:
```
Why aren't special characters (like umlauts or accented characters) showing when attaching to a weechat screen/tmux session with ssh -t?
 
Likely the session started by ssh -t does not have the LANG or LC_* environment variables set correctly.
You can check this with ssh -t <host and options> locale. If the output contains entries like LC_CTYPE="POSIX" you need to instruct your ssh-server to set these variables in the session environment to something proper like LC_CTYPE="en_US.UTF-8".
One way to achieve this for OpenSSH is to add "AcceptEnv LANG LC_*" to sshd_config and "SendEnv LANG LC_*" to your ssh-client's configuration making sure that the server has the encodings set this way actually available using locale-gen. Also refer to your ssh-server's manual page for alternate ways to configure the ssh-session's environment.
```

Edit: Ideally the ssh server would simply take the ssh host's environment variables. I currently don't know how to do that.

**Comment by flashcode** [comment]
Hi,
Are you sure this is related to the `-t` option? I'm not sure there's any relation between this option and the LOCALE or other variables set when you connect to a target host.
I think it's a more general problem with the locale config on your target host.

**Comment by RGamma** [comment]
Yes, the -t option starts the command given in a non-interactive/ssh-specifiic shell, while without you're entering an interactive shell that sources all the usual files. There are many cases to distinguish including alll that may modify the ssh environment as given in `man sshd_config`, but I think I've nailed down the most obvious.

My target host is functioning normally when I execute the very same command from an interactive shell as obtained by a normal `ssh <host>`, then in the resulting shell `screen -r <weechat-sess>`.

**Comment by RGamma** [comment]
My above comment wasn't quite correct as the `ssh -t` shell is indeed interactive, but somehow ssh still clears the environment. In the end I fixed my problem by setting `PermitUserEnvironment yes` in sshd_config on the ssh server and then putting the correct environment variables in `$HOME/.ssh/environment` of the server's ssh user that I log in as. Don't know if you still want to add this quirk to the FAQ, as it's probably something that doesn't come up very often.
