### ISSUE TITLE
Selection color

### ISSUE THREAD

**Issue by Brottweiler** [weechat/weechat#914]
I am trying to find what the setting is for "selection background", like the red background for the selected script in this screenshot:

![](https://weechat.org/media/images/ft_scripts.png)

I believe `buffers.pl` uses same color, and I am trying to find it in the config, but I am unable to locate it. What's the name of it?

**Comment by MatthewCox** [comment]
`script.color.text_bg_selected`, buffers.pl is `buffers.color.current_bg`

For future reference, if you install iset.pl you can do eg: `/iset =red`
Which will list all settings containing red in their value

**Comment by Brottweiler** [comment]
@MatthewCox `buffers.color.current_bg` is not the selected background, but the background of the entire buffers window. Like so: https://i.imgur.com/AErS7nb.png

But I understand that the question about buffers is invalid since it's a script issue, not weechat issue.

`script.color.text_bg_selected` don't seem to change what I want, but as you say, might be for the red in the screenshot in my original post.

**Comment by Brottweiler** [comment]
Ignore the post above ^, I mistook `buffers.color.current_bg` with `buffers.color_bg`. 

It's solved!
