### ISSUE TITLE
Apply smart filter to the backlog

### ISSUE THREAD

**Issue by ssixty** [weechat/weechat#915]
When I restart Weechat and rejoin my channels it's great to have the backlog loaded, but on quiet channels the majority is joins/parts/mode changes/etc.

Would it be feasible to have the smart filter applied to the backlog?

**Comment by weechatter** [comment]
problem with backlog is, that no tags will be logged only the pure text. therefore smart filter can not work. Maybe an option with a regex to ignore matching lines is a possible "work around".

**Comment by ssixty** [comment]
Ah I see,  yes even just a dumb regex would be useful.  Not sure if that would be more suited to a script instead of core functionality.

**Comment by arza-zara** [comment]
Backlog-specific filter regex is already supported:
`/filter add backlogtidy * logger_backlog ^\S+ \(\S+\) has (joined|left|quit) |^\S+ is now known as \S+$`

**Comment by weechatter** [comment]
Ah! i did not know. Its working with the filter. i'll close the issue.

**Comment by ssixty** [comment]
Excellent, I'll also add mode changes to the regex.  thankyou
