### ISSUE TITLE
cmake: Inform user about missing libraries

### ISSUE THREAD

**Issue by sideeffect42** [weechat/weechat#916]
When compiling WeeChat with CMake it may silently disable explicitly enabled options when dependencies are missing.

E.g. when `ENABLE_PERL=ON` is set, but `libperl-dev` is not installed, WeeChat will silently not compile the perl target.

Instead there should be a warning or error, so that the user can take action (install dependencies or disable options)

**Comment by flashcode** [comment]
It will be closed when #956 will be merged.
