### ISSUE TITLE
Avoid hanging when the home/logging directory becomes unavailable

### ISSUE THREAD

**Issue by jansol** [weechat/weechat#92]
Weechat version: 0.4.2

Recently people have been timeouting on a user shell I am administrating and it seems many of those people are weechat users. Upon closer inspection it turned out that the NFS server responsible for said shell's home directories was suffering from heat issues.

This brought up the question if it would be possible to make weechat resistant against such situations where the homedir becomes unavailable. Currently whenever the NFS volume disconnects, weechat practically hangs.

Steps to reproduce:
1. run weechat with config & logs on a separate volume (NFS volume in our case, a USB stick should do just fine)
2. forcibly disconnect the separate volume (the kernel probably won't allow unmounting) and watch weechat hang

**Comment by flashcode** [comment]
Issue #123 has been fixed in WeeChat 2.7, so I close this one.
If there are still problems, feel free to comment on this issue.
