### ISSUE TITLE
I cannot load perl plugin..

### ISSUE THREAD

**Issue by hdarwin** [weechat/weechat#924]
client@ubuntu:~/weechat/bin$ ./weechat --version
1.8-dev
```
02:58:08 =!= | Error: unable to load plugin "perl": /usr/lib/x86_64-linux-gnu/perl: cannot read file data: Is a directory
02:58:08 =!= | If you're trying to load a script and not a C plugin, try command to load scripts (/perl, /python, ...)
02:58:20     | 5.22
02:58:20     | 5.22.1
02:58:20     | cross-config-5.22.1
02:58:20     | debian-config-data-5.22.1
02:58:20     | exec: end of command 0 ("ls /usr/lib/x86_64-linux-gnu/perl"), return code: 0
```
how can I load perl plugin??

**Comment by weechatter** [comment]
In weechat type: /plugin load perl

Did you compile weechat yourself? Check out that all dependencies are installed (especially perl-dev):
https://weechat.org/files/doc/stable/weechat_user.en.html#dependencies

**Comment by flashcode** [comment]
If you installed binary package, check that package weechat-plugins is installed (this package contains perl plugin).

**Comment by flashcode** [comment]
Works for me, closing the issue.

**Comment by ward** [comment]
For anyone coming across this: I had to install `weechat-perl` (and `weechat-python` and whichever you need) to fix the issue.

**Comment by weechatter** [comment]
@ward: The package weechat-plugins has been split into 9 packages in V2.0. He was talking about V1.8.
