### ISSUE TITLE
Improve prefix_same_nick with a special prefix for middle lines

### ISSUE THREAD

**Issue by abjugard** [weechat/weechat#930]
I've long wanted a different prefix for the middle line between two messages sent by the same user, as I've always thought it would look good.

Screencap of my implementation:
![](https://i.imgur.com/RQBTNM9.png)

**Comment by dkasak** [comment]
This looks amazing. Will this get merged or is there some issue with it?

**Comment by weechatter** [comment]
I agree, this is a really useful one. +1
