### ISSUE TITLE
[stick_buffer.py] Respect sticky window when switching with meta-a or similar

### ISSUE THREAD

**Issue by squigglezworth** [weechat/weechat#935]
With this, and respecting buffer changes from go.py, this would make stick_buffer respond to almost, if not all, buffer changes :)

**Comment by squigglezworth** [comment]
I think stick_buffer is also interacting badly with meta-arrow key movement. If I move onto a stuck buffer with them, it switches to the appropriate sticky window, BUT also switches to the next buffer in line to the one that is supposed to be stuck.

**Comment by flashcode** [comment]
Hi,
If this is about changes in the script and not WeeChat itself, please open an issue in the [weechat/scripts](https://github.com/weechat/scripts/) repository.

**Comment by flashcode** [comment]
Sticky window is a script feature, so weechat doesn't know that (weechat is not looking for scripts loaded).
If you want a different behavior for meta-a, then the script could implement it with a command that you bind on the key (and then it's a feature request for the script, not weechat).

**Comment by squigglezworth** [comment]
you're quite right, I should have created this in the scripts repo
