### ISSUE TITLE
Window separators mess up buffer list indenting

### ISSUE THREAD

**Issue by squigglezworth** [weechat/weechat#949]
https://ptpb.pw/Qdu0.png

It seems the window separator messes up the indentation. I've tested by adding and removing buffers, and it always affects the one in the line after the separator. Both buflist and buffers.pl do this.

**Comment by flashcode** [comment]
Hi,

I'm almost sure this is not a WeeChat issue, but a terminal bug.
I already had such problem with some terminals and some unicode chars displayed.
Could you please try another terminal?

By the way when reporting an issue, please add the required info (see file Contributing.adoc).
Thanks.

**Comment by squigglezworth** [comment]
My previous terminal was rxvt-unicode, and now I'm trying xterm, and I'm still experiencing this drawing issue.

Debian Jessie, weechat version 1.8-dev (git: v1.7-127-ge6db618)

**Comment by squigglezworth** [comment]
To add to this, when I zoom a window and redraw, the indentation is fixed. However, when I unzoom (and all my windows are displayed) and redraw, it goes back to what is pictured.

**Comment by arza-zara** [comment]
Have you touched `weechat.look.eat_newline_glitch`?

**Comment by squigglezworth** [comment]
With initial testing, it seems turning the option off works. Thanks very much.
Closing
