### ISSUE TITLE
Don't use max_length_nick when determining message splitting

### ISSUE THREAD

**Issue by spaghetti2514** [weechat/weechat#950]
A particular ircd (inspircd instance) with maxnick set to 423 results in all weechat users being limited to only sending 2 characters of text to a channel at a time. No other client seems to have this problem.

Setting maxnick on the ircd to higher than 425 seems to break splitting entirely for weechat.

**Comment by arza-zara** [comment]
That's bad configuration and seems to break a lot if there actually are that long nicks.
But yeah, why not use the length of your own nick for the splitting.
Related: #828.

**Comment by flashcode** [comment]
Hi,
In WeeChat 2.1-dev there's now a server option called "split_msg_max_length" to setup the max length for split of outgoing messages on WeeChat side, you could try to increase it for broken servers like this one.
Anyway for me it's a server issue, not a WeeChat one, so I close the issue.
