### ISSUE TITLE
More buflist sort options

### ISSUE THREAD

**Issue by squigglezworth** [weechat/weechat#968]
Having more advanced options to sort the buflist would be great, such as by number of channels, or disconnected/connected status

**Comment by arza-zara** [comment]
Buflist-specific? Why not reorder the buffers (with a script)?

**Comment by squigglezworth** [comment]
True, this could be done in a script, but I don't have any Weechat
scripting knowledge, and buflist already has a sorting option.

There is also the autosort.py script, but that's not quite advanced enough
to achieve this.
