### ISSUE TITLE
/names is missing user count for admin and owner

### ISSUE THREAD

**Issue by 0xallie** [weechat/weechat#97]
The `/names` command is missing user count for admin/"protected" (e.g. `+a`, `!`/`&`) and owner/founder (e.g. `+q`/`+y`, `~`).

**Comment by flashcode** [comment]
Hi,

As modes above "o" (op) are not standard, I propose to display like this, supposing we have `PREFIX=(qaohv)~&@%+`:

```
-- | Nicks #test: [~alice &bob @chuck @david %eve +frank grace harold]                               
-- | Channel #test: 8 nicks (1 +q, 1 +a, 2 ops, 1 halfops, 1 voiced, 2 regular)
```

OK, or other ideas?
