### ISSUE TITLE
Headless bouncer?

### ISSUE THREAD

**Issue by JulienPalard** [weechat/weechat#973]
Hi,

I'm using weechat more as a bouncer than a ncurses client. (Looks like [I'm not alone](http://www.mythmon.com/posts/2015-02-15-systemd-weechat.html)).

It would be great to provide a headless build with less dependencies if not completly separating the ncurses client from the bouncer (if it's not already the case).

**Comment by flashcode** [comment]
Same as #1120 (which has a bit more info, so I close this one as duplicate).
