### ISSUE TITLE
buflist - hidden buffer

### ISSUE THREAD

**Issue by pascalpoitras** [weechat/weechat#974]
When a buffer is hidden and you click on a buffer number following, you dont go to the right buffer. Was working good with buffers.pl 

WeeChat 1.8-dev (git: v1.7-195-g00eddd3) [compiled on Apr 29 2017 15:12:42]

**Comment by flashcode** [comment]
Hi,
I can't reproduce that.
Can you try to reproduce the problem with a default WeeChat config?
It's just by clicking on a buffer name (so the default buflist mouse action)?

**Comment by pascalpoitras** [comment]
sorry! I added a trigger when buflist was not supporting mouse, I forgot to remove it! everything works well
