### ISSUE TITLE
Snap package for Ubuntu Core

### ISSUE THREAD

**Issue by chrmod** [weechat/weechat#979]
I'm working on Ubuntu Core snap package for weechat that will run on Raspberrypi.

So far I was able to run snapcraft cross compilation on travis and submit snap directly to ubuntu store - everything automated. 

Created snap runs, but it cannot find any plugins. 

Unfortunately I'm new to both Ubuntu Core and Weechat. Can someone please help me to debug why weechat cannot find plugins? I know they are packaged, so probably the path is wrong.

Source code for automation: https://github.com/chrmod/snap-weechat

**Comment by flashcode** [comment]
Hi,
WeeChat tries to load plugins from `LIBDIR/plugins` (this LIBDIR is set at compilation time).
You can see it inside WeeChat with this command: `/eval -n ${info:weechat_libdir}/plugins`

**Comment by chrmod** [comment]
`/eval -n ${info:weechat_libdir}/plugins` is a great help, thanks.

the issue I'm experiencing is probably caused by the fact that LIBDIR not only decides where to look for plugins but also where they are installed. Snap packages are sandboxed, so `LIBDIR=/usr/lib` will become `/snap/weechat-armhf/current/usr/lib` and changing LIBDIR will only move it relatively to `/snap/weechat-armhf/current/`, so plugins will never be found. 

@flashcode I see two solutions here:
- split LIBDIR into two variables, one for install, one for lookup
- statically compile plugins

Which route you would recommend?

**Comment by flashcode** [comment]
@chrmod: there's the PR #971 pending, could that help for snap?

**Comment by chrmod** [comment]
@flashcode oh yes, it is definitely helping. I'm finally getting some plugins successfully loading.

there quite few errors on missing libraries but that is probably yet another snap sandboxing issue:
```
         |21:57:55 =!= | Error: unable to load plugin "/snap/weechat-armhf/current/usr/lib/weechat/plugins/aspell.so": libaspell.so.15: cannot open shared object file: No
         |             | such file or directory
         |21:57:55 =!= | If you're trying to load a script and not a C plugin, try command to load scripts (/perl, /python, ...)
         |21:57:55 =!= | Error: unable to load plugin "/snap/weechat-armhf/current/usr/lib/weechat/plugins/javascript.so": libv8.so.3.14.5: cannot open shared object file:
         |             | No such file or directory
```

using WEECHAT_EXTRA_LIBDIR branch I've managed to run irc plugin with this setup:
https://github.com/chrmod/snap-weechat/blob/bc7006930dcfc10d8bd2ae6c4f6a32294c884feb/snap/snapcraft.yaml 

cc: @lheckemann

**Comment by lheckemann** [comment]
Great to see it's already coming in useful for another purpose!

I was also planning on trying to separate out some other stateful stuff like logs to make creating a read-only configuration more feasible (see https://github.com/NixOS/nixpkgs/pull/25274#issuecomment-297995056). I'm not sure how exactly to go about this yet considering that weechat doesn't make much of a distinction between long-term config (e.g. channels to join) and UI state for example. I should find the time to look at it sometime this week though.

**Comment by flashcode** [comment]
Since #971 is merged, is this issue solved?

**Comment by rogersachan** [comment]
@chrmod Is this issue solved?
