### ISSUE TITLE
multiline message support

### ISSUE THREAD

**Issue by oblitum** [weechat/weechat#984]
Hi, weechat is awesome and extensible, I'm using it for IRC and a bunch of other IMs. One of these is Slack through https://github.com/wee-slack/wee-slack. Slack supports sending multiline messages but I couldn't figure it out whether I can do the same in weechat. This is specially useful for code snippets, currently I can see the multiline code snippets in a single message from weechat, sadly I can't produce one. Is there a configuration for this? Would it be acceptable to request it?

https://github.com/wee-slack/wee-slack/issues/118

**Comment by flashcode** [comment]
Hi,
There's a script: `/script install multiline.pl`.
Not sure if it does exactly what you're looking for, you could try it.

**Comment by oblitum** [comment]
[I did try](https://github.com/wee-slack/wee-slack/issues/118#issuecomment-299340365) it but:

> This plugin just allows **editing** in multiple lines but **sends** each line in a row separately, not as a single multi line message.

As noted on wee-slack/wee-slack#118:

> It would be awesome if there was a way to send multiline messages. According to the slack API this should be possibly by sending \n in the text, but it seems like before sending the message these get escaped to \\n. Any suggestions on how to make this work?

Anything I tried just sends multiple individual lines instead of a single message embedding `\n`s.

**Comment by flashcode** [comment]
OK.

**Comment by Jacoby6000** [comment]
@oblitum I use weechat with the multiline plugin, and it works as expected.

**Comment by oblitum** [comment]
@Jacoby6000 I think this issue is well covered by a pull request already.

**Comment by amerlyq** [comment]
Hm, what still prevents PR from being merged? I haven't found any discussion of its problems.
