### ISSUE TITLE
Option to prevent resetting read marker and hotlist when switching buffers

### ISSUE THREAD

**Issue by devkev** [weechat/weechat#992]
There are times when I switch to a buffer (since it has shown up in my hotlist), only to discover that for some reason, I now need to switch away again.  For example, I don't have time to deal with the messages in the buffer right now, but would like to return to them later.

Unfortunately, when I switch away from the buffer the read marker and hotlist are reset, which means that the buffer no longer shows up in my hotlist.  This makes it highly likely that I will forget to return to it later, as I originally intended.

I tried to solve this by using multiple windows, but it is a clumsy workaround - eventually I have too many windows open.

I figured out that what I really wanted was to have fully manual control over when the read marker and hotlist for a buffer are cleared.  This would allow me to "preview" or "peek" at a buffer, knowing that if it turns out that I don't have time to respond or deal with the messages, I can safely navigate away from the buffer without losing the read marker position and hotlist counts.

To this end, I need a way of inhibiting Weechat's currently non-configurable behaviour of resetting the read marker and hotlist when I switch away from a buffer.  If this is possible, then I can simply bind a key to `/input  set_unread_current_buffer` and press that when I would like to reset the buffer's read marker and hotlist.

**Comment by weechatter** [comment]
There is a script to set buffer as unread. Maybe its possible to set the read_marker in any way

**Comment by devkev** [comment]
`unread_buffer.py` only sets the hotlist.  I remember looking around in the source and not finding any way to set the read marker to an arbitrary location in the buffer, even via the plugin API.  But I could be wrong or misremembering.

In any case, using a command (or buffer switch trigger) to put the read marker and hotlist back to the way they were prior to switching away, seems like a poor solution to this problem (eg. it invites races).

**Comment by mkoskar** [comment]
FYI. There is also #552 which is in part similar (not resetting read marker automatically).
