### ISSUE TITLE
buflist bar created even when buflist is disabled

### ISSUE THREAD

**Issue by NoctuaNivalis** [weechat/weechat#994]
When I delete the buflist bar with `/bar del buflist` and `/save`, the bar configuration is still in weechat.conf, and the bar returns when I start weechat again.

If I disable the buflist in buflist.conf, (`enabled = off`), the bar is still created, but it shows up empty.

I'm hoping for a way to delete the bar (not just setting it to hidden).

**version:** WeeChat 1.8 [compiled on May 13 2017 15:05:16]
**operating system:** Void Linux

**Comment by vv7v7** [comment]
Same here. I've made "/bar del buflist" and "/save", but after restart it shows *two* buffer list. One from scripts and one builtin.

**Comment by flashcode** [comment]
To disable buflist, see: https://weechat.org/files/releasenotes/ReleaseNotes-devel.html#v1.8_buflist_plugin
To remove the script: `/script remove buffers.pl`
