### ISSUE TITLE
Add "calc" function for eval expressions

### ISSUE THREAD

**Issue by squigglezworth** [weechat/weechat#997]
This was already shortly discussed on IRC, but it would probably be best to have it here.

A `${calc:<some expression>}` function that would take parse simple math formulas would be very handy

`${calc:1+1} == 2`
`${calc:(2+2)*2} == 8`

**Comment by Zarthus** [comment]
Can you include some functions you feel this would be useful for? It seems weird to have weechat do the maths rather than precompile it. I imagine you're looking to do something like `${calc:60-${current_idle_time}} > 0` of sorts rather than just plain maths?

**Comment by squigglezworth** [comment]
Right, most use-cases would involve using another variable to do some
calculation. I should have included such examples.

**Comment by flashcode** [comment]
Done, for more information and supported operators, see the documentation here: https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_string_eval_expression
