### ISSUE TITLE
doc for "Connect to Freenode with TOR/SASL" is imprecise

### ISSUE THREAD

**Issue by weechatter** [weechat/weechat#999]
§ 4.7.6 Connect to Freenode with TOR/SASL 

14:09:43 WubTheCap+| It suggests sasl_mechanism ecdsa-nist256p-challenge, but also to set sasl_password
14:09:58 WubTheCap+| For freenode specifically, they disabled plain password auth
14:10:18 WubTheCap+| And ecdsa-nist256p-challenge works on ECDSA keys (NickServ SET pubkey), right?
14:11:20 WubTheCap+| Indeed, irc.server_default.sasl_password documentation also says in description
14:11:21 WubTheCap+| > this option is not used for mechanisms "ecdsa-nist256p-challenge" and "external"

**Comment by flashcode** [comment]
Thanks, doc is fixed.
